Feature/Facet Selector
openequella/openEQUELLA pull request #2216
Opened 2020-08-21 05:55 UTC by PenghaiZhang

#1306 

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Here is another refine control - Facet Selector.  A new type representing Search page specific Classifications was firstly added in `SearchPage.tsx`.  A function transforming standard Classifications to the Search page Classifications was also added in and will be consumed in the next integration. 

The component does not have its own state so at this stage only props changes can trigger a re-render. 
Jest tests and Storybooks for this component are also included.

![image](https://user-images.githubusercontent.com/47203811/90856592-98cf3400-e3c5-11ea-92c0-dd4235684240.png)

2020-08-21 06:17 UTC, SammyIsConfused reviewed
Looking good Penghai! A few tweaks.

2020-08-21 06:17 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/__mocks__/FacetSelector.mock.ts
> +        term: "scala",
It's probably worth having a really long name in one of these to show the wrapping.

2020-08-21 06:17 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +  // Mocked callbacks.
nit: comments don't need full stops

2020-08-21 06:17 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +    padding: 0,
For single styles, didn't we decide to just add a style prop inline?

2020-08-21 06:17 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +            Show more
Language string missing here.

2020-08-21 06:17 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +    // The number of displayed facets Depends on whether to show more
```suggestion
    // The number of displayed facets depends on whether to show more
```

2020-08-21 06:17 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +    .map((c) => {
I'd avoid these single character parameter names - it would improve readability to have a meaningful identifier.

2020-08-21 07:11 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +    .map((c) => {
Thanks @SammyIsConfused . All addressed!

2020-08-21 15:20 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/__mocks__/FacetSelector.mock.ts
> +import { SearchPageClassification } from "../tsrc/search/SearchPage";
```suggestion
import type { SearchPageClassification } from "../tsrc/search/SearchPage";
```

2020-08-21 15:20 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +import { SearchPageClassification } from "../SearchPage";
```suggestion
import type { SearchPageClassification } from "../SearchPage";
```

2020-08-21 15:20 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +              selectedTerms ? selectedTerms.indexOf(facet.term) !== -1 : false
```suggestion
              selectedTerms ? selectedTerms.includes(facet.term) : false
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

2020-08-24 02:07 UTC, edalex-ian requested changes
Thanks @PenghaiZhang 

A few things:

* Let's start using the new Args and Controls for storybook;
* Not I've remove all most all words of render, as at that point all you are doing is generating data structures in mem;
* A few other bits of tidy up and consideration.

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__stories__/search/FacetSelector.stories.tsx
> +export const noTermsSelected = () => <FacetSelector {...commonProps} />;
Could you please check in with @mrblippy on this so that we can start using the new Args and Controls approach?

Obviously we also have @ChristianMurphy 's #2182 coming on `develop` too, but let's do all the new ones with that in mind.

Also, I know you have mock data that has showMore as true and false, however it could be worthwhile to have two a stories which demonstrates this explicitly. That is, have a single Classification, and render once with it having showMore as true, and then another with it as false. Then you can click between the two stories and see the effect.

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +    return classification as HTMLElement;
I've got a feeling that if you change the function signature to specify the return type:

```typescript
  const getClassificationByName = (container: HTMLElement, name: string): HTMLElement => {
```

Then you wont need the `as` coercion.

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +  const SHOW_MORE = "Show more";
Be good to pull that from the matching language string.

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +  });
Is that needed?

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +    let showMoreButton;
There's no real need to be putting this into a variable.

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +  const getShowMoreButton = (
We should try and matching the React Testing Library function signatures. So this function should be:

```suggestion
  const queryShowMoreButton = (
```

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +
It feels to me that this actually belongs over in `FacetSelector.tsx`. This really sticks out, as it's not even needed here yet, but most certainly is over in `FacetSelector`.

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +  selectedTerms?: string[];
Is `string[]` specific enough. What if I have the same term in multiple Classifications? Sure the search will work the same, but the UI will not look correct.

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +            id={`${classificationName}_show_more`}
What if `classificationName` has spaces?

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +  const renderFacet = (facet: OEQ.SearchFacets.Facet) => (
```suggestion
  const facetListItem = (facet: OEQ.SearchFacets.Facet) => (
```

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +   * Render a MUI Checkbox and a Label for a facet.
This is not rendering, just building.

```suggestion
   * Build a ListItem consisting of a MUI Checkbox and a Label for a facet.
```

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +  const renderCategories = (classification: SearchPageClassification) => {
```suggestion
  const listCategories = (classification: SearchPageClassification): ListItem[] => {
```

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +   * Render a list for a Classification's categories. Some categories
```suggestion
   * Build a list for a Classification's categories. Some categories
```

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +   * @param classification A Classification..
Bit redundant, maybe we flesh it out a bit.

```suggestion
   * @param classification A fully defined Classification with a list of terms to build into a list - including metadata detailing how many to include.
```

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +    return facets.slice(0, showMore ? maxDisplay : undefined);
You don't need to bother building for items you're then just going to throw away:

```suggestion
    return categories.slice( 0, showMore ? maxDisplay : undefined)
      .map(facet) => renderFacet(facet));
```

When you do that though, then the return is redundant:

```typescript
const listCategories = ({categories, maxDisplay, showMore}: SearchPageClassification): ListItem[] =>
  categories.slice( 0, showMore ? maxDisplay : undefined)
      .map(facet) => renderFacet(facet));
```

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +  return <List>{renderClassifications}</List>;
Blank line to make this final bit stand out.

```suggestion

  return <List>{renderClassifications}</List>;
```

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +   * Sort and render Classifications that have categories.
```suggestion
   * Sort and build Classifications that have categories.
```

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +  const renderClassifications = classifications
```suggestion
  const buildClassifications = classifications
```

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +      const { name, showMore } = classification;
Why not combine these two lines?

2020-08-24 02:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +        <ListItem divider key={name} id={`classification_${name}`}>
What happens if `name` has spaces?

2020-08-24 02:12 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +  selectedTerms?: string[];
No enough :smile: .
I did not commit another type for this field which is a Map<string, string[]>. I will bring that in this PR.

2020-08-24 04:38 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +    return classification as HTMLElement;
This is not working on my machine. Does it work on yours ?

2020-08-24 04:41 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +  const getShowMoreButton = (
Good idea. If the functions throws an error then it's name should be `getByxxx`.

2020-08-24 04:45 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +    return classification as HTMLElement;
hmmm, I thought it did on one of my new functions in the SearchPage.test.tsx refactor.

This it's this one (snipped off comments for readability here):

```typescript
const queryRefineSearchComponent = (
  container: Element,
  componentSuffix: string
): HTMLElement | null => {
  const id = `#RefineSearchPanel-${componentSuffix}`;
  return container.querySelector(id);
};

const getRefineSearchComponent = (
  container: Element,
  componentSuffix: string
): HTMLElement => {
  const e = queryRefineSearchComponent(container, componentSuffix);
  if (!e) {
    throw new Error(`Failed to find ${componentSuffix}`);
  }

  return e;
};
```

`getRefineSearchComponent` used to do the coercion. (Probably still does on this branch if you want to take a look/have a play.)

2020-08-24 04:55 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +  const renderCategories = (classification: SearchPageClassification) => {
`ListItem` is not a type so do you like `ReactElement[]` instead ?

2020-08-24 05:06 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +      const { name, showMore } = classification;
Because function `listCategories`, which is called inside this `map`,  takes a classification as its parameter. But I can change its signature.

2020-08-24 05:39 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +            id={`${classificationName}_show_more`}
hmmm, it turns out we don't need IDs for these buttons. So I will remove them.

2020-08-24 05:51 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +    return classification as HTMLElement;
I think if you assign `container.querySelector(id)` to a new variable you would see the error. But, if we do 
`container.querySelector<HtmlElement>(id)` or specify the type of the variable, then the error is gone.

2020-08-24 06:05 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +        <ListItem divider key={name} id={`classification_${name}`}>
Can we replace spaces with `_` ? Actually if there are another approach that can help me find a ListItem(a `li` in DOM) then I don't need these IDs.

2020-08-24 06:09 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +        <ListItem divider key={name} id={`classification_${name}`}>
Ah I can use `.closest("li")` !!!

2020-08-24 06:25 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +        <ListItem divider key={name} id={`classification_${name}`}>
That'd be okay, and we can do similar in Selenium. At least we've got an ID at the top level of the selector, so we narrow in anyway and don't search the _whole_ DOM.

2020-08-24 23:25 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__stories__/search/FacetSelector.stories.tsx
> +export const notShowMore: Story<FacetSelectorProps> = (args) => (
I am repeating this pattern to create stories:  creating a story and configuring its arguments. I probably can create a `template` to reduce repeating.

2020-08-24 23:48 UTC, PenghaiZhang commented
Two more Storybooks

1. Show more button is visible.
![image](https://user-images.githubusercontent.com/47203811/91107199-06c27680-e6b8-11ea-9ec5-c311ad118e86.png)

2. The button is invisible.
![image](https://user-images.githubusercontent.com/47203811/91107234-222d8180-e6b8-11ea-8d96-0f3a705c044b.png)

2020-08-25 04:29 UTC, edalex-ian approved these changes
Looking good @PenghaiZhang . Just wonder if we can get away with using Classification name. :thinking:

2020-08-25 04:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +  selectedClassificationTerms?: Map<string, string[]>;
Hmmm, I'm reluctant to mention this - as this is so close. But... I wonder if in `SearchFacetsModule.Classification` we should be bringing in the UUID from the server. :thinking: (I'm not sure why I didn't in the first place.)

Then we'd use the UUID rather than the name for the key here, but also when doing the handlers etc. That way if someone does decide to have two Classifications/Facets with the same name, we'll be safe.

What do you think?

2020-08-25 04:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +      <ListItem key={`${term} ${count}`} style={{ padding: 0 }}>
Interesting. Did realise you could have spaces in the `key`, but I guess at the end of the day internally React is probably just using the string.

I assume this all works, so no need to change anything. Just observing.

2020-08-25 05:00 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +      <ListItem key={`${term} ${count}`} style={{ padding: 0 }}>
:thinking:  I would like to avoid any potential errors. What about adding a `-` between term and count.

2020-08-25 05:03 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +      <ListItem key={`${term} ${count}`} style={{ padding: 0 }}>
Up to you. I don't know for 100% sure if terms are always devoid of spaces (and/or punctuation).

2020-08-25 05:08 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +      <ListItem key={`${term} ${count}`} style={{ padding: 0 }}>
Just had a conversation with Tom regarding this. As we can't guarantee `${term} ${count}` is unique, in this case maybe we have to use `index` . What do you think @edalex-ian ?

2020-08-25 05:11 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +      <ListItem key={`${term} ${count}`} style={{ padding: 0 }}>
Well, now that you have `id` from Classification in, how about `${id}:${term}`?

2020-08-25 06:01 UTC, edalex-ian approved these changes
Good stuff @PenghaiZhang . Up to you with the `id`..

2020-08-25 06:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
> +        id: settings.id ?? index,
Hmmm, so it's only undefined if it's dirty. We should not have any 'dirty' entries here, so perhaps we should throw an error. If we leave like this it will probably be fine, but if we ever get corrupt data this could compound the situation.

Up to you.

2020-08-25 07:09 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
> +        id: settings.id ?? index,
I prefer leave it like this for now.

2020-08-25 22:52 UTC, merged