Facet Selector integration
openequella/openEQUELLA pull request #2245
Opened 2020-08-28 07:16 UTC by PenghaiZhang

#1306 

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR attempts to integrate the Facet Selector with Search page. Changes include:
1. Facet Selector manages the 'Show more/less' buttons by its own state; and
2. Selected terms are used to generate a Where clause for Search and Facet Search; and
3. Move the component to a separate MUI Card; and
4. Only add non-empty Collections to facet search param; and
5. Modify the fields of interface `Classification`; and
6. Strip out the starting `/xml` for selected Schema node in the Facet dialog.

![image](https://user-images.githubusercontent.com/47203811/91532794-2e347000-e952-11ea-9043-0b28cc773598.png)

2020-08-31 00:51 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__stories__/search/FacetSelector.stories.tsx
> -export const showMore: Story<FacetSelectorProps> = FacetSelectorTemplate.bind(
Now this is controlled by the component's state so we don't need these two stories (the remaining stories can also show/hide the buttons. I also did some research about how to directly modify state with Storybook to and this seems not to be encouraged (and well supported).

2020-08-31 00:51 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  const processNodeTerms = ({ node, terms }: NodeAndTerms) =>
Do we want to move this function outside ?

2020-08-31 00:51 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +  }, [searchPageOptions]);
Separate the update of Classification list from the first `useEffect` to help understand the logic more easily.

2020-08-31 00:51 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +      classificationTerms: undefined,
You will see more `classificationTerms: undefined,` below, but the benefit of doing this is we don't need to put  `classificationTerms` into state, which does not break 'New search' and 'Back to Search page'. So I feel the repeating is fine.

2020-08-31 04:57 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +  const SHOW_LESS = languageStrings.searchpage.facetSelector.showLessButton;
These two language strings will likely be used throughout the app. They should probably go inside languageStrings.common.action

2020-08-31 05:26 UTC, SammyIsConfused reviewed
Looking good! Just a few tweaks.

2020-08-31 05:26 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/__mocks__/FacetSelector.mock.ts
> +import { Classification } from "../tsrc/modules/SearchFacetsModule";
```suggestion
import type { Classification } from "../tsrc/modules/SearchFacetsModule";
```

2020-08-31 05:26 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
> +   * The configured Schema node of this classification.
```suggestion
   * The configured schema node of this classification.
```

2020-08-31 05:26 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
> +        OEQ.Common.ItemStatuses.alternatives.map((i) => i.value).sort()
I'd suggest you rename `i` to something more meaningful.

2020-08-31 05:26 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
> +        collections: collections.map((c) => c.uuid),
I'd suggest you rename `c` to something more meaningful.

2020-08-31 05:26 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
> +    (r) => r.term
As above - single letter identifier.

2020-08-31 05:26 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    terms.map((t) => `/xml${node}='${t}'`);
As above.

2020-08-31 05:26 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +   * Create a button to help show more/less categories for each Classification.
```suggestion
   * Create a button to show more/less categories for each Classification.
```

2020-08-31 05:26 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +    const selectedCategories = categories.filter((c) =>
As above.

2020-08-31 05:26 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +      (c) => !selectedTerms.includes(c.term)
As above.

2020-08-31 05:26 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
> +      showLessButton: "Show less",
These should probably be common strings.

2020-08-31 05:33 UTC, edalex-ian requested changes
Wowsers! This Ended up a big PR hey. :) I'm really excited to see this coming in.

A few things to do.

* Looks like SearchModule.test.ts needs a bit of a tidy
* I think types need a bit of a tidy-up/rethink. The Map<Number,NodeAndTerms> is getting confusing, and indeed there is probably overlap here with existing types (see other comments).
* We may also want to move away from adding the newer 'Terms' on the front-end code and try and go with `category` or `facet`. It's getting pretty confusing in places.
* We've started to end up with really tight coupling with bidirectional type references between the presentation layer and the business layer. We need to address this, going forward, but here there is a case where it's further been done so while fixing that DateRange should be fixed at the same time.
* `FacetSelector`: Seems to be doing a whole lot of stuff with `schemaNode`, but doesn't really need to, and as a result that's complicating some function signatures unnecessarily.

BTY.

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__stories__/search/FacetSelector.stories.tsx
> -export const showMore: Story<FacetSelectorProps> = FacetSelectorTemplate.bind(
Yeah it's interesting, as ideally you'd have a different story for each state. However here the state can not be externally triggered other than by interactions.

With the state being internally managed though, does that mean when you click show more/show less in storybook it is now actually properly itnteractive?

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +  it("should generate a Where clause for schema node and terms", () => {
```suggestion
  it("should generate a where clause for schema node and terms", () => {
```

.... Actually.... This test sits weird. Let's look at the bigger picture of `SearchModule.test.ts`....

We have a single describe block of `describe( "SearchModule" )` where all the tests have mainly been about calling the primary function of `searchItems`. However, now that we have an additional function maybe we need to rework the structure here to make sense. For example:

* describe: searchItems
  * it: lists items
  * it: will not do a wildcard search if the query is empty
  * it: does a wildcard search if the query is non-empty and rawMode is false
  * it: will not do a wildcard search when rawMode is true

* describe: generateWhereQuery
  * it: returns a where query built from supplied schema nodes and terms

(One thing that then jumps out at me, is the naming of that new function is probably too abstract - as it only generates a rather specific type of where query. I'll try to comment on that again where the new function is.)

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +import { generateWhereQuery } from "../../../tsrc/modules/SearchModule";
Should just use the below wildcard import and then call `SearchModule.generateWhereQuery()`.

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +import { NodeAndTerms } from "../search/components/FacetSelector";
Oooh, this is not ideal is it. We're setting up rather tight coupling here between our business logic layers and our presentation layers. NodeAndTerms should probably belong here if we need them here, or at least be broken out from a UI component. (And I note the same for the general `DateRange` below.)

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +   * A map of selected Classifications and their terms.
It would be worthwhile highlighting what the `number` (i.e. key) value is representing.

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  const processNodeTerms = ({ node, terms }: NodeAndTerms) =>
I don't see any need yet.

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
>    }
Should add a test for this. There's currently only the positive test. (Oh, actually I think there's only a test for when there are multiple queries. Ideally there should be a test which covers none, one and greater than one.)

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +export const generateWhereQuery = (
This needs a more specific name - as it's not a generic where clause builder. It also contains logic specific to how we want to query with selected facets/categories.

Maybe:

```suggestion
export const generateFacetedWhereQuery = (
```

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  classificationTerms?: Map<number, NodeAndTerms>
This method does not really care about the key for this map, so should it just be:

```suggestion
  classificationTerms?: NodeAndTerms[]
```

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +    const terms = new Map([
For readability, could you please type this Map. I think it's:

```suggestion
    const terms = new Map<number, NodeAndTerms>([
```

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +]);
If this is only used in one describe block (as it is), then best to just scope it into that block.

Also, the `CLASSIFICATION_ID` and `SCHEMA_NODE` variables seem largely redundant. And again, please type this map for readability.

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +const selectTerm = (container: HTMLElement, term: string) => {
Seeing this is global, and 'term' is rather generic, you may want to go with a more specific name:

```suggestion
const selectCategory = (container: HTMLElement, term: string) => {
```

Also (similar to changeQuery), there could be value in asserting that it has now checked the box. Otherwise this function is really just `clickCategory` - it's not really concerned with selecting.

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +  const mockedSelectedTerms = new Map([
Hmmmm, here's this untyped map again. I look forward to when I find the source of this.

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +  const queryButton = (
I wonder how this relates to the button query in MuiQueries. If it's the same, we should use that. If not, we should look at moving this there perhaps?

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
> +    if (collections && collections.length > 0) {
Can't this just be:

```suggestion
    if (collections?.length > 0) {
```

?

But overall it'd be nice if we can keep it declarative inline with the above structure. Maybe we could have in the above block:

```typescript
collections: collections?.length > 0 ? collections.map((c) => c.uuid) | undefined
```

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
> +  ); // Filter out empty terms
```suggestion
  ); // Filter out empty terms, as although the server generates them, sending them back will generate a 500
```

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  classificationTerms?: Map<number, NodeAndTerms>;
hmmm, I enjoy Maps for their ease of use and overhead. But I must admit this one is becoming some prolific it seems it should be a type. Maybe it'd be fine to simply use a type alias.

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +export interface NodeAndTerms {
As mentioned elsewhere I believe this should be defined in one of the lower modules - not the presentation layer.

There's also some kind of relationship between this, `SearchFacetsModule.Classification` and `OEQ.SearchFacets.Facet`. It would be effort well spent to see how this can be harmonized over in `SearchFacetsModule`. That work may actually also align with sorting out the `Map<number, NodeAndTerms>` as that seems like a sub class of `SearchFacetsModule.Classification`.

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
>     * A list of Classifications.
Can we tweak this while here. This currently states the obvious (due to the types). But what is the purpose of this list?

Maybe:

```suggestion
   * A list of Classifications which will be rendered to sections for each Classifications under which will be the
   * categories as clickable checkboxes.
```

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +  const [showMoreMap, setShowMoreMap] = useState<Map<number, boolean>>(
What about this for the var name:

```suggestion
  const [collapsedClassifications, setCollapsedClassifications] = useState<Map<number, boolean>>(
```

(Alternatively I feel `[expandedClassifications, setExpandedClassifications]` reads slightly better, but you'd have to rework all your logic.)

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
>     * @param classificationID The name of a Classification
```suggestion
   * @param classificationID The ID of a Classification
```

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +    schemaNode: string,
Seems unnecessary for you to be managing the `schemaNode` here - you have the more specific Classification ID which can be used for those purposes. This could lead to odd issues if they get out of wack.

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +  selectedClassificationTerms?: Map<number, NodeAndTerms>;
Can we reworking the naming here? It was confusing down below when reviewing `listCategories()` where you then start using the agreed terminology of 'categories' (rather than the server side, 'terms').

```typescript
/**
 * The currently selected categories, where the key of the map is the ID of
 * the `Classification` they below to.
 */
selectedCategories?: Map<number, NodeAndTerms>;
```

Hmmm, I wonder why you even need `NodeAndTerms` here. I mention this further down, I think you should only need the Classification ID and the string array of terms. :thinking:

2020-08-31 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +    );
As mentioned above on `selectedClassificationTerms`, let's normalise on our terminology. 

But... Is this even all required? Doesn't `selectedClassificationTerms` already hold all this value... Maybe it's because you need it in a different shape for TS, in which case maybe all you need is a `.map` over it. :thinking:

2020-08-31 05:37 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
> +        collections: collections.map((c) => c.uuid),
Single character is okay if it's in close context - like here and below in single use anonymous functions. So these are all good. :+1:

2020-08-31 06:00 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +  const SHOW_LESS = languageStrings.searchpage.facetSelector.showLessButton;
I pondered this too. Then I was wondering... What if people do want to control the text differently specifically on these buttons (vs. other show more/less buttons). If we want to support that, we'd want to keep it specific like this.

What do peeps think?

2020-08-31 06:45 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
> +        collections: collections.map((c) => c.uuid),
Sure thing! I'll resolve them.

2020-09-01 04:54 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__stories__/search/FacetSelector.stories.tsx
> -export const showMore: Story<FacetSelectorProps> = FacetSelectorTemplate.bind(
Yes, they are interactive in storybook now.

2020-09-01 04:59 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__mocks__/FacetSelector.mock.ts
> +import { Classification } from "../tsrc/modules/SearchFacetsModule";
Thanks Sam. I always forget this :disappointed_relieved:

2020-09-03 01:23 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
> +    if (collections && collections.length > 0) {
The reason for dong this is to make sure `collections` is not included in the search params when it's undefined or it is empty.  If we pass `undefined` or an empty collections to the facet search api, we will get nothing returned. (but we can  make some changes on the api side to make it happy with `undefined` or an empty collections)

2020-09-03 01:24 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFacetsModule.ts
> +    if (collections && collections.length > 0) {
And Typescript is not happy with `if (collections?.length > 0)` because collections?.length can be undefined. So we can do `if (collections?.length ?? 0 > 0)` instead.

2020-09-03 01:47 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FacetSelector.tsx
> +    );
I think we may need because generating each category's label text needs full information of a `facet` (term and count) , but `selectedClassificationTerms` only knows the `term`.

2020-09-03 01:48 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +  const SHOW_LESS = languageStrings.searchpage.facetSelector.showLessButton;
I prefer they stay here :smile: , what about other peeps ?

2020-09-03 02:27 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +const selectTerm = (container: HTMLElement, term: string) => {
I prefer change to name to `clickCategory` because we use MUI `FormControlLabel` which should ensure clicking the label will tick the box.

2020-09-03 04:02 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +import { NodeAndTerms } from "../search/components/FacetSelector";
I agree. I also feel `DateRange` should be sitting in a `utility module` because it's not specific to Search page.

2020-09-03 04:51 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FacetSelector.test.tsx
> +  const SHOW_LESS = languageStrings.searchpage.facetSelector.showLessButton;
I see @mrblippy changed them over in his PR. So I'll leave it for you guys to reach agreement. ;)

2020-09-03 07:59 UTC, edalex-ian requested changes
Good stuff @PenghaiZhang I think it's pretty well there now.

You'll see my feedback is really just formatting, typos and naming. Other than that just the listCategories function.

It looks like you've not refactored DateRange at this time. If that's not the case (please confirm) I'll put it on the backlog for next sprint or so.

2020-09-03 07:59 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CategorySelector.tsx
> +export interface GategorySelectorProps {
Whoops! Typo.

And please make sure we have white space between definitions of interfaces, classes and funcs at the top level.

```suggestion

export interface CategorySelectorProps {
```

2020-09-03 07:59 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CategorySelector.tsx
> +export const CategorySelector = ({
```suggestion

export const CategorySelector = ({
```

2020-09-03 07:59 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CategorySelector.tsx
> +  /**
```suggestion

  /**
```

2020-09-03 07:59 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CategorySelector.tsx
> +    term,
Nit: Could be good to rename this too - and then update the JSDoc.

2020-09-03 07:59 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CategorySelector.tsx
> +  const listCategories = (
As discussed, I'm finding this one a little tricky to read. Seems mainly due to variable names, and variable shadowing, but I think also compounded by the imperative nature of it.

I've come up with this alternative more declarative implementation:

```typescript
  const listCategories = (
    { id, categories, maxDisplay }: Classification,
    expanded: boolean
  ): ReactElement[] => {
    const selectedTerms: string[] =
      selectedCategories?.find((c) => c.id === id)?.categories ?? [];
    const selectedFacets: OEQ.SearchFacets.Facet[] = selectedTerms.map((selectedTerm) => {
      const facet = categories.find((c) => selectedTerm === c.term);
      if (!facet) {
        throw new Error(
          "Data integrity issue, we're unable to match a selected term."
        );
      }

      return facet;
    });
    const orderedFacets = selectedFacets.concat(
      categories.filter((c) => !selectedFacets.includes(c))
    );

    return orderedFacets
      .slice(0, expanded ? undefined : maxDisplay)
      .map((facet) => categoryListItem(id, facet));
  };
```

Two things interesting here:

1. Although it should never happen, this showed the potential for a data integrity issue that would be glossed over; and
2. Against my own advice I've been drawn into having to use Categories, Terms and Facets in the one function. But this was to align with data types and existing variable names. So, I dunno. :shrug: 

(Also, because this is declarative it highlights the data linkages/flow. I could've chained all this together, but I erred on the side of readability. :wink:  )

2020-09-03 07:59 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__stories__/search/CategorySelector.stories.tsx
> +  title: "Search/FacetSelector",
```suggestion
  title: "Search/CategorySelector",
```

2020-09-03 07:59 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__stories__/search/CategorySelector.stories.tsx
> +const FacetSelectorTemplate = (args: GategorySelectorProps) => (
```suggestion
const CategorySelectorTemplate = (args: GategorySelectorProps) => (
```

2020-09-03 07:59 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +    it("should provide an list of items", async () => {
```suggestion
    it("should provide a list of items", async () => {
```

2020-09-03 07:59 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +    it("should generate a where clause for one category", () => {
```suggestion

    it("should generate a where clause for one category", () => {
```

2020-09-06 23:45 UTC, edalex-ian approved these changes
Looks GTG @PenghaiZhang 

Thanks for all your hard work on this. :+1:

2020-09-07 00:08 UTC, merged