Feature/facet selector integration
openequella/openEQUELLA pull request #2259
Opened 2020-09-09 00:00 UTC by PenghaiZhang

#1306 

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

According to the latest discussions, we want to refactor the Category Selector for below changes: 
1. Each Classification is joined by `AND`; 
2. Each category of a Classification is joined by `OR`; 
3. Selected categories that do not apply to current search criteria are still displayed and their counts are 0 so that users can deselect them;
4. To generate a where clause for updating one Classification, only categories selected from other Classifications are used.
4.

2020-09-09 00:05 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CategorySelector.tsx
> +    const selectedAndExist = categories.filter((c) =>
It was struggling for me to give proper names in this function. so HELP wanted.

2020-09-09 02:17 UTC, edalex-ian commented
@PenghaiZhang 

When you say:

> 1. Each Classification is joined by AND;
> 2. Each category of a Classification is joined by OR;

Are you just referring to when they're used for the queries for the Facet Search, not the item search?

2020-09-09 02:52 UTC, PenghaiZhang commented
> @PenghaiZhang
> 
> When you say:
> 
> > 1. Each Classification is joined by AND;
> > 2. Each category of a Classification is joined by OR;
> 
> Are you just referring to when they're used for the queries for the Facet Search, not the item search?

They are used for both.

2020-09-09 04:29 UTC, edalex-ian requested changes
Fair effort @PenghaiZhang ! :+1: 

A couple of things:

* Need to rework JSDoc description for `generateCategoryWhereQuery`. The doco there is currently the old way, and I guess this might be the place to capture the business rules around what's been done here.
* Feedback given to your "HELP wanted" query. Up to you if you want to drop the `reduce` in there. :wink:

2020-09-09 04:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CategorySelector.tsx
> +    const selectedAndExist = categories.filter((c) =>
You could go with:

* `selectedApplicable`
* `selectedNotApplicable`
* `notSelected`

And to further this idea, it'd be great to maintain the relationships here strictly back to `selectedTerms`. So how about changing the first two sets to be processed with something like:

```typescript
const [selectedApplicable, selectedNotApplicable] =
  selectedTerms.reduce<[OEQ.SearchFacets.Facet[], OEQ.SearchFacets.Facet[]]>(
    ([applicable, notApplicable], term) => {
      const applicableCategory = category.find( c => c.term === term );
      return applicableCategory
        ? [applicable.concat(applicableCategory), notApplicable]
        : [applicable, notApplicable.concat({term: term, count: 0});
    }, [[], []]);
```

This is a bit more verbose, but it ties it the data structure it is being generated from, and so I think it's worth that.

2020-09-09 04:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CategorySelector.tsx
> +    const noSelected = categories.filter(
I'm guess this is a typo and should be:

```suggestion
    const notSelected = categories.filter(
```

2020-09-09 04:32 UTC, edalex-ian commented
> > @PenghaiZhang
> > When you say:
> > > 1. Each Classification is joined by AND;
> > > 2. Each category of a Classification is joined by OR;
> > 
> > 
> > Are you just referring to when they're used for the queries for the Facet Search, not the item search?
> 
> They are used for both.

Ah yes, of course. So in my review feedback where I said putting the business rules on `generateCategoryWhereQuery`, probably half go there, but the other half are on `listClassifications` in `SearchFacetsModule` I guess.

2020-09-09 04:50 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CategorySelector.tsx
> +    const selectedAndExist = categories.filter((c) =>
This is a very nice good use of reduce! I like it!

2020-09-10 02:13 UTC, PenghaiZhang commented
Verbally approved by Ian.

2020-09-10 02:14 UTC, merged