Check user agent, and render unsupported browser if it's ie11
openequella/openEQUELLA pull request #2283
Opened 2020-09-15 05:37 UTC by mrblippy

##### Checklist

- [x] the [contributor license agreement][] is signed
- [ ] commit message follows [commit guidelines][]
- [ ] screenshots are included showing significant UI changes

##### Description of change

#1306 

At the moment i am only checking the user agent string for "Trident", to determine if the browser is ie11. The styling has deliberately been kept very simple

![ie11 unsupported](https://user-images.githubusercontent.com/4625498/93169796-3f121d80-f769-11ea-9990-5dd0d85113a6.png)

Potential issues for discussion:

- Should i also be checking for earlier versions of ie? i personally don't think it's worth it
- Should the error messages be language stringed? 

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-09-15 05:46 UTC, SammyIsConfused approved these changes
Looks good! Just one indentation tweak. 
Also - what happens if you append `?old=true` to the URL? Does it get through then?

2020-09-15 05:46 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/resources/view/layouts/outer/unsupportedbrowser.ftl
> +  <style>
Is it just me, or is there some weird formatting happening here? The indenting should be different.

2020-09-15 05:58 UTC, SammyIsConfused commented
Another note, as discussed in the office; These strings should probably be in the language pack.

2020-09-15 15:23 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/resources/view/layouts/outer/unsupportedbrowser.ftl
> +    html{
```suggestion
    html {
```

2020-09-15 15:23 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/resources/view/layouts/outer/unsupportedbrowser.ftl
> +    #unsupported{
```suggestion
    #unsupported {
```

2020-09-15 15:23 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/resources/view/layouts/outer/unsupportedbrowser.ftl
> +      box-shadow: 0px 2px 1px -1px rgba(0,0,0,0.2), 0px 1px 1px 0px rgba(0,0,0,0.14), 0px 1px 3px 0px rgba(0,0,0,0.12);
```suggestion
      box-shadow: 0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0,0,0,0.12);
```

2020-09-15 15:23 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/resources/view/layouts/outer/unsupportedbrowser.ftl
> +  </p>
```suggestion
  <p>
    For the openEQUELLA New UI you must be using a current version of Firefox, Chrome or Microsoft Edge.
  </p>
```

2020-09-15 23:45 UTC, mrblippy commented
> Looks good! Just one indentation tweak.
> Also - what happens if you append `?old=true` to the URL? Does it get through then?

Yep, appending old=true to the url will let them in

2020-09-16 03:46 UTC, edalex-ian commented
Just a note based on the formatting comments I'm seeing. Evidentially we don't have formatting for our Freemarker files. So you may want to simply load in IntelliJ and do the <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>l</kbd>.

2020-09-16 03:53 UTC, mrblippy commented
> Just a note based on the formatting comments I'm seeing. Evidentially we don't have formatting for our Freemarker files. So you may want to simply load in IntelliJ and do the CTRL+ALT+l.

Yup, that's the key combo I used to format the ftl file. It's in the next commit

2020-09-17 01:35 UTC, PenghaiZhang reviewed
Looks good to me.

2020-09-17 01:35 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/template/RenderNewTemplate.scala
> +  }
This method can be slightly simplified to
```scala
  def isInternetExplorer(request: HttpServletRequest): Boolean = 
    Option(request.getHeader("User-Agent")).exists(_.contains("Trident"))
```

2020-09-17 03:57 UTC, edalex-ian requested changes
Looks good to me - no issues with what this PR is actually about.

But two things:

1. Could we please target `develop` for this one - it'll make more sense merge wise; and
2. If we can just add the new lang strings changelog that'd be great.

2020-09-17 03:57 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
> +unsupportedbrowser.message=For the openEQUELLA New UI you must be using a current version of Firefox, Chrome or Microsoft Edge.
We've casually discussed the idea o tracking changes to language strings. So, let's start with this PR.

Could you please (as part of this PR) start a new file called `changelog.languagestrings.md` with content like:

```markdown
# Language Strings ChangeLog

This file tracks the changes, additions and deletions to openEQUELLA language strings starting with version 2020.2.
This file can be useful when upgrading, to ensure you make any update to any custom language packs you may have.

## 2020.2

### Modified

- None

### Added

- `unsupportedbrowser.heading`
- `unsupportedbrowser.message`

### Removed

- None
```

2020-09-17 03:58 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
> +unsupportedbrowser.message=For the openEQUELLA New UI you must be using a current version of Firefox, Chrome or Microsoft Edge.
Yep, that's no problem

2020-09-17 06:13 UTC, edalex-ian commented
Woah! Hold on a sec, looks like you're request to merge essentially component to develop:

![image](https://user-images.githubusercontent.com/43919233/93427181-be862500-f900-11ea-9f3f-3445cbf3219d.png)

2020-09-17 06:25 UTC, mrblippy commented
> Woah! Hold on a sec, looks like you're request to merge essentially component to develop:
> 
> ![image](https://user-images.githubusercontent.com/43919233/93427181-be862500-f900-11ea-9f3f-3445cbf3219d.png)

Yeah, that's bad :/ I will rectify ASAP

2020-09-18 05:08 UTC, closed without merging