Functional tests for new Search page
openequella/openEQUELLA pull request #2286
Opened 2020-09-16 00:47 UTC by PenghaiZhang

#1306

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Created functional tests for new Search page. 

Four scenarios are tested: 
1. open the page and perform an initial search; and
2. perform a new search and then search with query and filters; and
3. view an Item's summary page; and
4. go back to the page.

2020-09-16 02:26 UTC, PenghaiZhang commented
The testing institution `fiveo` has items contributed by other tests, so this test failed on CI. I need to find another institution.

2020-09-16 06:24 UTC, edalex-ian commented
Is this ready for review yet @PenghaiZhang ? Or are you fixing some things up?

2020-09-17 01:19 UTC, PenghaiZhang commented
This PR will be ready for review once we work out the ACL issue for Search page.

2020-10-06 23:12 UTC, PenghaiZhang commented
Before I granted permissions to the testing account, I created another account which had no permissions (e.g. SEARCH_COLLECTION && VIEW_ITEM ). I used this account to open the new search page and did not see any 500 error. And definitely, no Collections and attachments were displayed due to no permissions.

2020-10-07 00:07 UTC, edalex-ian requested changes
Looks good @PenghaiZhang . I like the tests and the clean abstract structure of the NewSearchPageTest class. :+1: 

Just could do with one more method in NewSearchPage to abstract out the user action of selecting an item; and then some swapping around of existing test abstract classes; and then just a couple of queries. :+1:

2020-10-07 00:07 UTC, edalex-ian commented on autotest/OldTests/src/test/java/com/tle/webtests/test/searching/NewSearchPageTest.java
> +    searchPage.waitForSearchCompleted(16);
Curious.... You say the initial search should return 10 items, but then you wait for 16...

2020-10-07 00:07 UTC, edalex-ian commented on autotest/OldTests/src/test/java/com/tle/webtests/test/searching/NewSearchPageTest.java
> +    SummaryPage summary = new SummaryPage(context).get();
It'd be good to have this as a method of `NewSearchPage`. Maybe with a signature of: `SummaryPage selectItem(String itemTitle)`.

2020-10-07 00:07 UTC, edalex-ian commented on autotest/OldTests/src/test/java/com/tle/webtests/test/searching/NewSearchPageTest.java
> +    assertEquals(searchBar.getAttribute("value"), "Java");
Could be good to add a comment above this to highlight what the following lines are doing:

```suggestion
    // Expect when going 'back' to the search page, the previous search settings have been remembered
    assertEquals(searchBar.getAttribute("value"), "Java");
```

2020-10-07 00:07 UTC, edalex-ian commented on autotest/OldTests/src/test/java/com/tle/webtests/test/searching/NewSearchPageTest.java
> +  }
I was wondering why you were going through this pain when you actually don't need anything else `AbstractCleanupAutoTest` really provides - other than perhaps the `prepareBrowserSession` implementation. So on digging deeper I think it would be good to:

1. Move `com.tle.webtests.test.AbstractCleanupTest#logon`, `com.tle.webtests.test.AbstractCleanupTest#AUTOTEST_LOGON` and `com.tle.webtests.test.AbstractCleanupTest#AUTOTEST_PASSWD` to `com.tle.webtests.test.AbstractSessionTest`
2. Make this test then simply extend `com.tle.webtests.test.AbstractSessionTest`
3. And in this test add your implementation of `prepareBrowserSession` which simply calls the newly located `com.tle.webtests.test.AbstractSessionTest#logon`

2020-10-07 00:07 UTC, edalex-ian commented on autotest/OldTests/src/test/java/com/tle/webtests/test/searching/NewSearchPageTest.java
> +package com.tle.webtests.test.searching;
Seeing this is all about testing the new stuff, should we perhaps move it (and the below `Page` class) over to the `io.github.openequella` package tree? Maybe they could be:

* io.github.openequella.search.NewSearchPageTest
* io.github.openequella.pages.search.NewSearchPage

2020-10-07 00:07 UTC, edalex-ian commented on autotest/OldTests/testng-codebuild.yaml
> +      - com.tle.webtests.test.searching.NewSearchPageTest
Hmmmm, so is this getting run as part of the 'Old UI' mode of tests?

2020-10-07 00:07 UTC, edalex-ian commented on autotest/Tests/src/main/java/com/tle/webtests/pageobject/searching/NewSearchPage.java
> +  public void selectDateRangeQuickOption(String quickOption) {
Is this unused?

2020-10-07 00:11 UTC, edalex-ian commented
> Before I granted permissions to the testing account, I created another account which had no permissions (e.g. SEARCH_COLLECTION && VIEW_ITEM ). I used this account to open the new search page and did not see any 500 error. And definitely, no Collections and attachments were displayed due to no permissions.

Could be worth adding a least one test (in `NewSearchPageTest`) that specifically logs in with a lower privileged user to ensure it still works. (Especially after all the work done to make sure it does.)

2020-10-07 05:37 UTC, edalex-ian commented on autotest/Tests/src/main/java/com/tle/webtests/pageobject/searching/NewSearchPage.java
> +  public WebElement getSearchBar() {
I wonder if instead we should use the `@FindById` and a class property. :thinking:

2020-10-07 21:53 UTC, PenghaiZhang commented on autotest/OldTests/src/test/java/com/tle/webtests/test/searching/NewSearchPageTest.java
> +    searchPage.waitForSearchCompleted(16);
oops I forgot to update the comment.

2020-10-07 22:43 UTC, PenghaiZhang commented on autotest/Tests/src/main/java/com/tle/webtests/pageobject/searching/NewSearchPage.java
> +  public void selectDateRangeQuickOption(String quickOption) {
It was actually used. The test expects no items found if `today` is selected, but this failed because of the two new items. So I removed it. Now I can call this method again. The test will select `Today` and check, and then select `All` and check.

2020-10-07 23:08 UTC, PenghaiZhang commented on autotest/OldTests/testng-codebuild.yaml
> +      - com.tle.webtests.test.searching.NewSearchPageTest
Yes it's. This test does not have any thing specific to either Old UI or New UI so it still works fine in Old UI mode.

2020-10-07 23:12 UTC, PenghaiZhang commented on autotest/OldTests/testng-codebuild.yaml
> +      - com.tle.webtests.test.searching.NewSearchPageTest
When we merge component to develop, there will be a difference - the ItemSummary page will display in Old UI  because of the `Old UI persisting fix` #2296

2020-10-07 23:40 UTC, PenghaiZhang commented on autotest/Tests/src/main/java/com/tle/webtests/pageobject/searching/NewSearchPage.java
> +  public WebElement getSearchBar() {
I think it's good to use this annotation for three components: the search bar, new search button and the refine panel show more button.

2020-10-08 03:28 UTC, edalex-ian commented on autotest/OldTests/testng-codebuild.yaml
> +      - com.tle.webtests.test.searching.NewSearchPageTest
But as we get more of these we don't want them running in Legacy UI testing mode - as it just wastes time and resources. Maybe we a TestNG annotation we can disable it when the newUI config value is set; or, maybe something in this YAML syntax.

2020-10-08 03:39 UTC, edalex-ian approved these changes
Looking good @PenghaiZhang 

Just two queries:

* Can we exclude the New UI only tests from running unnecessarily against Legacy UI mode; and
* Do we need that low priv test to be dependent on the others - or can it run alone.

But really, this is GTG.

2020-10-08 03:39 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/search/NewSearchPageTest.java
> +  @Test(description = "Search with a low privileged user", dependsOnMethods = "backToSearchPage")
Does it need to depend on any prior test? Seeing it's logging in with a new session, it should be stand-alone really shouldn't it?

2020-10-11 22:11 UTC, PenghaiZhang commented
Well obviously there are lots of commits... Builds for New UI failed strangely. From screenshots, the Item Summary page is open in Old UI.  I noted that builds for c8e9776d128ce2cecb49d92fd7c51c856658d0a6 are green so changes made after this commit must break things.

2020-10-12 05:01 UTC, edalex-ian commented
I reckon merge on, and then create a new branch to try and address the new REST module CI failures (due to merge from develop).

2020-10-12 05:03 UTC, merged