EBP: User Preferences Page styles
openequella/openEQUELLA pull request #2290
Opened 2020-09-16 07:27 UTC by SammyIsConfused

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] screenshots are included showing significant UI changes

##### Description of change
#1983 
- Save and Change password buttons padding and shadow fix
- First and last name alignment
- Timezone/Language section alignment
- Checkbox padding and alignment
- Header size and font aligns with other new stuff (I.E contribution page)
- Uses MUI theme colours
- Added padding to expanded dropdowns when they are at the bottom of a page
- Change dividers to use MuiDivider styles
- border radius for the watched collections box
![Peek 2020-09-16 17-24](https://user-images.githubusercontent.com/24543345/93305217-8bc92780-f841-11ea-8121-ccbaafde0489.gif)
![image](https://user-images.githubusercontent.com/24543345/93305322-ae5b4080-f841-11ea-9854-ac9f670d3d8b.png)
![image](https://user-images.githubusercontent.com/24543345/93305377-c4690100-f841-11ea-8ad8-04f3b8135d56.png)

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-09-16 08:02 UTC, edalex-ian requested changes
Looks nice and tidy @SammyIsConfused !

Just need to push a couple of things into variables to keep it DRY for easy maintenance and consistency.

2020-09-16 08:02 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +  .edit:nth-last-child(2) {
I think once you start getting opaque selectors like this, it's worth adding a comment to explicitly state your target.

2020-09-16 08:02 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    width: 250px;
I'm guessing you want this to match the above 250px. So could be worth dropping it in a variable.

2020-09-16 08:02 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    border-radius: 3px;
Could make sense to pull this 3px out into a variable, and then you can also re-use in those other places which has this. One place was the buttons, however looking above I now see that's at 4px. Shouldn't these match? If so, should it be 4 or 3? (I guess that highlights the use of putting it in a variable.)

2020-09-17 03:08 UTC, mrblippy reviewed
It's much tidier now that those extra variables are being used :+1:

2020-09-17 04:02 UTC, edalex-ian approved these changes
Looks good, you just missed one `curvedCorners`. GTG after that's fixed.

2020-09-17 04:02 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +  border-radius: 4px;
Should this be the new `curvedCorners`?

2020-09-17 06:03 UTC, merged