Add a tooltip to show the username on the account icon
openequella/openEQUELLA pull request #2307
Opened 2020-09-21 04:50 UTC by SammyIsConfused

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] screenshots are included showing significant UI changes

##### Description of change
#796 
Change the tooltip on the account icon in the top right of a page to show the user's username instead.
![image](https://user-images.githubusercontent.com/24543345/93733692-c522de00-fc19-11ea-8f4e-e91663f5c757.png)

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-09-21 05:16 UTC, edalex-ian requested changes
Good stuff @SammyIsConfused :+1: 

But it has reminded me of some outstanding refactoring that needs to be done. So let's squeeze that into this PR.

2020-09-21 05:16 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/api/currentuser.ts
> +  username: string;
Aaahhhh, this reminds me.

We need to drop out `currentuser.ts` and use the support in oeq-ts-rest-api. So, this PR seems as good as any.

Could you please remove `currentuser.ts` and move the code to use getCurrentUserDetails (and supporting interfaces) @ https://github.com/openequella/openEQUELLA/blob/develop/oeq-ts-rest-api/src/LegacyContent.ts#L38

2020-09-21 05:16 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
> +            <Tooltip title={currentUser?.username}>
Could be good to also have a fallback here - just so we never have an empty "bubble" of a tooltip. Maybe "Username unknown". :thinking:

2020-09-23 00:02 UTC, edalex-ian requested changes
Looks good @SammyIsConfused 

Just two things:

1. Please stick with the convention for importing `@openequella`; and
2. With your renamed `UserDetailsModule.ts` could we please go with `UserModule.ts`. This will align with what's been done in `component/new-search-page` with the [UserModule.ts](https://github.com/openequella/openEQUELLA/blob/component/new-search-page/Source/Plugins/Core/com.equella.core/js/tsrc/modules/UserModule.ts) there. Sure it'll create a bit of a conflict, but it'll highlight it should sit alongside it.

2020-09-23 00:02 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/legacycontent/LegacyContent.tsx
> +import type { CurrentUserDetails } from "@openequella/rest-api-client/dist/LegacyContent";
The convention for this library is to:

```suggestion
import * as OEQ from "@openequella";
```

And then use accordingly.

2020-09-23 00:02 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/Template.tsx
> +} from "@openequella/rest-api-client/dist/LegacyContent";
The convention for this library is to:

```suggestion
import * as OEQ from "@openequella";
```

And then use accordingly.

2020-09-23 00:02 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/index.tsx
> +import type { CurrentUserDetails } from "@openequella/rest-api-client/dist/LegacyContent";
The convention for this library is to:

```suggestion
import * as OEQ from "@openequella";
```

And then use accordingly.

2020-09-23 14:43 UTC, ChristianMurphy approved these changes

2020-09-23 23:21 UTC, PenghaiZhang approved these changes
Looks good to me Sam! Thanks.

2020-09-23 23:21 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
> +      usernameUnknown: "Username unknown",
As we have a language string change log now, do we need to put this new string into the log  when component is merged to develop?

2020-09-23 23:21 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/UserDetailsModule.ts
> +      return result;
Can simplify the callback to `(result: OEQ.LegacyContent.CurrentUserDetails) => result` to save 2 lines :smile:

2020-09-24 01:37 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
> +      usernameUnknown: "Username unknown",
You raise a good point there @PenghaiZhang 

I was only thinking though to do that with the ResourceCentre ones for now - i.e. the old properly released ones. It feels like all these (`langstrings.ts`) are essentially 'new' for 2020.2. But after that, then we'd want to document these too me thinks.

What do you think?

2020-09-24 01:59 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
> +      usernameUnknown: "Username unknown",
That's a good idea! I agree.

2020-09-25 00:02 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/UserDetailsModule.ts
> +      return result;
Done!

2020-09-25 02:31 UTC, edalex-ian approved these changes
Aw man, looks like the hooks failed on you again. I wonder what that is.

But, aside from that, GTG. :+1: :wink:

2020-09-28 03:26 UTC, merged