Bugfix/search page acl issues
openequella/openEQUELLA pull request #2308
Opened 2020-09-21 06:37 UTC by PenghaiZhang

#1306 

### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

At least three ACL issues were found during the work for creating functional tests. They are: 
1. without `EDIT_SEARCH_SETTINGS`,  403 is returned when calling `api/settings/search` and 
`api/settings/facetedsearch/classification`.
2. if `SEARCH_COLLECTION` is granted on Collection level, front-end infinitely calls `api/collection`  because the resumption token is totally wrong; and
3. without `COMMENT_VIEW_ITEM`, 403 is returned when calling `api/search2`.

So they are three fixes in this PR: 
1. Remove the ACL checks for the GET endpoint of Search settings and Classifications.
2. Fix the logic of generating a resumption token in `PagedResult.scala`.
3. Perform ACL check for the comment one, and make the number of comments optional.

2020-09-21 06:55 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
> -                               offset,
Using `offset` here causes incorrect data such as duplicated data. For example, when offset is 0 and length is 10, 17 entities are found then 10 entities are included in the result. However, these 10 entities are not necessarily from No.1 to No.10.  No.2 entity could be filter out due to no permission and No.11 is included in the result. As a result, in the next call (offset is 10 now), No.11 entity is included in the result again.

2020-09-21 06:56 UTC, PenghaiZhang commented
I think the hardest one to review is definitely `PagedResult` so please grab me whenever needed!

2020-09-21 08:11 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
> -          val withPriv = nextLot.asScala
After removing `amountToTry`, moving `nextLot` and `privMap` to the object level  and renaming them, this method looks easier to read and understand to me, but I have not worked out how to properly move `ExtraPrivs` outside.

2020-09-21 08:11 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
> +        .getPrivilegesForObjects(allReqPriv.asJavaCollection, availableEntities.drop(offset).asJava)
I wonder if peope are confused about the use of `drop` so let me give an example.
Say there are 15 available entities. The initial token is `0:10`, which means offset is 0 and length is 10. So the first response include the first 10 entities.  And then, the secdon token must be `10:10`. We no longer need the first 10 entities, so we drop them and only return 11th - 15th entities.

2020-09-23 00:43 UTC, edalex-ian requested changes
Heya @PenghaiZhang 

I'm happy with the removal of the permissions checks side of this fix; but I think we can do the comments count better, and there's an issue with the PagedResult update.

BTY.

2020-09-23 00:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
> +      commentCount = getItemComments(key).map(_.size),
Strange that to get a count of the number of comments, we first go and retrieve **all** the comments from the DB. This is unnecessary load on the DB, normally you'd just do a count query. I note however that the Service currently lacks such a method. Might be good to keep the new methods you have - as we'll need them later - but maybe we should do this properly with a DB call.

2020-09-23 00:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
> +      new EnumerateOptions(q, -1, MaxEntities, system, if (includeDisabled) null else false))
As discussed, there's an issue here to resolve before I can review the Collections part of this PR.

2020-09-23 23:01 UTC, PenghaiZhang commented
Screenshots for the fixed resumption tokens.

Logged in as administrator: 
![image](https://user-images.githubusercontent.com/47203811/94082404-334ae900-fe44-11ea-9b07-7b2f926714de.png)
![image](https://user-images.githubusercontent.com/47203811/94082421-3e9e1480-fe44-11ea-8d2f-65e28ae0006b.png)

Logged in as a user who is not accessible to some Collections:

![image](https://user-images.githubusercontent.com/47203811/94082538-7d33cf00-fe44-11ea-853f-9260a02869d4.png)

![image](https://user-images.githubusercontent.com/47203811/94082555-8755cd80-fe44-11ea-8cf6-2913bdf3bae4.png)

2020-09-23 23:08 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/item/standard/service/impl/ItemCommentServiceImpl.java
> +      return itemDao.getCommentCounts(Collections.singletonList(item)).get(0);
I did not create a new method for comment count. Instead, I reused `itemDao.getCommentCounts` like how old search page uses it.

2020-09-24 01:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/item/standard/service/impl/ItemCommentServiceImpl.java
> +      return itemDao.getCommentCounts(Collections.singletonList(item)).get(0);
Good find, I see it's doing a HQL `count()`, so that's perfect. :+1:

2020-09-24 02:21 UTC, edalex-ian approved these changes
I'm thinking this is good to go. Maybe just a comment to add, and if you like a slight reworking of the comment retrieval and counting with Optionals and lambdas. But.. Up to you.

2020-09-24 02:21 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/item/standard/service/impl/ItemCommentServiceImpl.java
> +  }
I'm just thinking. Both the methods above which call this are almost the same. And indeed, if you change the above two methods to instead return `Optional<List<Comment>>` and `Optional<Integer>` you could then possibly change this method to take a lambda which receives an `Item` and the returns an `Optional` (returning `Optional.empty()` if **can't** view comments). And then the other two methods could look something like (the very rough code):

```java
@Override
@Transactional
public Optional<Integer> getCommentCountWithACLCheck(ItemKey itemId) {
  return canViewComment( itemId, (item) -> Optional.of(
    itemDao.getCommentCounts(Collections.singletonList(item)).get(0)
  ));
}
```

2020-09-24 02:21 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
> +      val entities = getBaseEntities(0, -1)
We may want to make a comment here to highlight we're retrieving all. But this is done in a considered way that the targetted BaseEntities are all small datasets.

2020-09-24 02:21 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
> +      val baseEntities = getBaseEntities(offset, MaxEntities)
I find it kinda wierd how we're relying on always getting `MaxEntities` (rather than say `length`) and then hoping we can prune it down. Rather then getting `length` entities, and topping it up with more queries as needed.

Feels like there's a chance that `MaxEntities` could potentially fail to have enough, and then we'd fall short. But maybe that's an extreme edge case. Or... Maybe I'm also mis-understanding something here. (I don't find `collectMore` that readable.)

2020-09-24 04:02 UTC, ChristianMurphy approved these changes

2020-10-05 03:45 UTC, edalex-ian approved these changes
Looking good @PenghaiZhang . Just a couple of comment tweaks, and a suggestion around DataProviders.

But one big thing... You've still a TODO in there. Does that still need todoing?

2020-10-05 03:45 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/BaseEntityAPITest.java
> +  public static Object[][] tokens() {
Just something to ponder...

You can make this a bit stricter on typing with:

```java
  @DataProvider(name = "initialResumptionTokens")
  public static Iterator<String> tokens() {
    return Arrays.asList({"0:5"}, {"0:10"}, {"0:20"}).iterator();
  }
```

2020-10-05 03:45 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
> +        // If quota is enough then simply plus the length of entities to offset.
```suggestion
        // The offset for subsequent calls needs to take into account the potential
        // skipping of entities due to filtering by ACLs.
        // If there is not enough quota after filtering entities, calculate the offset
        // for the next call by adding the index of the last entity in the result list
        // to the current offset.
        // If there is enough for the quota, then simply return the current offset plus
        // the length of retrieved entities.
```

2020-10-05 03:45 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
> +    // When there are no enough entities retrieved, do not return a resumption token.
```suggestion
    // When the number of results returned are less than asked for, we have reached the end.
    // So do not return a resumption token.
```

2020-10-05 03:45 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
> +    // todo: Support getting full information.
Is this still TODO?

2020-10-05 06:46 UTC, PenghaiZhang commented on autotest/OldTests/src/test/java/io/github/openequella/rest/BaseEntityAPITest.java
> +  public static Object[][] tokens() {
We probably need to update TESTNG to change the type of `DataProvider`.

2020-10-05 07:26 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/portal/dao/PortletDaoImpl.java
> -                        if (callback != null && callback.getOrderBy() != null) {
Here is why PortletTest failed. The `callback` passed in this method is essentially a `PagedListCallback` so an `order by` will be appended to the HQL, which resulted in Postgresl error `[42803]: column "be.id" must appear in the GROUP BY clause or be used in an aggregate function Position: 42`  .

However, this method is used to count the number of Portlets. There is no point to do a sorting. So I believe we should remove this if statement. One good example is method `createEnumerateQuery` from `GenericInstitionalDaoImpl`.

2020-10-05 21:59 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/BaseEntityAPITest.java
> +  public static Object[][] tokens() {
Yeah, we did have a Renovate PR there for a bit, but it got closed. #2022

2020-10-05 21:59 UTC, PenghaiZhang commented
ApidocsTest failed. I will restart.

2020-10-05 22:06 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/portal/dao/PortletDaoImpl.java
> -                        if (callback != null && callback.getOrderBy() != null) {
I agree.

This is odd it's doing an order for a count. I wonder if it's a case of copy pasta. :thinking:

2020-10-05 22:08 UTC, PenghaiZhang commented on autotest/OldTests/src/test/java/io/github/openequella/rest/BaseEntityAPITest.java
> +  public static Object[][] tokens() {
I see that PR failed on scala check, but I can't remember why we did not give Renovate some help.

2020-10-05 22:27 UTC, edalex-ian approved these changes
Probably pretty good to go. Just maybe a couple of things to tidy up. But if you can do at least the Test tweak, then you should be good to merge.

2020-10-05 22:27 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/BaseEntityAPITest.java
> +    // is accessible whereas that of the second is not accessible.
Maybe expand this out then to highlight what the significance of then checking for `security` is. (As personally, I'm not sure what the point is...)

2020-10-05 22:27 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/BaseEntityAPITest.java
> +  private JsonNode getResultList(JsonNode result) {
You should update `getResultLength` to also use this new method.

2020-10-05 22:27 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
> +      val results: ListBuffer[(BE, Boolean, Set[String])] = ListBuffer()
The addition of this tuple (`(BE, Boolean, Set[String])`) is getting a bit obtuse. Especially when the return of the method is now a tuple which includes a `List` which contains a tuple which also includes a `Set`. (I think that mouthful highlights the situation.)

I wonder if a case class may be in order for the inner tuple of `(BE, Boolean, Set[String])`. :thinking:

2020-10-06 00:12 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/entity/PagedResults.scala
> +      val results: ListBuffer[(BE, Boolean, Set[String])] = ListBuffer()
It's a very good idea to use a case class here!

2020-10-06 00:19 UTC, edalex-ian commented
:crossed_fingers: for a green build :crossed_fingers:

2020-10-06 01:47 UTC, ChristianMurphy approved these changes

2020-10-06 01:47 UTC, ChristianMurphy commented on autotest/Tests/tests/rest/institution/itemdefinition/25/f5db7438-a367-4c3e-85b9-ab67be09d5e6.xml
> +</com.tle.beans.entity.itemdef.ItemDefinition>
```suggestion
</com.tle.beans.entity.itemdef.ItemDefinition>

```

2020-10-06 03:09 UTC, PenghaiZhang commented on autotest/Tests/tests/rest/institution/itemdefinition/25/f5db7438-a367-4c3e-85b9-ab67be09d5e6.xml
> +</com.tle.beans.entity.itemdef.ItemDefinition>
Hi Christian, this xml file is from an Institution export and in the format oEQ expects.

2020-10-06 03:09 UTC, merged