Add lookup functionality to UserQuery rest module, with a few basic tests
openequella/openEQUELLA pull request #2338
Opened 2020-09-28 01:01 UTC by mrblippy

…ests

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included

##### Description of change

Adds oEQ userquery/lookup REST endpoint support to the oeq-ts-rest-api module. 

This will enable us to lookup oEQ users, groups and roles by id. 

The primary driver for implementing this is to allow for the new Search page to read in a user id from a query string, and display the correct user details in the OwnerSelector control. 

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-09-28 01:13 UTC, edalex-ian requested changes
Looks good @mrblippy 

But we will want to have a validator for `POST`, and tweak the comments a bit.

BTY.

2020-09-28 01:13 UTC, edalex-ian commented on oeq-ts-rest-api/src/UserQuery.ts
> +  /** String array of User IDs to lookup. */
No need to put the type info in the comment. So this (and the below three) can be:

```suggestion
  /** User IDs to lookup. */
```

Or if you want more, keep it abstract:

```suggestion
  /** List of User IDs to lookup. */
```

2020-09-28 01:13 UTC, edalex-ian commented on oeq-ts-rest-api/src/UserQuery.ts
> + * Lookup for users and related entities (i.e. groups and roles).
Be good to highlight in this description how this is different from `search()`.

2020-09-28 01:13 UTC, edalex-ian commented on oeq-ts-rest-api/src/AxiosInstance.ts
> +export const POST = <T, R>(path: string, data?: T): Promise<R> =>
Please include support for a validator here (like in `GET`).

2020-09-28 01:13 UTC, edalex-ian commented on oeq-ts-rest-api/src/UserQuery.ts
> +  );
Once you add support for a validator to `POST`, you want to add that in here too.

2020-09-28 01:42 UTC, mrblippy commented on oeq-ts-rest-api/src/AxiosInstance.ts
> +export const POST = <T, R>(path: string, data?: T): Promise<R> =>
Ok, I will give it a go

2020-09-28 04:03 UTC, edalex-ian approved these changes
Looks good! Thanks @mrblippy :+1:

2020-09-28 04:29 UTC, ChristianMurphy approved these changes

2020-09-28 04:29 UTC, ChristianMurphy commented on oeq-ts-rest-api/src/AxiosInstance.ts
> +    .then((response: AxiosResponse<R>) => {
Do we know that the `AxiosResponse` contains `R` yet?
I though that is what validator on line 87 is for?

2020-09-28 05:14 UTC, edalex-ian commented on oeq-ts-rest-api/src/AxiosInstance.ts
> +    .then((response: AxiosResponse<R>) => {
Good catch. :+1:

2020-09-28 05:16 UTC, mrblippy commented on oeq-ts-rest-api/src/AxiosInstance.ts
> +    .then((response: AxiosResponse<R>) => {
Oh yes, i didn't update that after putting the validator in.  Thank you @ChristianMurphy

2020-09-29 00:25 UTC, SammyIsConfused approved these changes
Looks good Charlie!

2020-09-29 04:00 UTC, merged