Spring 5 / Hib 5 Initial Efforts
openequella/openEQUELLA pull request #2344
Opened 2020-09-29 02:56 UTC by cbeach47

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]

##### Description of change
Upgraded to Spring 5, Hibernate 5, and supporting libraries.

Comments with `TODO [SpringHib5]` needs some more review.

Want to get this PR out here so the community can start taking a look, and to see how it fairs with the CI pipeline.

2020-09-29 02:58 UTC, cbeach47 commented
oEQ succeeds with `sbt cleanrun` on postgreSQL.  Contributions, edits, and deletes work.

Discovered hierarchies have a column mismatch, so looking into that now.

2020-10-05 21:48 UTC, edalex-ian commented
Heya @cbeach47 

For c237a0e you may want to merge in `develop` where we recently disabled the hard fail for that with PR #2362.

2020-10-09 01:26 UTC, cbeach47 commented
@edalex-ian - finally got green lights across the github CI builds. :)

Could you please provide some insight into what is failing for CodeBuild?

2020-10-09 03:50 UTC, edalex-ian commented
> @edalex-ian - finally got green lights across the github CI builds. :)
> 
> Could you please provide some insight into what is failing for CodeBuild?

Heya Chris,

Looks like the Hibernate upgrade has broken the build of the [Kaltura plugin](https://github.com/openequella/openEQUELLA-Kaltura):

```
[error] /codebuild/output/src122370099/src/github.com/openequella/openEQUELLA/Source/Plugins/Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/migration/MigrateKalturaSettings.java:30:1: cannot find symbol
[error]   symbol:   class Session
[error]   location: package org.hibernate.classic
[error] import org.hibernate.classic.Session;
[error] /codebuild/output/src122370099/src/github.com/openequella/openEQUELLA/Source/Plugins/Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/migration/MigrateKalturaSettings.java:60:1: cannot find symbol
[error]   symbol:   class Session
[error]   location: class com.tle.core.kaltura.migration.MigrateKalturaSettings
[error]     protected void executeDataMigration(HibernateMigrationHelper helper, MigrationResult result, Session session)
[error] /codebuild/output/src122370099/src/github.com/openequella/openEQUELLA/Source/Plugins/Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/migration/MigrateKalturaSettings.java:119:1: cannot find symbol
[error]   symbol:   class Session
[error]   location: class com.tle.core.kaltura.migration.MigrateKalturaSettings
[error]     protected int countDataMigrations(HibernateMigrationHelper helper, Session session)
[error] /codebuild/output/src122370099/src/github.com/openequella/openEQUELLA/Source/Plugins/Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/migration/UpdateKalturaAttachmentsMigration.java:44:1: cannot find symbol
[error]   symbol:   class Session
[error]   location: package org.hibernate.classic
[error] import org.hibernate.classic.Session;
[error] /codebuild/output/src122370099/src/github.com/openequella/openEQUELLA/Source/Plugins/Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/migration/UpdateKalturaAttachmentsMigration.java:73:1: cannot find symbol
[error]   symbol:   class Session
[error]   location: class com.tle.core.kaltura.migration.UpdateKalturaAttachmentsMigration
[error]     protected void executeDataMigration(HibernateMigrationHelper helper, MigrationResult result, Session session)
[error] /codebuild/output/src122370099/src/github.com/openequella/openEQUELLA/Source/Plugins/Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/migration/UpdateKalturaAttachmentsMigration.java:106:1: cannot find symbol
[error]   symbol:   class Session
[error]   location: class com.tle.core.kaltura.migration.UpdateKalturaAttachmentsMigration
[error]     private KalturaServer getKalturaServer(Session session, Institution inst)
[error] /codebuild/output/src122370099/src/github.com/openequella/openEQUELLA/Source/Plugins/Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/migration/UpdateKalturaAttachmentsMigration.java:117:1: cannot find symbol
[error]   symbol:   class Session
[error]   location: class com.tle.core.kaltura.migration.UpdateKalturaAttachmentsMigration
[error]     protected int countDataMigrations(HibernateMigrationHelper helper, Session session)
[error] /codebuild/output/src122370099/src/github.com/openequella/openEQUELLA/Source/Plugins/Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/migration/UpdateKalturaControlsMigration.java:38:1: cannot find symbol
[error]   symbol:   class Session
[error]   location: package org.hibernate.classic
[error] import org.hibernate.classic.Session;
[error] /codebuild/output/src122370099/src/github.com/openequella/openEQUELLA/Source/Plugins/Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/migration/UpdateKalturaControlsMigration.java:64:1: cannot find symbol
[error]   symbol:   class Session
[error]   location: class com.tle.core.kaltura.migration.UpdateKalturaControlsMigration
[error]     protected void executeDataMigration(HibernateMigrationHelper helper, MigrationResult result, Session session)
[error] /codebuild/output/src122370099/src/github.com/openequella/openEQUELLA/Source/Plugins/Kaltura/com.tle.core.kaltura/src/com/tle/core/kaltura/migration/UpdateKalturaControlsMigration.java:97:1: cannot find symbol
[error]   symbol:   class Session
[error]   location: class com.tle.core.kaltura.migration.UpdateKalturaControlsMigration
[error]     protected int countDataMigrations(HibernateMigrationHelper helper, Session session)
```

2020-10-09 18:08 UTC, cbeach47 commented
Ah yes - Here's a fix for that - https://github.com/openequella/openEQUELLA-Kaltura/pull/5

@edalex-ian - any clever ideas on how to get this PR's CodeBuild to pickup the oEQ-K PR #5 ?  Otherwise, do we just need to merge #5 now?

2020-10-13 23:48 UTC, cbeach47 commented
Well that's encouraging to see green checks across the board.  : )

Before I switch this PR out of draft mode, highlights of my todo list are:
- Review the `TODO [SpringHib5]` comments
- Understand why SQL Server is deadlocking on `com.tle.webtests.test.importexport.CloneTest` when deleting institutions
- Understand/resolve why Oracle is failing on import with `java.sql.SQLSyntaxErrorException: ORA-00904: "ITEMDEFINI1_1_"."ID": invalid identifier`
- Cluster test

2020-10-31 01:15 UTC, cbeach47 commented
@edalex-ian - this is finally ready for review.  I have noted in the description the areas I focused on for manual testing.

I will be doing some final runs of the autotests against the DBs next week, however the majority of the tests pass.

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Plugins/Admin/com.tle.web.adminconsole/build.sbt
> +  // As per https://stackoverflow.com/questions/54834125/sbt-assembly-deduplicate-module-info-class , discarding is OK for Java 8
Is this an error you anticipate people will run into?
Is including the error in the source a good way to guide adopters/future developers on how to work with this?

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Plugins/Admin/com.tle.web.adminconsole/jarsrc/build.sbt
> +  // since we already have logging in place, we can safely exclude the dep from spring.
Is this an error you anticipate people will run into?
Is including the error in the source a good way to guide adopters/future developers on how to work with this?

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Plugins/Admin/com.tle.web.adminconsole/jarsrc/build.sbt
> +  // As per https://stackoverflow.com/questions/54834125/sbt-assembly-deduplicate-module-info-class , discarding is OK for Java 8
Is this an error you anticipate people will run into?
Is including the error in the source a good way to guide adopters/future developers on how to work with this?

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Plugins/Applet/com.tle.web.filemanager.applet/appletsrc/build.sbt
> +  // As per https://stackoverflow.com/questions/54834125/sbt-assembly-deduplicate-module-info-class , discarding is OK for Java 8
Is this an error you anticipate people will run into?
Is including the error in the source a good way to guide adopters/future developers on how to work with this?

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/jarsrc/build.sbt
> +  // As per https://stackoverflow.com/questions/54834125/sbt-assembly-deduplicate-module-info-class , discarding is OK for Java 8
Is this an error you anticipate people will run into?
Is including the error in the source a good way to guide adopters/future developers on how to work with this?

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/dao/AbstractHibernateDao.java
> +      // template.setAllowCreate(false);
is this still pending review?

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/dao/AbstractHibernateDao.java
> +            // TODO need to understand the impact of the removal
is this still pending review?

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/equella/service/impl/InitialiserServiceImpl.java
> +              "Ignoring error with type ["
would it be possible/make sense to filter the objects for valid ones?
Or is swallowing the error the only/most effective way to handle this?

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateMigrationHelper.java
> +// directly.
How large would this change be?

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateServiceImpl.java
> +    //     SpringTransactionFactory.class.getName());
is this still a pending change?

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Plugins/Security/com.tle.core.security/src/com/tle/core/security/impl/SecurityAttributeSource.java
> +  // TODO - this assumes Java 5+ is required for oEQ.
Is Java 5 in the support matrix?
I thought it was already set to 7 or 8

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Server/equellaserver/build.sbt
> +  //  .../org.bouncycastle/bcprov-jdk15on/jars/bcprov-jdk15on-1.65.jar:META-INF/versions/9/module-info.class
Is this an error you anticipate people will run into?
Is including the error in the source a good way to guide adopters/future developers on how to work with this?

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Server/equellaserver/build.sbt
> +  // ...
Is this an error you anticipate people will run into?
Is including the error in the source a good way to guide adopters/future developers on how to work with this?

2020-11-05 22:24 UTC, ChristianMurphy commented on Source/Server/equellaserver/build.sbt
> +  // ...
Is this an error you anticipate people will run into?
Is including the error in the source a good way to guide adopters/future developers on how to work with this?

2020-11-05 22:24 UTC, ChristianMurphy commented on buildspec.yml
> +    # TODO [SpringHib5] keep this in sync with the appropriate oEQ-Kaltura branch before merging into `develop`, and eventually into `master`.
is this still todo?

2020-11-05 23:40 UTC, cbeach47 commented on Source/Plugins/Security/com.tle.core.security/src/com/tle/core/security/impl/SecurityAttributeSource.java
> +  // TODO - this assumes Java 5+ is required for oEQ.
Sounds right.  I did a search for documentation - our known supported software guide doesn't say - https://openequella.github.io/server-administration/KnownWorkingSupportingSoftware.html

SO - anyone concerned if we set the minimum version to 7, but note the developers only test against JDK 8?

2020-11-05 23:49 UTC, cbeach47 commented on Source/Plugins/Admin/com.tle.web.adminconsole/build.sbt
> +  // As per https://stackoverflow.com/questions/54834125/sbt-assembly-deduplicate-module-info-class , discarding is OK for Java 8
If folks omit that merge strategy with the current dependency tree, they'll hit the error.

I put that in there as documentation for why the merge strategy was put in place. I think _something_ should be in there as to why it was added, but if folks find it too noisy, I can make it more brief.  When affected deps are upgraded, a review of the associated merge strategies would be good, but very time consuming with the current build system.

2020-11-05 23:50 UTC, cbeach47 commented on Source/Plugins/Admin/com.tle.web.adminconsole/jarsrc/build.sbt
> +  // since we already have logging in place, we can safely exclude the dep from spring.
see note above

2020-11-05 23:50 UTC, cbeach47 commented on Source/Plugins/Admin/com.tle.web.adminconsole/jarsrc/build.sbt
> +  // As per https://stackoverflow.com/questions/54834125/sbt-assembly-deduplicate-module-info-class , discarding is OK for Java 8
see note above

2020-11-05 23:50 UTC, cbeach47 commented on Source/Plugins/Applet/com.tle.web.filemanager.applet/appletsrc/build.sbt
> +  // As per https://stackoverflow.com/questions/54834125/sbt-assembly-deduplicate-module-info-class , discarding is OK for Java 8
see note above

2020-11-05 23:50 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.core/jarsrc/build.sbt
> +  // As per https://stackoverflow.com/questions/54834125/sbt-assembly-deduplicate-module-info-class , discarding is OK for Java 8
see note above

2020-11-05 23:50 UTC, cbeach47 commented on Source/Server/equellaserver/build.sbt
> +  //  .../org.bouncycastle/bcprov-jdk15on/jars/bcprov-jdk15on-1.65.jar:META-INF/versions/9/module-info.class
see note above

2020-11-05 23:51 UTC, cbeach47 commented on Source/Server/equellaserver/build.sbt
> +  // ...
see note above

2020-11-05 23:51 UTC, cbeach47 commented on Source/Server/equellaserver/build.sbt
> +  // ...
see note above

2020-11-05 23:52 UTC, cbeach47 commented on buildspec.yml
> +    # TODO [SpringHib5] keep this in sync with the appropriate oEQ-Kaltura branch before merging into `develop`, and eventually into `master`.
Yes - we'll need to coordinate how to merge this PR into `develop`, and then up into `master` since Kaltura `master` has been historical used for all branch builds.

2020-11-06 05:27 UTC, cbeach47 commented
The recommended new hibernate and log4j configs are now added by default to installs and upgrades.

Tested with:
- `sbt prepareDevConfig`
- `sbt installEquella`
- Standalone installer
- Upgrader

2020-11-10 06:41 UTC, edalex-ian requested changes
Wowsers! Fair effort @cbeach47 - 246 files. I think I'm now permanently cross-eyed. :grin: 

Sure is a lot of type casting! :wink: 

Interesting to see all the deprecations that'll need to be addressed for `HibernateTemplate`. I guess that'll come in the next major version. :thinking: 

Interesting that with such a big Spring upgrade `HttpInvoker` for the Admin Console side of things didn't need to change. :thinking: 

Question: A lot of changes of single parameter queries simply from `?` to `?0`. Was this required with Hibernate 5, or more so a preference for explicitness? (Just curious.)

Anyway, there's a few things I'd like to see changed and tidied up (but nothing major), and it looks like there's still a few WIPs in play so will be interested to hear what else is to be done. But for now, back to you.

2020-11-10 06:41 UTC, edalex-ian commented on Dev/learningedge-config/defaults/learningedge-log4j.properties.default
> +# Generator warning suppression
I guess once these are merged in we should have a tech debt issue to map against. Ideally we'd reference that ticket here, but hen we have a bit of chicken and egg.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Admin/com.tle.web.adminconsole/build.sbt
> +  // As per https://stackoverflow.com/questions/54834125/sbt-assembly-deduplicate-module-info-class , discarding is OK for Java 8
I think it's fine. If we wanted to optimise I'd keep the first and last lines. (I.e. Concisely state the issue, and then any reference on approach taken.)

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/usermanagement/standard/ReplicatedConfiguration.java
> +  // ordinal since they aren't piped through JPA / Hibernate logic.
Not sure I'm following this new comment. I guess I'm confused that these aren't going through JPA / Hibernate (how are they used), but also that no other changes are below so is this comment still needed?

Feels like the comment might be a bit of a fragment of a bigger situation. :thinking: 

There's several instances of this comment, so I'm rather interested to understand.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/copyright/dao/AbstractCopyrightDao.java
> +                .find(query("select p.holding from %p p where p.item = ?0"), item); // $NON-NLS-1$
FYI - As we update code where it has the old NLS check comments, we've been removing them seeing it's now cruft with the absence any checking. Feel free to do the same.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/i18n/dao/impl/LanguageDaoImpl.java
> +        query.append('?').append(paramCounter++);
Would it be better to keep things simple (even if not enhanced for readability) by simply using `i` here? If we just want to enhance readability, I would't be opposed to a comment saying: generating ordinal parameter strings of ?0, ?1 .. ?n

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/item/dao/impl/ItemDaoImpl.java
> +          .append(paramCounter++)
As before, maybe just use `i`.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/item/dao/impl/ItemDaoImpl.java
> +    LOGGER.trace("selectForIds sql: " + hql);
Couple of considerations:

1. Is this still needed - or was it just while you were working through things? (This can be see just be turning on Hibernate logging.)
2. If still needed, maybe the log message can be improved and maybe change " sql:" to " HQL:"
3. Also consider placing in block of `if(LOGGER.isTraceEnabled())`

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/item/standard/dao/impl/ItemCommentDaoImpl.java
> +                    // Tread very carefully.
Gah!

Well, even the GitHub diff broken down on this one. But from what I can tell it looks like you were careful. Are you giving some extra special testing to this?

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/legacy/migration/RemoveAssemblerAndActivityWizard.java
> +    @ElementCollection(fetch = FetchType.LAZY)
Wow, I see this class was using a mixture of these annotations. Well, at least that's now tidied up. :+1:

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/settings/dao/impl/ConfigurationDaoImpl.java
> +    buffer.append(" and key.institutionId = ?").append(paramCounter++);
In this case I see the value of `paramCounter`. :+1: 

(Just thought I'd mention to avoid an ambiguity.)

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/core/filter/HibernateFilter.java
> +        // TODO - previous code with SessionFactoryUtils:
Is this TODO still to be done?

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/core/filter/HibernateFilter.java
> +    session.setHibernateFlushMode(FlushMode.MANUAL);
Oh! Is that right? Seems like a significant change and I don't see it in the old code. :thinking: :confused:

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/scalasrc/com/tle/core/db/RunWithDB.scala
> +    val con = sessionHolder.getSession().asInstanceOf[SessionImpl].connection()
@PenghaiZhang do you have any thoughts on how this can be re-worked with a lambda/anonymous function and the Work API mentions at the SO post?

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/ExtendedAnnotationConfiguration.java
>      while (iter.hasNext()) {
I'd normally comment about moving away from the iterator... However in the context and size of this PR, minimal change is good. :smile:

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/HibernateFactory.java
> +          LOGGER.trace("Adding annotated class: " + class1.getCanonicalName());
I'm concerned this could impact start-up times and load - even if only minor. Could this be wrapped in a `isTraceEnabled()` check please?

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/dao/AbstractHibernateDao.java
> +            // TODO need to understand the impact of the removal
What @ChristianMurphy said. :wink:

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/dao/GenericDaoImpl.java
> +    // Hibernate now throws an NullPointerException if we try evicting a null object
That could be for good reason, as it possibly implies we're in an unexpected state - but would depend on how oEQ is written.

To match your new `if` block I wonder if there is value having an `else` to log a warning. (Of it it's super prevalent, maybe at a lower log level.)

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/equella/service/impl/InitialiserServiceImpl.java
> +        if (iae.getMessage().startsWith("Non-entity object instance passed to evict")) {
This could be brittle. Are we better to have a look at the cause and/or stack trace and check the class, method or file?

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateMigrationHelper.java
> +// TECH_DEBT - found in SpringHib5, SessionFactoryImpl is now internal and should not be used
Should raise a matching GitHub issue and reference here.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateMigrationHelper.java
> +          }
All the additional logging has made this method now rather long and cumbersome - especially when combined with all the branching and nesting. I think now it needs to be split into it's core parts as part of this.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateMigrationHelper.java
> +    sqlStrings.add("Existing index is null.  Creating index SQL: " + sql);
Eeck! Am I reading this wrong? To me it seems `sqlStrings` should have ... SQL. It would seem this should have been another `LOGGER.debug()` followed by `sqlStrings.add(sql)`?

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateServiceImpl.java
> +// import org.springframework.orm.hibernate5.SpringTransactionFactory;
This combined with the TODO below makes it look like this file is still a WIP?

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/type/HibernateCsvType.java
> +// TECH_DEBT - found in SpringHib5, StringHelper is now internal and should not be used directly.
Needs a GitHub Issue and reference.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/InPlaceUniqueDelegate.java
> +//  in the create table logic, so we need to add our own.
Might as well do as proper bit of JavaDoc.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/InPlaceUniqueDelegate.java
> +    }
Could void the iterator and go with:

```java
    StringBuilder sb = new StringBuilder();
    table.getUniqueKeyIterator()
      .forEachRemaining(uniqueKey ->
        sb
          .append(", ")
          .append(uniqueConstraintSql(uniqueKey)));
```

Be nice to take it to a stream so you could simply reduce, but.... You're starting from an Iterator. :disappointed:

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/MySQL5DialectEQUELLA.java
> +    //  the supported oEQ DBs
That is interesting. Wonder if it still even works, or if it should be removed. Wonder if it'd be worth raising a GitHub ticket for someone to check. :shrug:

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/OeqImplicitNamingStrategy.java
> +public class OeqImplicitNamingStrategy extends ImplicitNamingStrategyJpaCompliantImpl {
Could you please add a JavaDoc description.

I gather it is only handling Join table bits, and the rest is all for logging. If so, two things:

1. The JavaDoc should capture that, and I wonder if we should have a more explicit class name - on the assumption that if we needed more we add them;
2. If we only have all the other methods for logging, do we need them? Or if one wanted to see what was happening should they just turn the logging on for `ImplicitNamingStrategyJpaCompliantImpl`?

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/OeqImplicitNamingStrategy.java
> +    LOGGER.trace(
Be nice if this had a `isTraceEnabled()` guard. And to save excessive messages - same with all the below trace messages where strings are being dynamically constructed.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/OeqPhysicalNamingStrategy.java
> +// TECH_DEBT - found in SpringHib5, StringHelper is now internal and should not be used directly.
Need GitHub Issue and ref.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/OeqPhysicalNamingStrategy.java
> +public class OeqPhysicalNamingStrategy extends ImprovedNamingStrategy
If it is still limited to lowercase naming of tables, then really the name it had before should remain.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/OeqPhysicalNamingStrategy.java
> +    LOGGER.trace(
`isTraceEnabled()` guard.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/SQLServerDialect.java
> +// TECH_DEBT - found in SpringHib5, StringHelper is now internal and should not be used directly.
As per elsewhere. I think this is the fourth or so, but if they all have the GitHub issue reference they'll be easy to fix when the time comes.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Generic/org.hibernate/build.sbt
> +  "org.hibernate"            % "hibernate-validator"   % "6.1.5.Final",
Interesting. Why didn't you keep this in the matching 5.4.x series to match core?

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Security/com.tle.core.security/src/com/tle/core/security/impl/SecurityAttributeSource.java
> +  // TODO - this assumes Java 5+ is required for oEQ.
You'll see in `project/CommonSettings.scala` that we build to target Java 8. So we should probably update the doco site, but also you're free to target 8 here. ;)

2020-11-10 06:41 UTC, edalex-ian commented on Source/Plugins/Security/com.tle.core.security/src/com/tle/core/security/impl/SecurityAttributeSource.java
> +    if (SystemUtils.isJavaVersionAtLeast(5)) {
Yup, as per above I don't believe we will run with < 8.

2020-11-10 06:41 UTC, edalex-ian commented on Source/Server/equellaserver/build.sbt
> +  "org.scala-sbt"                 %% "io"                       % "1.3.4",
Oh!! Hold on... That's a regression vs. the above.

And unfortunately that was an easy one to pick up. Due to the formatting changes it's very onerous to review all these and make sure they're correct. But being your PR, could I please ask that you go back and check all these. (Not just this block, but the real big blocks above.)

2020-11-10 06:41 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/src/com/tle/upgrade/LineFileModifier.java
> +            result.addLogMessage("Added line '" + addLine + "'");
Heh, nice pick up. :+1:

2020-11-10 06:41 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/src/com/tle/upgrade/upgraders/AddPostHib5UpgradeConfig.java
> +public class AddPostHib5UpgradeConfig extends AbstractUpgrader {
Could be good value in adding a JavaDoc description here with a synopsis of what upgrade steps are needed/included.

2020-11-10 06:41 UTC, edalex-ian commented on buildspec.yml
> +    # TODO [SpringHib5] keep this in sync with the appropriate oEQ-Kaltura branch before merging into `develop`, and eventually into `master`.
Hmmm, I wonder if you'll want to do the merges on your local machine, and then do an additional commit direct here to modify this, and then push both. :thinking:

2020-11-12 01:10 UTC, cbeach47 commented on Source/Plugins/Security/com.tle.core.security/src/com/tle/core/security/impl/SecurityAttributeSource.java
> +  // TODO - this assumes Java 5+ is required for oEQ.
Sounds good. I've removed the java version comments / checks and opened:

    https://github.com/openequella/openequella.github.io/pull/74

to update the docs.

2020-11-12 01:12 UTC, cbeach47 commented on Source/Plugins/Security/com.tle.core.security/src/com/tle/core/security/impl/SecurityAttributeSource.java
> +    if (SystemUtils.isJavaVersionAtLeast(5)) {
resolved as per above.

2020-11-12 01:22 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/item/standard/dao/impl/ItemCommentDaoImpl.java
> +                    // Tread very carefully.
The changes in this file were a handful of casts, and an `import` path switch.  The github diff unfortunately makes it look quite ugly.

For clarity, these are the type castings added:

![image](https://user-images.githubusercontent.com/28629296/98882816-b6ef8200-2452-11eb-93db-28b5c1c446af.png)

![image](https://user-images.githubusercontent.com/28629296/98882851-d4bce700-2452-11eb-9752-262e6963d423.png)

![image](https://user-images.githubusercontent.com/28629296/98882885-e7cfb700-2452-11eb-9251-b4ba5feb400d.png)

2020-11-12 17:50 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/i18n/dao/impl/LanguageDaoImpl.java
> +        query.append('?').append(paramCounter++);
yeah, that's a good point - I switched out `paramCounter` for `i`.

2020-11-12 18:04 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/item/dao/impl/ItemDaoImpl.java
> +          .append(paramCounter++)
Sounds good :+1:

2020-11-12 18:09 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/item/dao/impl/ItemDaoImpl.java
> +    LOGGER.trace("selectForIds sql: " + hql);
I find it helpful to look at the query before Hibernate touches it, so I left it in.  I did wrap it in the `isTraceEnabled` block and improved the messaging.

2020-11-12 18:41 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/HibernateFactory.java
> +          LOGGER.trace("Adding annotated class: " + class1.getCanonicalName());
yep, done.

2020-11-12 18:54 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/dao/GenericDaoImpl.java
> +    // Hibernate now throws an NullPointerException if we try evicting a null object
I like the idea of not just swallowing the null object state.  I added a warning and will check the logs during tests - it's currently the only logging statement in the class, so if it gets noisy, it's simple enough to switch off.

2020-11-12 20:49 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateMigrationHelper.java
> +// directly.
Interesting - looks like a pretty minor change.  I got rid of the internal reference.  If things start breaking, I'll revert an open an issue ticket for `tech_debt`.

2020-11-12 20:50 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateMigrationHelper.java
> +// TECH_DEBT - found in SpringHib5, SessionFactoryImpl is now internal and should not be used
Ended up just removing the internal reference.

2020-11-12 21:23 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateMigrationHelper.java
> +    sqlStrings.add("Existing index is null.  Creating index SQL: " + sql);
oy - good catch.

2020-11-12 21:33 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateServiceImpl.java
> +    //     SpringTransactionFactory.class.getName());
no - leftover comment - the default strategy of JDBC suffices.

2020-11-12 21:34 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateServiceImpl.java
> +// import org.springframework.orm.hibernate5.SpringTransactionFactory;
no - I'll remove the comment and the todo - the default strategy of JDBC suffices.

2020-11-12 21:41 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/type/HibernateCsvType.java
> +// TECH_DEBT - found in SpringHib5, StringHelper is now internal and should not be used directly.
Ended up removing that comment entirely

2020-11-12 21:47 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/InPlaceUniqueDelegate.java
> +    }
works for me - done.

2020-11-12 21:52 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/MySQL5DialectEQUELLA.java
> +    //  the supported oEQ DBs
Can't hurt - I opened https://github.com/openequella/openEQUELLA/issues/2508

2020-11-12 22:05 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/OeqImplicitNamingStrategy.java
> +public class OeqImplicitNamingStrategy extends ImplicitNamingStrategyJpaCompliantImpl {
Currently all dialects use the same naming strategies, so the name implies it's __the__ oEQ strategy.  If it a dialect needs to branch off into it's own future, I lean towards renaming at that point.

The overridden methods to inject logging was noisy.  I removed those and guarded the trace statements.

2020-11-12 22:11 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/OeqImplicitNamingStrategy.java
> +    LOGGER.trace(
done.

2020-11-12 22:21 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/OeqPhysicalNamingStrategy.java
> +public class OeqPhysicalNamingStrategy extends ImprovedNamingStrategy
It's not only lower-casing the table names, and in the spirit of the theory behind the Implicit Naming Strategy, I'd like to leave it general for now.  I updated the javadoc to help reflect that mindset.

2020-11-12 22:53 UTC, cbeach47 commented on Source/Plugins/Generic/org.hibernate/build.sbt
> +  "org.hibernate"            % "hibernate-validator"   % "6.1.5.Final",
Not super intuitive, but hibernate projects don't have a 'release train'. From https://hibernate.org/community/compatibility-policy/ :
> There is no "release train" in Hibernate projects. Each Hibernate project releases new versions independently and picks the version of its dependencies according to its needs and compatibility requirements.

2020-11-12 23:19 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/usermanagement/standard/ReplicatedConfiguration.java
> +  // ordinal since they aren't piped through JPA / Hibernate logic.
I've revised the comment to the following.  I figured adding this comment without code changes would help clarify why there is a difference.  Does the revision make more sense?

```
// General note on the queries in this class - With the advent of hibernate 5,
// queries with '?' in them need to be ordinal ( ie `?4` ).  However, this class
// does not leverage the JPA / Hibernate logic, so we can leave the `?`s as-is.
```

2020-11-12 23:57 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/core/filter/HibernateFilter.java
> +        // TODO - previous code with SessionFactoryUtils:
mmm leftover comment.  I'll clean it up

2020-11-13 01:21 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/core/filter/HibernateFilter.java
> +    session.setHibernateFlushMode(FlushMode.MANUAL);
Thanks for calling this out - interesting logic on this one.  I've added a comment in the code to explain why MANUAL is chosen.  Please let me know if there are further questions on this one.

2020-11-13 01:26 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/dao/AbstractHibernateDao.java
> +      // template.setAllowCreate(false);
Ah - no, just a leftover comment.  I'll clean it up.

2020-11-13 01:27 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/dao/AbstractHibernateDao.java
> +            // TODO need to understand the impact of the removal
Ah - no, just a leftover comment.  I'll clean it up.

2020-11-13 01:37 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/equella/service/impl/InitialiserServiceImpl.java
> +              "Ignoring error with type ["
Please see response above.

2020-11-13 02:54 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/equella/service/impl/InitialiserServiceImpl.java
> +        if (iae.getMessage().startsWith("Non-entity object instance passed to evict")) {
It may work as well to bind to the stack trace, class, or other indicator(s).  However, after further consideration of the situation, I feel it’s sufficient to bind to the message than a specific stack trace, given the message specificity.

2020-11-13 03:08 UTC, cbeach47 commented on Source/Server/equellaserver/build.sbt
> +  "org.scala-sbt"                 %% "io"                       % "1.3.4",
I don't know why the formatter does that.  I thought the massive reformat a while back was supposed to resolve this kind of 'big block' diffs where little changes can hide.

Either way, I compared the tip of `develop` with this file, and `scala-sbt` was the only regression.  Thanks for the catch.

2020-11-13 03:20 UTC, cbeach47 commented
@edalex-ian  / @ChristianMurphy  - thanks for the reviews.  I've pushed the revisions and provided commentary. I think the only outstanding item is to break apart that one method that got a bit lengthy with the `debug` statements. I have that and some minor things to tidy up next week along with a condensed round of testing, but I think we are close. 

For the Work API effort, while I'm not specifically against it being enhanced now, due to the budget / timeline and that it is functional, I'm considering if it should be a `tech_debt` issue.

Ian - to your question:
> A lot of changes of single parameter queries simply from ? to ?0. Was this required with Hibernate 5, or more so a preference for explicitness? (Just curious.)
This was required with Hibernate 5.

Please take another look at my responses to this review and let me know if anything else stands out to you.

2020-11-13 08:55 UTC, cbeach47 commented
@edalex-ian - could you please let me know why CodeBuild is failing?

2020-11-15 22:52 UTC, edalex-ian commented
> @edalex-ian - could you please let me know why CodeBuild is failing?

Looks like maybe the browser died when running the ScalaCheck tests. Odd, so I'm retrying now. :crossed_fingers:

2020-11-16 20:18 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateMigrationHelper.java
> +          }
Fair point - This is split out now

2020-11-16 20:58 UTC, ChristianMurphy reviewed
Thanks @cbeach47 the code looks good.
Question from the documentation side, will we need a migration guide for hibernate 5?
Are there any minor (or major) updates needed to the existing openEquella guides to reflect the the new Hibernate version?

2020-11-16 21:19 UTC, cbeach47 commented
I appreciate the review @ChristianMurphy . I plan to put a blurb in the release notes about the log4j and hib configs, but it should be normal operations otherwise

2020-11-16 21:19 UTC, cbeach47 commented
@edalex-ian - CodeBuild is failing again :/  Is the browser still dying?

2020-11-16 22:14 UTC, edalex-ian commented
> @edalex-ian - CodeBuild is failing again :/ Is the browser still dying?

Yup, looks like it. I'm retrying now.

2020-11-16 23:32 UTC, cbeach47 commented
Thx - CodeBuild looks happier now.  `functional_testing (false)` with a TimeoutException so I'm retrying the jobs.

2020-11-16 23:47 UTC, cbeach47 commented
In testing, I learned that oEQ on Oracle starts up a bit slower as well as migrates the database slower with the Spring / Hib 5 code vs tip of develop - each takes minutes.  Once the database stats are optimized, the difference of speed, for just startup, is under 10 seconds, and the migration is now within seconds, both of which I think are manageable.  Note, SQL Server and Postgres didn't experience any noticeable slowdowns. 

Looks like the query that causes the issue is in `Oracle8iDialect`, which contains `getQuerySequencesString()` > `select * from all_sequences`.  

Running that `select` query from the command line took about 50 seconds.  From this SO post ( https://stackoverflow.com/questions/61016702/oracle-select-from-all-sequences-too-slow ), I optimized the database ( see below ) and now that query takes less than seconds to run.

```
begin
    dbms_stats.gather_dictionary_stats;
    dbms_stats.gather_fixed_objects_stats;
end;
/
```

Putting this here as a reminder to add into the release notes for adopters on Oracle.

2020-11-17 00:25 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/scalasrc/com/tle/core/db/RunWithDB.scala
> +    val con = sessionHolder.getSession().asInstanceOf[SessionImpl].connection()
Since this works, and we're getting close on time, I propose I move this into a tech debt issue.  

@edalex-ian - any concerns with that path forward?

2020-11-17 00:38 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/usermanagement/standard/ReplicatedConfiguration.java
> +  // ordinal since they aren't piped through JPA / Hibernate logic.
Good stuff. :+1:

2020-11-17 00:40 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/scalasrc/com/tle/core/db/RunWithDB.scala
> +    val con = sessionHolder.getSession().asInstanceOf[SessionImpl].connection()
Sure thing. Tech debt issue it is. :+1:

2020-11-17 00:48 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/equella/service/impl/InitialiserServiceImpl.java
> +        if (iae.getMessage().startsWith("Non-entity object instance passed to evict")) {
I guess the only difference if it does break is that a debug log message will be missing, so no probs. :wink:

2020-11-17 00:51 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateMigrationHelper.java
> +  }
Nice work @cbeach47 :+1:

2020-11-17 00:51 UTC, cbeach47 commented on buildspec.yml
> +    # TODO [SpringHib5] keep this in sync with the appropriate oEQ-Kaltura branch before merging into `develop`, and eventually into `master`.
Not sure of the value add in doing local merges in this case.  Personally, I would rather have github processes do as much of the flow as possible.

The problem I see is we now have to keep `openEQUELLA` and `openEQUELLA-Kaltura` branches in sync.

I think the simplest solution would be to setup the following branches in `openEQUELLA-Kaltura`:
* `master-pre-hib5`
* `master-post-hib5`
* `develop`

And then as part of the openEQUELLA release process, we modify the CodeBuild branch for Kaltura as needed.

I've also considered having the branches in `openEQUELLA-Kaltura` mimic `openEQUELLA`'s branches, but that seems like a lot of effort for little gain.

@edalex-ian - interested in your thoughts on how to proceed.

2020-11-17 01:03 UTC, edalex-ian reviewed
Looks good @cbeach47 

Just a couple of things to tidy. But with time in mind, should be good to press on.

2020-11-17 01:03 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateMigrationHelper.java
> +    LOGGER.debug("Existing index is null.  Creating index SQL: " + sql);
Hmmm, good to see this fixed, but.... Should the `String` output from `index.sqlCreateString()` be added to `sqlStrings`? As that looks like it just creates the string for logging purposes only. But ultimately this method is about processing the indices?

2020-11-17 01:03 UTC, edalex-ian commented on Source/Plugins/Security/com.tle.core.security/src/com/tle/core/security/impl/SecurityAttributeSource.java
> +    specificMethod = BridgeMethodResolver.findBridgedMethod(specificMethod);
So this then makes the assignment on line 91 redundant. Perhaps this line should merge with 91 to make

```java
    Method specificMethod = BridgeMethodResolver.findBridgedMethod(specificMethod);
```

2020-11-17 01:15 UTC, edalex-ian commented on buildspec.yml
> +    # TODO [SpringHib5] keep this in sync with the appropriate oEQ-Kaltura branch before merging into `develop`, and eventually into `master`.
No probs, up to you.

With the branches, I'd say you'd only want to end up with:

* `develop`
* `master` - representing the current up to date code matching oEQ `master`
* `pre-2020.2-support`

Keeps things simple, but with explicit names. And if you really wanted to highlight the point on the master branch, drop a tag on `master` with a name like `hibernate5-upgrade`. Or then again, a version tag should highlight that. :thinking:

2020-11-17 16:37 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/impl/HibernateMigrationHelper.java
> +    LOGGER.debug("Existing index is null.  Creating index SQL: " + sql);
nice catch - tip of `develop` has it in there.  I've left the logger msg in place, and added the `sql` into `sqlStrings` now.

2020-11-17 16:44 UTC, cbeach47 commented on Source/Plugins/Security/com.tle.core.security/src/com/tle/core/security/impl/SecurityAttributeSource.java
> +    specificMethod = BridgeMethodResolver.findBridgedMethod(specificMethod);
Yeah, that is a bit odd.  I'll streamline it

2020-11-17 17:15 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.serverbase/scalasrc/com/tle/core/db/RunWithDB.scala
> +    val con = sessionHolder.getSession().asInstanceOf[SessionImpl].connection()
Sounds good - https://github.com/openequella/openEQUELLA/issues/2525

2020-11-17 17:23 UTC, cbeach47 commented on buildspec.yml
> +    # TODO [SpringHib5] keep this in sync with the appropriate oEQ-Kaltura branch before merging into `develop`, and eventually into `master`.
I like the names you noted - having the version is good, but we don't have to necessarily create a oEQ-K branch for each oEQ branch.  I think the version tag will suffice for the tagging.

2020-11-17 18:06 UTC, cbeach47 commented
@edalex-ian I am going to run some regression tests due to this recent revisions.  Assuming I don't find anything awry, I believe this PR is good for merging (along with the Kaltura branch efforts discussed in the PR).  My goal is to do the merge tomorrow (Wednesday in the US).

Any final comments before I proceed?

2020-11-17 21:44 UTC, edalex-ian commented
> @edalex-ian I am going to run some regression tests due to this recent revisions. Assuming I don't find anything awry, I believe this PR is good for merging (along with the Kaltura branch efforts discussed in the PR). My goal is to do the merge tomorrow (Wednesday in the US).
> 
> As per our previous discussions, I plan to 'squash and merge' so the commit is clean.
> 
> Any final comments before I proceed?

I think that's fine @cbeach47 . In an ideal world, it'd be great if we also had time to run it up and play, but we'll just have to wait until the merge.

And on the merge, I think a squash probably makes sense in this case. :+1: 

Good luck. :crossed_fingers:

2020-11-17 21:49 UTC, cbeach47 commented
sounds good.

Another bit for the release notes - hibernate on Oracle creates these `HT_` global temporary tables.  This appears to be appropriate (according the doc link below, they note it's probably the 'best choice').  If an adopter cannot have the DDL change that much, hibernate makes strategies available ( https://in.relation.to/2017/02/01/non-temporary-table-bulk-id-strategies/  via the hibernate configs.  Have not specifically tested them, but they are standard hibernate options.

2020-11-18 01:26 UTC, cbeach47 commented
FYI - https://github.com/openequella/openEQUELLA/issues/2528

I don't believe this blocks this PR and we can release oEQ with the warning since it's documented now.  @edalex-ian - please let me know if this raises a concern with you.

2020-11-18 17:38 UTC, cbeach47 commented on buildspec.yml
> +    # TODO [SpringHib5] keep this in sync with the appropriate oEQ-Kaltura branch before merging into `develop`, and eventually into `master`.
Branches are now created and pushed.  Will open a PR against that repo with a quick explanation of the branches after this merging is complete.

2020-11-18 17:42 UTC, merged