EBP: Improve URL attachment dialog styles
openequella/openEQUELLA pull request #2359
Opened 2020-10-02 01:58 UTC by SammyIsConfused

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] screenshots are included showing significant UI changes

##### Description of change
#1983 
Turns out the styles applied to the file attachment dialog in #2255 didn't apply in the URL attachment dialog, and so this PR applies the same styling to the URL dialog.
Before change:
![image](https://user-images.githubusercontent.com/24543345/94880422-38441400-04a6-11eb-981a-7a03126faafc.png)

After change:
![image](https://user-images.githubusercontent.com/24543345/94880393-22365380-04a6-11eb-8453-8e80f766797a.png)

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-10-04 22:27 UTC, mrblippy reviewed
I guess my only query would be the blank space between the two panels. Is that also how file attachment dialog looks?

2020-10-04 22:45 UTC, SammyIsConfused commented
> I guess my only query would be the blank space between the two panels. Is that also how file attachment dialog looks?

Not quite, but the structure of the dialog is different here. If I were to make it look identical, it would break the other page of the dialog (the initial dialog you input the URL in)

2020-10-05 00:51 UTC, edalex-ian requested changes
Looks good other than the duplicated block. Please address, and then it should be fine to go.

2020-10-05 00:51 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +  }
It'd seem here that the intention is to match that of the same classes when under `.fileHandler`. As a result, a mixin should be used to keep things DRY and avoid copy pasta.

2020-10-05 03:00 UTC, edalex-ian approved these changes
LGTM, but just a query on the naming of the new mixin.

2020-10-05 03:00 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +@mixin editDialogCommonStyles {
A query on the name here. `editDialog` seems very generic, is that the intention - i.e. that it could be used on any of the dialogs for editing? Or, should it be slightly more specific like `editAttachmentDialog`?

2020-10-05 03:22 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +@mixin editDialogCommonStyles {
It should mainly have been for editing attachments, yeah. I've renamed to `editAttachmentDialogStyles`.

2020-10-05 23:48 UTC, merged