View Item comment count from new search page
openequella/openEQUELLA pull request #2410
Opened 2020-10-15 04:45 UTC by PenghaiZhang

#1306

### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Show the number of Comments as a link. Clicking the link will open Item Summary page with `#comments-list` anchor. 

The link is hidden if users don't have permission to view comment or the number is 0.

![image](https://user-images.githubusercontent.com/47203811/96078221-73f6c900-0efd-11eb-9072-f62f29d5b3de.png)

2020-10-15 06:29 UTC, edalex-ian requested changes
Looks good @PenghaiZhang 

But needs to tests added to `SearchResult.test.tsx` at least for some and none comments. Also, do a quick check of the Storybook story.

(Also note, my PR #2411 heavily plays in `SearchResult` - and its tests and stories - as well.

2020-10-15 22:09 UTC, PenghaiZhang commented
Screenshots from Storybook: 

Show comment count: 
![image](https://user-images.githubusercontent.com/47203811/96191128-32166300-0f8f-11eb-9f47-be07bc3eb730.png)


Hide comment count: 
![image](https://user-images.githubusercontent.com/47203811/96191159-44909c80-0f8f-11eb-87a1-daf3666a6596.png)

2020-10-15 23:18 UTC, edalex-ian requested changes
Thanks for adding the tests! :+1: 

A few tweaks and considerations for them.

2020-10-15 23:18 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +      queryByLabelText(container, `No comments`, { selector: "a" })
Should use the languageString for 'No comments'.

2020-10-15 23:18 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +      expect(countLink).toBeInTheDocument();
This line will never fail, because if `getByText` fails it'll throw an exception. In this context I normally go with queryByText for an item to be checked.

2020-10-15 23:18 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +      const { container } = renderSearchResult(item);
Better to just go straight to destructing what you want:

```suggestion
      const { getByText } = renderSearchResult(item);
```

2020-10-15 23:18 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +        formatSize(item.commentCount ?? 0, languageStrings.searchpage.comments),
This is kind of just copying the same code from the code under test. Almost like testing 1 === 1 directly. Really a test should do it a different way to the code under test.

2020-10-16 02:31 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +      expect(countLink).toBeInTheDocument();
Ah I completely forgot this :)

2020-10-18 21:59 UTC, PenghaiZhang commented
GHA failed to install OS tools so I restarted it again.

2020-10-19 00:02 UTC, edalex-ian approved these changes
LGTM! Merge on. :grin:

2020-10-19 00:06 UTC, merged