Feature/legacy search params
openequella/openEQUELLA pull request #2414
Opened 2020-10-15 23:07 UTC by mrblippy

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes

##### Description of change

#1306

This feature allows a Legacy /searching.do url and query parameters to be used on the new search page.
![old to new search](https://user-images.githubusercontent.com/4625498/96150046-bc41d580-0f55-11eb-98bc-eeefe2438d98.gif)

Some bumps were experienced while writing an additional SearchPage test. From my commit message:
> * I also had to add the esModuleInterop property to tsconfig. Otherwise, the rendering of a SearchPage with dateRangeQuickModeEnabled in jest will fail. The solution was found at https://github.com/mui-org/material-ui-pickers/issues/805
> * I had to modify how the imports work in the jest setup. This came about as a result of adding the esModuleInterop

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-10-16 05:45 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/routes.tsx
> +    path: "(/page/search|/searching.do)",
The change made here means we are no long able to see the old search page in new UI mode. I think we still need the old search page at this stage.

2020-10-16 16:22 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/jest.setup.ts
> +configure({ adapter: new adapter.default() });
Would this be the same as

```suggestion
import Adapter from "enzyme-adapter-react-16";
configure({ adapter: new Adapter() });
```

?

2020-10-16 16:22 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsconfig.json
> +    "esModuleInterop": true,
Are synthetic defaults needed?
Could this polyfill be avoided by using `import * as SomeName from 'some-package'` instead of `import SomeName from 'some-package'`?

2020-10-16 16:29 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    rangeType: string,
Could range type be narrowed?

```suggestion
  type RangeType = "between" | "after" | "before" | "on";

  const getLastModifiedDateRange = (
    rangeType: RangeType,
```

2020-10-18 22:30 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/routes.tsx
> +    path: "(/page/search|/searching.do)",
This change will not affect `Selection Section` because  `Selection Section` does not use routes.

2020-10-18 23:09 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/routes.tsx
> +    path: "(/page/search|/searching.do)",
This change will affect `Selection Section` if it's in `selectOrAdd` mode. The reason is in this mode, the URL to search page is  `searching.do` whereas it's `access/course/searching.do` in the other mode.

2020-10-18 23:21 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/routes.tsx
> +    path: "(/page/search|/searching.do)",
> The change made here means we are no longer able to see the old search page in new UI mode. I think we still need the old search page at this stage.

I thought that was our intention, to remove access to the old searching.do in the upcoming release of oEQ

2020-10-18 23:52 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> + * @return SearchOptions object
This function can also return `undefined`.

2020-10-18 23:52 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  const getUserDetails = async (
Just a personal taste here: if you change the signature of `resolveUsers` to use rest parameters, than here you can simplify the function to 
```
 const getUserDetails = async (
    userId: string
  ): Promise<OEQ.UserQuery.UserDetails> => await resolveUsers(userId)[0]
```

2020-10-18 23:52 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +      undefined,
Have you tested when `getQueryParam(LegacySearchParams.SORT)` returns undefined ? I feel casting undefined to SortOrder will cause error.

2020-10-18 23:52 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +          sortOrder:
I wonder what will happen in this scenario.
 `queryStringSearchOptions` includes sortOrder being Rank, changed the sort order to Datemodified, go to another page and go back. Which sort order will be remembered?

2020-10-18 23:52 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
> +      // if there is a current query, clear it out and trigger a search
Hehe this is the same thing I did, and then I changed back to `iff`.

2020-10-19 00:06 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsconfig.json
> +    "esModuleInterop": true,
May I ask what are the reasons to add these two configurations?

2020-10-19 00:08 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/jest.setup.ts
> +configure({ adapter: new adapter.default() });
@ChristianMurphy I tried this out, but the Adapter import is giving me an error in intellij

`TS1259: Module '"/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/@types/enzyme-adapter-react-16/index"' can only be default-imported using the 'esModuleInterop' flag` 

But, despite this error, all of the js tests are passing, so maybe it's ok?

2020-10-19 00:49 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsconfig.json
> +    "esModuleInterop": true,
Inside my jest test I was rendering the SearchPage component with `dateRangeQuickModeEnabled: false`, which causes the utils prop of MuiPickersUtilsProvider in DateRangeSelector to be undefined. Because the LuxonUtils import isn't working properly
[This link](mui-org/material-ui-pickers#805) suggested adding those configuration options to get around the issue.

But, as mentioned by @ChristianMurphy above. I can avoid making changes to the tsconfig.json and jest.setup.ts, simply by modifying the LuxonUtils import in DateRangeSelector.tsx

2020-10-19 01:00 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    rangeType: string,
Yes, i believe so. Good idea @ChristianMurphy

2020-10-19 01:17 UTC, edalex-ian requested changes
Wow, fair bit in there hey! :)

A few things to tidy up, as well as some testing and refactoring an ACL string literal. But also looks like it'll be good to get `runtypes` in.

Any questions, give me a shout.

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +    const mockedCollection = jest.spyOn(
These variable names are mis-leading. Makes it sound like it's just a mock for singular data structure. Better to go with `mockedResolveUsers` and `mockedCollectionListSummary`. (Mind you, that second one is not ideal, but at least you're matching the function name you're mocking.)

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +      `converts legacy date range query params: %s to search options containing lastModifiedDateRange of %s`,
No need for string template / backticks here:

```suggestion
      "converts legacy date range query params: %s to search options containing lastModifiedDateRange of %s",
```

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +      async (queryString, expectedRange: DateRange) => {
Rather than specifying your types here, I feel it'd be better up in the generic for `.each`. So you'd have:

```typescript
it.each<string, DateRange>([
```

And then here you'd omit the typing.

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +  describe("convertParamsToSearchOptions", () => {
There's no testing in here for any error handling.

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +const mockQueryParamSearchOptions = jest.spyOn(
```suggestion
const mockConvertParamsToSearchOptions = jest.spyOn(
```

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +  it("should call convertParamsToSearchOptions if there were query paramaters in url", async () => {
You test here is saying it should call the function _if there were query parameters in url_ however you don't appear to be setting such in the URL. Did I miss something.

And arguably, there should be an inverse function then to ensure it's not called if there are none. (If such implied constraints are correct.)

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/jest.setup.ts
> +configure({ adapter: new adapter.default() });
Like @ChristianMurphy I'm also unsure what you're doing here. It looks almost like for like.

But also, I'm not sure _why_ you're playing here. The tests you updated were React Testing Library based - not enzyme. Could you please tell us what's the haps?

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsconfig.json
> +    "esModuleInterop": true,
Similar to `jest.setup.ts`, what was the issue you're trying to address here?

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/routes.tsx
> +    path: "(/page/search|/searching.do)",
Ultimately yes, but not as part of this work - we plan to do that once all the search features are available in the New Search UI. (And then we'll also remove the toggle option etc.)

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +}
Just a reminder that typescript enums are removed post transpilation and can cause issues in Jest tests. So we're pretty well staying away from them.

The more idiomatic way of JS is to use constants, or in typescript it seems safer to go with simple string unions - as unpalatable as that may feel coming from other languages. And lastly, if you also wish to be able to enumerate what is available (not possible with either of the above) then we do have the option of `Union` fom [runtypes](https://www.npmjs.com/package/runtypes) as I use in the REST module.

Any this just in... I've found that runtypes has [Pattern Matching](https://www.npmjs.com/package/runtypes#pattern-matching)!! I was looking for that in my View Attachments work to avoid a switch statement - and so would be a great fit for you here.

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> + * @param queryString query string params from a shared searching.do url
```suggestion
 * @param queryString query string params from a shared `searching.do` URL
```

Two things there:

* good to get capitalisation for acronyms right; and
* You can use markdown in these comments and the formatting will carry over (if we ever get around to generating it)

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +export const convertParamsToSearchOptions = async (queryString: string) => {
Please specify return type.

For exported / externally used functions they should be fully typed.

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  if (!queryString) return undefined;
Should this either:

* Return default search options; or
* Throw an error

More so though, is this redundant as the function signature does not allow `undefined`. :thinking:

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    return userDetails[0];
So if a `userId` is invalid, then I guess (without having read `resolveUsers`) that `userDetails.length` could be less than 1 and this will return `undefined`. Should you specify that in the return type, or do you need to throw or...

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    const collectionList = await collectionListSummary(["SEARCH_COLLECTION"]);
This will now have the `SEARCH_COLLECTION` string in three (+) places. Being a standard ACL arguably it should in an `ACL_SEARCH_COLLECTION` constant. Maybe we need a `oeq-ts-rest-api/src/Acl.ts`.

This ideally would've been addressed when we reached two instances, so we definitely need to do it now.

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    rangeType: string,
So as mentioned above, I reckon let's bring in `runtypes` and then setup a `Union` for the ranges, and then with that in place you can also replace the below switch statement using `rangeType` a pattern match.

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +        dr = { start: primaryDate ?? undefined };
What's the `??` here for when primaryDate is typed as `Date` - i.e. no `undefined` or `null` allowed.

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +      (getQueryParam(LegacySearchParams.SORT)?.toUpperCase() as SortOrder) ||
Should this be:

```suggestion
      (getQueryParam(LegacySearchParams.SORT)?.toUpperCase() as SortOrder) ??
```

?

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  const searchOptions: SearchOptions = {
I wonder if in the below where you do various coalescing to `undefined` or `""` whether you really should be going back to the value from `defaultSearchOptions`?

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/UserModule.ts
> + * @param ids An array of oEQ ids
We know it's an array (more or less) from the type signature. How about reworking to something more generic - and also defining which IDs:

```suggestion
 * @param ids A list of oEQ user IDs
```

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +  };
Two things:

1. Why were the superfluous curly braces added?
2. In doing so we've no lost white space between the end of this function (`handleQueryChanged`) and the next (`handleCollectionSelectionChanged`).

2020-10-19 01:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
> +      // if there is a current query, clear it out and trigger a search
Yup, it was `iff` as in https://en.wikipedia.org/wiki/If_and_only_if

But if it keeps confusing people, then we can leave it.

2020-10-19 01:17 UTC, edalex-ian commented on autotest/Tests/src/test/scala/equellatests/tests/SearchQueryProperties.scala
>  object SearchQueryProperties extends ShotProperties("Search Query Properties") {
We probably need to mark this test with a TODO so that @PenghaiZhang can pick is up when he does his work to exclude tests which only work in old or new from certain modes. :thinking:

2020-10-19 02:44 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsconfig.json
> +    "esModuleInterop": true,
I remember  I used to try the modified LuxonUtils import in DateRangeSelector.tsx and I got warnings/errors, but I might be wrong.

2020-10-19 02:47 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/jest.setup.ts
> +configure({ adapter: new adapter.default() });
interesting 🤔 
In it's current form could `as any` be removed?

2020-10-19 03:06 UTC, mrblippy commented on autotest/Tests/src/test/scala/equellatests/tests/SearchQueryProperties.scala
>  object SearchQueryProperties extends ShotProperties("Search Query Properties") {
Yes indeedy

2020-10-19 03:25 UTC, PenghaiZhang commented on autotest/Tests/src/test/scala/equellatests/tests/SearchQueryProperties.scala
>  object SearchQueryProperties extends ShotProperties("Search Query Properties") {
Yes, please also add this in Jira ticket.

2020-10-19 05:32 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  const searchOptions: SearchOptions = {
Yeah, i think that would be a good idea. Helps with consistency

2020-10-23 03:23 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/jest.setup.ts
> +configure({ adapter: new adapter.default() });
Nah, any cannot be removed

2020-10-23 03:24 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsconfig.json
> +    "esModuleInterop": true,
Yeah, you are correct Penghai, changing the import makes the tests work. But it breaks the control when viewed in the browser. I have put it back to how it was

2020-10-23 03:25 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> + * @return SearchOptions object
Yes, i have added that

2020-10-23 03:25 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +      undefined,
It didn't cause any errors that I could see

2020-10-23 03:25 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +          sortOrder:
yeah

2020-10-23 03:25 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
> +      // if there is a current query, clear it out and trigger a search
I changed it back, but now I know what iff means :)

2020-10-23 03:31 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +    const mockedCollection = jest.spyOn(
I was just following the convention we had in other tests. But yeah, your suggested change makes sense

2020-10-23 03:34 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +  };
I don't know how that got added. But i will change it back

2020-10-23 03:35 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    return userDetails[0];
I have specified undefined in the return type

2020-10-23 03:36 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +  it("should call convertParamsToSearchOptions if there were query paramaters in url", async () => {
This was an oversight by me. I have altered the test to simulate how a query string will be handled when accessing the SearchPage

2020-10-23 03:39 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/jest.setup.ts
> +configure({ adapter: new adapter.default() });
I was having issues rendering the search page inside tests with Quick Options disabled for the DateRangeSelector control. More information on the issue can be found here https://github.com/mui-org/material-ui-pickers/issues/805

2020-10-23 03:40 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +  describe("convertParamsToSearchOptions", () => {
Perhaps I am missing something here. But what error handling would i need to do?

2020-10-23 06:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +  describe("convertParamsToSearchOptions", () => {
Incorrect/corrupt params or values are set in the URL string - failures to look-up collections/values.

2020-10-23 13:53 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/jest.setup.ts
> +configure({ adapter: new adapter.default() });
I'm not sure I follow here, the issue referenced has to do with Moment not Enzyme.

Looking at `enzyme-adapter-react-16` both the source https://github.com/enzymejs/enzyme/blob/7c898db96505f1e7e7462797e8aa4bc90d3cf2ec/packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js#L967 and the built version https://unpkg.com/enzyme-adapter-react-16@1.15.5/build/index.js
use common js imports

This would most likely be related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29655
The official solution appears to be https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9b525a23c4f0c86b9832522f4345ab21e9e71e70/types/enzyme-adapter-react-16/enzyme-adapter-react-16-tests.ts#L2

2020-10-23 13:55 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/jest.setup.ts
> +configure({ adapter: new adapter.default() });
> I was having issues rendering the search page inside tests with Quick Options

Can you expand on what the issues were?
And why changing Enzyme fixes what sounds like a Moment issue?

2020-10-23 13:58 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/package.json
> +    "runtypes": "^5.0.1",
Out of curiosity, why is `runtypes` used here for type validation, while
https://github.com/openequella/openEQUELLA/blob/7d32b922860f752e2c79d2c3bc92e119071b392c/oeq-ts-rest-api/package.json#L37
is used in the rest API?

2020-10-26 02:45 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/jest.setup.ts
> +configure({ adapter: new adapter.default() });
> > I was having issues rendering the search page inside tests with Quick Options
> 
> Can you expand on what the issues were?
> And why changing Enzyme fixes what sounds like a Moment issue?

Sure, this was the sequence of steps that led me to altering the jest.setup.ts file:
- In SearchPage.test, I was trying to render a SearchPage containing a MuiPickersUtilsProvider (inside DateRangeSelector.tsx). 
- It failed with the following error:
` console.error
    Error: Uncaught [TypeError: Utils is not a constructor]
        at reportException (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at innerInvokeEventListeners (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
        at invokeEventListeners (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
        at HTMLUnknownElementImpl._dispatch (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
        at Object.invokeGuardedCallbackDev (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at beginWork$1 (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
        at performUnitOfWork (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/react-dom/cjs/react-dom.development.js:22157:12) TypeError: Utils is not a constructor
        at /home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/@material-ui/src/MuiPickersUtilsProvider.tsx:21:37
        at mountMemo (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/react-dom/cjs/react-dom.development.js:15442:19)
        at Object.useMemo (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/react-dom/cjs/react-dom.development.js:15738:16)
        at Object.React [as useMemo] (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/react/cjs/react.development.js:1521:21)
        at MuiPickersUtilsProvider (/home/charlie/Charliequella/Source/Plugins/Core/com.equella.core/js/node_modules/@material-ui/src/MuiPickersUtilsProvider.tsx:21:17)
....`
- I researched the error, and it appeared that others have been having the same issue https://github.com/mui-org/material-ui-pickers/issues/805. I implemented the 'solution' of adding "esModuleInterop": true to tsconfig.json
- After setting esModuleInterop to true, running SearchPage.test failed with the following:
`Test suite failed to run

    jest.setup.ts:20:26 - error TS2351: This expression is not constructable.
      Type 'typeof ReactSixteenAdapter' has no construct signatures.

    20 configure({ adapter: new Adapter() });
                                ~~~~~~~

      jest.setup.ts:19:1
        19 import * as Adapter from "enzyme-adapter-react-16";
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
`

2020-10-27 01:40 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/package.json
> +    "runtypes": "^5.0.1",
It's being used for its pattern matching in this context. See:

https://github.com/openequella/openEQUELLA/pull/2414/files#diff-09ca53eeab09f58aab1ed2726f5edfcc2528a21e6d10d232615e850dc2104cc7R276

2020-10-27 06:02 UTC, edalex-ian approved these changes
Cool, looks like you got there. Shame that you still have the `esModuleInterop` there but we may just have to push on for now and revisit. (Or, maybe once merged @ChristianMurphy may have an opportunity at some point to see if it can be sorted. :thinking: )

2020-10-27 13:56 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    )(rangeType.toLowerCase() as RangeType);
according to the typing `rangeType` should already be `RangeType`?


```suggestion
    )(rangeType.toLowerCase());
```

also since the value comes from a dropdown,

```suggestion
    )(rangeType);
```

may work?

2020-10-27 13:56 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    )(rangeType.toLowerCase() as RangeType);
> [Runtypes is] being used for its pattern matching in this context.

Is matching needed? This looks like it could be a case statement

2020-10-27 13:56 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +        dateRange as RangeType,
Since `runtypes` and `typescript-is` are available would it make sense to validate rather than cast?

2020-10-27 13:56 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +      (getQueryParam("sort")?.toUpperCase() as SortOrder) ??
Since `runtypes` and `typescript-is` are available would it make sense to validate rather than cast?

2020-10-27 21:06 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    )(rangeType.toLowerCase() as RangeType);
Correct, it replaces a `switch` statement. In replacing the `switch` statement with pattern matching we can write the code more declaratively rather than imperatively enabling us to avoid the pitfalls of `switch` statements.

2020-10-27 21:58 UTC, merged