Feature/integrate new search page in selection section
openequella/openEQUELLA pull request #2437
Opened 2020-10-19 06:16 UTC by PenghaiZhang

#1306

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR integrates the new search UI into Selection Section.

The approach is basically checking if new search is enabled in `RootSearchSection`. If yes, then parse `NewSearchPage.html` and put the content into the section.  This approach is also applied to show the settings page in Old UI.

This PR only affects Selection Section in 'structured' mode. The reason is users should only change the mode 'selectOrAdd' when they use oEQ 6 or older versions. So I think the old search UI should be used in mode 'selectOrAdd' .

2020-10-21 04:55 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/entrydev/NewSearchPage.tsx
> +      <ThemeProvider theme={oeqTheme}>
I guess we don't need to use `StylesProvider` in dev environment ?

2020-10-21 04:55 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +  width: 100vw;
This `100vw` will cause a problem - when there is a vertical scroll bar, the actual width of the page is bigger than 100vw, so a horizontal scroll bar gets displayed.

2020-10-21 04:55 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +  // The width of this div is Full viewport width minus vertical scrollbar width.
I just forgot to remove this comment.

2020-10-23 03:41 UTC, edalex-ian commented
Thanks for the two videos @PenghaiZhang 

Before digging into the code, I note one issue with formatting for the `NORMAL` mode. The alignment of the top edge of the cards in New Search vs Legacy UI:

![2020-10-23-143815_576x220_scrot](https://user-images.githubusercontent.com/43919233/96953767-a88e0480-153d-11eb-84a9-d0997f63bd4e.png)

Actually, I note the selection card is missing rounded corners... Is this the latest EBP from `develop` - post merge of component/new-search-page ?

2020-10-23 04:43 UTC, edalex-ian commented
As discussed... I think this PR has pushed us to the point where we finally need to resolve `js/entrybuild` and `js/entrydev`. So I propose that as part of this PR and your new files:

* Merge those two folders into one (maybe just go with `entrypoint` for now), and update `js/package.json` accordingly;
* Tidy the collection of files in there such that you end up with:
  * `index.html` and `index.ts`;
  * `SearchPage.html` and `SearchPage.ts` (was your new `NewSearchPage`);
  * `Settings.html` and `Settings.ts` (was `oldsettings`, but previous re-used `index.ts`);
  * `tsrc/mainui/index.ts` should have that default function take a string union argument along the lines of `"react-index" | "react-search" | "react-settings"` and this can be passed in in each of the above `.ts` files. Further, that same value can be used as the `div` `id` in each of the `.html` files;
  * Also, the JSX you've got in `NewSearchPage.tsx` should be over in `tsrc/mainui/index.tsx` which should then still only have one `render` call, however it should swap between the JSX based on the string union - (ideally using runtypes `match` to choose the correct one).

I'll now proceed to read on the rest of this.

2020-10-23 05:09 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/entrydev/NewSearchPage.html
> +<div id="newSearchPage">
So this file is only for displaying the New Search Page inside a selection session? If so, could the filename be modified to reflect this?

2020-10-23 05:46 UTC, edalex-ian requested changes
Looks pretty good @PenghaiZhang 

Obviously I've requested a few things. But also, are we able to add tests due to the integ tester?

2020-10-23 05:46 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/entrybuild/NewSearchPage.tsx
> +  productionPrefix: "new-search-page",
Would it be good to keep it shorter and go with something specific to oEQ. Maybe `oeq-nsp`. Then maybe we should also specify one for our normal full build - perhaps just `oeq`.

2020-10-23 05:46 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/entrydev/NewSearchPage.tsx
> +      <ThemeProvider theme={oeqTheme}>
I think we should keep it the same for both.

2020-10-23 05:46 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +  width: 98%;
Why 98%? Could be handy to add a comment here.

2020-10-23 05:46 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +  width: 80%;
Why 98%? Could be handy to add a comment here.

2020-10-23 05:46 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +  margin: 0 15px 0 0;
I believe there is a variable along the lines of `$doubleMargin` which is 16px. Would that be appropriate here?

2020-10-23 05:46 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/search/base/AbstractRootSearchSection.java
> +    // If new search UI should be rendered, keep the right column content and override
The below code is not immediately clear, as it seems it has gone more with a pattern of augmentation. I wonder if instead the above code can be broken into a few useful private methods, and then further up in this method the below `if` becomes part of an `if/else`.

2020-10-23 05:46 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/search/base/AbstractRootSearchSection.java
> +          templateResult.getNamedResult(info, TwoColumnLayout.RIGHT);
Could this fail to `getNamedResult`?

2020-10-23 05:46 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/search/base/AbstractRootSearchSection.java
> +    public boolean isNewSearchUIInNormalLayout() {
I reckon a bit of JavaDoc would go a long way here to help readers understand what you mean by 'Normal Layout'.

2020-10-23 05:46 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/section/RootSearchSection.java
> +      } else {
Should this be an `else if`, and then follow with an `else` to throw an `IllegalStateException` if we've ended up with an unexpected `Layout`? Or are there only two `Layouts`? (Maybe if there are only two, we might want to protect from the unknown future.

2020-10-26 00:55 UTC, PenghaiZhang commented
> Thanks for the two videos @PenghaiZhang
> 
> Before digging into the code, I note one issue with formatting for the `NORMAL` mode. The alignment of the top edge of the cards in New Search vs Legacy UI:
> 
> ![2020-10-23-143815_576x220_scrot](https://user-images.githubusercontent.com/43919233/96953767-a88e0480-153d-11eb-84a9-d0997f63bd4e.png)
> 
> Actually, I note the selection card is missing rounded corners... Is this the latest EBP from `develop` - post merge of component/new-search-page ?

Yes this PR definitely has latest EBP work from develop. This PR includes EBP for `COURSE` layout but not for `NORMAL`. I will add more EBP after addressing the `entrypoint` issue.

2020-10-27 02:14 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/entrybuild/NewSearchPage.tsx
> +  productionPrefix: "new-search-page",
The normal full build is not happy with `StylesProvider` due to `PrivateHiddenCss`. 
For example, without the provider, a style from `PrivateHiddenCss` is named `jss25` which is unique.
However, with the provider used and the prefix being `oeq`, this style is named `oeq1` which is duplicated. I expect it should be named `oeq25`.

2020-10-27 03:03 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/entrydev/NewSearchPage.html
> +<div id="newSearchPage">
Selection session and the Resource Selector are the two places where this file is used. And it can be used in other places as long as we need. And this file has been renamed to `SearchPage.html`.

2020-10-27 03:13 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +  width: 98%;
I have changed this back to 100%

2020-10-27 05:02 UTC, PenghaiZhang commented
> Thanks for the two videos @PenghaiZhang
> 
> Before digging into the code, I note one issue with formatting for the `NORMAL` mode. The alignment of the top edge of the cards in New Search vs Legacy UI:
> 
> ![2020-10-23-143815_576x220_scrot](https://user-images.githubusercontent.com/43919233/96953767-a88e0480-153d-11eb-84a9-d0997f63bd4e.png)
> 
> Actually, I note the selection card is missing rounded corners... Is this the latest EBP from `develop` - post merge of component/new-search-page ?

These two style issues should be fixed in 3a76ecc0b149d3e0c1d493a8c51bb5df1ad9af0b

2020-10-28 00:05 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/search/base/AbstractRootSearchSection.java
> +    public boolean isNewSearchUIInNormalLayout() {
I think this method is redundant so I remove it.

2020-10-28 22:09 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/section/RootSearchSection.java
> +      } else {
After more digging I realised that there is no need to check what layout is used. 
But to answer your question, there are three layouts: NORMAL, COURSE, SKINNY. So far, I have seen NORMAL and COURSE in selection session. Take Moodle as an example, if the `openEQUELLA action` is configured to use `selectOrAdd` then NORMAL is used, and if that's configured to use 'structured' then COURSE is used.

2020-10-29 06:40 UTC, edalex-ian commented
> 
> These two style issues should be fixed in [3a76ecc](https://github.com/openequella/openEQUELLA/commit/3a76ecc0b149d3e0c1d493a8c51bb5df1ad9af0b)
> 
> ![image](https://user-images.githubusercontent.com/47203811/97259060-fbcdc300-186d-11eb-96b2-5669250752fc.png)

I note in the image that there is a styling mismatch between EBP and MUI in the amount of shadow for the 'Selection' card. However a mixin has definitely been setup to standardise that, so looks like we need a fix. (I guess I'll see it more when I jump into the review.)

The only other thing that now jumps out is the font styling differences in the 'Selection' card. But maybe that's beyond our limits.

Overall though, visually improved on the original. :+1:

2020-10-30 01:10 UTC, edalex-ian requested changes
Looking good @PenghaiZhang . Pretty well there, but just need some tweaks.

Plus I think you've got a good sized conflict waiting with the work you've done in App etc against `develop`, so I think it'd be worthwhile for this foundational PR if you go that merged across and the conflicts resolved so that this PR aligns nicely.

2020-10-30 01:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/package.json
> +    "entryScript": "entrypoint/scripts/*.js",
How about merging into a single `parcelEntryFiles`? It'd make things a bit simpler, as we don't need this fragmentation.

2020-10-30 01:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/package.json
> +    "runtypes": "^5.0.1"
Should be a pinned version. Mind you though, this is now on `develop`, so whether you want to merge into `component` and then into this one......

2020-10-30 01:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/package.json
> +    "entryTarget": "entrypoint/target"
My understanding of this config value is that it's really only used for the output of the purescript upload component which has historically gone into a target folder within the entry folders. With all that in mind I suggest a few things:

1. This folder should just use the shared `target/` folder;
2. As a result, this config value becomes redundant - so don't add it - simply use that path prefix down in the `bundleps:uploadlist` task; and
3. Update the `require` in `entrypoint/scripts/uploadlist.js` to be `require("../../target/uploadlist.js")`

This will have the added bonus that the `clean` script will now also clean this previously missed file.

(This is not a perfect solution, that would require a whole lot of extra tidy up of this `package.json` - but that's well outside the scope of this PR. We really need to better organise the `output` and `target` directories - and understand if we even need `pulp`)

2020-10-30 01:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/App.tsx
> +  const emptyFunc = () => {};
Nit (just maybe a bit more understandable as to intention).

```suggestion
  const nop = () => {};
```

2020-10-30 01:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/App.tsx
> +  page: ReactNode;
```suggestion
  children: ReactNode;
```

And then that way below you can go with the more usual:

```
<NewPage>
  <SettingsPage ... />
</NewPage>
```

Rather than the current slightly unusual:

```
<NewPage
  page={(<SettingsPage .../>})
/>
```

(It was that unusual pattern that caught my eye.)

2020-10-30 01:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/App.tsx
>  function IndexPage() {
Be advised that this component has been pushed out into its own `.tsx` file on `develop` to assist with lazy loading. So I'd suggest you get that stuff merged across as you'll need to do the same (lazy loading) here/below.

2020-10-30 01:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/App.tsx
> +  return renderApp(entryPage);
Nice work with the pattern matching. Very tidy. :+1:

2020-10-30 01:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +  border-radius: 4px;
You probably want to look at using `curvedCorners` mixin whenever you find yourself doing this.

2020-10-30 01:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +  border-radius: 4px;
As above, look at using `curvedCorners`.

2020-11-03 04:44 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/package.json
> +    "entryTarget": "entrypoint/target"
Since we moved 'uploadlist.js' from `entrypoint/target` to `target`, we need to run `npm run dev:build` first after we do a clean.

2020-11-05 02:52 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/package.json
> +    "entryTarget": "entrypoint/target"
You mean rather than just going straight to `npm run dev`?

Because in theory `sbt cleanrun` would also have already done what's needed. :thinking:

2020-11-05 02:58 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> -  margin-left: $doubleMargin;
Oooh, this looks like something recently added to fix EBP stuff for 2020.2. Removing it's not removing a fix is it?

2020-11-05 03:04 UTC, edalex-ian approved these changes
Looks good @PenghaiZhang . There is one more DRY fix needed in legacy.scss, but really, it's good to merge me thinks.

2020-11-05 03:04 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +  border-radius: 4px;
This change, combined with the above, looks like you're attempting to achieve the standard style defined in `buttonShadowBorder`. Should that be used instead? (And maybe still keeping the background declaration.)

Otherwise at the very least, it should be using `curvedCorners`.

2020-11-05 04:59 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +  border-radius: 4px;
Yes `buttonShadowBorder` is good. Thanks for reminding!

2020-11-05 05:24 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/selection/SearchSelectable.java
> +    return controller.createForward(info, "/selectoradd/searching.do");
I'm just wondering how this may inadvertently affect clients who are not using the new ui? 
I can't think of any specific examples, but it might be safe to check if the new UI is enabled before using this path?

2020-11-05 23:15 UTC, merged