Allow skipping tests in TestNG at runtime
openequella/openEQUELLA pull request #2452
Opened 2020-10-23 00:22 UTC by PenghaiZhang

#### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Add the ability of skipping tests in TestNG at runtime based on the environment.

There are three steps done to support this.
1. Add a new annotation which is used to specify whether to skip a test or not.
2. In 'TestAnnotationTransformer', dynamically disable a test based on the annotation and environment.
3. Include the Transformer in `tesnng-codebuild.yaml `.

This PR also refactored the directory structure where `TestAnnotationTransformer` is sitting.

2020-10-23 00:32 UTC, PenghaiZhang commented on autotest/OldTests/src/test/java/io/github/openequella/search/NewSearchPageTest.java
> +  @SkipTest(skipOldUI = true)
I wonder if people want to add this annotation on class level. Adding it on method level gives more flexibility though.

2020-10-23 06:02 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/search/NewSearchPageTest.java
> +  @SkipTest(skipOldUI = true)
Depends. If this class is dedicated to newUI, I'd say put it at the class level.

2020-10-23 06:09 UTC, edalex-ian requested changes
Good stuff @PenghaiZhang , just a couple of tweaks. But after they're done, you're probably good to merge.

2020-10-23 06:09 UTC, edalex-ian commented on autotest/OldTests/src/test/java/testng/TestAnnotationTransformer.java
> +    }
Arguably these should be split out into two methods:

* `checkRetryAnnotation`; and
* `checkSkipTestAnnotation`.

2020-10-23 06:09 UTC, edalex-ian commented on autotest/OldTests/src/test/java/testng/annotation/SkipTest.java
> +public @interface SkipTest {
Seeing this annotation is just about skipping base on old vs new, should we maybe go with naming like NewUiOnly? And have a simple `value` so that then you can have:

```java
@NewUiOnly(true)
@Test
class NewUiTests {
```

2020-10-23 06:09 UTC, edalex-ian commented on autotest/OldTests/testng-codebuild.yaml
> +  - testng.TestAnnotationTransformer
Nice work dude! Shame our retry tests appear to have not been running on CI.

2020-10-23 14:00 UTC, ChristianMurphy approved these changes

2020-10-26 01:25 UTC, PenghaiZhang commented
611 tests were executed on Codebuild and GHA (New UI on). And 606 tests were executed on GHA (New UI off). So I believe the build results are correct.

2020-10-26 16:52 UTC, ChristianMurphy commented on autotest/OldTests/src/test/java/io/github/openequella/search/NewSearchPageTest.java
> +  @NewUIOnly(true)
out of curiosity, why does this need to be passed `true`?
Wouldn't it default to true?

2020-10-26 22:34 UTC, PenghaiZhang commented on autotest/OldTests/src/test/java/io/github/openequella/search/NewSearchPageTest.java
> +  @NewUIOnly(true)
Oh I thought it defaults to false :thinking:  I might be wrong.

2020-10-26 22:37 UTC, ChristianMurphy commented on autotest/OldTests/src/test/java/io/github/openequella/search/NewSearchPageTest.java
> +  @NewUIOnly(true)
Okay, and why is the default false?
If it shouldn't run in `NewUIOnly`, wouldn't it not have the `NewUIOnly` annotation?
It seems like `false` would be the exception, not the rule?
Unless I'm missing some context here

2020-10-26 23:10 UTC, PenghaiZhang commented on autotest/OldTests/src/test/java/io/github/openequella/search/NewSearchPageTest.java
> +  @NewUIOnly(true)
I think you are right!

2020-10-26 23:23 UTC, ChristianMurphy approved these changes

2020-10-27 01:24 UTC, edalex-ian approved these changes
Good stuff @PenghaiZhang :+1:

2020-10-27 02:44 UTC, merged