feat(server): Maintain logo aspect ratio
openequella/openEQUELLA pull request #2479
Opened 2020-11-02 02:21 UTC by edalex-ian

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] screenshots are included showing significant UI changes

##### Description of change

Just a quick one when I was exploring what we can now do with setting up a custom theme. This increases what images we can use for a logo.

Biggest issue was before if you image was not 36px high, it'd get squashed and stretched making most images unrecognisable. As you can see in the screenshot, now we can use nice square ones for example - as somewhat common logo format.

#2478

![image](https://user-images.githubusercontent.com/43919233/97823693-d594a100-1d0d-11eb-8fdb-47330a545a83.png)

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-11-02 04:06 UTC, ChristianMurphy approved these changes
LGTM :+1: 
Though a more general question, why is ImageMagick used elsewhere while Graphics2D is used here?

2020-11-02 04:06 UTC, SammyIsConfused requested changes
Love this. Was far too restrictive before. 
The only thing I'd say is worth including is that you'll want to rework the language string that displays on the Theme Editor page, which prescribes a ratio to use. (Use a PNG file of 230 x 36 for best results).
![image](https://user-images.githubusercontent.com/24543345/97828937-9caff880-1d1c-11eb-9a24-0f652310716f.png)

2020-11-02 04:32 UTC, edalex-ian commented
> LGTM +1
> Though a more general question, why is ImageMagick used elsewhere while Graphics2D is used here?

I'd say because ImageMagick is a lot more capable than the inbuilt java graphics libraries. ImageMagick is generally considered the most powerful widely available tool suite out there when it comes to automation of media manipulation (and interrogation). As a result it is a common pattern for servers to call out to it (either the CLI, or if native the libraries) to do image related activities.

So I've just made the assumption that's why oEQ uses it. But definitely before my time, and I've not looked closely as it how it's being used.

2020-11-02 04:34 UTC, edalex-ian commented
> The only thing I'd say is worth including is that you'll want to rework the language string that displays on the Theme Editor page, which prescribes a ratio to use. (Use a PNG file of 230 x 36 for best results).

What do you suggest. Just drop the bit in parens?

2020-11-02 04:38 UTC, SammyIsConfused commented
> 
> What do you suggest. Just drop the bit in parens?
Yup, that should do it. Unless your method requires PNG? I vaguely remember that being the only way to get transparency. Perhaps (Supports .png files)?

2020-11-05 04:35 UTC, edalex-ian commented
In the end reworked to advise on max width - so as to avoid scaling artefacts:

![image](https://user-images.githubusercontent.com/43919233/98198197-87d1a000-1f7c-11eb-87fb-5c3f0ec605fd.png)

Will merge on green builds.

2020-11-05 04:44 UTC, SammyIsConfused approved these changes
Thanks for fixing that up. Good to go!

2020-11-05 23:37 UTC, merged