Add steps to ci.yaml to build and artefact storybook
openequella/openEQUELLA pull request #2491
Opened 2020-11-05 02:52 UTC by SammyIsConfused

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]

##### Description of change
This PR adds steps to GitHub Actions workflow to build the static instance of Storybook and upload it as an artefact. 
Drafted until I see it working on CI.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-11-05 03:58 UTC, SammyIsConfused commented
Failed at 402fd57 because the storybook-static folder was included in Run Checks. Adding a step to remove the folder once we have used it.

2020-11-05 04:41 UTC, SammyIsConfused commented
Failed at 18a26df because the path for the rm call was wrong - needed not to start with a `/`.

2020-11-05 21:59 UTC, ChristianMurphy approved these changes
Very nice!
I also see that gh-pages isn't being used on this repo yet, it could be interesting to have these published to gh-pages from the action.

2020-11-05 21:59 UTC, ChristianMurphy commented on .github/workflows/ci.yaml
> +          rm -R storybook-static
This seems like something which we may want to add to the eslint ignore or prettier ignore.
It will likely be an issue if the static storybook pages are built locally, could be nice to fix it for both cases.

2020-11-09 21:56 UTC, SammyIsConfused commented
This is now ready for review - just wanted to tidy things up and get it how I wanted it before undrafting.

2020-11-09 23:54 UTC, PenghaiZhang approved these changes
Looks good to me!  Is it better to merge `Generate`, `Package` and `Remove` ?

2020-11-09 23:59 UTC, SammyIsConfused commented
> Looks good to me! Is it better to merge `Generate`, `Package` and `Remove` ?

Thanks Penghai. I dont think so - since each of the other situations in which we build, package and save artefacts are done separately it would make sense to stay consistent. (See lines 116-132, 264-280 for similar examples).

2020-11-10 00:02 UTC, ChristianMurphy approved these changes

2020-11-10 00:02 UTC, ChristianMurphy commented on .github/workflows/ci.yaml
> +          rm -R storybook-static
does this still need to be removed?
Now that it is ignored by the linting and formatting tools?

2020-11-10 00:02 UTC, ChristianMurphy commented on .github/workflows/ci.yaml
> +          tar cvf storybook.tar storybook-static
could these be combined into a single step?

2020-11-10 02:02 UTC, SammyIsConfused commented on .github/workflows/ci.yaml
> +          tar cvf storybook.tar storybook-static
As I said to Penghai above, the other steps that involve building, tarring and uploading artefacts split this into steps. It was a deliberate choice to stay separate in order to be consistent with the rest of the yaml. It also helps with diagnosing build issues to split into steps, as at-a-glance it tells us exactly where the issue arose.

2020-11-10 02:03 UTC, SammyIsConfused commented on .github/workflows/ci.yaml
> +          rm -R storybook-static
Not necessarily, but it just makes sure that the storybook steps clean up after themselves.

2020-11-10 03:32 UTC, edalex-ian requested changes
Heya @SammyIsConfused 

Great to see this in here. :+1: 

Could we please do two things:

1. Put it in its own job - like the import/export tool;
2. Like @ChristianMurphy suggested, no need for the clean-up in a CI (hence why you don't seen any `sbt clean` or `npm run clean`)

With splitting it into it's own job, it will pave the way for use to look at using gh-pages, and expanding out to include the JavaDoc, ScalaDoc and TS Doc that everyone has put so much effort into.

2020-11-10 03:54 UTC, SammyIsConfused commented
> Heya @SammyIsConfused
> 
> Great to see this in here. +1
> 
> Could we please do two things:
> 
>     1. Put it in its own job - like the import/export tool;
> 
>     2. Like @ChristianMurphy suggested, no need for the clean-up in a CI (hence why you don't seen any `sbt clean` or `npm run clean`)
> 
> 
> With splitting it into it's own job, it will pave the way for use to look at using gh-pages, and expanding out to include the JavaDoc, ScalaDoc and TS Doc that everyone has put so much effort into.

@edalex-ian This should be fixed up now. Only thing I'm not sure on is the Ivy/SBT caches - are they required or would it just be the NPM one?

2020-11-10 03:56 UTC, SammyIsConfused commented on .github/workflows/ci.yaml
> +          rm -R storybook-static
Removed the step in 6dbd054.

2020-11-10 06:49 UTC, edalex-ian commented
> @edalex-ian This should be fixed up now. Only thing I'm not sure on is the Ivy/SBT caches - are they required or would it just be the NPM one?

Just the NPM ones - i.e. on the ones that'd content artefacts you'd need to assist with your job.

2020-11-11 02:48 UTC, edalex-ian requested changes
Good stuff @SammyIsConfused 

Just needs a few minor tweaks, and then should be good to go. :+1:

2020-11-11 02:48 UTC, edalex-ian commented on .github/workflows/ci.yaml
> +          java-version: 1.8
Is that required? AFAICT, everything done below is JS / Node.

2020-11-11 02:48 UTC, edalex-ian commented on .gitignore
> +storybook-static/
This should sit down with the code it belongs to: `Source/Plugins/Core/com.equella.core/js/.gitignore`

2020-11-11 02:48 UTC, edalex-ian commented on .github/workflows/ci.yaml
> +            ${{ runner.os }}-npm-
It would be prudent to have it's own cache for this me thinks.

be good to replace `-npm-` on lines 124 and 126:

```suggestion
          key: ${{ runner.os }}-npm.storybook-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm.storybook-
```

2020-11-11 05:56 UTC, edalex-ian approved these changes
Looks good @SammyIsConfused . Merge on once green. :+1:

2020-11-11 13:58 UTC, ChristianMurphy approved these changes

2020-11-12 22:07 UTC, merged