Feature/navigate to item summary page
openequella/openEQUELLA pull request #2504
Opened 2020-11-12 00:10 UTC by PenghaiZhang

#688 

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR focuses on the feature of navigating from new Search page to the ItemSummary page. 

In the context of Selection Session, the link to ItemSummary page requires some extra query params to help the Legacy server rendering. 

All required information is available in front-end now,  and we just need to add these query params in each Item title link.

Also, you will see `MUI Link` is used. This is probably due to two reasons: 
1. the mixed environment where new tsx component is used in Legacy content;
2. the only component that can be used when the ItemSummary  page URL is matched in the routes is `LegacyPage`. 

So I suggest we come back and address the problem when we have a new tsx component for ItemSummary page. 
`LegacyPage`

2020-11-12 01:14 UTC, edalex-ian requested changes
Looks good @PenghaiZhang, just needs a couple of tweaks me thing.

And also, I think it could be prudent to add a two tests:

1. The generation of the link URL; and
2. A test of the page that it correctly switches between the two types of links based on the presence of `selectSessionInfo`.

2020-11-12 01:14 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/App.tsx
> +        <NewPage classPrefix="oeq-nsp" forceRefresh={false}>
How about if you you make `forceRefresh` default to `false` so that the absence of this property on the element means it's off?

2020-11-12 01:14 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +  totalCount: number;
I believe you need to update the SB stories for these - I'd say that's what's triggering the build failure.

hmmm, is it possible these props will help us later to add support for the Item Summary Page next/prev buttons?

2020-11-12 01:14 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +      }
This block of logic should really be out in the Module layer. It's more to do with the internal workings of oEQ as opposed to how we present a result.

```typescript
const buildSelectionSessionItemSummaryLink =
  ({ stateId, integId, layout }: SelectionSessionInfo,
  indexNumber?: number, totalCount?: number): string => {
    ...
}
```

If you had something like that, then this method could be more (declarative) like:

```typescript
const itemLink = () => {
  const itemTitle = name ? highlightField(name) : uuid;
  const basicLink = <Link to={routes.ViewItem.to(uuid, version)}>{itemTitle}</Link>;
  return renderData?.selectionSessionInfo ?
    (<MUILink
      href={buildSelectionSessionItemSummaryLink(renderData.selectionSessionInfo)}
      underline="none">
        {itemTitle}
    </MUILink>) :
    basicLink;
}
```

Added bonus, would be that you can then also easily unit test this.

2020-11-12 02:59 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +  totalCount: number;
Yes they will! And perhaps more importantly,  these two buttons are missing if ItemSummary page is opened from new Search page. But I already worked out why and how to fix this.

2020-11-12 04:56 UTC, PenghaiZhang commented
> Looks good @PenghaiZhang, just needs a couple of tweaks me thing.
> 
> And also, I think it could be prudent to add a two tests:
> 
> 1. The generation of the link URL; and
> 2. A test of the page that it correctly switches between the two types of links based on the presence of `selectSessionInfo`.

I have done the first test. For the second one, I think we should do it in the test for `SearchResult` ?

2020-11-12 06:25 UTC, edalex-ian commented
> I have done the first test. For the second one, I think we should do it in the test for `SearchResult` ?

Yup, that's what I had in mind. :)

2020-11-12 06:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SelectionSessionModule.ts
> + * @param layout The UI layout used in Selection Session
Hmmm, TSDoc is a bit curious here, as really the param is a `SelectionSessionInfo` object and you'd refer there for the value of the inside params. :confused: 

Here's how it's done in JSDoc land... But no TSDoc / typedoc description is jumping out for me. :disappointed:

2020-11-13 23:10 UTC, edalex-ian approved these changes
GTG dude. I've dropped a few queries in there, and a couple of optional nit-picks. Other than that, some wording enhancements for the tests.

Once you've addressed what you think should be, go for a merge. ;)

2020-11-13 23:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SelectionSessionModule.test.ts
> +describe("SelectionSessionModule", () => {
Due to the name of this file we already know it's for the `SelectionSessionModule`. More so, this block is all about the `buildSelectionSessionItemSummaryLink` so it'd make more sense to go with:

```suggestion
describe("buildSelectionSessionItemSummaryLink()", () => {
```

And then later when `SelectionSessionModule` has more functions, you'd add another `describe` block for each function.

2020-11-13 23:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SelectionSessionModule.test.ts
> +  it("should build a URL for accessing ItemSummary page in Selection Session", () => {
```suggestion
  it("builds basic URLs for accessing ItemSummary pages in Selection Session mode", () => {
```

2020-11-13 23:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SelectionSessionModule.test.ts
> +  it("should also include Integration ID in the URL", () => {
```suggestion
  it("will include the Integration ID in the URL if provided in SelectionSessionInfo", () => {
```

2020-11-13 23:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/AppConfig.ts
> +  selectionSessionInfo: SelectionSessionInfo | null;
Should this be:

```suggestion
  selectionSessionInfo?: SelectionSessionInfo;
```

Or is it explicitly `null` sometimes?

2020-11-13 23:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/AppConfig.ts
> +export const getRenderData = () => {
Being an exported function, we should make sure we fully type it:

```suggestion
export const getRenderData = (): RenderData | undefined => {
```

2020-11-13 23:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/AppConfig.ts
> +  if (typeof renderData !== "undefined") {
Nit: Should this be more specific - should we be checking to see if `renderData` is an instance of `RenderData`. If so, maybe rework this function to a simple `() => match(...)`.

2020-11-13 23:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/RichTextEditor.tsx
> +const renderData = getRenderData();
Noice! :+1:

2020-11-13 23:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/mainui/index.tsx
> -}
Yup, I think this makes much more sense now in `AppConfig`. Good work. :+1:

2020-11-13 23:10 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +  const renderData = getRenderData();
Nit. Seeing you're only using in once place below, throwing in a variable is a bit redundant.

2020-11-14 02:47 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/AppConfig.ts
> +  if (typeof renderData !== "undefined") {
In order to use `match(...)`, we need to create a `runtype` for `RenderData` and one for `SelectionSessionInfo`. 
There are discussions around the feature of transforming a TS interface to a runtype and this feature is not supported yet.

https://github.com/pelotom/runtypes/issues/128

2020-11-14 03:27 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/AppConfig.ts
> +  if (typeof renderData !== "undefined") {
I guess we have to resort to `typeof` to ensure `settings page` works fine in Old UI. This is because `renderData` does not exist in Old UI at all. So any use of it will trigger a `uncaught reference error`.

2020-11-15 22:00 UTC, merged