Feature/new search query params
openequella/openEQUELLA pull request #2506
Opened 2020-11-12 10:20 UTC by mrblippy

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included

##### Description of change

#1306

This builds further upon the PR i did to support legacy search parameters (#2414)

Summary of work performed:
- Adding SearchModule function to serialize a searchOptions object to a JSON string, to be used in a query string. This is intended to be used to allow for a new Search Page user to get a link to copy their current search.
  - in order to cut down on characters, only the bare minimum collection and owner identifiers are serialized. Undefined properties are also excluded.
- Deserialisation of the query string back into a searchOptions object
- Updating the SearchPage to accomodate the fact that we now can support two types of linkable searches.

- A PR will be submitted in the near future to add a button on the SearchPage to obtain the linkable url

All feedback welcomed, I have been staring at this for too long 😑

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-11-14 00:30 UTC, edalex-ian requested changes
So most of the comments are about comments and the like.

But two significant ones in `SearchModule` around the serialisation and de-serialisation - which I appreciate are the two hard parts of this work. So just let me know when you're in a position to work through those tricky bits and we can do together.

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +  const location = useLocation<LocationState>();
What's all this about?

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +      //defaultSearchOptions contains an an undefined sortOrder property
```suggestion
      //defaultSearchOptions contains an undefined sortOrder property
```

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> + * A function that takes a parses a saved search query string from a shared legacy searching.do or /page/search URL, and converts it into a SearchOptions object
```suggestion
 * A function that takes and parses a saved search query string from a shared legacy searching.do or /page/search URL, and converts it into a SearchOptions object
```

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> + * @param location object, typically obtained from the SearchPage component.
Hmmm, needs to be reworked. I'm not entirely sure what you're saying so I can't provide a concrete suggestion.

Is it something like:

```typescript
* @param location representing a Location which includes search query params - such as from the <SearchPage>
```

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> + * @return SearchOptions object, or undefined if there were no query string parameters.
```suggestion
 * @return SearchOptions containing the options encoded in the query string params, or undefined if there were none.
```

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +      }
So a couple of things here:

1. I note you've provided two of the three possible types in your `value: (object | Collection)[]` declaration - why not also the type for `"owner"` (is that perhaps `Owner` - I assume so in the next point, but could be wrong)?
2. But thinking on that, rather than matching against string `Literal` on the `key` how about using the matchers ability to match on Type and instead use `Collection`, `Owner`, `Unknown`?

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> + * @param searchOptionsJSON a JSON representation of a SearchOptions object.
```suggestion
 * @param searchOptionsJson a JSON representation of a SearchOptions object.
```

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> + * @return searchOptions Search options selected on Search page.
```suggestion
 * @return searchOptions A deserialized representation of that provided by `searchOptionsJson`
```

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  const parsedOptions: SearchOptions = JSON.parse(
As discussed with @mrblippy 

1. The type here is not `SearchOptions`, really it should be `unknown` and we validate after further work below;
2. For the code further down to rehydrate collections and owner (which had to be split out due to needing async calls), they should be pushed into their own functions for readability.
3. At the end of all this, we really need some validation to confirm we are actually returning `SearchOptions`.

Grab me at some point, and we'll work together to refactor this function.

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    return collectionUuids.includes(c.uuid);
`return` is superfluous.

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  return filteredCollectionList.length > 0
I wonder if prior to this we want to log a warning or something if `filteredCollectionList.length !== collectionUuids.length`.

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    : defaultSearchOptions.collections;
This function reads more generic, and so shouldn't be tied to a specific implementation detail. Therefore I think it should return `undefined` or `[]`. I think possibly `[]` because if a list has been the input, it'd seem the output should also be a list - even if empty due to issues.

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  return userDetails.length > 0 ? userDetails[0] : defaultSearchOptions.owner;
hmmm, if we can end up with more than 1 user, we should probably at least log a warning, but maybe we need to throw an error. Just assuming to use the first one is possibly a bit risky. :thinking:

2020-11-14 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> + * @param location query string params from a shared `searching.do` URL
Looks like this comment is completely outta wack. :confused:

2020-11-15 22:47 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +        '{"rowsPerPage":10,"currentPage":0,"sortOrder":"NAME","query":"test machine","rawMode":true,"status":["LIVE","REVIEW"],"searchAttachments":true,"selectedCategories":[{"id":766943,"categories"
Just a thought on this test...

What is currently here is essentially a regression test. That is, it will work to ensure that if the format of the params change in the future, we'll need to deliberately address it.

However what we missing is a test which explicitly takes the output from the serialisation of params and feeds to back into the deserializer. That is, validating what we produce we can definitely consume at any point in time.

So you may need to add one more test.

2020-11-16 23:36 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +  const location = useLocation<LocationState>();
I mistakenly left this in while still in development. I will remove it, as it has no reason to be here anymore

2020-11-17 04:39 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +        '{"rowsPerPage":10,"currentPage":0,"sortOrder":"NAME","query":"test machine","rawMode":true,"status":["LIVE","REVIEW"],"searchAttachments":true,"selectedCategories":[{"id":766943,"categories"
Good point, I hadn't thought of that case. It has been added

2020-11-17 04:46 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +      }
As discussed in-person, runtypes won't match on regular Typescript types. I would need to define them again as Runtypes, which is probably overkill

2020-11-17 04:55 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  const parsedOptions: SearchOptions = JSON.parse(
Thank you very much for assisting me in refactoring this @edalex-ian, it was very much appreciated.

However, i wasn't able to fully guard against a extraneous properties being added during the JSON.parse, due to this issue currently in [the Runtypes library](https://github.com/pelotom/runtypes/issues/169) https://github.com/pelotom/runtypes/issues/169

2020-11-17 04:57 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    return collectionUuids.includes(c.uuid);
I'm (very slowly) getting better at not doing this, but I still slip up sometimes. Thanks for picking up on it

2020-11-17 05:03 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> + * @param location query string params from a shared `searching.do` URL
it sure was, my late night typing was subpar at best in this case

2020-11-17 23:22 UTC, edalex-ian requested changes
Fair effort here @mrblippy 

The issues around types were monumental, and I'll be sure to send out an email to the dev list later covering them. I think it's as good as we can get at this point in time.

But there's a few other minor bits left to sort out. BTY.

2020-11-17 23:22 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  const getCollections = async (collectionId: string | undefined) => {
```suggestion
  const parseCollectionId = async (collectionId: string | undefined): Promise<Collection[]> => {
```

2020-11-17 23:22 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +const getCollectionDetails = async (
As discussed, let's tweak this name a bit. At first I was going to suggest `getCollectionsByUuid` however this is just a find, as anything that doesn't match is silently skipped. So:

```suggestion
const findCollectionsByUuid = async (
```

2020-11-17 23:22 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +): Promise<OEQ.UserQuery.UserDetails | undefined> => {
Similar to above, this is probably more so a `find` rather than a get. But I do also wonder if `undefined` is actually ever returned. :thinking: 
```suggestion
const findUser = async (
  userId: string
): Promise<OEQ.UserQuery.UserDetails | undefined> => {
```

2020-11-17 23:22 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  return userDetails[0];
What if `userDetails` is empty?

2020-11-17 23:22 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +
Rather than comment out, did you mean to:

```suggestion
```

2020-11-18 02:39 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  return userDetails[0];
Calling `userDetails[0]` when it's empty will return undefined. So it won't cause any errors.

2020-11-18 02:48 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  const getCollections = async (collectionId: string | undefined) => {
Yeah, that function naming makes more sense. But I had to change the return type to be `Promise<Collection[] | undefined>`. Because it turns out that `defaultSearchOptions.collections` returns undefined

2020-11-18 02:50 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +
https://static.wikia.nocookie.net/simpsons/images/c/c3/D%27oh.jpg/revision/latest/top-crop/width/360/height/360?cb=20141226214635 

Yep, that's definitely what should've been done

2020-11-18 03:54 UTC, edalex-ian approved these changes
Looks good @mrblippy 

You've now arrived at the ready for merge stage. :wink:

2020-11-18 05:55 UTC, merged