Feature/buttons for selecting resources
openequella/openEQUELLA pull request #2515
Opened 2020-11-16 01:03 UTC by PenghaiZhang

#688 

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR created a new component called `ResourceSelector` which is used to select the ItemSummary page and attachments in Selection Session.

This PR is more focused on UI so there are no concrete event handlers passed into `ResourceSelector` yet. 

![Screenshot from 2020-11-16 12-01-26](https://user-images.githubusercontent.com/47203811/99202501-794c7980-2803-11eb-8ebb-0a3883bbd8ec.png)

2020-11-16 22:36 UTC, SammyIsConfused requested changes
Looks good! Just a few grammar tweaks in the todo comments, and a missing bit of JSDoc.

2020-11-16 22:36 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/ResourceSelector.tsx
> +export const ResourceSelector = ({
You could probably have a bit of JSDoc explaining this function.

2020-11-16 22:36 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +                  onClick={nop} // todo: replace nop with an handler for selecting one attachment
```suggestion
                  onClick={nop} // todo: replace nop with a handler for selecting one attachment
```

2020-11-16 22:36 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +            onClick={nop} // todo: replace nop with an handler for selecting attachments
```suggestion
            onClick={nop} // todo: replace nop with a handler for selecting attachments
```

2020-11-16 22:36 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +          onClick={nop} // todo: replace nop with an handler for selecting summary page
```suggestion
          onClick={nop} // todo: replace nop with a handler for selecting summary page
```

2020-11-16 22:46 UTC, edalex-ian approved these changes
Looks good @PenghaiZhang . Only one optional nit-pick to assist readability.

:+1:

2020-11-16 22:46 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +  const selectionSessionData = renderData?.selectionSessionInfo;
Nit: I wonder if doing a change like this would help readability:

```suggestion
  const inSelectionSession: boolean = renderData?.selectionSessionInfo;
```

And then in the one place you need `selectionSessionInfo` as the actual data structure, you simply use `renderData?.selectionSessionInfo`.

2020-11-18 02:58 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +              component="div"
This seems a bit surprising.
Why remove the `ul` list semantics from a list element?

2020-11-18 21:58 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +              component="div"
Hi @mrblippy, do you have any answer for Christian's query ? 
I probably miss the background of using `div` here. Actually, I have tried to remove `component="div"` and the UI seems unchanged.

2020-11-18 22:59 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +  const selectionSessionData = renderData?.selectionSessionInfo;
I like this, but this we need to do a type casting from `undefined` to `boolean`. 
Also we will need to change the parameter type of `buildSelectionSessionItemSummaryLink`. 
And lastly, we need to add a type check for whether Selection Session info is null/undefined and throw an error if yes.

2020-11-20 00:34 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +  const selectionSessionData = renderData?.selectionSessionInfo;
As per discussions this morning, it'd still be good to address this for future readability/maintainability. @PenghaiZhang is going to see what he can come up with.

2020-11-20 00:38 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +              component="div"
I can't remember exactly why i added that. But, when i look at it now, it really doesn't make sense for a List component to be a div :thinking: 

I would say you are fine to remove it @PenghaiZhang

2020-11-20 06:29 UTC, edalex-ian approved these changes
LGTM @PenghaiZhang . A couple of tweaks could be good, but I'll leave it with you. :+1:

2020-11-20 06:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SelectionSessionModule.ts
> +const isSelectionSession = (
Nit

```suggestion
const isSelectionSessionInfo = (
```

2020-11-20 06:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SelectionSessionModule.ts
>   * Build a Selection Session specific ItemSummary Link.
```suggestion
 * Build a Selection Session specific ItemSummary Link. Recommended to first call `inSelectionSession()`
 * before use.
```

2020-11-20 06:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SelectionSessionModule.ts
> +export const inSelectionSession = isSelectionSession(selectionSessionInfo);
Be good to force the issue here - also for the sake of doco:

```suggestion
export const inSelectionSession: boolean = isSelectionSession(selectionSessionInfo);
```

2020-11-23 01:22 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SelectionSessionModule.ts
> +export const inSelectionSession = isSelectionSession(selectionSessionInfo);
I have to change this const to a function to make tests passed. As a const, it gets evaluated during those imports (SearchResult imports this from the module) and the mocks done in the test are too late. So making it a function can help solve this issue.

2020-11-23 04:27 UTC, PenghaiZhang commented
Merged on although GHA failed on `BaseEntityAPITest` as this PR has nothing related to what the test is testing.

2020-11-23 04:28 UTC, merged

2020-11-23 22:12 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SelectionSessionModule.ts
> +export const inSelectionSession = isSelectionSession(selectionSessionInfo);
Ha! I almost commented on this during the review, but then decided the single evaluation would be fine. I forgot about the test side of things. ;)