Handle PDF thumbnailing safely
openequella/openEQUELLA pull request #2526
Opened 2020-11-18 00:01 UTC by SammyIsConfused

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]

##### Description of change
Thumb-nailing of PDFs is done by an external ImageMagick process. This is then delegated by ImageMagick to a program called Ghostscript. If uploading a broken PDF, Ghostscript will attempt indefinitely to "fix" the PDF, slamming the server CPU and affecting performance. If the process takes too long to finish it can cause issues with server stability. 

This PR solves the problem by adding a new config property to `plugins/com.tle.core.imageMagick/config.properties` called `imageMagick.seconds.before.cancel.pdf.thumbnailing`. This adds a timeout cap to the imageMagick process - if exceeded thumb-nailing for that attachment will error out and cancel, and will not be retried. When not set, the default is 20 seconds. It is possible to use the standard non-capped thumb-nailing process by setting it to 0. 

**Note:** the timeout only affects the very first imageMagick call that the thumbnailer calls for a PDF, the `identify` call from getImageDimensions. It is assumed that if this step succeeds the PDF is valid and will get through all the other steps. I have tested with other imageMagick calls and they all carry out the first "fix PDF" step in the same way. 

**Also note:** Similar problems occur with indexing broken PDFs for freetext search using Tika - this will be addressed in another PR. 

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-11-20 00:31 UTC, edalex-ian requested changes
Good stuff @SammyIsConfused , looks like this would solve the issue. But just a few things:

1. Use caution with logging at INFO and above - as it can render the logs quickly useless for typical (non-dev) use;
2. The approach should really be one which is along the lines of "thumbnailing is a non-critical task, and so should be constrained to x seconds per attachment" (i.e. regardless of type); and
3. If we add a new config param, we should ensure it's documented at least in an example config file.

2020-11-20 00:31 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +      LOGGER.info("maxDurationInSeconds not set. Using a regular non-timed process.");
This will make for some rather verbose logs, and is really only relevant for debugging issues so

```suggestion
      LOGGER.debug("maxDurationInSeconds not set. Using a regular non-timed process.");
```

2020-11-20 00:31 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +      LOGGER.info("Started timed process");
```suggestion
      LOGGER.debug("Started timed process");
```

2020-11-20 00:31 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +      LOGGER.info("Timed process finished");
```suggestion
      LOGGER.debug("Timed process finished");
```

2020-11-20 00:31 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/imagemagick/ImageMagickServiceImpl.java
> +    if (image.getAbsolutePath().toLowerCase().contains(".pdf")) {
Doesn't need to be this specific. Arguably any thumbnail process going rouge/forever should be hit on the head. I think the check should be removed, and the configuration property made more generic - e.g. `thumbnailing.timeout`.

That in turn raises the question as to whether all thumbnailing goes through here. And if not, should we really do the circuit breaker higher up.

2020-11-20 00:31 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/imagemagick/ImageMagickServiceImpl.java
> +                  StandardCharsets.UTF_8));
This duplicates the above. As per above, this branch may be removed. But if not, this should be centralised in a shared String[] as used above.

2020-11-20 00:31 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/imagemagick/guice/ImageMagickModule.java
> +    bindInt("imageMagick.seconds.before.cancel.pdf.thumbnailing", 20);
This should also be added to the example optional config properties file as way of documentation.

2020-11-20 00:57 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/imagemagick/ImageMagickServiceImpl.java
> +    if (image.getAbsolutePath().toLowerCase().contains(".pdf")) {
All of the ThumbnailGenerators (ImageThumbnailGenerator, PDFThumbnailGenerator, VideoThumbnailGenerator) pass through here. There is one exception - in the ImageThumbnailGenerator it checks if the file is a gif. If it is, it goes straight to conversion. All others hit here first. 
I could resolve this in a few different ways: 
- Surround the conversion step with a time limit too
- Move this up to generateThumbnailAdvanced - all thumbnailing operations use this. However - this would work quite a bit differently as it's not an external process. 
- Make the GIF check run getImageDimensions too
- Refactor this PDF validation check out into it's own operation that gets run before all else in thumbnailing. Essentially running the identify call again but this time right at the start, doing nothing with the output - just as a validation step. And then operate as normal. While this would add a new load, if the file is valid this will take a split second and neglible processing power.

2020-11-20 04:12 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/imagemagick/ImageMagickServiceImpl.java
> +    if (image.getAbsolutePath().toLowerCase().contains(".pdf")) {
Went with the option to refactor this into it's own validation step.

2020-11-24 00:28 UTC, PenghaiZhang commented
Hi Sam, I just have one query. If I upload a broken PDF which thumbnailing exceeds the timeout, will I see the 500 error or anything else that tells me the timeout?

2020-11-24 01:03 UTC, edalex-ian approved these changes
LGTM @SammyIsConfused 

You'll just want to restart the failing build though to make sure it's green and good to merge.

2020-11-24 01:27 UTC, SammyIsConfused commented
> Hi Sam, I just have one query. If I upload a broken PDF which thumbnailing exceeds the timeout, will I see the 500 error or anything else that tells me the timeout?

There will be a TimeoutException in the Resource centre logs, but no indication on the user side from the browser that anything has happened.

2020-11-24 04:02 UTC, SammyIsConfused commented
MimeTypesTest failed in the old UI :thinking: I'll retry in case it was a fluke.

2020-11-24 05:53 UTC, SammyIsConfused commented
Okay this time around everything was fine except one of the Scalacheck tests in the new UI (Wizard file uploads.edit). So definitely both flakey.

2020-11-26 05:15 UTC, SammyIsConfused commented
That MimeTypesTest keeps tripping up. I've added a wait before a check it fails on, hopefully that helps. Can't see anything that ties that test to this branch though :thinking:

2020-11-26 21:58 UTC, SammyIsConfused commented
There we go, that seems to have done the trick! :confetti_ball: Merging.

2020-11-26 21:59 UTC, merged