Feature/share search button
openequella/openEQUELLA pull request #2536
Opened 2020-11-19 10:31 UTC by mrblippy

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes

##### Description of change

#1306

This is essentially adding a ui layer for my previous PR (#2506)

A new share button has been added to the SearchResultList component. 
It generates the url of the current search page, along with a query string param that stores the current state of the search page. The link is stored in the user's clipboard, and a snackbar is displayed.

![Peek 2020-11-19 21-29](https://user-images.githubusercontent.com/4625498/99654476-7c1ec700-2aae-11eb-8b14-7f50d104e11d.gif)

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-11-19 23:04 UTC, PenghaiZhang reviewed
Thanks Charlie! Just a few suggestions.

2020-11-19 23:04 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +          () => value?.map((collection) => pick(collection, ["uuid"])),
Why added this question mark may I ask ? The type of `value` is Array which should ensure it won't be undefined or null.

2020-11-19 23:04 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +import { RenderData } from "../mainui";
```suggestion
import type { RenderData } from "../mainui";
```

2020-11-19 23:04 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +      title={languageStrings.searchpage.shareSearchConfirmationText}
You can reuse `searchStrings`.

2020-11-19 23:04 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +    navigator.clipboard.writeText(searchUrl).then(() => {
Is there any possibility that `writeText` could fail ?

2020-11-19 23:04 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultList.tsx
> +import { Share } from "@material-ui/icons";
```suggestion
import Share from "@material-ui/icons/Share"
```

2020-11-19 23:04 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultList.tsx
> +                <IconButton onClick={onCopySearchLink}>
What about adding a label here for accessibility and writing tests more easily ?

2020-11-19 23:53 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultList.tsx
> +import { Share } from "@material-ui/icons";
Definitely a good one to be cautious of for tree shaking and package sizes.

2020-11-20 00:14 UTC, edalex-ian requested changes
Cool, looks good, I've only got a few bits of feedback - and then there's @PenghaiZhang's. And one other thing (as discussed) by good to have an end-to-end test for this one. That is, with Selenium in the NewSearchPageTest:

1. make a few minor option selections on the search page - maybe just query text would work;
2. share the link - so it's in the clipboard
3. Use that link to `go()` to
4. Confirm you're back at the search page and your option has taken effect.

2020-11-20 00:14 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +});
Two things:

1. How come you can't do it like the `window.scroll` below; and
2. Even if you can't, rather than using `() => {}` could be better to use `jest.fn()`;

2020-11-20 00:14 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +    const copySearchButton = screen.getByTitle("Copy search link to clipboard");
Best to use languageString here rather than raw string literal.

2020-11-20 00:14 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +      screen.getByText("Search link saved to clipboard")
langstrings

2020-11-23 23:58 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultList.tsx
> +                <IconButton onClick={onCopySearchLink}>
An IconButton wrapped in a Toolip component uses the Tooltip text as the title of the Button element:
`<button class="MuiButtonBase-root MuiIconButton-root" tabindex="0" type="button" title="Copy search link to clipboard">`

2020-11-24 05:28 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +});
I did try doing it like` window.scroll` 
`window.navigator.clipboard.writeText = jest.fn();`. But it fails with `TypeError: Cannot set property 'writeText' of undefined`.

2020-11-24 05:49 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +    navigator.clipboard.writeText(searchUrl).then(() => {
It's possible, so i will put a catch in for it

2020-11-24 05:52 UTC, mrblippy commented
> Cool, looks good, I've only got a few bits of feedback - and then there's @PenghaiZhang's. And one other thing (as discussed) by good to have an end-to-end test for this one. That is, with Selenium in the NewSearchPageTest:
> 
> 1. make a few minor option selections on the search page - maybe just query text would work;
> 2. share the link - so it's in the clipboard
> 3. Use that link to `go()` to
> 4. Confirm you're back at the search page and your option has taken effect.

I wrote the test for this, but for step 2, it's fiddly to get the selected values of the controls using xpath selectors. My approach seems like it could be fragile, but I wasn't sure what else to do

2020-11-24 21:54 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +});
Does that include if you try:

```typescript
Object.assign(navigator, {
  clipboard: {
    writeText: jest.fn(),
  },
});
```

2020-11-24 22:11 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +});
Yup, that works just fine

2020-11-25 00:38 UTC, edalex-ian commented
> > [..] b[e] good to have an end-to-end test for this one. That is, with Selenium in the NewSearchPageTest:
> > 
> > 1. make a few minor option selections on the search page - maybe just query text would work;
> > 2. share the link - so it's in the clipboard
> > 3. Use that link to `go()` to
> > 4. Confirm you're back at the search page and your option has taken effect.
> 
> I wrote the test for this, but for step [4], it's fiddly to get the selected values of the controls using xpath selectors. My approach seems like it could be fragile, but I wasn't sure what else to do

As discussed, step 4 can be as simple as validating that you have the expected number of results (say, aim for 1) and the correct item(s) - just by checking name. All the heavy lifting of logic and setting of options has been (correctly) addressed over in Jest tests at the unit level. Minimise overlap, and just focus here on the round trip of the clipboard. :wink:

2020-11-25 05:30 UTC, mrblippy commented
> > > [..] b[e] good to have an end-to-end test for this one. That is, with Selenium in the NewSearchPageTest:
> > > 
> > > 1. make a few minor option selections on the search page - maybe just query text would work;
> > > 2. share the link - so it's in the clipboard
> > > 3. Use that link to `go()` to
> > > 4. Confirm you're back at the search page and your option has taken effect.
> > 
> > 
> > I wrote the test for this, but for step [4], it's fiddly to get the selected values of the controls using xpath selectors. My approach seems like it could be fragile, but I wasn't sure what else to do
> 
> As discussed, step 4 can be as simple as validating that you have the expected number of results (say, aim for 1) and the correct item(s) - just by checking name. All the heavy lifting of logic and setting of options has been (correctly) addressed over in Jest tests at the unit level. Minimise overlap, and just focus here on the round trip of the clipboard.

Yeah, that's a good idea @edalex-ian . But, it turns out that was the least of my issues. The github actions autotests run in headless mode. 
Which meant that the method i was using to get the contents of the clipboard (`java.awt.Toolkit.getSystemClipboard()`) wouldn't work.

The next thing i tried was to call the javascript Clipboard API, using `JavascriptExecutor.executeAsyncScript`, but that also fails using chrome headless. Because it requires the user to allow access to the clipboard. 
There appears to be a way to set this using selenium, but it's not in a stable release version. https://groups.google.com/g/chromedriver-users/c/gq9P0wPTmTY/m/VnNVUKS9AAAJ

So instead, i have added some additional testing in the SearchPage.test.tsx to verify that the correct value is being sent to the mocked clipboard

2020-11-26 00:25 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +          () => value?.map((collection) => pick(collection, ["uuid"])),
This is marked resolved but there is no answer or change?

2020-11-26 00:27 UTC, edalex-ian approved these changes
Looks like it's ready to go other than that one outstanding query from @PenghaiZhang .

If no action needed there, then I reckon you can merge. :+1:

2020-11-26 04:50 UTC, mrblippy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +          () => value?.map((collection) => pick(collection, ["uuid"])),
I thought I had put a comment for this one :thinking: 

But, without the ? it can get into that match with an undefined value

2020-11-26 05:55 UTC, PenghaiZhang approved these changes
Looks good to me !

2020-11-26 21:51 UTC, merged