Feature/select resource from new search page
openequella/openEQUELLA pull request #2547
Opened 2020-11-24 06:14 UTC by PenghaiZhang

#688 

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR includes much more code than I imaged.

Here is a list of what changes have been made: 

1. Functions made in 'SelectionSessionModule.ts' to support selecting resources from new search UI (e.g. API calls and DOM update).

2. Changes made in Java/JS files in order to ensure selecting/unselecting resources from either `structure` or `selectOrAdd` in new/old UI  works correctly.

3. Changes made in `SearchPage.tsx` to skip query string param conversion if Selection Session is open.

4.

2020-11-24 22:54 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/scripts/attachments/attachments.js
> +			// To support using the standard reload function for selecting all attachment,
The format of these comments is broken here but looks good locally. :thinking:

2020-11-24 22:54 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SelectionSessionModule.test.ts
> +const basicRenderData: RenderData = {
This mocked renderData consts and functions appear in here and `SearchResult.test.ts`. Perhaps  we can centralise them in a utility file ?

2020-11-24 22:54 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SelectionSessionModule.ts
> +const submitSelection = <T>(
I did not put this function in the REST Module as we don't have REST endpoints for Selection Session yet. In addition, I am unsure how to write tests for this function. I can make a mocked `Axios.post` though and check if the callback has been called or not.

2020-11-25 07:17 UTC, edalex-ian requested changes
Wowsers, there's a fair tangle here. Looking forward to the future where we can do the full New UI implementation of Selection sessions. But in the mean time, fair effort wrangling all that together! :+1: 

A couple of minor tweaks requested. And then probably also a desire to futher highlight all this AJAX interaction code is 'Legacy'.

There's a lot of building of data structures etc in SelectionSessionModule on the legacy side. Should we test that? Feels like we should, feels like it could break easily. :confused:

2020-11-25 07:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SelectionSessionModule.test.ts
> +const basicRenderData: RenderData = {
Yup, sounds like a good plan to me. :+1:

2020-11-25 07:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SelectionSessionModule.test.ts
> +      when: string,
It's a bit more common, and makes a bit more sense, to put the description/when string as the first item (or column if you think of this as tabular data). And then the string you'd have you'd have: `"when [%s] then return [%s]"`

2020-11-25 07:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SelectionSessionModule.test.ts
> +    [true, "selectionSessionInfo has correct type", basicRenderData],
Should this perhaps be:

```suggestion
    [true, "RenderData includes SelectionSessionInfo", basicRenderData],
```

2020-11-25 07:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +      SelectionSessionModule.selectResourceForNonCourseList;
Why didn't you just do this on the import?

E.g.

```typescript
import {selectResourceForCourseList, selectResourceForNonCourseList} from ...
```

2020-11-25 07:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +        fireEvent.click(getByLabelText(resourceType));
It's unclear what this is all about. I'm guessing - which we don't want readers to have to do - that the intention here is to check on the presence of a selection button and then click it. If so, it could greatly benefit by something like:

```typescript
const makeSelection = (selectorLabel: string) => {
  // First, make sure the selector control is active
  expect(queryByLabelText(selectorLabel)).toBeInTheDocument();
  // And then make a selection by clicking it
  fireEvent.click(getByLabelText(selectorLabel));
}
```

And then tweak this to be:

```suggestion
        makeSelection(resourceType);
```

2020-11-25 07:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +    it.each([
Although we have this test to (I think) check that the selector controls are active in Selection Sessions. We don't seem to have a function to ensure we don't show them during non-Selection Sessions. Could be handy...

2020-11-25 07:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SelectionSessionModule.ts
> +const submitSelection = <T>(
Yup, you're right not to put this in the REST module. But I feel we need to somehow highlight this is the interface to Legacy Selection Sessions. I wonder if we should push these interface definitions, HTTP calls and supporting functions into maybe something called `LegacySelectionSessionModule.ts` and maybe at the top of the file a file wide comment stating that this Module is all about interacting with the Legacy AJAX endpoints for selections sessions, and will be used until the supporting REST endpoints are developed. :thinking:

2020-11-25 07:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SelectionSessionModule.ts
> + * Select resources in 'structured'. The approach is to call the server ajax method 'reloadFolder'
```suggestion
 * Select resources in 'structured'. The approach is to call the server AJAX method 'reloadFolder'
```

2020-11-25 07:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SelectionSessionModule.ts
> +  return submitSelection(
So is this:

```suggestion
  return submitSelection<void>(
```

2020-11-25 07:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/scripts/attachments/attachments.js
> +			// To support using the standard reload function for selecting all attachment,
I'd imagine it's tabs vs. spaces in this ol' stuff.

2020-11-25 07:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/scripts/courselist.js
> +  updateCourseList: function(result) {
Was this pushed into a function to allow you to call from TS side?

2020-11-25 07:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/scripts/courselist.js
> +    $tree.html($newTree.find(".foldertree"))
This seems like a significant change and removal of an optimisation. Could you explain the backstory here please?

2020-11-25 07:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/itemlist/standard/AbstractItemlikeListAttachmentDisplaySection.java
> +  public void selectAttachmentsFromNewSearch(
Sorry, I've lost track of the threads. Where is this triggered from?

2020-11-25 22:58 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/scripts/courselist.js
> +  updateCourseList: function(result) {
Yes it's. It was part of `updateTargetFolder`

2020-11-25 22:58 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/scripts/courselist.js
> +    $tree.html($newTree.find(".foldertree"))
With previous code, if we want to remove some selected resources in the dialog, when we close the dialog, we will only see that the currently selected course gets its UI updated. 

For example, course A has two resources and course B has one. And B is currently selected.

So in the course list we should see
```
A   (2)
B   (1)
```

And then we remove all selected resources and it's expected to see
```
A   (0)
B   (0)
```

But what is actually displayed is 
```
A   (2)
B   (0)
```

A does not get updated. If we navigate to a different page which results in a page refresh, we will see the correct UI.

2020-11-25 22:58 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/scripts/courselist.js
> +    $tree.html($newTree.find(".foldertree"))
With previous code, if we want to remove some selected resources in the dialog, when we close the dialog, we will only see that the currently selected course gets its UI updated. 

For example, course A has two resources and course B has one. And B is currently selected.

So in the course list we should see
```
A   (2)
B   (1)
```

And then we remove all selected resources and it's expected to see
```
A   (0)
B   (0)
```

But what is actually displayed is 
```
A   (2)
B   (0)
```

A does not get updated. If we navigate to a different page which results in a page refresh, we will see the correct UI.

2020-11-25 22:59 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/scripts/courselist.js
> +  updateCourseList: function(result) {
Yes, we use this function in `SelectionSessionModule.ts`

2020-11-25 23:11 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/itemlist/standard/AbstractItemlikeListAttachmentDisplaySection.java
> +  public void selectAttachmentsFromNewSearch(
The only usage of this is in `SelectionSessionModule.ts`. There is an existing one named `selectAttachment`, and there are two key differences:

1. this one will not unselect an attachment if the button is clicked again.
2. this one supports selecting multiple attachments.

2020-11-25 23:36 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SelectionSessionModule.ts
> +const submitSelection = <T>(
Good idea. I have renamed the module.

2020-11-25 23:39 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +      SelectionSessionModule.selectResourceForNonCourseList;
Because there is an import of the entire module into a single variable so I was thinking if I should skip the duplicated imports.

2020-11-25 23:51 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +        fireEvent.click(getByLabelText(resourceType));
Sorry for the confusion. Yes your guess is 100% correct.

2020-11-26 00:07 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +    it.each([
What about adding a test to check these buttons disappear in non-Selection Sessions ?

2020-11-26 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/web/scripts/courselist.js
> +    $tree.html($newTree.find(".foldertree"))
Okay, but... Does that mean this is effectively fixing a bug in the Legacy mode too? Or more so, that bug was just not exhibited due to a server side re-render?

2020-11-26 00:31 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/itemlist/standard/AbstractItemlikeListAttachmentDisplaySection.java
> +  public void selectAttachmentsFromNewSearch(
Ah! How it is triggered? Just but building up the correct events etc for the POST?

2020-11-26 00:54 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/scripts/courselist.js
> +    $tree.html($newTree.find(".foldertree"))
Yes, the server side re-render hides the bug for Legacy mode.

2020-11-26 01:14 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SelectionSessionModule.ts
> +  return submitSelection(
I think we should use `unknown`  as this type is for the parameter passed to the callback, which is `unknown` in this case.

```
 updateCourseList: (data: unknown) => void;
```

2020-11-26 01:20 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/itemlist/standard/AbstractItemlikeListAttachmentDisplaySection.java
> +  public void selectAttachmentsFromNewSearch(
Yes, as long as we tell the server which section we need, which is `ilad` here. 
`ilad` is probably the short name of `AbstractItemlikeListAttachmentDisplaySection`

2020-11-26 05:34 UTC, edalex-ian approved these changes
Good stuff dude. This is good to go, just two bits for the tests first would be nice. :grin: 

Feel free to merge when you're ready.

2020-11-26 05:34 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/LegacySelectionSessionModule.test.ts
> +  describe("buildPostDataForSelectOrAdd", () => {
That's odd. Are you aware this is sitting in the `buildPostDataForStructured` describe block?

2020-11-26 05:34 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +    };
This could be simplified with:

```suggestion
    const makeSelection = (
      findSelector: (text: string) => HTMLElement | null,
    ) => {
      const selectorControl = findSelector();
      // First, make sure the selector control is active
      expect(selectorControl).toBeInTheDocument();
      // And then make a selection by clicking it
      fireEvent.click(selectorControl);
    };
```

And that way when you use it you'd only have to:

```typescript
makeSelection(() => queryByLabelText(resourceType));
```

2020-11-26 05:37 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +    };
But I guess `fireEvent.click` will complain because `selectorControl` could be null.

2020-11-26 05:42 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +    };
Yeah, here is the error: 

Argument of type 'HTMLElement | null' is not assignable to parameter of type 'Element | Node | Window | Document'.
      Type 'null' is not assignable to type 'Element | Node | Window | Document'.

What about we use a if statement and throw an error if `queryByLabelText` returns null ? We have used this approach for `querySelector` in a few places.

2020-11-26 05:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +    };
Yup, I'd say that'd be the plan. But just wrap the fireEvent in the `if`.

Actually, this is probably a valid case of using the not null (`!`) postfix operator - as we definitely know (due to validation with `expect`) that this is non-null. :thinking:

2020-11-26 05:46 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/LegacySelectionSessionModule.test.ts
> +  describe("buildPostDataForSelectOrAdd", () => {
oops I will move his describe out.

2020-11-26 06:59 UTC, edalex-ian approved these changes
Merge on. :+1:

2020-11-26 09:14 UTC, merged