Make pdf extraction safe
openequella/openEQUELLA pull request #2561
Opened 2020-11-27 01:07 UTC by SammyIsConfused

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]

##### Description of change
#2530 
Text extraction for indexing on "broken" PDF files can cause performance and stability issues, slamming server CPU. This PR is to address this by adding a new column to the ATTACHMENT table. After a timeout (controlled by the existing property `textExtracter.parseDurationCap` in milliseconds in the `plugins/com.tle.core.freetext/optional.properties` file) PDF extraction will error out and a flag will be set to true on the attachment, errored_when_indexing. When the item is re-indexed for any reason, that attachment will be skipped for extraction. 

This will serve to prevent perpetual server load hammering by the TextExtracter and also highlight problem attachments in the database. An admin would be able to go into the ATTACHMENT table and check for any with `errored_while_indexing`. If there are any, those attachments can be followed up and checked for issues. 

This PR includes a migration to add the new column, `com.tle.core.institution.migration.v20202.addIndexingErrorColumnMigration` and set it to false by default. It has also been incorporated into Attachment serialization.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-11-27 05:28 UTC, SammyIsConfused commented
Missing license header. Fixing up now

2020-11-29 21:45 UTC, edalex-ian commented
Noticed that you re-requested reviews but then still had a few commits to do. So let us know when it's ready again.

2020-11-30 01:04 UTC, SammyIsConfused commented
Gah! MimeTypesTest flaked again. 
Looked into it and found a fix, I've put it as a separate PR so that this branch doesn't hold up others. 
I think this test failure can be safely ignored as the fix already exists. 
@edalex-ian This branch is now ready for review.

2020-12-01 01:54 UTC, edalex-ian requested changes
Good stuff @SammyIsConfused . Just needs a bit of JavaDoc and some Java 8 treatment. Other than that, maybe the new Thread can be simplified.

Also, being that it has a data migration, I'd be really keen to have @PenghaiZhang review before merge.

2020-12-01 01:54 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/item/attachments/IAttachment.java
> +  boolean isErroredIndexing();
Although not done historically, for the new stuff we add JavaDoc to help our future selves. Please add.

2020-12-01 01:54 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.base/src/com/tle/web/api/item/interfaces/beans/AttachmentBean.java
> +  public boolean isErroredIndexing() {
Please JavaDoc - even if it's a `@see` to `IAttachment` matching method.

2020-12-01 01:54 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
> +/com.tle.core.entity.services.migration.v20202.indexing.errored=Add column to attachment table to allow indexer to skip individual attachments that have timed out.
Be worthwhile to keep wording around it generic. That way if in the future we have other failure modes, we're all set.

```suggestion
/com.tle.core.entity.services.migration.v20202.indexing.errored=Add column to attachment table to allow indexer to skip individual attachments that have failed.
```

2020-12-01 01:54 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/extracter/standard/PdfExtracter.java
> +        new Runnable() {
Being in Java 8 land, best to now go with an anonymous lambda rather than an anonymous class and all its overhead.

2020-12-01 01:54 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/extracter/standard/PdfExtracter.java
> +            } catch (Exception t) {
It could be good to add a `catch` for `InterruptException` to capture when it's terminated early (or by other unforeseen interrupts). :thinking:

2020-12-01 01:54 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/extracter/standard/PdfExtracter.java
> +    executor.shutdownNow();
Bringing in an `ExecutorService` etc. seems rather heavy handed for a single thread. How about just going with:

```java
Thread extractThread = new Thread(() -> { ... }, "ExtractThread");
extractThread.join(parseDuration);
extractThread.interrupt();
```

I'm assuming that `interrupt()` will be sufficient, as that's they typical recommendation for `ExecutorService.shutdownNow()`. But maybe you had issues?

2020-12-01 23:24 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/extracter/standard/PdfExtracter.java
> +    executor.shutdownNow();
I tried your way and it doesn't seem to work. The problem with interrupt is that it seems to simply set a flag that needs to be handled in the thread with isInterrupted(), which would be fine if we had a loop but we don't, it's parser.parse that is the cause of the issue.

2020-12-02 00:03 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/extracter/standard/PdfExtracter.java
> +    executor.shutdownNow();
Cool, evidentially the implementation is doing more of a hard stop - which is typically advised against due to stray objects etc. But that is more so where there are multiple threads of the same code.

So in this case, you have cause for the increased complexity. Thanks for checking. :+1:

2020-12-02 01:17 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/extracter/standard/PdfExtracter.java
> +            } catch (Exception t) {
The InterruptedException isn't actually thrown here - it's thrown by future.get. So I surrounded that with try/catch and logged the InterruptedException/TimeoutException/ExecutionException that can throw. Then I rethrew so that the indexerThread can catch it further up where it sets the erroredIndexing flag.

2020-12-02 03:13 UTC, SammyIsConfused commented
AdvancedScriptControlTest flaked. Rerunning.

2020-12-03 04:13 UTC, ChristianMurphy reviewed
Error recovery/management is a nice add, thanks @SammyIsConfused!

2020-12-03 04:13 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/item/attachments/Attachment.java
> +  private boolean erroredIndexing;
:thinking: would this make sense as a state/enumeration?
something like
```
             state machine
+-----------------------------------------+
|                                         |
|                        +--------------+ |
|                        |              | |
|         +-----------+->+ indexed      | |
| added   |           |  |              | |
+-------->+ unindexed |  +--------------+ |
|         |           |  |              | |
|         +-----------+->+ index failed | |
|                        |              | |
|                        +--------------+ |
|                                         |
+-----------------------------------------+

```

new attachments start as unindexed, they can move to indexed, to index failed when processed.
A state system would also leave to door open for partially indexed content, or other possible states.

Though it may be overkill here :thinking: 
Thoughts? :thought_balloon:

2020-12-03 04:13 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/item/attachments/Attachment.java
> +  public void setErroredIndexing(boolean skipIndexing) {
would it make sense for the param to also be `errorIndexing`?

2020-12-03 04:13 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/item/attachments/Attachment.java
> +  public boolean isErroredIndexing() {
Maybe `hasErroredIndexing` would read more naturally here? :thinking:

2020-12-06 23:20 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/item/attachments/Attachment.java
> +  private boolean erroredIndexing;
This is what we were talking about at the start @SammyIsConfused . But I believe you highlighted that unfortunately the tracking of this is split across levels of the entity hierarchy. I think the primary index tracking is done at the item level, yet what was being addressed and flagged here was the actions occurring at the item attachment level.

So now we can have an item which is 'indexed' (after previously being 'unindexed'), but potentially some attachments are flagged as having errored - avoiding excessive future indexing. Is that right?

2020-12-06 23:36 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/item/attachments/Attachment.java
> +  public boolean isErroredIndexing() {
Although I agree that it would read more natural. The Java standard for booleans on Beans (this being an `Entity` bean) is to  use the `is` prefix for boolean getters.

2020-12-06 23:37 UTC, edalex-ian approved these changes
Looking good @SammyIsConfused . Feel free to proceed when others happy.

I see there's a method param you missed renaming of which @ChristianMurphy , and I've also requested @PenghaiZhang to come and review - especially seeing you've got a migration in here.

2020-12-07 00:35 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/institution/migration/v20202/AddIndexingErrorColumnMigration.java
> +    @Column boolean errored_when_indexing;
If you do `nullable = false` in `Attachment.java`, you also need to do that here.

2020-12-07 00:35 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/institution/migration/v20202/AddIndexingErrorColumnMigration.java
> +    return helper.getAddNotNullSQL("attachment", "errored_when_indexing");
Hi Sam, I have two questions here. 
1. Do we need to drop column 'errored_when_indexing'  in any situation?  If yes, I think we should use
'getDropModifySql'.

2. I am not quite sure why use `getAddNotNullSQL`. If this column needs a not null constraint, you can try
`@Column(name = "errored_when_indexing", nullable = false)` in  `attachment.java`.

2020-12-07 01:45 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/institution/migration/v20202/AddIndexingErrorColumnMigration.java
> +    return helper.getAddNotNullSQL("attachment", "errored_when_indexing");
Hey Penghai - if we wanted to make it backwards compatible, that would require removing the column. So I should fix that up.
The reason for using getAddNotNullSQL was simply that I was using AddInstitutionFileWarningColumn as a template - if there's a better way I'm happy to use that.

2020-12-07 01:50 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/item/attachments/Attachment.java
> +  private boolean erroredIndexing;
Well summed up Ian, yes that's correct. The index tracking is at the item level and doesn't keep info about specific attachments. This change means that an entire item can be indexed even if it has an attachment flagged as errored - that attachment will simply be skipped in future indexes to prevent performance problems. 

This also gives the ability to look at the database and get a list of all attachments that need fixing up to be indexed properly. `SELECT * FROM attachment WHERE errored_when_indexing=true` will point a DBA at exactly where the problems are. It would not have been possible to glean this info from the `item` table alone.

2020-12-07 01:51 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/item/attachments/Attachment.java
> +  public void setErroredIndexing(boolean skipIndexing) {
Well spotted, will fix that up. That was the old name of this field.

2020-12-07 05:43 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/institution/migration/v20202/AddIndexingErrorColumnMigration.java
> +    return helper.getAddNotNullSQL("attachment", "errored_when_indexing");
There's no need for the getDropModifySql, I was following another as a template.
Adding nullable=false to Attachment.java now.

2020-12-07 05:45 UTC, ChristianMurphy approved these changes

2020-12-08 02:21 UTC, PenghaiZhang approved these changes
Looks good to me!

2020-12-08 02:33 UTC, merged