Make sure that thumbnailing timeout kills both imagick and ghostscript
openequella/openEQUELLA pull request #2566
Opened 2020-11-29 22:14 UTC by SammyIsConfused

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]

##### Description of change
Related to #2527, the delegate `ghostscript` doesn't inherently close when imagemagick does. This PR ensures that when thumbnailing times out, any child processes of imagemagick are killed first. 

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-11-30 03:41 UTC, edalex-ian requested changes
Heya @SammyIsConfused 

Good work sticking through the difficulties here. A few things to tidy up and consider.

Obviously we're first focusing on Linux, but still not a bad idea to ponder the Windows situation too for any quick wins - like the process ID.

BTY.

2020-11-30 03:41 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +    public static void main(String[] args) {
I gather this must be following an example, as there is no need for this setup here. It can just be a stand-alone static method like the others in this class. Probably with a signature like: `public static void killLinuxProcessTree(int pid)`

2020-11-30 03:41 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +        LinuxKill.main(new String[] {pid});
Should you check first you're running on linux?

2020-11-30 03:41 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +            }
Couple of things here.

1. you may wish to consider using `CharStreams.copy(new InputStremReader(getChildPid.getInputStream(), childPid);`; and
2. What if you get multiple PIDs back? Are they find coming back with new lines and getting fed to the following `exec`?

2020-11-30 03:41 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +          }
So if it returns non-zero, it won't throw an exception (I gather). So the catch block wont be triggered and nothing will be logged (or noted).

2020-11-30 03:41 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +          LOGGER.debug("Exit value: " + exitVal); // often 1 under Ubuntu 12.10
Your comment is confusing me. Above you check to see that `kill -9` returns zero. Then here you're saying it could return 1. Which is it?

Also, be good here to do the same as the above and check the result.

And arguably this code is the same as the above and should be in it's own method, perhaps: `static void int sendSigKill(int pid)`. Could encapsulate waiting and logging, but then ultimately still return the exit code.

2020-11-30 03:41 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +        LOGGER.warn("Process Kill failed. Process may be left hanging");
Be good to know why it failed. (Also, slight change in capitalisation.)

```suggestion
        LOGGER.warn("Process kill failed. Process may be left hanging. " + e.getMessage());
```

2020-11-30 03:41 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +      return pid;
What exceptions get thrown here? Could be good to be more targetted, and to log what happened.

2020-11-30 03:41 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +    return pid;
Seems awkward to have the two `return` statements right next to each other. Would a `finally` block perhaps be a better fit?

2020-11-30 03:41 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +   * Gets the PID of a given process.
```suggestion
   * Gets the process ID (PID) of a given *nix process.
```

2020-11-30 03:41 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +        Field f = p.getClass().getDeclaredField("pid");
What's the difference with say Windows? As those processes also have IDs, is it simply a case of a different name for the field?

2020-12-01 02:13 UTC, SammyIsConfused commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +        Field f = p.getClass().getDeclaredField("pid");
No unfortunately, not with Java 8. With 9, you can just `process.pid();` I've been looking into it, the ID is not a field in a Windows Process. Other solutions include: 

- Using JNA (com.sun.jna) https://stackoverflow.com/a/43426878 but that requires us to install new dependencies
- Calling `tasklist` (windows command to get all running process IDs) before starting the process and again after, and using the diff of the two to find the new PIDs (I don't like this idea, if another process just happened to start between the two checks that could be a false positive)

Once we have a Windows PID however, killing it and it's child processes is not too difficult with `taskkill`. But targeting the right process is where it gets tricky. 

Another complication is that I have no dev environment for Windows (testing installers yes, but debugging a dev environment no).  So making it work for Windows would probably take too long (at least for 2020.2).

2020-12-01 02:39 UTC, SammyIsConfused commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +    return pid;
I tried that, but apparently the inspector has a problem with having a return within a finally block. 

>'return' inside 'finally' block 
 Inspection info: Reports return statements inside of finally blocks. While occasionally intended, such return statements may mask exceptions thrown, and tremendously complicate debugging.

2020-12-01 03:40 UTC, SammyIsConfused commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +          LOGGER.debug("Exit value: " + exitVal); // often 1 under Ubuntu 12.10
So that comment was left over from an [example](https://askubuntu.com/questions/222604/killing-processes-from-java) that I was editing to suit me. In my testing, it returns 0. But apparently it can return 1 according to the SO link, so I'm unsure. 
Either way I have refactored, and removed the comment.

2020-12-01 03:55 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +    return pid;
I see it's now refactored to simply use the default return with `pid`. Much better.

2020-12-01 03:57 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +      return childPid.toString().replaceAll("\n", "").split(" ");
IShould that be:

```suggestion
      return childPid.toString().replaceAll("\n", " ").split(" ");
```

2020-12-01 04:01 UTC, SammyIsConfused commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +      return childPid.toString().replaceAll("\n", "").split(" ");
Ah yup, you're right. I had assumed that it prints them all on one line space-separated and then ends with \n. But testing it now I see that it has \n after each one.

2020-12-01 04:57 UTC, edalex-ian requested changes
Great tidy up there @SammyIsConfused . Now that we can see the wood for the trees, unfortunately a few more things to sort.

But after that you should have a winner.

2020-12-01 04:57 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +    if (pid > 0) {
Rather than silently doing nothing, how about invert this logic:

```java
if(pid < 1) {
  throw new IllegalArgumentException("Process ID should be greater than 0");
}
```

2020-12-01 04:57 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +      }
The way you're having to use this highlights a few issues with the below methods. Really, you'd expect the methods to support something like:

```java
getChildUnixProcessPids(pid)
  .ifPresent(pids ->
    sendSigKill(pids));
```

Comments which follow have this in mind.

2020-12-01 04:57 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +   * @return String[] An array of process IDs for the children of pid. Can be empty.
If 'Can be empty' how about return an `Optional`? You'd then reap the benefits hoped for above, plus your method signature than flags this without the need for a comment.

2020-12-01 04:57 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +      return childPid.toString().replaceAll("\n", " ").split(" ");
It's expected that this method would return an array of numbers (PIDs) not strings. Keep in mind the above suggestion for an `Optional` it'd be good if you also streamed across the strings to transform them to Integers. Something like:

```java
Arrays.stream(childPid...split(" "))
  .stream()
  .mapToInt(s -> Integer.parseInt(s))
  .toArray();
```

2020-12-01 04:57 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +  public static int sendSigKill(int pid) {
Seeing `kill` has a definition of:

```
kill [options] <pid> [...]
```

It'd make sense to allow this to support a list of PIDs too:

```suggestion
  public static int sendSigKill(int[] pid) {
```

That also then supports your use case of killing potentially multiple PIDs. If you did also want to support the form of taking a single PID (which I'm not sure you have a use for here), then you could add an overload that does the transform simply to an array and chain to this method.

2020-12-01 04:57 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +    return -1;
If you should get here, should you perhaps ensure that by adding a line to your above catch to throw or rethrow?

2020-12-01 04:57 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +              "Platform not yet supported for process tree kill. Processes may be left hanging");
```suggestion
              "Platform (" + platform + ") does not supported process tree kill. Processes may be left hanging.");
```

2020-12-01 07:09 UTC, SammyIsConfused commented
Should be good now @edalex-ian :+1:

2020-12-01 07:13 UTC, SammyIsConfused commented
Just snook in a merge of develop so that MimeTypesTest doesn't bite us, but it's good to go :+1:

2020-12-01 23:30 UTC, edalex-ian approved these changes
Good stuff @SammyIsConfused .

If you just want to tweak the comment and log messages, then merge on in. :+1:

2020-12-01 23:30 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +   * @return Optional<String[]> An array of process IDs for the children of pid.
```suggestion
   * @return Process IDs for the children of {@code pid}.
```

2020-12-01 23:30 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +      LOGGER.error("Output of getChildPids command not parsable as integers", e);
Being an `error` level log message, would be good if it was a more useful error message for an administrator.

```suggestion
      LOGGER.error("Unsupported output from 'pgrep -P'. Unable to terminate child processes.");
      LOGGER.error("'pgrep' output: " + childPid.toString());
      LOGGER.error("Parsing exception.", e);
```

2020-12-01 23:30 UTC, edalex-ian commented on Platform/Plugins/com.tle.platform.common/src/com/tle/common/util/ExecUtils.java
> +        LOGGER.debug("kill function did not run properly.\n" + errorOutput);
Be useful for administrators to know when this kind of thing is not functioning correctly.

```suggestion
        LOGGER.warn("Attempt to terminate processes failed (" + command + "):\n" + errorOutput);
```

2020-12-01 23:54 UTC, SammyIsConfused commented
That failure was caused by `childPid` not being accessible from line 104:
`      LOGGER.error("'pgrep' output: " + childPid.toString());`
Fix was to declare the StringBuilder childPid outside of the try/catch.

2020-12-02 02:15 UTC, SammyIsConfused commented
ViewerTest failed because Vimeo search returned nothing - probably caused by temporary issues on Vimeo's end. Rerunning.

2020-12-02 04:47 UTC, merged