Parse Youtube Date Modified dates properly
openequella/openEQUELLA pull request #2577
Opened 2020-12-02 05:46 UTC by SammyIsConfused

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included

##### Description of change
The YouTube controls were not working properly. This is because once oEQ got to parsing the date modified string that was returned for a YouTube result it was found to be unparsable. It used to work properly but updates to the YouTube API involved changes to the date format. 
This PR addresses the issue by parsing the date properly, in the YoutubeHandler when running Youtube searches and displaying results, in the YoutubeAttachmentSerializer when saving attachments to the database, and YoutubeViewableResource when displaying the resource summary.
![image](https://user-images.githubusercontent.com/24543345/100833335-df045b00-34bd-11eb-97b9-5d1b287ac49b.png)

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-12-02 14:19 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeAttachmentSerializer.java
> +            .getMillis();
Would this a be a place where Joda time, could be dropped in favor of `java.Time`?
https://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html#parse-java.lang.CharSequence-
https://docs.oracle.com/javase/8/docs/api/java/time/chrono/ChronoZonedDateTime.html#toInstant--
https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#toEpochMilli--

2020-12-06 23:09 UTC, edalex-ian requested changes
As @ChristianMurphy mentioned, and as dicussed today, when in Java 8+ land best to move to Java 8 date/time classes.

Further to that though, it would be worthwhile having a shared/static `parseYouTubeDate(string date)` method to abstract the data specification and avoid the duplication of `ISODateTimeFormat.dateTimeNoMillis().parseDateTime(...)`. Obviously this would return the needed Java 8 date type which you can then simply call the equivalent of `.toDate()` and `.getMillis()` on in these three places.

2020-12-07 05:08 UTC, SammyIsConfused commented
Ready for review - looks like I had the wrong version of the commit hook formatter installed for 398d0cc.

2020-12-07 06:19 UTC, edalex-ian approved these changes
Looks good. Just keep in mind with your optional you don't need to be as verbose with intermediate variables (if they're not needed later). And also, be careful re-wrapping exceptions into generic ones, as callers can't then filter to that.

If you could please address some of those suggestions, then you're good to merge I'd say.

2020-12-07 06:19 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeAttachmentSerializer.java
> +    date.ifPresent(ybean::setUploadedDate);
In this case, the intermediate `date` variable is rather redundant. I'd keep it nice and tidy and simply have:

```suggestion
    YoutubeUtils.parseDateModifiedToDate((String) cattach.getData(YoutubeUtils.PROPERTY_DATE))
      .ifPresent(ybean::setUploadedDate);
```

2020-12-07 06:19 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeHandler.java
> +                  date -> result.setDate(dateRendererFactory.createDateRenderer(date)));
Similar to above.

```suggestion
              YoutubeUtils.parseDateModifiedToDate(vidInfo.getPublishedAt())
                .ifPresent(
                  date -> result.setDate(dateRendererFactory.createDateRenderer(date)));
```

(Unless I'm missing them being used somewhere else.)

2020-12-07 06:19 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeViewableResource.java
> +    Optional<Date> date =
As above. `date` redundant.

2020-12-07 06:19 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeUtils.java
> +      throw new RuntimeException("Unable to parse youtube date modified: " + date, e);
Rewrapping into a generic exception can limit possibilities for callers. I'd say just drop the `try/catch` adn allow the DateTimeParseException to percolate. Or, if you feel it's handy to add the extra message, consider doing so but maybe go with a more meaningful exception - say, `IllegalArgumentException` or reuse `DateTimeParseException`.

2020-12-07 23:57 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeUtils.java
> +      throw new RuntimeException("Unable to parse youtube date modified: " + date, e);
I think it's worth keeping the message. So I'll just throw a new DateTimeParseException with the message and the contents of the initial thrown one.

2020-12-08 01:40 UTC, SammyIsConfused commented
Took out the <p> tag but it turns out the formatter requires it, so I reverted a367caa.

2020-12-08 02:08 UTC, SammyIsConfused commented
So the reason for the failures on 68b8970 is because in the test institutions there are existing YouTube attachments that were created in the old v2 API implementation - and for those they are stored in epoch long format. af68070 fixes that by making the parse function accept and Object - if its a long we assume its an epoch, otherwise we assume its a ISO_DATE_TIME string.

2020-12-08 02:11 UTC, edalex-ian requested changes

2020-12-08 02:11 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeUtils.java
> +    } else {
I like the rework of this method - and supporting calls. But, why not do an `else if(date instanceof String)` for this block, and then have a final `else` block which throws an `IllegalArgumentException`?

Best to only assume if you have to.

2020-12-08 02:24 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeUtils.java
> +    } else {
Fixed in 3be02e2.

2020-12-08 04:29 UTC, edalex-ian approved these changes
That all looks nice and tidy @SammyIsConfused and a great improvement over what was there.

One last lingering query. But after that, you'd be good to merge. :+1:

2020-12-08 04:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeUtils.java
> +      }
Is this not just something like:

```suggestion
      parsedDate = parseDateModifiedToMillis((String) date)
        map(millis -> new Date(millis));
```

I'm just freestyling there, but hopefully you get the idea.

2020-12-08 05:05 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/controls/youtube/YoutubeUtils.java
> +      }
You were close! It has to be `flatMap`.

2020-12-08 12:33 UTC, ChristianMurphy approved these changes

2020-12-08 22:05 UTC, merged