Fix Bb LTI / REST caching and request all course folders
openequella/openEQUELLA pull request #2592
Opened 2020-12-09 19:12 UTC by cbeach47

History in #2587

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included - N/A
- [x] screenshots are included showing significant UI changes - N/A
- [x] documentation is changed or added - N/A

##### Description of change

Caching adjustments:
* Leverage Bb REST API refresh tokens so the user does not have to log back into Bb during the same oEQ session
* User session caching now in place for auth token
* Auth caches now combined into a single cache of the entire `Token`
* `Course`s and `Folder`s requests are now setup to check the cache, and if none are available, pull a fresh set of results from Bb

Found a unrelated bug where only the first 200 content items from a Bb course were being returned.  Now pulls all pages of content results.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2020-12-09 19:47 UTC, ChristianMurphy commented
https://github.com/openequella/openEQUELLA/pull/815#pullrequestreview-222997052 applies here as well.
Maybe with the Spring upgrade Lombok would work?

2020-12-09 20:59 UTC, cbeach47 commented
It's a fair point.  Budget on this effort is tight, so I added #2593

2020-12-09 21:37 UTC, ChristianMurphy approved these changes

2020-12-10 05:33 UTC, edalex-ian requested changes
Heya Chris,

Interesting stuff. Was a tad hard to review as one minute I've paged in the design around auth tokens, then I need to swap pages to building up folder trees. It would've been really great if these were split in two, as then I could've reviewed them properly and thoroughly - and much quicker.

But in the end, the things that jumped out at me:

* Great to see some more JavaDoc being added, but need a bit more polish in some cases (especialy with `@param` and `@return` from the template added, but then ignored);
* The `sendBlackboardData` function really needs to be tidied up, and each addition to it (such as here) is definitely making it worse - and now it even has duplicate string comparisons to check current state/mode; and
* Two big blocks of code for getting lists should simply be do-while as opposed to while, and even then share the same algorithm which could be simply broken out.

It's really great to see the increased use of Optional and streams - and the continuation here. Thank you so much for taking that on board in the last review. Was a great value add and will definitely help us into the future.

2020-12-10 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/BlackboardRESTConnectorService.java
>     * @return
Arguably these should be completed. Or, otherwise removed. (But it would be nice if they were actually populated to assist with future maintenance - it's one area that bites us again and again maintaining oEQ code.)

2020-12-10 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/BlackboardRESTConnectorService.java
> +  String encryptKeyAndSecret(Connector connector);
A comment on this would be gold. As it's definitely unclear what this should be doing/implemented as.

From reading on more, I'd suggest a different name though: `buildBasicAuthorizationCredentials`. As that seems to be the aim, and it's definitely not encrypting anything (just encoding).

2020-12-10 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +    authCache = cacheService.getCache(CACHE_ID_AUTH, 1000, 90, TimeUnit.MINUTES);
Maybe I've misread... But, if a token expires after 60mins, why cache for 90mins - shouldn't it also be 60?

I assume with a refresh that'd do an update to the cache item and then it would start its TTL again.

2020-12-10 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +   */
I'd normally only expect this defined in the `interface`, or if you wish to change it maybe have a reference back.

2020-12-10 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +        .replace("\r", "");
Are you sure you want to do that - it's kind of expected with Base64.

2020-12-10 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +      if ("grant_type=refresh_token".equals(data)) {
This function (`sendBlackboardData`) is really getting out of hand and needs to be refactored I'm afraid. We have it implementing two concerns at least - making a request and processing the response - and even in the request areas we have some headers added at the start, some then added later after the body, and then a MIME type set here or there. But then with this modification the request building also includes the verbatim details of whether to attempt a refresh, or use an existing token.

At the very least it should be refactored into: `makeBlackboardRequest` and `processBlackboardResponse`. Following that, each of those should then be tidied up to be more orderly.

2020-12-10 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +      if ("grant_type=refresh_token".equals(data)) {
This string and logic check is duplicated from a few lines up. Should at the very least be stored in a flag, and possibly the logic joined together - or split into another method.

2020-12-10 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +    }
Should this just be a do-while? Something like:

```java
    Optional<String> url = Optional
        .of(API_ROOT_V1 + "courses/" + courseId + "/contents?recursive=true");
    final List<Content> allContent = new ArrayList<>();
    do {
      Contents contents =
          sendBlackboardData(connector, url.get(), Contents.class, null, Request.Method.GET);
      allContent.addAll(contents.getResults());
      url = Optional.ofNullable(contents.getPaging()).map(Paging::getNextPage);
    } while (url.isPresent());
```

2020-12-10 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +    return auth.get();
Should be an orElseThrow:

```suggestion
    return userSessionService.getAttribute(BlackboardRESTConnectorConstants.USER_SESSION_AUTH_KEY)
      .orElseThrow(
        () -> new AuthenticationException("User authentication details are not available in the session"));
```

2020-12-10 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +    }
Is this:

```suggestion
    Token expAuth = getAuth(connector)
      .orElse(() -> getUserSessionAuth());
```

2020-12-10 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +      new AuthenticationException("Unable to refresh auth token.  Please retry action.");
Is this missing a throw?

```suggestion
      throw new AuthenticationException("Unable to refresh auth token.  Please retry action.");
```

2020-12-10 05:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +    }
This looks like it should be a do-while like earlier up.

One thing also interesting here is the duplicated pattern: `sendBlackboardData` -> process output to create a `List` -> check for another page -> repeat. Feels like that should be a method which takes a lambda to support abstracting the commonality of processing/consuming `List` output.

2020-12-10 17:57 UTC, cbeach47 commented
Hmmm - those commits assume java's Optional, and there is a mix of Java and Guava Optional in these classes.  I've put it on the CDM agenda for Jan'21, however, to clean up the code, and since it sounds like Guava recommends Java Optional where possible, I'll convert the Guava Optional to Java Optional early on, and see how that goes.

https://stackoverflow.com/questions/8534442/shortcut-for-guavas-optional-use-with-exceptions

2020-12-10 18:30 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +      new AuthenticationException("Unable to refresh auth token.  Please retry action.");
doh - yes it is.

2020-12-10 20:11 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +        .replace("\r", "");
I pulled that from existing code.  When I remove the 2 `replace` methods, Blackboard responds with `Invalid Credentials`, so I'll leave that logic as-is for now.

2020-12-10 21:46 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +    authCache = cacheService.getCache(CACHE_ID_AUTH, 1000, 90, TimeUnit.MINUTES);
The 3LO flow with Blackboard requires user interaction (or at least a full page redirect).  This disrupts the user experience, and at times, can make the user stop what they are doing and relaunch the 'Add to External System' or LTI Selection Session flows.  The theory with setting this to 90 minutes is to offer a cushion to those users using the flows for extended periods, who may work with the integration over 60 minutes.

With these latest fixes to (a) put the auth token in the user session and (b) leverage the refresh_token flow, I think we can safely bring the cache ttl to match Blackboard's expiry.  I could be convinced that we can bring the size and the ttl lower, to say, 200 and 30 minutes, if folks are concerned with the resources to maintain that cache.

2020-12-10 22:36 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +    }
fixed the do-while.  Time is a bit tight, so I need to forego gathering in the list logic, though I like the idea.

2020-12-10 22:37 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +      if ("grant_type=refresh_token".equals(data)) {
I pulled out the preparation bits and cleaned it up - quite a bit easier to read now, though it could likely use future work, including pagination of results.

2020-12-10 22:51 UTC, cbeach47 commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/BlackboardRESTConnectorService.java
>     * @return
I don't have time for a complete overhaul of the Blackboard code atm, but I'll keep that in mind to not leave javadoc skeletons around :+1:

2020-12-10 23:56 UTC, cbeach47 commented
@edalex-ian - thanks for the review

Good point about the JavaDoc, I'll keep that in mind.

I responded inline about the other comments - overall they made sense, just running up against some time constraints, so I had to prioritize.  I believe this PR is now in good shape to merge once it goes green.  

I'd like to merge this tomorrow (my Friday).  Please let me know if there are any blocking concerns.

2020-12-14 05:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +    authCache = cacheService.getCache(CACHE_ID_AUTH, 1000, 90, TimeUnit.MINUTES);
hmmm, not sure that addresses my concern. It seems we're holding onto an expired token for an additional 30mins. Surely sending an expired token would force the refresh anyway from the Bb side. :thinking:

2020-12-14 05:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +    authCache = cacheService.getCache(CACHE_ID_AUTH, 1000, 90, TimeUnit.MINUTES);
Ah hold on, I now see you've address that. :+1:

2020-12-14 05:55 UTC, edalex-ian approved these changes
Thanks @cbeach47 for making some of the improvements especially with your time constraints. I reckon what you have is GTG. :+1:

2020-12-14 17:58 UTC, merged