Bugfix/search portlet do not support new search UI
openequella/openEQUELLA pull request #2614
Opened 2020-12-17 04:28 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Currently, when a search is triggered from quick search in Selection Session, the endpoint is not `selectoradd/searching.do`. This will result in showing the regular page in Selection Session. So we need to change the endpoint.

Also, in order to pass the search query to new search UI, we need to 
1. enable the feature of `converting query strings to search options` in Selection Session;
2. append the query to the URL.

When I was testing,  I noticed that `converting query strings to search options` is not quite compatible with `back to search page`. The issue is if back to a search URL which has query strings, the search option stored in browser history is ignored. 

So overall, this PR fixes above issue and make quick search work fine with new search UI.

Here is a [video](https://streamable.com/dq5ut2) for all changes.

2020-12-17 23:02 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsconfig.json
> +    "lib": ["es2020", "dom", "dom.iterable"],
Without this library, TS complains that the function `keys()` does not exist in `URLSearchParams`.

2020-12-17 23:02 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  Array as RuntypeArray,
As I need to use the standard Array, I need to rename this Runtype Array.

2020-12-17 23:16 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +    .location.state as SearchPageHistoryState;
do we know the state will be this shape for certain?
Would a runtype make sense here?

2020-12-18 00:17 UTC, edalex-ian requested changes
Looks good @PenghaiZhang , need to tidy up some comments, but there's also a bit of undesirable result in building up the query params where we could have `&?q=blah` so I've a suggestion for that.

2020-12-18 00:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +      // If the search option already exists, don't do query string conversion.
```suggestion
      // If the search options are available from browser history, ignore those in the query string
```

2020-12-18 00:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +    // option is the default one.
We have a few comments like this scattered around the place, what's really missing though is the _why_. Could you please add that here.

2020-12-18 00:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/section/SearchQuerySection.java
> +    from.forwardToUrl(basicUrl + "&q=" + query);
As discussed, probably want to rework to this rough idea - maybe need try/catch too.

```suggestion
    URL basicUrl = new URL(info.getPublicBookmark().getHref());
    
    from.forwardToURL(
      basicUrl.toString()
      + (basicUrl.getQuery().isEmpty ? "?" : "&")
      + "q=" + query));
```

2020-12-18 00:23 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/section/SearchQuerySection.java
> +    from.forwardToUrl(basicUrl + "&q=" + query);
Oops.... URL.getQuery() returns `null` if there is no query, so that should be `basicUrl.getQuery() == null`.

2020-12-18 00:55 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +    .location.state as SearchPageHistoryState;
Thanks Christian! 

Like your idea ! I will raise an Github issue for this and do it in next release :smile:

2020-12-18 01:28 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +    }
with the return, else is not needed
```suggestion
      return;
    }
    history.replace({
      ...history.location,
      state: { searchPageOptions, filterExpansion },
    });
```

2020-12-18 02:11 UTC, ChristianMurphy approved these changes

2020-12-18 03:59 UTC, merged