Generate language string bundle by Typescript.
openequella/openEQUELLA pull request #2632
Opened 2020-12-23 05:33 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR uses Typescript to generate the language bundle which has the same data structure as the one generated by Purscript.   Some npm scripts have been updated accordingly. 

I have not removed `GenLangStrings.purs` yet in this PR, but I can do this when all the changes are reviewed and approved.

2020-12-23 17:48 UTC, ChristianMurphy approved these changes
LGTM, thanks @PenghaiZhang!

2021-01-03 22:50 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/package.json
> +    "bundle:languagestring": "cross-env-shell tsc --types \"node\" --outDir target/language_bundle tsrc/util/BuildLanguageBundle.ts",
I image we would have another for `bundle:uploadlist`.

Also Line 24, 27 and 28 will be removed once rewriting `uploadlist` is completed.

2021-01-03 23:17 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/util/BuildLanguageBundle.ts
> +    languageBundle.push(...generateLanguageBundle(key, languageStrings[key]));
I have tried to use `flatMap` instead of `push`, but there was an error complaining `flatMap` does not exist on type `[key]: value...`. 
I tried to add es2019 or es2019.array in `tsconfig - lib` but that did not help.

2021-01-04 03:53 UTC, edalex-ian requested changes
Thanks for this @PenghaiZhang .

One thing, this script is a build tool (well, kind of - it's a bit tightly coupled to the code, but hey), not part of the core source, and so really I think it should be somewhere like `js/build-tools` - not mixed in with the core source. Sure tree shaking should shake it out, but let's not even have to worry about that.

And also my reply comment about how I think this file should look with the different build tasks.

2021-01-04 03:53 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/util/BuildLanguageBundle.ts
> +  } else {
Should this perhaps be an `else if (typeof value === "object)` and then an `else` catch all would throw an error as someone has messed up the languagestrings?

2021-01-04 03:53 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/package.json
> +    "bundle:languagestring": "cross-env-shell tsc --types \"node\" --outDir target/language_bundle tsrc/util/BuildLanguageBundle.ts",
> I image we would have another for `bundle:uploadlist`.

For that, I don't believe we'll need anything. It should just end up as a component which is part of the existing source tree.

2021-01-04 03:53 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/package.json
> -    "bundleps:langbundle": "cross-env-shell \"purs bundle \"${npm_package_config_psglob}\" -m Tools.GenLangStrings --main Tools.GenLangStrings -o target/genlang.js\"",
Hmmm, I think we can improve on this tangle of tasks. Currently with your changes it looks like this:

```json
"build": "npm-run-all build:*",
"build:bundles": "run-s bundle && cross-env-shell parcel build --public-url=. --out-dir=${npm_package_config_dist} ${npm_package_config_parcelEntryFiles}",
"build:langbundle": "cross-env-shell parcel build target/language_bundle/BuildLanguageBundle.js --no-minify --no-source-maps --target node --out-dir=target/tools && cross-env-shell \"node target/tools/BuildLanguageBundle.js > ${npm_package_config_buildlang}/jsbundle.json\"",
"compileps": "pulp build",
"bundle": "npm-run-all bundle:* && run-s bundleps",
"bundle:languagestring": "cross-env-shell tsc --types \"node\" --outDir target/language_bundle tsrc/util/BuildLanguageBundle.ts",
"bundleps": "npm-run-all compileps && npm-run-all --parallel bundleps:*",
"bundleps:uploadlist": "cross-env-shell \"purs bundle \"${npm_package_config_psglob}\" -m Uploads.UploadList --main Uploads.UploadList -o target/uploadlist.js\"",
```

I'd suggest something along the lines of:

```json
"compile:ps": "pulp build",
"compile:langbundle-tool": "cross-env-shell tsc --types \"node\" --outDir target/language_bundle tsrc/util/BuildLanguageBundle.ts",
"build:langbundle-tool": "cross-env-shell parcel build target/language_bundle/BuildLanguageBundle.js --no-minify --no-source-maps --target node --out-dir=target/tools",
"build:langbundle": "cross-env-shell \"node target/tools/BuildLanguageBundle.js > ${npm_package_config_buildlang}/jsbundle.json\"",
"build:ps-uploadlist": "cross-env-shell \"purs bundle \"${npm_package_config_psglob}\" -m Uploads.UploadList --main Uploads.UploadList -o target/uploadlist.js\"",
"build:bundle": "cross-env-shell parcel build --public-url=. --out-dir=${npm_package_config_dist} ${npm_package_config_parcelEntryFiles}",
"build": "npm-run-all compile:* build:*"
```

There may be issues in the above as I've just hacked it out. But hopefully you can see what's happening there.

Also, if such a structure is arrived at, once the upload control is converted, you'd just remove `compile:ps` and `build:ps-uploadlist`.

Lastly, you'd want to consider putting the common path for the compiling/building/running of the language bundle tool into a config variable.

2021-01-04 06:58 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/package.json
> -    "bundleps:langbundle": "cross-env-shell \"purs bundle \"${npm_package_config_psglob}\" -m Tools.GenLangStrings --main Tools.GenLangStrings -o target/genlang.js\"",
Coming along nicely dude! :+1:

Looks like you just need some config vars for `target/language_bundle` and `target/tools`.

2021-01-05 02:13 UTC, edalex-ian approved these changes
Good stuff @PenghaiZhang , a definite improvement in many ways. :+1:

2021-01-05 05:48 UTC, merged