[WIP] [Discussion] test: drop enzyme
openequella/openEQUELLA pull request #2673
Opened 2021-01-15 01:25 UTC by ChristianMurphy

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

One possible approach to address https://github.com/openequella/openEQUELLA/pull/2460#issuecomment-716192531 is to remove enzyme from the project, instead leveraging testing library react, which does support react 17.

Opening an initial, work in progress, partly broken draft as a starting point and a concrete example of the possible approach.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2021-01-15 05:12 UTC, edalex-ian commented
This is definitely where we ultimately want to end up, so if you can pull it off that'd be great!! :+1: :bowing_man: 

I'll review a bit next week.

2021-01-20 04:20 UTC, edalex-ian reviewed
Looking relatively straight forward! Great stuff @ChristianMurphy :bow: 

A few bits of feedback and comments. :)

2021-01-20 04:20 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/components/MimeTypeFilterEditingDialog.test.tsx
> +      expect(saveButton).toHaveTextContent("OK");
Make sense to do at least one of:

1. push the query call out to a function such as `getSaveButton()`; or
2. Move the four lines into a simple function like `expectSaveButtonText(string: expectedValue)`

2021-01-20 04:20 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/components/SearchSettingFormControl.test.tsx
> +      fireEvent.change(textField, {});
Ummm, this whole test file is rather odd - not sure about the value of the test - feels almost like it's just testing if the MUI `TextField` `onChange` handler works. :thinking:  But if we ignore that, typically in react-testing-library land we aim to avoid direct event triggering and instead use user-event - indeed that's proven invaluable already a few times.

So here's I'd suggest using `userEvent.type` with some random text. :shrug:

2021-01-20 04:20 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +    // Needed to keep tests below happy
Mind you though, as per the comment... If there's no more Enzyme than can this `afterEach` be removed?

2021-01-20 04:20 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +    // Needed to keep tests below happy
As per above:

> Mind you though, as per the comment... If there's no more Enzyme than can this `afterEach` be removed?

2021-01-20 04:20 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/jest.setup.ts
> +import "@testing-library/jest-dom";
You sure you need to add this - we haven't previously needed it?

2021-01-20 04:20 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/MimeTypeFilterEditingDialog.tsx
> +          data-testid="MimeTypeFilterEditingDialog_save"
Ideally I'd like to avoid us using this and instead use `id`. As previous experience has shown me the greater value of using `id` when it comes to speed for Selenium tests and so I'd prefer to go with just one.

2021-01-20 04:20 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/setupEnzyme.js
> -enzyme.configure({ adapter: new Adapter() });
Could this file be removed?

2021-01-20 04:44 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/jest.setup.ts
> +import "@testing-library/jest-dom";
Previously testing library specific assertions like `expect().toHaveAttribute()` weren't used.
https://github.com/testing-library/jest-dom#table-of-contents

They aren't strictly needed, but they can be more concise and clearer

2021-01-20 04:48 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/MimeTypeFilterEditingDialog.tsx
> +          data-testid="MimeTypeFilterEditingDialog_save"
It looks like on the testing library side it could be overridden to use `id` https://testing-library.com/docs/queries/bytestid/#overriding-data-testid
I'm a bit cautious about (mis)using `id` semantics for tests, particularly because some components can appear more than once on the page, but that can be saved for a future discussion.

2021-01-20 06:18 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/jest.setup.ts
> +import "@testing-library/jest-dom";
We use some of them lots, especially `toBeInTheDocument` - see `SearchPage.test.tsx`. But we just did the import directly, e.g:

https://github.com/openequella/openEQUELLA/blob/develop/Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx#L19

Definitely a fan of them.

2021-01-20 06:21 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/settings/Search/searchfilter/MimeTypeFilterEditingDialog.tsx
> +          data-testid="MimeTypeFilterEditingDialog_save"
Yes indeed, need to be thoughtful of how you use them. The main way is to use them for an anchor point into the DOM, and then you can do you search from there. Reasonable performance still on Selenium, and code with RTL also straightforward. One example that comes to mind is for the testing of the various search page 'Refine Search' selectors: https://github.com/openequella/openEQUELLA/blob/develop/Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx#L228

2021-01-20 06:22 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/setupEnzyme.js
> -enzyme.configure({ adapter: new Adapter() });
Sorry, to clarify... Could this _file_ be removed?

2021-04-23 05:49 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/components/SearchSettingFormControl.test.tsx
> +      fireEvent.change(textField, {});
When `userEvent.type` is used, the handler `onChange` is called multiple times because each character triggers a call.

2021-04-23 05:57 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +    // Needed to keep tests below happy
I have removed this.

2021-04-23 05:57 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/setupEnzyme.js
> -enzyme.configure({ adapter: new Adapter() });
I have removed this file.

2021-04-23 06:00 UTC, PenghaiZhang commented
Hi @ChristianMurphy , I have checkout your branch and refactored some Jest tests. Now everything looks good on my local environment. So I pushed and hope we can get green builds.

2021-04-23 06:50 UTC, edalex-ian commented
Ooooh, this sounds exciting. Great work @PenghaiZhang :tada:

2021-04-23 14:23 UTC, ChristianMurphy commented
Thanks @PenghaiZhang!

2021-04-27 06:12 UTC, edalex-ian requested changes
Awesome! Almost on React 17!! :tada: 

Really appreciate your efforts @ChristianMurphy and @PenghaiZhang .

Just  couple of queries. But if you're able to knock these on the head @PenghaiZhang (or @ChristianMurphy ) maybe we can get this merged in tomorrow.

Notes (no action required here, but probably in later PRs):

- Curiously, down the bottom of `FacetedSearchSettingsPage.test.tsx` there is a describe block ("when remove a facet") which contains a whole lot of tests which should be in a TS test file for the `FacetedSearchSettingsModule`).
- I've ignored places where string literals are used rather than language strings for this review, as that's not what this was about. But it should be noted that there are some places to tidy in the future.

2021-04-27 06:12 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/mainui/ContentIndexSettings.test.tsx
> +  const contentIndexSettings =
```suggestion
  const contentIndexSettingsStrings =
```

Could be useful to make it clearer what this is. (Plus I note some cases below that look almost like it's shadowing this.)

2021-04-27 06:12 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/mainui/ContentIndexSettings.test.tsx
> +  it("Should fetch the search settings", () => {
See we've lost a describe block here for context, how about:

```suggestion
  it("Should fetch the search settings on page load", () => {
```

2021-04-27 06:12 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/mainui/FacetedSearchSettingsPage.test.tsx
> +// import MessageDialog from "../../../tsrc/components/MessageDialog";
Should be deleted if not used.

2021-04-27 06:12 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/mainui/FacetedSearchSettingsPage.test.tsx
> +// import {getMuiButtonByText} from "../MuiQueries";
Should be deleted if not used.

2021-04-27 06:12 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/mainui/FacetedSearchSettingsPage.test.tsx
> +      getAllClassifications().filter((c) => queryByText(c, facetName) !== null),
To stay within the idiom, may want to consider:

```suggestion
      getAllClassifications()
      A.filter((c) => queryByText(c, facetName) !== null),
```

2021-04-27 06:12 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/mainui/FacetedSearchSettingsPage.test.tsx
> +      )
Could this be:

```suggestion
      O.getOrElse(
        () => {
          throw new Error(`Failed to find classification ${facetName}`);
        }
      )
```

2021-04-27 06:12 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/mainui/FacetedSearchSettingsPage.test.tsx
> +      languageStrings.settings.searching.facetedsearchsetting.edit
Might want to drop `languageStrings.settings.searching.facetedsearchsetting` into a `facetedSearchSettingStrings`.

2021-04-27 06:12 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/jest.setup.ts
> +import "@testing-library/jest-dom";
Looks like we still need to do something here. So elsewhere when we use these we simply do an:

```typescript
import "@testing-library/jest-dom/extend-expect";
```

So I'd say this import should perhaps be for `@testing-library/jest-dom/extend-expect`. However, I'd also suggest that perhaps seeing this Jest setup also runs tests for non-TSX files do we want to pollute the matchers all the time?

2021-04-28 00:04 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/mainui/ContentIndexSettings.test.tsx
> +  it("Should fetch the search settings", () => {
Good idea!!

2021-04-28 00:05 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/mainui/FacetedSearchSettingsPage.test.tsx
> +// import MessageDialog from "../../../tsrc/components/MessageDialog";
Sorry I forgot to delete.

2021-04-28 04:06 UTC, edalex-ian approved these changes
Thanks heaps for kicking this off @ChristianMurphy and thanks @PenghaiZhang for finalising. Let's merge this in! :+1: :tada:

2021-04-28 04:08 UTC, merged