Move the Axios usage for 'heartbeat' to REST module.
openequella/openEQUELLA pull request #2706
Opened 2021-01-28 05:34 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Refactor the Axios usage in 'util/heartbeat.ts' to REST Module.

2021-01-28 14:40 UTC, ChristianMurphy approved these changes

2021-01-28 14:40 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/Heartbeat.ts
> +        throw new Error(
Since this appears to be a form of type check would it make sense to throw a `TypeError`?
```suggestion
        throw new TypeError(
```

2021-01-28 14:40 UTC, ChristianMurphy commented on oeq-ts-rest-api/src/Heartbeat.ts
> +    is<string>(data)
Above it appears that is should specifically be the literal `"OK"`, does `typescript-is` support checking literal types? Would it make sense to check if the value is `"OK"` at this level?

2021-01-28 23:11 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/Heartbeat.ts
> +        throw new Error(
Hmmmm, this is not so much validating the type, it's more so validating a business layer response. Ideally it could probably return something like `OK` when all in order, or `UNAVAILABLE` if server is undergoing some kind of maintenance mode etc.

But what is also interesting is that currently the server (if it responds at all) will only ever respond with `OK` - so we could even choose to skip this for now.

2021-01-28 23:17 UTC, edalex-ian commented on oeq-ts-rest-api/src/Heartbeat.ts
> +    is<string>(data)
It would be a good idea to check it is the correct acceptable literals. Considering there is currently only the one (`OK`) we could probably skip `typescript-is` on this one (and just do a string comparison). However, nice to have the consistency if it works.

2021-01-28 23:22 UTC, edalex-ian requested changes
Looks good @PenghaiZhang , but if you could just make a coupla tweaks that'd be handy:

* Use arrow function syntax;
* Don't worry about checking for `OK` in the module layer; and
* In the REST module validate the allowed string literal.

(That may also mean tweaking the test - as it won't need to validate `OK` is returned, just that no exception is thrown.)

2021-01-28 23:22 UTC, edalex-ian commented on oeq-ts-rest-api/test/Heartbeat.test.ts
> +afterAll(() => OEQ.Auth.logout(TC.API_PATH, true));
It's actually an unsecured endpoint, so can probably remove these.

2021-01-28 23:22 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/Heartbeat.ts
> +export function checkHeartbeat() {
For consistency of new stuff:

```suggestion
export const checkHeartbeat = (): void => {
```

2021-02-01 00:46 UTC, PenghaiZhang commented on oeq-ts-rest-api/src/Heartbeat.ts
> +    is<string>(data)
I believe we can do `is<"OK">`

2021-02-01 02:21 UTC, edalex-ian approved these changes
GTG! :+1:

2021-02-01 02:29 UTC, ChristianMurphy approved these changes

2021-02-01 03:57 UTC, merged