Feature/add and remove favourite
openequella/openEQUELLA pull request #2753
Opened 2021-02-19 04:48 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR includes: 
1. New REST endpoints to support adding/removing a favourite Item.
2. Improvements of Legacy code to better support the new endpoints.
3. Adding a flag in `search2` response to indicate whether an item is already added to favourite.
4. Adding new types and functions In REST module to communicate with the new endpoints.
5. Functional tests and Jest tests for above changes. 

![image](https://user-images.githubusercontent.com/47203811/108458527-f25ae180-72c8-11eb-9870-f4681b03b8ee.png)
![image](https://user-images.githubusercontent.com/47203811/108458558-043c8480-72c9-11eb-97fc-ce1d37f5486a.png)

2021-02-19 14:48 UTC, ChristianMurphy commented on oeq-ts-rest-api/src/AxiosInstance.ts
> +  queryParams?: Parameters<typeof stringify>[0] // eslint-disable-line @typescript-eslint/ban-types
does eslint give specific on what is being flagged.
it generally looks like it should be valid with the default settings https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md#default-options

2021-02-19 14:48 UTC, ChristianMurphy commented on oeq-ts-rest-api/src/AxiosInstance.ts
> +    .then((response: AxiosResponse<R>) => response.data)
```suggestion
    .then(({ data }: AxiosResponse<R>) => data)
```

2021-02-21 22:41 UTC, PenghaiZhang commented on oeq-ts-rest-api/src/AxiosInstance.ts
> +  queryParams?: Parameters<typeof stringify>[0] // eslint-disable-line @typescript-eslint/ban-types
I saw this rule is also disabled in function `GET` so I just copied it to here...
But now I have removed this comment and I don't see new warnings.

2021-02-22 04:42 UTC, edalex-ian requested changes
Thanks @PenghaiZhang , looking mostly there but just a few implementation tweaks and a few design queries. BTY.

2021-02-22 04:42 UTC, edalex-ian commented on Platform/Plugins/com.tle.web.sections/src/com/tle/web/sections/render/TextUtils.java
> +   */
Missing `@return`

2021-02-22 04:42 UTC, edalex-ian commented on Platform/Plugins/com.tle.web.sections/src/com/tle/web/sections/render/TextUtils.java
> +          collection.add(s.toLowerCase());
This function shouldn't really be mutating an input. It should simply build one up and return it.

2021-02-22 04:42 UTC, edalex-ian commented on Platform/Plugins/com.tle.web.sections/src/com/tle/web/sections/render/TextUtils.java
> +      for (String s : text.split("\\s|,|;")) {
It'd be preferable to use a more declarative style.

```java
Arrays.asList(text.split(...))
  .filter(s -> !Check.isEmpty(s))
  .map(s -> s.toLowerCase())
  .collect(Collectors::toList);
```

You could even do that initial input check by changing that first line to use a ternary where you pass in an empty collection.

(Also, I note where you use this you're more interested in having a Set, so perhaps you want to use `Collectors::toSet` and maybe also reflect that in the function name.)

2021-02-22 04:42 UTC, edalex-ian commented on Platform/Plugins/com.tle.web.sections/src/com/tle/web/sections/render/TextUtils.java
> +   * a provided collection.
It also changes it to lower case - you should mention that. Although, it also raises the question if that's appropriate for a function that has nice generic name of `convertStringToCollection`.

2021-02-22 04:42 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/favourite/FavouriteResource.scala
> +    Option(bookmarkService.getByItem(new ItemId(s"${uuid}/${version}"))) match {
Why don't we just have callers to the API send the UUID for the bookmark rather than doing a look-up on a synthetic key?

2021-02-22 04:42 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
> +      isAddedToFavourite = isAddedToFavourite(key)
Does it matter that this is not checking a specific version - even though favourites can be at a version level?

2021-02-22 04:42 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResultItem.scala
> +    isAddedToFavourite: Boolean
Should this perhaps be `Option[String]` where the string would be the favourite UUID?

2021-02-22 04:42 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/FavouriteApiTest.java
> +    assertEquals(HttpStatus.SC_NO_CONTENT, statusCode);
Could be good to make a subsequent call to ensure you can't get the item. :thinking:

2021-02-22 04:42 UTC, edalex-ian commented on oeq-ts-rest-api/src/Favourite.ts
> +export interface FavouriteItem {
Missing JSDoc for all this.

2021-02-22 04:42 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/FavouriteApiTest.java
> +    body.put("isAlwaysLatest", "true");
Hmmm, you appear to be lacking test coverage for adding a specific version.

2021-02-22 23:31 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/favourite/FavouriteResource.scala
> +    Option(bookmarkService.getByItem(new ItemId(s"${uuid}/${version}"))) match {
I have added a method named `getById` to `BookmarkService` so we no longer need this synthetic key. However, there is no UUID for Bookmark at the moment. The ID we can use is the unique numeric ID.

2021-02-22 23:48 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResultItem.scala
> +    isAddedToFavourite: Boolean
Yes, as the DELETE endpoint takes a Bookmark ID now, this field should be a Bookmark ID. So I rename this field to `bookmarkId`.

2021-02-23 03:08 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/favourite/FavouriteResource.scala
> +    Option(bookmarkService.getByItem(new ItemId(s"${uuid}/${version}"))) match {
That sounds good. Numeric ID is fine - just thought I saw UUID somewhere, so ignore that. :wink:

2021-02-23 04:08 UTC, PenghaiZhang commented on autotest/OldTests/src/test/java/io/github/openequella/rest/FavouriteApiTest.java
> +    body.put("isAlwaysLatest", "true");
As discussed, this will require using REST endpoints to add a new version of an Item. So no implementation is needed for now due to the complexity.

2021-02-23 04:18 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
> +      isAddedToFavourite = isAddedToFavourite(key)
As discussed, `key` consists of UUID and version.

2021-02-23 23:32 UTC, edalex-ian reviewed
I think it's almost there @PenghaiZhang , just need to further tweak the tag tokenizing.

2021-02-23 23:32 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/favourites/actions/AddToFavouritesSection.java
> +            .collect(Collectors.toSet());
Seeing this is duplicated below, it seems it should be placed in a shared utility static method somewhere - perhaps `Optional<String[]> tagsFromString(String tagString)`.

Whether that function should also go in `TextUtils` I'm unsure. Maybe tags from strings is only used in the Favourites Sections and should stay there. I'll leave that up to you.

2021-02-23 23:32 UTC, edalex-ian commented on Platform/Plugins/com.tle.web.sections/src/com/tle/web/sections/render/TextUtils.java
> +  public static Stream<String> convertStringToStream(String text) {
Hmmm, I fear this name is far too generic and doesn't really capture what's happening here. Seems like it should perhaps change slightly further and be:

```java
public static Stream<String> tokenizeString(String regex, String input)
```

Also, the JavaDoc for this method needs to be reworked - especially with the above change, but also as it still mentions the 'provided collection'.

2021-02-23 23:42 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/favourites/actions/AddToFavouritesSection.java
> +            .collect(Collectors.toSet());
I think the best place is `SectionUtils`

2021-02-24 00:24 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/favourites/actions/AddToFavouritesSection.java
> +            .collect(Collectors.toSet());
`RootFavouritesSection` is the best place for sure!

2021-02-24 02:47 UTC, edalex-ian approved these changes

2021-02-24 03:45 UTC, ChristianMurphy approved these changes

2021-02-24 04:07 UTC, merged