Fix another two File Uploader issues
openequella/openEQUELLA pull request #2754
Opened 2021-02-22 05:56 UTC by PenghaiZhang

#2559 

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR has two fixes:
1. Making sure deleting an uploaded file also deletes the file's child files.
2. Making sure the Attachment number restriction counts for unzipped files.

https://user-images.githubusercontent.com/47203811/108668166-c80a5d80-752e-11eb-9e87-7b7853af3876.mp4

2021-02-22 15:45 UTC, ChristianMurphy approved these changes

2021-02-22 22:54 UTC, edalex-ian requested changes
As discussed, I think for readability sake we need to rework/replace the `reduce` block.

BTY.

2021-02-22 22:54 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/fileuploader/InlineFileUploader.tsx
> +      const remainingFiles = [id, ...children.map((child) => child.id)].reduce(
I sat here looking at this `reduce` for awhile, and it feels like an anti-pattern. What you're really doing here is filtering, and as a result should really be just a `filter`. Roughed out like:

```typescript
const toRemove = [id, ...children.map((child) => child.id)];
const remainingFiles = uploadedFiles.filter( f => !(f.id in toRemove));
```

You get the idea - I've not checked any types etc here, but hey.

2021-02-24 02:49 UTC, edalex-ian approved these changes

2021-02-24 03:05 UTC, merged