Add Items to user's favourites
openequella/openEQUELLA pull request #2765
Opened 2021-02-27 05:33 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR is to support the feature of adding an Item to favourites from Search page.

What's  included:
1. A new component named `FavouriteItemDialog`.
2. A new module named `FavouriteModule` which interacts with REST Module. 
3. Changes made in `SearchPage`, `SearchResult` and `SearchResultList` to interact with the dialog.
4. Search page responsiveness improvements - hiding the Star icons and Item comment count in small screens.
5. Storybooks and Jest tests for all of above changes.

2021-02-28 22:54 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/ConfirmDialog.tsx
> +        <DialogContentText component="div" id="alert-dialog-description">
does the default `p` need to be changed to a `div`?
https://github.com/mui-org/material-ui/blob/4d50a9ed6a7c2007b9e5061d0842f38df191cfb2/packages/material-ui/src/DialogContentText/DialogContentText.js#L13-L15

2021-02-28 22:54 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/FavouriteModule.ts
> +  }).then((newFavouriteItem: OEQ.Favourite.FavouriteItem) => newFavouriteItem);
I may be missing something here.
It looks like the function `then`s `newFavouriteItem` unchanged? Is the `then` needed?

2021-03-01 00:01 UTC, edalex-ian requested changes
Good stuff @PenghaiZhang , I like the look of it. :+1: 

Just a few suggestions though, and also some queries. BTY.

2021-03-01 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +  it.each([
```suggestion

  it.each([
```

2021-03-01 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FavouriteItemDialog.test.tsx
> +  it("shows a RadiaGroup of two options for adding an Item that's on the latest version", () => {
```suggestion
  it("shows a RadioGroup of two options for adding an Item that's on the latest version", () => {
```

2021-03-01 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +      expect(iconButton).toBeInTheDocument();
Would it be better to just:

```suggestion
      const iconButton = getByLabelText(iconLabel);
```

2021-03-01 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/FavouriteModule.ts
> + */
Optional, but could be nice to say that this returns the details of the newly created favourite from the server.

2021-03-01 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +  const favouriteDialogHelper = (itemInfo: FavouriteItemInfo) => {
Is it really a "helper" so much as it's the onConfirm 'handler'?

If so, should it be called something more like `favouriteDialogOnConfirm`?

2021-03-01 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FavouriteItemDialog.tsx
> +  setVersionOption: (version: FavouriteItemVersionOption) => void;
Do you perhaps what to change the naming of these to make them more idiomatic handler functions? e.g. `onChangeTags` and `onChangeVersionOption`.

2021-03-01 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FavouriteItemDialog.tsx
> +    if (onConfirmProps) {
Why is `onConfirmProps` optional?

As it then makes for some weird reading of code here where you could end up with a confirm handler which does nothing. :confused:

2021-03-01 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FavouriteItemDialog.tsx
> +        setVersionOption("latest");
Wont this result in a visual oddity where you click confirm, and suddenly you see the option switch values before then closing? (We've had this kind of thing before.)

2021-03-01 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +  favouriteDialogHelper: (itemInfo: FavouriteItemInfo) => void;
Maybe rename as per comment elsewhere. Here it seems like this should be called `onFavouriteItem`.

2021-03-01 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResult.tsx
> +        )}
This should really be pushed into it's own component or function - makes this return block a bit unwieldy (poor readability). It'd also then appear you really don't need that map either - just a ternary to build up the args (or props) to pass to a function (or component).

2021-03-01 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
> +        description: "Provide tags to help when searching (optional).",
'Provide' might be overly verbose, perhaps:

```suggestion
        description: "Tags to help when searching (optional).",
```

2021-03-01 00:01 UTC, edalex-ian commented on oeq-ts-rest-api/src/index.ts
> +export * as Favourite from './Favourite';
Please keep sorted.

2021-03-01 00:44 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/ConfirmDialog.tsx
> +        <DialogContentText component="div" id="alert-dialog-description">
Because the type of `children` is ReactNode, it can be another JSX element. So it causes warnings: `validateDOMnesting(...): <div> cannot appear as a descendant of <p>.`

2021-03-01 00:47 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/FavouriteModule.ts
> +  }).then((newFavouriteItem: OEQ.Favourite.FavouriteItem) => newFavouriteItem);
The only difference is `newFavouriteItem` has a numeric bookmarkID which is generated on server.

2021-03-01 00:52 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/SearchResult.test.tsx
> +      expect(iconButton).toBeInTheDocument();
Yeah! And I can remove the `!` in next line.

2021-03-01 00:54 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FavouriteItemDialog.tsx
> +  setVersionOption: (version: FavouriteItemVersionOption) => void;
Yes good idea!

2021-03-01 01:19 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FavouriteItemDialog.tsx
> +    if (onConfirmProps) {
I must be wrong. I thought when the dialog is firstly rendered, it does not need to know what is the confirm handler. 
I will make it not optional.

2021-03-01 01:25 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +  const favouriteDialogHelper = (itemInfo: FavouriteItemInfo) => {
I have renamed this function :smile:

2021-03-01 02:12 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FavouriteItemDialog.tsx
> +        setVersionOption("latest");
Actually, it won't because `versionOption` is even not passed to RadioGroup. I only set the RadioGroup's  default value to ensure when the dialog is open the first option get selected.

2021-03-01 05:22 UTC, edalex-ian approved these changes
LGTM @PenghaiZhang !

There would be value (and be pretty easy) in changing `buildHeartIcon()` to a component - as then you see it in the React tools when debugging. But, up to you.

Merge when ready.

2021-03-01 10:29 UTC, merged