Search page MIME type filter
openequella/openEQUELLA pull request #2781
Opened 2021-03-02 09:31 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Open a draft PR to see if any test fails.

2021-03-03 00:05 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +  it("should be hidden if there are no configured filters", async () => {
Perhaps this test case should be moved to the describe for `<SearchPage />` ?

2021-03-03 00:05 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +      mimeTypes: filters.flatMap((f) => f.mimeTypes),
Please note that IDE is not happy with this `flatMap`. The error is : TS2339: Property 'flatMap' does not exist on type 'MimeTypeFilter[]'.

2021-03-03 04:07 UTC, edalex-ian requested changes
Looks good @PenghaiZhang , just two things:

1. It looks as though when sharing a search the MIME types - not the filter IDs - are being stored, but this'd cause issues then selecting the filters in the UI no?; and
2. I think we need to do something with the state for storing the MIME types from the server, and I'm leaning towards having one bit of state for Search Page Settings - as they all have the same lifecycle.

2021-03-03 04:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +        '{"rowsPerPage":10,"currentPage":0,"sortOrder":"NAME","query":"test machine","rawMode":true,"status":["LIVE","REVIEW"],"searchAttachments":true,"selectedCategories":[{"id":766943,"categories"
hmmm, rather than the MIME Types, shouldn't this be the filter ID?

2021-03-03 04:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +  .mockResolvedValue(getMimeTypeFilters);
For (maybe all) of the others, we only do the `mockResolvedValue` down near the test so that we maintain maximum visibility and control. Any reason specifically this one needs to be done up here?

2021-03-03 04:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +  it("should be hidden if there are no configured filters", async () => {
More so the describe block of `"Hide Refine Search controls"`. There should arguably be a similar one for Classifications.

2021-03-03 04:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +  const [mimeTypeFilters, setMimeTypeFilters] = useState<MimeTypeFilter[]>([]);
~Does this really need its own state? Can't it just be what's in `searchPageOptions`?~

Ahhh, I see, this is to hold the configured filters. Maybe we might need a more verbose name - `configuredMimeTypeFilters` or `availableMimeTypeFilters`. Or, do we need to broaden the current `searchSettings` such that it becomes:

```typescript
const [
  searchSettings,
  setSearchSettings,
] = useState<{
  core: OEQ.SearchSettings.Settings,
  mimeTypeFilters: MimeTypeFilter[]
}>();
```

2021-03-03 04:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/MimeTypeFilterSelector.tsx
> + * filter search results by Mime Types. It supports filtering options by typing keywords.
```suggestion
 * filter search results by MIME Types. It supports filtering options by typing keywords.
```

2021-03-03 04:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/SearchFilterResource.scala
> +    searchPrivProvider.checkAuthorised()
Oooh, nice pick-up. :+1:

2021-03-03 05:03 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +  .mockResolvedValue(getMimeTypeFilters);
What about moving it to the test case and then do `mockMimeTypeFilters.mockResolvedValueOnce(...);` there ?
`

2021-03-03 05:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +  .mockResolvedValue(getMimeTypeFilters);
Yup, that's exactly what I was talking about - as that's what we do with the others. And depends on the test as to whether you do a `Once` or not.

2021-03-03 06:08 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +  .mockResolvedValue(getMimeTypeFilters);
We need this to ensure `renderSearchPage` does not throw any error. Without this mock, we will set lots of `network error` as the test is calling the real implementation of `getMimeTypeFiltersFromServer`

2021-03-03 09:27 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +        '{"rowsPerPage":10,"currentPage":0,"sortOrder":"NAME","query":"test machine","rawMode":true,"status":["LIVE","REVIEW"],"searchAttachments":true,"selectedCategories":[{"id":766943,"categories"
I actually have another PR which has changes to support conversion between query string and search option. The key change is to convert to search page option.

2021-03-04 00:11 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +        '{"rowsPerPage":10,"currentPage":0,"sortOrder":"NAME","query":"test machine","rawMode":true,"status":["LIVE","REVIEW"],"searchAttachments":true,"selectedCategories":[{"id":766943,"categories"
According to the implementation of `generateQueryStringFromSearchOptions`, I can confirm that both `mimeTypes` and `mimeTypeFilters` are included in the query string. And then looking to `newSearchQueryToSearchOptions`, although we explicitly return a `SearchOptions`, `mimeTypeFilters` is also returned. As a result, `SearchPage` knows what filters to select.

2021-03-04 00:13 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +        '{"rowsPerPage":10,"currentPage":0,"sortOrder":"NAME","query":"test machine","rawMode":true,"status":["LIVE","REVIEW"],"searchAttachments":true,"selectedCategories":[{"id":766943,"categories"
Using the filter ID is also OK - this is how Old UI does.

2021-03-04 00:23 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +  const [mimeTypeFilters, setMimeTypeFilters] = useState<MimeTypeFilter[]>([]);
The code you suggested is more consistent with back-end -  SearchFilter is an inner class of SearchSetting. 

So I will go this way.

2021-03-04 01:42 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +      mimeTypes: filters.flatMap((f) => f.mimeTypes),
I can add a `ts-ignore` to get IDE happy...

2021-03-04 01:55 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> -  let page: RenderResult;
While moving the test for MIME type filter selector visibility into this describe, I found tests in this describe can be simplified a lot...so I have made changes for these tests.

2021-03-04 01:55 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +export const defaultSearchPageOptions: SearchPageOptions = {
This variable was originally defined inside `SearchPage`. The first change I did was moving it to outside `SearchPage` but still in that tsx file. Then when I ran tests, this variable caused some trouble as `defaultSearchOptions` became undefined. So I moved it to here and then all trouble was gone.

2021-03-04 01:55 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    //todo: Support converting legacy query string to SearchPageOptions. Once this done, change the return type of this functio
This will be done in my next PR .

2021-03-04 02:23 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  return mimeTypeFilters.filter((f) => f.id && filterIDs.includes(f.id));
```suggestion
  return mimeTypeFilters.filter(({ id }) => id && filterIDs.includes(id));
```

2021-03-04 04:00 UTC, edalex-ian reviewed
Good work on simplifying the hiding of selectors @PenghaiZhang :+1: 

All looks good, except for the change around `defaultSearchPageOptions`. I'm not sure I entirely follow the why or wherefore there - so I can't really suggest alternatives - but I am concerned with the coupling of the lower layers to the UI.

2021-03-04 04:00 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +  it("should be possible to disable MIME tyle filter selector", async () => {
I think the test here is more so:

```suggestion
  it("If not MIME type filters are available, the selector should be hidden", async () => {
```

2021-03-04 04:00 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +import { SearchPageOptions } from "../search/SearchPage";
This concerns me. We don't want the module layer coupled to the UI layer. With this import we suddenly have a two-way coupling (SearchPage -> SearchModule && SearchModule -> SearchPage). So, very high coupling.

2021-03-04 04:27 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +import { SearchPageOptions } from "../search/SearchPage";
> Good work on simplifying the hiding of selectors @PenghaiZhang 
> 
> All looks good, except for the change around `defaultSearchPageOptions`. I'm not sure I entirely follow the why or wherefore there - so I can't really suggest alternatives - but I am concerned with the coupling of the lower layers to the UI.

The implementation of defaultSearchPageOptions is 
```
{
  ...defaultSearchOptions,
  dateRangeQuickModeEnabled: true,
  mimeTypeFilters: [],
}
```

The problem is in the context of tests, `defaultSearchOptions` is undefined if we do  `import defaultSearchPageOptions from SearchPage`.

2021-03-04 05:57 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +import { SearchPageOptions } from "../search/SearchPage";
As discussed, let's move `mimeTypeFilters` to `SearchOptions`.

2021-03-04 05:59 UTC, PenghaiZhang commented
Since we have moved 'mimeTypeFilters' to 'SearchOptions', I found it much easier to support shared searches that have MIME types. So I also include the support of legacy shared searches in this PR.

2021-03-04 07:02 UTC, edalex-ian approved these changes
I think it's now good to go, but just two queries for your consideration.

2021-03-04 07:02 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +const findMIMETypeFiltersById = async (
I wonder if perhaps this function should be `memoized` to reduce the calls to `getMimeTypeFiltersFromServer()`. :thinking: We don't want to memoize `getMimeTypeFiltersFromServer` though as we need that for configuration on the settings page I think.

2021-03-04 07:02 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +    mimeTypeFilters: [],
Should this be specified here or as part of `defaultSearchOptions`?

2021-03-04 23:22 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +const findMIMETypeFiltersById = async (
As discussed, we don't need to memorize this function since it only gets called once when opening a new browser tab with shared search link.

2021-03-05 01:23 UTC, merged