Skinny selection session EBP and MIME Types support
openequella/openEQUELLA pull request #2797
Opened 2021-03-10 00:10 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR includes: 

1. Addressing a couple Skinny Selection Session UI issues through CSS changes. 
2. Fixing the Refine Search panel width issue by creating a new TSX component named `TootipChip` and using it in `CollectionSelector` and `MIMETypeFilterSelector`. 
3. Support for filtering search results by MIME types provided by LMS. This support requires both back-end and front-end changes. The approach is to add provided MIME types to URL as query strings (back-end) and then convert the query strings to `SearchOptions` (front-end).
4. Not showing the MIME Type Filter selector when MIME types are provided by LMS.
5. Some tweaks for JSDoc and tests.

2021-03-10 15:50 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/TooltipChip.tsx
> +  maxWidth?: number;
in what unit? px?

2021-03-10 23:06 UTC, SammyIsConfused approved these changes
Looks good Penghai!

2021-03-10 23:06 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +   * A list of MIME types provided by an Integration (e.g. with Moodle), which has high priority than `mimeTypes`.
```suggestion
   * A list of MIME types provided by an Integration (e.g. with Moodle), which has a higher priority than `mimeTypes`.
```

2021-03-10 23:06 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  // So the logic is using filters if any gets selected, or using MIME types already provided.
```suggestion
  // So the logic is, we use MIME type filters if any are selected, or specific filters already provided by the Image Gallery.
```
I think I understood this correctly?

2021-03-10 23:06 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    mimeTypes: externalMimeTypes ?? internalMimeTypes,
So in this file we use the identifiers `internalMimeTypes`, `integrationMIMETypes`, and a string  `_int.mimeTypes`. Since there are two different words that could be shortened to `int`, the phrase `_int.mimeTypes` is ambiguous and probably shouldn't be shortened that way. Possible renames could be `_integ.mimeTypes`, `_internal.mimeTypes`, `_intern.MimeTypes` (obviously depending on which way `_int.mimeTypes` is supposed to mean).

2021-03-10 23:06 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    mimeTypes: externalMimeTypes ?? internalMimeTypes,
Another alternative would be to set it to be a constant string. 
`const INTEGRATION_MIMETYPES = "_int.mimeTypes";`

2021-03-10 23:06 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +        !!searchPageOptions.externalMimeTypes,
Never seen this double !! symbol before (or if I have, I've forgotten about it.) what does it do?

2021-03-10 23:06 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/integration/IntegrationSection.java
> +    // 'AnnotationBookmarkListener' and 'InfoBookmark - getBookmarkParams'.
```suggestion
    // This field is primarily used to let the new Search UI filter search results by MIME types
    // provided by Integrations.
    // The approach is to add these MIME types to the URL as query strings and then convert
    // Legacy Search params to SearchOptions.
    // For example, a URL would be 'searching.do?_sl.stateId=1&_int.id_2&_int.mimeTypes=xxx'.
    // To achieve this, we must use annotation 'Bookmarked'. For details, please look
    // 'BookmarkEvent', 'AnnotatedBookmarkScanner',
    // 'AnnotationBookmarkListener' and 'InfoBookmark - getBookmarkParams'.
```

2021-03-10 23:43 UTC, edalex-ian requested changes
Looks pretty well there @PenghaiZhang . Just a few minor queries and request.

BTY.

2021-03-10 23:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__stories__/components/TooltipChip.stories.tsx
> +export const Standard: Story<TooltipChipProps> = (args) => (
As well as the 'Standard' story, could be worthwhile to add a story for a ReallyLongChip - seeing you specifically did work to support that visual oddity.

2021-03-10 23:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +    const refineSearchPanel = page.container.querySelector<HTMLDivElement>(
I wonder if this should reside as a function over in `SearchPageHelper.tsx` (which incidentally should only be `.ts` as it contains no JSX).

2021-03-10 23:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/TooltipChip.tsx
> +   * Props of the return type of AutocompleteGetTagProps, which is generated by MUI Autocomplete.
Could be useful to provide a [@see](https://tsdoc.org/pages/tags/see/) here to `@link` to information on how this is typically used. (Because 'Props of the return type' doesn't really mean much...)

2021-03-10 23:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    mimeTypes: externalMimeTypes ?? internalMimeTypes,
Personally I don't see any issue here, as it's highlighted that `_int.mimeTypes` is something passed as a param from legacy content - and so we kind of know that's outside of the control of New UI.

But that said, I personally would've gone with the old underscore prefix for something 'internal' to a function - .e.g `_mimeTypes` rather than `internalMimeTypes`.

2021-03-10 23:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +      isSelectionSessionOpen()
To keep the function call clear, and seeing you're already building up the assisting variable above, I'd suggest leaving this logic up in the initialisation of the variable.

As a curio, look how this would read with fp-ts `pipe`:

```typescript
pipe(
  {
    ...defaultSearchPageOptions,
    sortOrder: searchSettings.core?.defaultSearchSort,
    externalMimeTypes: isSelectionSessionOpen()
      ? searchPageOptions.externalMimeTypes
      : undefined
  },
  search);
```

Not saying you do have to do that (use `pipe`, but I do like the point-free style of it. (But please do at least rework to keep the function the variable initialisation in one place.)

2021-03-10 23:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CollectionSelector.tsx
> +            maxWidth={200}
Interesting that this has changed from 50% to 200 - is that likely to be an issue?

2021-03-10 23:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/TooltipChip.tsx
> +  maxWidth?: number;
Should it perhaps be `number | string` so as to support things like `"50%"`?

2021-03-10 23:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/MimeTypeFilterSelector.tsx
> +          maxWidth={150}
So for collections it was 200, why 150 here?

2021-03-10 23:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/RefineSearchPanel.tsx
> +    close: closePanelString,
Isn't there a 'common' string for this - not sure we need one specific for the refineSearchPanel.

2021-03-10 23:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/util/langstrings.ts
> +      close: "Close Refine Search Panel",
As mentioned above, it may be sufficient to just use the common close.

2021-03-11 02:10 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/TooltipChip.tsx
> +  maxWidth?: number;
Yes :smile:

2021-03-11 02:12 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +  // So the logic is using filters if any gets selected, or using MIME types already provided.
Yes, mostly. I think Image Gallery provides MIME types rather than filters

2021-03-11 02:15 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +    mimeTypes: externalMimeTypes ?? internalMimeTypes,
I will rename it to `_mimeTypes`.

2021-03-11 02:19 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +        !!searchPageOptions.externalMimeTypes,
Simply speaking, it converts an object or a primitive value to a boolean. The logic is `not(not(xx))`  which is equivalent to `yes`. For example, `!!1` = `true`,  `!!undefined` = `false`.

2021-03-11 02:33 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/TooltipChip.tsx
> +  maxWidth?: number;
Good idea.

2021-03-11 02:34 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/CollectionSelector.tsx
> +            maxWidth={200}
If the Chip width is 50%, when a collection name is quite long, the whole panel width gets expanded.
![image](https://user-images.githubusercontent.com/47203811/110727314-19c12080-826f-11eb-8011-d7113add4334.png)

2021-03-11 02:34 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/MimeTypeFilterSelector.tsx
> +          maxWidth={150}
I thought a Collection may have a longer name...

2021-03-11 02:53 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/MimeTypeFilterSelector.tsx
> +          maxWidth={150}
I have changed it to 200.

2021-03-11 03:10 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +    const refineSearchPanel = page.container.querySelector<HTMLDivElement>(
Do you want me to rename this file to `SearchPageHelper.ts`?

2021-03-11 03:15 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +      isSelectionSessionOpen()
I am quite happy to use `pipe`.

2021-03-11 06:59 UTC, edalex-ian approved these changes
Looks good @PenghaiZhang , other than where I mislead you with the `pipe`.

If you can tweak that, I reckon this is good to merge.

2021-03-11 06:59 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
>      );
I'm sorry @PenghaiZhang . But now that I see the change sitting there with out all the variable declarations from before, `pipe` is rather redundant and contrasts with all the other `search` calls in this file. This should just be:

```typescript
search({
  ...defaultSearchPageOptions,
  sortOrder: searchSettings.core?.defaultSearchSort,
  externalMimeTypes: isSelectionSessionOpen()
    ? searchPageOptions.externalMimeTypes
    : undefined,
});
```

2021-03-11 22:15 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
>      );
Ah yes! Cool I have removed it.

2021-03-12 00:07 UTC, merged