Suuport updating classification by mime types
openequella/openEQUELLA pull request #2798
Opened 2021-03-10 03:50 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

To support the feature of filtering facet search results by MIME types, this PR updates the facet search endpoint and REST module.

2021-03-10 03:56 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/api/search/EquellaSearchResource.java
> +      @ApiParam("A list of MIME types") @QueryParam("mimeTypes") List<String> mimeTypes);
I wonder if we still need to maintain this old search endpoint.

2021-03-10 04:09 UTC, PenghaiZhang commented
Front-end changes are quite simple so I wonder if we can include them in this PR. But I am also happy to open another PR.

2021-03-10 15:43 UTC, ChristianMurphy approved these changes
TypeScript changes LGTM

2021-03-11 00:01 UTC, edalex-ian requested changes
So there's no explicit change to the front-end, so how does this work? Is it because we were already simply passing the whole SearchOptions into the classifications search?

Other than that query, just a couple of things to address.

2021-03-11 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.base/src/com/tle/web/api/search/interfaces/SearchResource.java
> +      @ApiParam("A list of MIME types") @QueryParam("mimeTypes") List<String> mimeTypes);
```suggestion
      @ApiParam("A list of MIME types to filter items based on their attachments matching the specified types.") @QueryParam("mimeTypes") List<String> mimeTypes);
```

2021-03-11 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.base/src/com/tle/web/api/search/interfaces/SearchResource.java
> +  FacetSearchBean searchFacets(
You sure you want to remove `public` and make this package private?

2021-03-11 00:01 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/api/search/EquellaSearchResource.java
> +      @ApiParam("A list of MIME types") @QueryParam("mimeTypes") List<String> mimeTypes);
Technically, now that we have a V2 of the endpoint this one should not change - unless to fix bugs etc.

2021-03-11 00:01 UTC, edalex-ian commented on oeq-ts-rest-api/src/SearchFacets.ts
> +   * A list of MIME types.
Yeah, please rework as per further up.

2021-03-11 00:01 UTC, edalex-ian commented on oeq-ts-rest-api/test/SearchFacets.test.ts
> +  it('should be possible to limit to a MIME type', async () => {
Although kinda handy to have this here, this kind of test should really be on the server side - i.e. autotest. Here we're just testing to make sure we match the API interface, but on the server side we test the implementation.

2021-03-14 23:36 UTC, edalex-ian approved these changes
GTG! :+1:

2021-03-14 23:55 UTC, merged