Front-end support for adding favourite search from New Search UI
openequella/openEQUELLA pull request #2819
Opened 2021-03-17 01:11 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR is all about the UI of saving a search to user's favourites.

Firstly, a new dialog named `FavouriteSearchDialog` was created and integrated into `SearchPage` .

Secondly, a Heart Icon Button was added to `SearchResultList`. By clicking this button, the new dialog should appear.  

Thirdly, I changed how we control the snack bar so that once a search is successfully saved, the snack bar pops up.

Lastly, Jest tests and Storybooks were added.

https://user-images.githubusercontent.com/47203811/111399616-d0168100-8719-11eb-9962-d66d3f7a993e.mp4

2021-03-17 04:15 UTC, ChristianMurphy reviewed
General design question, could the positioning of the favorite over the results, rather than over the search filers cause confusion?
Could it be interpreted as saving the results as showing as a collection, rather than saving the filters the created the results?

2021-03-17 04:15 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/__stories__/search/FavouriteSearchDialog.stories.tsx
> +import { Meta, Story } from "@storybook/react";
```suggestion
import type { Meta, Story } from "@storybook/react";
```

2021-03-17 04:15 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/FavouriteModule.ts
> +  );
This `then` appears to be a no-operation return?
Would:

```suggestion
  });
```

work?

2021-03-17 04:15 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FavouriteSearchDialog.test.tsx
> +import { act } from "react-dom/test-utils";
it may make sense to import this from testing library react https://testing-library.com/docs/react-testing-library/api#act

2021-03-17 22:49 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/FavouriteModule.ts
> +  );
Yes! Thanks.

2021-03-17 22:51 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FavouriteSearchDialog.test.tsx
> +import { act } from "react-dom/test-utils";
Yes we should import this from `@testing-library/react` !

2021-03-18 02:05 UTC, PenghaiZhang commented
> General design question, could the positioning of the favorite over the results, rather than over the search filers cause confusion?
> Could it be interpreted as saving the results as showing as a collection, rather than saving the filters the created the results?

I am not quite sure. @edalex-ian @cathfitz  What do you think  ?

2021-03-18 05:56 UTC, edalex-ian commented
> > General design question, could the positioning of the favorite over the results, rather than over the search filers cause confusion?
> > Could it be interpreted as saving the results as showing as a collection, rather than saving the filters the created the results?
> 
> I am not quite sure. @edalex-ian @cathfitz What do you think ?

I think it's a developing area. We discussed this a little bit and the main thing is that the favouriting of a search is a similar action to the sharing of a search (the icon next to it). However soon we'll be adding another button which is to download the search results to a CSV file.

That may potentially further muddy the waters, but also end up with a significant number of buttons so at the point we may need to look at this closer and come up with an improved UI.

2021-03-18 06:29 UTC, edalex-ian requested changes
Looks good @PenghaiZhang , but I feel a few pieces of refactoring are called for - with moving some get queries into MuiQueries and better managing the proliferation of dialogs and their state on the SearchPage.

2021-03-18 06:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +    }
This is calling out that we need a `getMuiTextField`. I think this should be refactored over into the `MuiQueries`.

2021-03-18 06:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +    }
Should this really just be `expect(confirmButton).toBeInDocument()`?

2021-03-18 06:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/components/FavouriteSearchDialog.test.tsx
> +    }
As mentioned for the text field query, looks like this should be refactored over into `MuiQueries` as `getMuiButtonByText`.

2021-03-18 06:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +  }>(defaultMessageInfo);
I wonder if you need this much complexity. I wonder if all you need is the message itself.

Then as far as the open prop down in MessageInfo that could just be based on the presence of a message. And so onClose would simply clear the message back to `""` or `undefined`.

If that was done, this is then simple `snackBarMessage, setSnackBarMessage`.

What do you think?

2021-03-18 06:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +        <FavouriteSearchDialog {...favouriteSearchDialogProps} />
Now with two dialogs and two bits of state to manage them - and ideally they're mutually exclusive (we never really want more than one dialog displayed) - and the knowledge there'll be possibly more (say, download to CSV maybe). Should we push this into a SearchPageDialogs component and perhaps use a reducer in there?

2021-03-18 06:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FavouriteSearchDialog.tsx
> +  const confirmHandler = () => onConfirm(searchName).finally(closeDialog);
Should we have a `catch` here and handle any error? Arguably if there is an error, could be good to keep the dialog displayed so they can try again....

2021-03-19 05:28 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +    }
Yes, but I changed it to `expect(confirmButton).not.toBeNull();`

2021-03-19 05:37 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +  }>(defaultMessageInfo);
Yes this is definitely better. I have done this way for the Lightbox but forgot here..

2021-03-22 00:17 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +        <FavouriteSearchDialog {...favouriteSearchDialogProps} />
Good idea! I have created a new component `SearchPageDialog` which is the entry to other dialogs.

2021-03-22 00:22 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FavouriteSearchDialog.tsx
> +  const confirmHandler = () => onConfirm(searchName).finally(closeDialog);
When an error is triggered, previous search result gets cleared. Would it look a bit strange to keep the dialog ? 
![image](https://user-images.githubusercontent.com/47203811/111926429-eb5e0380-8b00-11eb-9061-c0a0bf08ee13.png)

2021-03-22 03:15 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/FavouriteSearchDialog.tsx
> +  const confirmHandler = () => onConfirm(searchName).finally(closeDialog);
The idea would be to keep the dialog up and have it report the error of the activity it just tried. (And possibly have the 'ok' button change to 'retry' or something...)

But as highlighted in the above screenshot, the error is being handled with the default `handleError` snackbar, AND all the other dialog in oEQ kind of work in the fashion of closing regardless. So... I'm happy to leave as is.

2021-03-22 03:34 UTC, edalex-ian reviewed
Nice work on the new component @PenghaiZhang . Just some queries and suggestions around it, then should be good to go. :+1:

2021-03-22 03:34 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPageDialog.tsx
> +export const SearchPageDialog = ({
Seeing this is not just for a single dialog, I think that needs to be highlighted. So its name could be along the lines of:

* `SearchPageDialogs` or
* `SearchPageDialogsSwitch` or
* `SearchPageDialogsController`

or something else along those lines. :thinking:

2021-03-22 03:34 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPageDialog.tsx
> +        type: "item";
Seeing there could be other non-favourite related dialogs, how about a bit of simple prefix namespacing for these discriminators, like:

* `fav-item`; and
* `fav-search`.

2021-03-22 03:34 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPageDialog.tsx
> + * Provide an entry to different Dialogs rendered in Search page.
```suggestion
 * Manage the various dialogs which can be displayed on the search page, including ensuring only one is displayed at a time.
```

2021-03-22 03:34 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPageDialog.tsx
> +      throw new Error("Unexpected Dialog type");
```suggestion
      throw new TypeError(`Unexpected Dialog type: [${additionalDialogProps?.type}]`);
```

2021-03-22 03:34 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPageDialog.tsx
> +  additionalDialogProps?:
If they're _required_ why are the optional?

2021-03-22 03:40 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPageDialog.tsx
> +export const SearchPageDialog = ({
I will go with `SearchPageDialogsSwitch`

2021-03-22 03:49 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPageDialog.tsx
> +  additionalDialogProps?:
Because when we are not going to show a dialog, we don't need this props. Or maybe another question: what would be the default value of this props which is used in the first rendering of search page?

2021-03-22 04:02 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPageDialog.tsx
> +      throw new Error("Unexpected Dialog type");
Actually, the type of `additionalDialogProps?.type` is `never` here because `type` must be either `fav-item` or `fav-search`. 

To make this working, I have added a third string literal `unknown`, which is also the default value as this props.

2021-03-22 04:03 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPageDialog.tsx
> +  additionalDialogProps?:
As mentioned above, since I use `unknown` as the default value, this property is not optional now.

2021-03-22 04:32 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPageDialog.tsx
> +      throw new Error("Unexpected Dialog type");
Aaaah! That's right, of course, this is just for the exhaustive check. Yeah, don't add the additional literal, just use TypeError and keep the string as was.

2021-03-22 04:34 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPageDialog.tsx
> +  additionalDialogProps?:
I wonder if rather than `unknown` you should simply go with `none`? Mind you, now that's just sounding like an optional working around `undefined`.

2021-03-22 14:40 UTC, ChristianMurphy approved these changes

2021-03-22 14:40 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPageDialogsSwitch.tsx
> +      };
does `unknown` mean it could have something, but we're not sure what it is?
Or does it mean there will not be additional props?

If the latter, would it make sense to rename it to `type: none`?

2021-03-23 01:34 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchPageDialogsSwitch.tsx
> +      };
I have removed this component.
Please have a look the new commits  :smile:  Thank you!!

2021-03-23 02:50 UTC, edalex-ian approved these changes
Nice refactor @PenghaiZhang . I think it's there, let's merge it. :+1:

2021-03-23 03:48 UTC, merged