View previous or next attachment in Lightbox
openequella/openEQUELLA pull request #2822
Opened 2021-03-19 05:12 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds the support of viewing previous or next attachment in the Lightbox.

The approach is to update the LightboxProps to take two more handlers which are fired when the two arrow icon buttons are clicked.

The two handlers are built in component 'ItemAttachmentLink` whose props is also updated to take a list of Lightbox viewable attachments.

I also updated the code of determining which viewer to be used for each attachment in `SearchResult`.

https://user-images.githubusercontent.com/47203811/111734235-d0f01400-88cd-11eb-8253-b866fdc29589.mp4

2021-03-22 04:26 UTC, edalex-ian reviewed
I'm not sure on this one @PenghaiZhang .

I like what you've done with the `Lightbox` component, however I'm not so sure the approach for `ItemAttachmentLink` and `SearchResult` is quite the way to go. With seeing what you need to hold onto, `ItemAttachmentLink` has gone from concerned with a single attachment to a multi-headed hydra.

It feels as though we need to split the attachment handling in general out of `SearchResult` and possibly introduce a `SearchResultAttachmentsList` component which could then handle all this kind of thing.

:thinking: 

Let's discuss further.

2021-03-22 04:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/Lightbox.tsx
> +  const LightBoxImage = () => (
I wonder if instead o needing this, you could simply get away with having the below `const content` in state, and then you have an handleOnNext and handleOnPrev which clears `content` before they call the `onNext` and `onPrev`. That way the functioning is explicit, and you wouldn't need the comment. :thinking:

2021-03-24 03:25 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/Lightbox.tsx
> +  const LightBoxImage = () => (
This is really a good idea! To do this, I need one more `useEffect` to update the content.

2021-03-25 00:39 UTC, edalex-ian requested changes
Great refactor @PenghaiZhang .

Almost halved SearchResult. Nice work. :+1: 

Few bits of feedback, but really just tidy up bits now.

Thanks!

2021-03-25 00:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/components/Lightbox.test.tsx
> +      expect(handler).toHaveBeenCalledTimes(1);
Could be good to also test that the display we updated to the new config provided by the handler. This might be easiest if you add a title into the config, and then simply check for that.

2021-03-25 00:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/ItemAttachmentLink.tsx
> +   * The attachment to be viewed in the LightBox.
This isn't specifically about the Lightbox, this is more so the details of the attachment to be linked to and how it should function/access/view the attachment.

2021-03-25 00:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/ItemAttachmentLink.tsx
> +  onNext?: () => LightboxConfig;
I'm wondering if the `onPrevious` and `onNext` should be part of the viewer definition found within `AttachmentAndViewer`. They seem at a bit of loose end sitting here.

Maybe if `viewer` is "lightbox" then it should include LightboxConfig. Maybe yet another string discriminated union like:

```typescript
type Viewer =
  | { viewer: "link"; url: string; }
  | { viewer: "lightbox"; config: LightboxConfig; };
```

Maybe falls into the building of the ViewerDefinition in ViewerModule. :thinking:

2021-03-25 00:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/Lightbox.tsx
> +  /** Configuration to help build Lightbox content. */
```suggestion
  /** Configuration specifying the Lightbox's content. */
```

2021-03-25 00:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/Lightbox.tsx
> +  const [lightBoxConfig, setLightBoxConfig] = useState<LightboxConfig>(config);
Just one thought (but no action required) is that these are closely related and would make a good candidate for a reducer. But seeing they're also simple, I can see the pros of leaving them just like this - and hope there is no increase in complexity.

2021-03-25 00:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +export const SearchResultAttachmentsList = ({
Please have a blank line around definitions of functions.

```suggestion

export const SearchResultAttachmentsList = ({
```

2021-03-25 00:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +  const buildLightboxNavigationHandler = (
Please have a blank line around definitions of functions.

```suggestion

  const buildLightboxNavigationHandler = (
```

2021-03-25 00:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +    (av) => av.viewer[0] === "lightbox"
Readability could improve with de-structuring.

2021-03-25 00:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +      const previousAttachment = lightboxAttachments[anotherAttachmentIndex];
De-structuring here with renaming and defaults will help below readability, and give you straight up variables named `src`, `title` and `mimeType`.

2021-03-25 00:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +    anotherAttachmentIndex: number
The naming of this variable is unclear. Please rename or add some TSDoc. :thinking:

2021-03-25 00:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +              lightboxAttachments.findIndex((v) => v.attachment.id === id) + 1
To keep it DRY, how about doing this just up above the return statement (line 234) and dropping it in a constant like `lightboxAttachmentIndex`?

2021-03-25 00:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +    ) {
This could be simplified with the help of `fp-ts` `Array` by something like:

    if(isSome(A.lookup(anotherAttachmentIndex, lightboxAttachments)))

or perhaps more readable with:

    if(pipe(lightboxAttachments, A.lookup(anotherAttachmentIndex), isSome))

2021-03-25 23:47 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +    ) {
With fp-ts I don't even need this if :smile:

2021-03-26 00:22 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/Lightbox.tsx
> +  const [lightBoxConfig, setLightBoxConfig] = useState<LightboxConfig>(config);
Yeah I image the reducer type would have 'init', 'onNext' and 'onPrevious' :thinking:

2021-03-26 00:38 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/components/Lightbox.test.tsx
> +      expect(handler).toHaveBeenCalledTimes(1);
Good idea!!!

2021-03-26 00:46 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/components/ItemAttachmentLink.tsx
> +   * The attachment to be viewed in the LightBox.
OK I will reword this.

2021-03-29 00:32 UTC, edalex-ian reviewed
Heya @PenghaiZhang 

I think you're there, and the layers are almost correct. But now with it all tidy with the abstractions etc it highlights there's probably one last step, and that looks like a whole bulk of interfaces and functions should now be moved over into ViewerModule and leave the components to just focus on the display.

2021-03-29 00:32 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +       * Build a function to handler navigation between Lightbox attachments.
```suggestion
       * Build a function to handle navigation between Lightbox attachments.
```

2021-03-29 00:32 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +              } = av;
How about just repacing `(av) => {` with the de-structure?

2021-03-29 00:32 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +              throw new TypeError("Unexpected viewer configuration");
```suggestion
              throw new TypeError(`Unexpected viewer configuration: ${viewer}`);
```

2021-03-29 00:32 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +      const buildLightboxNavigationHandler = (
Just like `transform()` it could be good to move this function outside of this self calling async function to try and keep the final logic succinct.

As it is, this whole effect is now around 150 lines long. You almost have to wonder if it'd be better to move this two functions (`transform` and `buildLightboxNavigationHandler`) out into the `ViewerModule` (may need a new name for `transform`) - perhaps there may be somewhere better.... Because as it stands, they're both stand-alone and not dependent on anything specific to this component, and then things may be more readable.

What do you think?

2021-03-29 00:32 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +export const isViewerLightConfig = (
```suggestion
export const isViewerLightboxConfig = (
```

2021-03-29 00:32 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +}
I can't help and wonder whether the above interfaces and functions belong here in this component, or more so generically over in the ViewerModule. I'm referring to:

* ViewerLinkConfig
* ViewerLightboxConfig
* ViewerConfig
* isViewerLightConfig
* AttachmentAndViewerDefinition
* AttachmentAndViewerConfig

As they're not part of the props for the component, and although they're building up those types possibly in the effect, is that kind of data processing etc more so what the Module layer should be looking after? Then we try and keep components simple and focused on display.

2021-03-29 02:24 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +      const buildLightboxNavigationHandler = (
I agree. But when I tried to move `transform` I found this function is slightly coupled to UI layer such as the usage of 'handleError'.  So I only moved part of it to ViewerModule.

2021-03-29 04:05 UTC, edalex-ian approved these changes
Thanks for your perseverance @PenghaiZhang . I reckon it's GTG! :+1:

2021-03-29 04:53 UTC, merged