Hide menu panel in selection sessions and items viewed from integration
openequella/openEQUELLA pull request #2842
Opened 2021-03-25 06:49 UTC by SammyIsConfused

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] videos are included showing significant UI changes

##### Description of change
We were defaulting to not full screen, which became a problem in selection sessions as it would take a short while to update based on width and height of the viewport. Now the default is false *unless* in a selection session or integration item view (integ/gen item link) where it is true. 

This involved adding to the renderData information passed from RenderNewTemplate a new variable viewedFromIntegration, which depends on a check as to whether the request is an /integ/gen item link. 
Before:
https://user-images.githubusercontent.com/24543345/112430075-c03e1300-8d91-11eb-979f-08c494bc6a8e.mp4

After:
https://user-images.githubusercontent.com/24543345/112429361-a6e89700-8d90-11eb-839f-def89e8e41ee.mp4

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2021-03-28 23:47 UTC, edalex-ian requested changes
Thanks @SammyIsConfused , just needs a comment and possibly a refinement of some code.

BTY

2021-03-28 23:47 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/AppConfig.ts
> +  viewedFromIntegration: boolean;
Please add TSDoc.

2021-03-28 23:47 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/LegacySelectionSessionModule.ts
> +  return typeof viewedFromIntegration == "boolean" && viewedFromIntegration;
I was going to comment on the type check needing triple eq, but then that made me wonder, why are you checking the type and not just doing a truthy check?

Maybe if it was just about wrangling around the possibly undef, then this function could just be:

```typescript
export const isItemViewedFromIntegration = (): boolean =>
  getRenderData()?.viewedFromIntegration ?? false;
```

Or if you want more concision:

```typescript
export const isItemViewedFromIntegration = (): boolean =>
  !!(getRenderData()?.viewedFromIntegration);
```

(Personally, I think I prefer the readability of the nullish coalescing.)

2021-03-29 02:53 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/LegacySelectionSessionModule.ts
> +  return typeof viewedFromIntegration == "boolean" && viewedFromIntegration;
The main reason I did it this way was for consistency with other functions in the same file - example, 
```
const isSelectionSessionInfo = (
  data: unknown
): data is { [K in keyof SelectionSessionInfo]: unknown } =>
  typeof data === "object" && data !== null && "stateId" in data;
```

I've simplified my function using nullish coalescing now.

2021-03-29 06:27 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/LegacySelectionSessionModule.ts
> +  return typeof viewedFromIntegration == "boolean" && viewedFromIntegration;
Yeah I was wondering if that was why - as I looked through the rest of the file. That example you provide is a little more special though.

That's for updating. :+1:

2021-03-29 06:28 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/AppConfig.ts
> +  viewedFromIntegration: boolean;
Wow, thanks for doing all the others while at it. :+1: :star:

2021-03-29 06:28 UTC, edalex-ian approved these changes
Thanks @SammyIsConfused - and thanks for the updates. :+1:

2021-03-29 22:35 UTC, merged