Back end support for downloading search results to CSV
openequella/openEQUELLA pull request #2851
Opened 2021-04-01 02:57 UTC by PenghaiZhang

#1971 

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds back-end supports for downloading search result to CSV, including: 

1. New REST endpoint in which  a search result is converted into a CSV format text and output in streaming.
2. New ACL to protect the endpoint.
3. Capturing the request in audit log.
4. Making sure only one Collection is allowed and all search results are exported.
5. Tests for the new endpoint.

The approach has three steps. 
1. Validating the request, which returns the Schema used in the Collection.
2. Building the CSV headers which contains a list of standard headers and Schema based headers. 
3. Building a row for each Item. To do this, the full XML of an Item is retrieved first, and then populate each cell based on headers. To get the full XML, I refactored `ItemXsltService.java ` so legacy stuff like `SectionInfo` is no longer needed in the new endpoint.

2021-04-07 03:26 UTC, edalex-ian requested changes
Cool, thanks @PenghaiZhang . Most of the comments relate to tidy up, however there is one big issue in here.

That is it would appear you're reading all items into memory from a single large search, then transforming all to XML before then streaming the results. This makes the streaming redundant - but we definitely want to stream properly.

Let me know if I've missed something, and we can discuss.

Cheers.

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +    val headers = ListBuffer[CSVHeader]()
Rather than this imperative approach, it'd be nice to see this more declarative with a reduce/fold and a pattern match. Further, you'd then be able to use an immutable collection approach rather than doing in place modification of the `ListBuffer`.

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +    buildHeadersForSchema(schema.getRootSchemaNode.getChildNodes, None) ++ STANDARD_HEADER_LIST
I'd expect the standard headers/values to be at the start. :thinking:

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +    * Build a text based on provided XML as a CSV cell content.
```suggestion
    * Build text based CSV content based on provided XML.
```

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +    * we have its name on the header, only use the value as content.
```suggestion
    * Iff a node is a root node and does not have any child nodes or attributes,
    * use only the value as CSV cell content (since we have the node name in the header).
```

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +    * For others, the content is a list of texts formatted as 'name:value' where 'name' may include parent node's name.
```suggestion
    * For others, the content is a list of strings formatted as `name:value` where `name` may include parent node's name.
```

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +      */
Not much value putting this scaladoc down here, as it won't really get extracted out. However, there is good value including this definition above following on from the function's Scaladoc ending at "Each text is separated by a delimiter."

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +    * @param xml The XML based on which a row is built
```suggestion
    * @param xml The XML from an Item for this row
```

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +    * Build one row for one Item XML
```suggestion
    * Builds a CSV row based on the XML for an Item.
```

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +            .mkString("|")
This is curious, should there be a 1:1 mapping for the headers. So should we really be accepting/supporting cases of multiples which result in a list? Or am I miss-reading something here?

Also, maybe you need to put this delimiter up in a constant - as this is the second place it's defined.

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +    val DOWNLOAD_ACL = "EXPORT_SEARCH_RESULT"
It's preferred if we declare this higher up as a constant and then reference the constant. This string literal is obviously now in two places.

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +      throw new BadRequestException("Only one Collection is allowed")
We really should be leaving these kind of exceptions further up. I know we do this all over the SearchHelper, but it would be good if these XyzHelper objects were not so tightly coupled to the UI context.

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
> +@Singleton
Why has this been added?

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
> +      convertSearchResultToXML(search(params, Option(-1)).getSearchResults.asScala.toList)
Hold on a sec... We can't just do an unpaged query and throw everything into memory, that's against the whole idea of streaming the response.

We basically want to chunk this via paging and streaming. So read a page in, convert and stream and then do the next page.

NOTE: You'll also then need to maintain a transaction through the paging.

2021-04-07 03:26 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
> +    }
This is a bit of an unexpected pattern, and makes the code below a bit unusual. I think it would be reworked such that:

1. There is no shared `csvContentContainer`
2. Use `scala.util.Using` to manage `bos`
3. And just have a single `writeRow` function

Roughly the code would look like:

```scala
import scala.util.Using

def writeRow(output: OutputStream, row: String): Unit = {
  output.write(s"${row}\n".getBytes())
  output.flush()
}

Using(new BufferedOutputStream(resp.getOutputStream)) { output ->
  val csvHeaders = buildCSVHeaders(schema)
  writeRow(output, csvHeaders.map(_.name).mkString(","))

  getXmlList.forEach(xml => writeRow(ouput, buildCSVRow(xml, csvHeaders)))
}
```

2021-04-07 03:26 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ExportTest.java
> +public class Search2ExportTest extends AbstractRestApiTest {
Could you please add a 'describe' attribute to each of the `@Test` annotations below - as some of the names are a bit misleading, but it's also the convention we have in the other tests now.

2021-04-07 05:42 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +    val headers = ListBuffer[CSVHeader]()
I initially used `map` and I found readability was bad so I changed to `foreach`. I will change to `foldLeft` .

2021-04-07 05:49 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +      throw new BadRequestException("Only one Collection is allowed")
Agreed! I have changed the return type to `Option[Schema]`.

2021-04-07 05:50 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
> +@Singleton
oops probably a left-over from some experimental code. Removed.

2021-04-07 05:52 UTC, PenghaiZhang commented on autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ExportTest.java
> +public class Search2ExportTest extends AbstractRestApiTest {
Yeah sorry about this. I forgot adding descriptions as it was a bit rush on last Thursday to open the PR.

2021-04-07 06:06 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +            .mkString("|")
One header can really have multiple mappings. 
For example,  in below screenshot, you can see multiple `<files>...</files>`. They all match to header `item/files` which is generated from Schema. Each value refers to an attachment UUID.

Also you can see there are multiple `<attachment type="xxx">` under `<attachments>` which just 1:1 matches to the stander header `Attachments`.

So I think we need to support multiple mapping here.

![image](https://user-images.githubusercontent.com/47203811/113817389-9507ea80-97b9-11eb-9139-3b59b9d3c3a4.png)

2021-04-07 06:16 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +    val DOWNLOAD_ACL = "EXPORT_SEARCH_RESULT"
I have moved the declaration to `SecurityConstants`

2021-04-07 06:18 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +    val DOWNLOAD_ACL = "EXPORT_SEARCH_RESULT"
Nice! That's the one that was scratching at the back of my head.

2021-04-08 06:29 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
> +    }
As discussed, as we are not using scala 2.13 we can't use `Using`.

2021-04-08 06:30 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
> +      convertSearchResultToXML(search(params, Option(-1)).getSearchResults.asScala.toList)
This has been addressed by creating a new `service`.

2021-04-09 06:03 UTC, edalex-ian requested changes
Looks like it's there @PenghaiZhang , just two main things:

1. Tidy up the generation of the start values for the chunking in export - and possibly remove the params for specifying start/length for the endpoint; and
2. Looks like we don't have a test that validates the actual output in any way. Be good if we at least validated that there is the correct number of rows and columns.

2021-04-09 06:03 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +    schemaNodes.asScala.foldLeft(List.empty[CSVHeader]) {
It occurred to me that perhaps this should actually be a for comprehension. But I'm not sure how to get syntax that's possibly as readable let alone code that is as efficient (with regards to excessive looping and data wrapping). For example, so far I'm at:

```scala
    val headers =
      for ((node, xpath) <- schemaNodes.asScala.map(node => (node, buildFullXpath(node.getName))))
        yield {
          if (node.hasChildren) buildHeadersForSchema(node.getChildNodes, Option(xpath))
          else List(CSVHeader(xpath, xpath))
        }
    headers.flatten.toList
```

But then if we stick with the `foldLeft` I'd revisit my suggestion of pattern matching to give something more like:

```scala
    schemaNodes.asScala.foldLeft(List.empty[CSVHeader])((list, node) => {
      val xpath = buildFullXpath(node.getName)
      node match {
        case n if n.hasChildren => list ++ buildHeadersForSchema(n.getChildNodes, Option(xpath))
        case _                  => list :+ CSVHeader(xpath, xpath)
      }
    })
```

I feel it provides for improved readability.

What do you think? Change, leave as is. I don't mind overly. :wink:

2021-04-09 06:03 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
> +    LegacyGuice.auditLogService.logGeneric("Download",
This seems slightly early for the auditing. Shouldn't it be only down once we start sending output - i.e. just before line 100.

If we want to generically capture the request coming in, we could just go with a logger.info - but probably not really required.

2021-04-09 06:03 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
> +                                     params.length,
Why do we accept a start and length? I though the point of the export was to export _all_ results for the search. :thinking:

2021-04-09 06:03 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/service/ExportService.scala
> +      .filter(start => start < count)
Could this be simplified with a for comprehension. For example, what if you had

```scala
def starts(max: Int, chunkSize: Int): Seq[Int] =
  for (i <- 0 until max / chunkSize + 1) yield i * chunkSize
```

The below you could have:

```scala
starts(count, 100).foreach(start => {
```

You may not need the function though - was more so to highlight the thinking here...

2021-04-09 06:03 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/legacy/LegacyGuice.java
> +  @Inject public static ExportService exportService;
Please maintain sort order is this massive list - you'll note all the above are (should be) sorted.

2021-04-09 06:03 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ExportTest.java
> +  @Test(description = "Export without ACL")
```suggestion
  @Test(description = "Export should fail when ACL is not granted")
```

2021-04-09 06:03 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ExportTest.java
> +  @Test(description = "Export with unsupported file formats")
```suggestion
  @Test(description = "Request to export in format other than CSV should fail")
```

2021-04-09 06:03 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ExportTest.java
> +  @Test(description = "Export with multiple Collections")
```suggestion
  @Test(description = "Attempts to export with multiple Collections should fail")
```

2021-04-09 06:03 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ExportTest.java
> +    assertEquals(statusCode, 200);
Umm, should this succeed? It doesn't actually seem to specify a collection, and based on that should fail. :thinking:

2021-04-09 06:15 UTC, PenghaiZhang commented on autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ExportTest.java
> +    assertEquals(statusCode, 200);
A collection is specified in method `buildExportRequest`

2021-04-09 06:45 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> +    schemaNodes.asScala.foldLeft(List.empty[CSVHeader]) {
As discussed, we can use `flatMap`.

2021-04-09 06:51 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
> +    LegacyGuice.auditLogService.logGeneric("Download",
I agree. I will move it to just before line 100,

2021-04-09 07:00 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
> +                                     params.length,
In the swagger page, I can set start to whatever number I want, but when it comes to search page, I think start is probably always 0 ? 
In terms of, what about we make it fixed to 10?

2021-04-11 23:08 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/service/ExportService.scala
> +      .filter(start => start < count)
Yeah this looks much more readable!

2021-04-12 00:36 UTC, edalex-ian approved these changes
Good stuff @PenghaiZhang ! GTG ! :+1: :tada:

2021-04-12 02:58 UTC, edalex-ian commented
Failed in a single flaky test, I'm happy for this to merge.

2021-04-12 03:28 UTC, merged