Replace 'raw search' with 'wildcard search'
openequella/openEQUELLA pull request #2866
Opened 2021-04-12 01:28 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR changes the current 'Raw search' label to be 'Wildcard search', and changes it to be enabled by default.

https://user-images.githubusercontent.com/47203811/114329261-34dec300-9b82-11eb-9709-d48ea76412dd.mp4

2021-04-12 01:51 UTC, edalex-ian requested changes
That's definitely functionally what we're after @PenghaiZhang , however structurally I think we should make it so that the `SearchBar` only knows about 'wildcard mode' and so we change the props to also align with this and make no mention of 'raw mode' within `SearchBar`. That way it acts as a clean boundary between what we do at a UX level verses internal lower level implementation.

Admittedly, this will then also require updates to the integration points and tests, but I think this is worth that.

P.S. Make sure you also don't miss the `id="rawSearch"` too.

2021-04-13 01:47 UTC, edalex-ian approved these changes
Looks good! I think just need to tweak that one comment, then should be GTG.

2021-04-13 01:47 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPage.tsx
> +    // We use `rawMode` which is the logic NOT of `wildcardMode` at lower level.
Sorry, I'm not sure what that is saying, but I propose:

```suggestion
    // `wildcardMode` is a presentation concept, in the lower levels its inverse is the value for `rawMode`
```

2021-04-13 14:44 UTC, ChristianMurphy approved these changes
Thanks @PenghaiZhang!

2021-04-13 14:44 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +    <Typography component="div">
Does this explicitly need to be set as a `div`?

2021-04-13 22:41 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchResultAttachmentsList.tsx
> +    <Typography component="div">
I asked the same question. @PenghaiZhang highlighted he did this due to a new warning emitting from the jest tests due to Typography being a `p` and should not be nesting `div`s which the `<Chip>` is.

2021-04-13 22:42 UTC, edalex-ian commented
Now the builds are finally all green, merging on behalf of @PenghaiZhang

2021-04-13 22:42 UTC, merged