REST endpoint for export validation
openequella/openEQUELLA pull request #2895
Opened 2021-04-14 06:54 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

As discussed, we'd like to send a `HEAD` request to check whether an export is valid or not. So I added a new endpoint to support the HEAD request. In REST module, I firstly created new functions to execute a HEAD request to do the export validation.

2021-04-14 07:02 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
> -                @Context req: HttpServletRequest,
`req` is not used so I removed it.

2021-04-14 07:02 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/ExportCSVHelper.scala
> -  def checkDownloadACL(): Unit = {
I moved this to `SearchResource` as I remember that we want to throw these exceptions in presentation layer rather than a helper.

2021-04-15 01:09 UTC, edalex-ian requested changes
Heya @PenghaiZhang 

Basically all good, just two things:

1. I think the validation in the endpoint should also include getting the collection; and
2. We need two tests added to `io.github.openequella.rest.Search2ExportTest` to cover negative and positive cases.

2021-04-15 01:09 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
> +    }
Probably also makes sense to do the validation of the collection in here too. That is, the code block:

```scala
    val schema: Schema = getSchemaFromCollection(collectionId) match {
      case Some(s) => s
      case None =>
        throw new NotFoundException(s"Failed to find Schema for Collection: $collectionId")
    }
```

And then you could return the `schema`. :thinking:

2021-04-15 01:09 UTC, edalex-ian commented on oeq-ts-rest-api/src/AxiosInstance.ts
> + * @param path The URL path for the target HEAD
```suggestion

 * @param path The URL path for the target HEAD
```

2021-04-15 01:09 UTC, edalex-ian commented on oeq-ts-rest-api/src/Search.ts
> + * @param apiBasePath Base URI to the oEQ institution and API.
```suggestion

 * @param apiBasePath Base URI to the oEQ institution and API.
```

2021-04-15 01:40 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchResource.scala
> +    }
Not a problem!

2021-04-15 07:05 UTC, edalex-ian approved these changes
Thanks @PenghaiZhang , just need to tweak the duplication in the test and then you're probably good to merge when I'm away.

2021-04-15 07:05 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ExportTest.java
> +    }
These five lines are duplicated 3 times. Seems you simply need a wrapper function which would end up looking like:

    assertResponseCode(buildExportRequest(null), 200);

You would then just change the 200 to the 400 and the 403 in each case above - as well as using the different params to `buildExportRequests`.

2021-04-16 00:06 UTC, PenghaiZhang commented on autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ExportTest.java
> +    }
Good idea!!!

2021-04-16 03:31 UTC, merged