Refactor search module
openequella/openEQUELLA pull request #2913
Opened 2021-04-22 06:49 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines]
- [x] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR is all about refactoring `SearchModule` as there are lots of functions inside the module do not really interact with the REST module. So I moved these functons to their new home named 'SearchPageHelper' . 

Another big change is moving `DisplayMode` from `SearchOptions` to `SearchPageOptions`.

2021-04-22 07:04 UTC, edalex-ian commented
Great effort @PenghaiZhang . Unfortunately I wont have a chance to review until Monday, but will jump on it then.

2021-04-24 01:34 UTC, ChristianMurphy approved these changes
Thanks @PenghaiZhang!

2021-04-24 01:34 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/search/SearchPage.test.tsx
> +  const nonLiveStatuses = SearchModule.nonLiveStatuses;
Destructuring can deduplicate this a little

```suggestion
  const { liveStatuses, nonLiveStatuses } = SearchModule;
```

2021-04-27 04:50 UTC, edalex-ian requested changes
Thanks @PenghaiZhang , great tidy up! :+1: 

A few suggestions and tweaks. And looks like we need to find an ESLint rule to try and add blank lines where we want them. :wink:

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +export const DisplayModeRuntypes = Union(
Missing TSDoc. If it's exported (public) it should have doco.

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> + * Type of three display modes.
```suggestion
 * Available modes for displaying search results.
 * @see {@link DisplayModeRuntypes} for original definition.
```

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +export type DisplayMode = Static<typeof DisplayModeRuntypes>;
Missing whitespace. I wonder if there's an ESLint rule for this - it's coming up often in reviews.

```suggestion
export type DisplayMode = Static<typeof DisplayModeRuntypes>;

```

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> +export const isDate = (value: unknown): value is Date => value instanceof Date;
I see these are simply moved from further up, but... Should these be in here. They're fairly generic, and could simply be in some kind of `Dates.ts` or `DateUtils.ts`. Oh, hold on, we already have a `Source/Plugins/Core/com.equella.core/js/tsrc/util/Date.ts` - I'd say add both of these to there.

Also, this `isDate` needs TSDoc.

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/__tests__/tsrc/modules/SearchModule.test.ts
> +});
This `describe` block (SearchModule) is not required, please remove.

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/CollectionsModule.ts
> +
The comment below this line is out of date - it returns the Collection type above (not a Map). Although not directly related to this work, makes sense to update it now.

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/CollectionsModule.ts
> + * @param collectionUuids Collection UUIDs used to filter the list of all Collections.
Be good to also have a `@return` definition on this function - especially seeing it's a union to `undefined`.

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFilterSettingsModule.ts
> + */
Again, good to add a `@return` section to this.

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPageHelper.ts
> + * @param location representing a Location which includes search query params - such as from the <SearchPage>
```suggestion
 *
 * @param location representing a Location which includes search query params - such as from the <SearchPage>
```

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPageHelper.ts
> + * @param searchPageOptions Search options selected on Search page.
```suggestion
 *
 * @param searchPageOptions Search options selected on Search page.
```

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPageHelper.ts
> + * @see {@link https://github.com/pelotom/runtypes/issues/169 }
```suggestion
 *
 * @see {@link https://github.com/pelotom/runtypes/issues/169 }
```

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPageHelper.ts
> +  )(rangeType.toLowerCase() as RangeType);
While you're here, do you want to add a `pipe` in here to match the below function?

And if you wanted, you could refactor this whole function to be an expression:

```typescript
!primaryDate && !secondaryDate ? undefined  :
  pipe(rangeType.toLowerCase() as RangeType,
    match(
      ...
    ));
```

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPageHelper.ts
> + * @param params URLSearchParams from a shared `searching.do` URL
```suggestion
 *
 * @param params URLSearchParams from a shared `searching.do` URL
```

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPageHelper.ts
> +  };
Rather than setting up a function, how's about:

```suggestion
  const externalMimeTypes = pipe(
    params.getAll("_int.mimeTypes"),
    O.fromPredicate(A.isNonEmpty),
    O.toUndefined
  );
```

Then below you can just use it directly for the object in the `return` statement.

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPageHelper.ts
> +    )
How's about:

```suggestion
    O.getOrElse(() => defaultSearchOptions.sortOrder)
```

2021-04-27 04:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPageHelper.ts
> + * @param options An object of SearchOptions
```suggestion
 *
 * @param options An object of SearchOptions
```

2021-04-27 06:28 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchModule.ts
> + * Type of three display modes.
I think we just need either `@see` or `@link` :thinking:

2021-04-27 23:44 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPageHelper.ts
> +  };
Good idea!  I feel the name could be better if it was `O.orUndefined` . :smile:

2021-04-28 00:30 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/SearchPageHelper.ts
> +  };
Yeah, I agree. It's a bit awkward that name. Probably should have gone with convention more and use `O.getOrElseUndefined` and `O.getOrElseNull`. As in the end, it's only needed as you can't returned `undefined` (and I guess `null` but didn't try) from `O.getOrElse`.

2021-04-28 04:17 UTC, edalex-ian approved these changes
Just two comment tweaks and then GTG @PenghaiZhang 

Great work! :tada:

2021-04-28 04:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/CollectionsModule.ts
> + * @returns { Collection[] | undefined } An array of Collections or undefined.
This comment simply repeats the type definition, you want to explain what to expect and when.

```suggestion
 * @returns { Collection[] | undefined } An array of `Collection` instances matching the specified UUIDs or undefined if none could be found.
```

2021-04-28 04:17 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/modules/SearchFilterSettingsModule.ts
> + * @returns { MimeTypeFilter[] | undefined } An array of MimeTypeFilter or undefined.
```suggestion
 * @returns { MimeTypeFilter[] | undefined } An array of `MimeTypeFilter` instances matching the provided IDs or `undefined` if none could be found.
```

2021-04-28 06:52 UTC, merged