Use 'useReducer' to better handle the state of SearchBar
openequella/openEQUELLA pull request #2920
Opened 2021-04-27 05:27 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR fixes the debounce issue of SearchBar by using `useReducer`. Also, the usage of `debounce` has been moved to SearchPage as whether to debounce a search is what SearchPage cares.

https://user-images.githubusercontent.com/47203811/116189953-19bca780-a76d-11eb-9d0a-33576229dc13.mp4

2021-04-27 15:49 UTC, ChristianMurphy approved these changes
Thanks @PenghaiZhang!

2021-04-27 15:49 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
> +};
really like the finite state machine approach here! :+1: 
It makes me wonder a bit if it would make sense to pull in something like https://xstate.js.org/docs or https://thisrobot.life ? or if that would be overkill? :thinking:

2021-04-27 15:49 UTC, ChristianMurphy commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
> +};
Also would it make sense to invoke the search from inside the state machine?
Something along the lines of https://xstate.js.org/viz/?gist=f68893d849bd0eba2afd6a5a7a0769df

2021-04-28 02:19 UTC, edalex-ian requested changes
Heya @PenghaiZhang 

As discussed the naming was a bit confusing and I also think we can get rid of the query in its own state and just use the reducer's state.

I've attached the diff that came out of our trials. Obviously you'll need to make sure any of it works first.

Cheers.

[searchbar.diff.txt](https://github.com/openequella/openEQUELLA/files/6388665/searchbar.diff.txt)

2021-04-28 02:21 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/js/tsrc/search/components/SearchBar.tsx
> +};
I like the look of XState, that'd be cool to take for a spin - some reasonable examples of React/TS too. It'd be interesting to redo the SearchPage with it.

2021-04-28 04:06 UTC, PenghaiZhang commented
> Heya @PenghaiZhang
> 
> As discussed the naming was a bit confusing and I also think we can get rid of the query in its own state and just use the reducer's state.
> 
> I've attached the diff that came out of our trials. Obviously you'll need to make sure any of it works first.
> 
> Cheers.
> 
> [searchbar.diff.txt](https://github.com/openequella/openEQUELLA/files/6388665/searchbar.diff.txt)

Thanks Ian for the diff file.  I have tested locally again and the SearchBar works well!

2021-04-28 04:43 UTC, edalex-ian approved these changes
Good stuff @PenghaiZhang , I reckon let's merge it in.

Maybe then if at some-point someone has time, we could see what things look like if we change this reducer and the SearchPage one to use XState. :thinking: (But definitely something separate to this PR.)

2021-04-28 04:55 UTC, PenghaiZhang commented
> Good stuff @PenghaiZhang , I reckon let's merge it in.
> 
> Maybe then if at some-point someone has time, we could see what things look like if we change this reducer and the SearchPage one to use XState.  (But definitely something separate to this PR.)

Good plan ! Maybe in the next tech debt ?

2021-04-28 05:55 UTC, edalex-ian commented
I think that's just flaky and could be merged.

2021-04-28 05:57 UTC, merged