Feature/rewrite audit log entry migration
openequella/openEQUELLA pull request #2950
Opened 2021-05-04 07:07 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR brings the Java entity class `AuditLogEntry` back and rewrites migration `NewAuditLogColumn` in oEQ traditional approach. By doing this, some usage of simpleDBA has been removed.

2021-05-04 07:16 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/audit/AuditLogEntry.java
> +@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
It will be better if we can register this type in `ExtendedPostgresDialect.java` as a global custom type so that we can reuse the custom type, but the trouble is how to convert  `JsonBinaryType` to `CustomType`. I have not found a good way to achieve this so any help will be appreciated!

2021-05-04 07:16 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/plugin-jpf.xml
> +    <parameter id="bean" value="bean:com.tle.core.institution.migration.v66.NewAuditLogColumn" />
Not 100% sure it's 6.6. I just checked the release page and 6.6 was published after 2018-06-01.

2021-05-04 07:16 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/institution/migration/v66/NewAuditLogColumn.java
> +    return true;
In `SimpleMigration.scala`, `isBackwardsCompatible` returns `true`. So here I make it return `true` to avoid extra trouble.

2021-05-04 07:16 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/institution/migration/v66/NewAuditLogColumn.java
> +  @TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
Have to define the type again. But if we can have this type globally we can remove this I reckon.

2021-05-04 07:16 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/ExtendedPostgresDialect.java
> -public class ExtendedPostgresDialect extends PostgreSQLDialect implements ExtendedDialect {
`PostgreSQLDialect` is deprecated.

2021-05-05 08:42 UTC, edalex-ian approved these changes
LGTM @PenghaiZhang . Could you please just add a couple of the suggested comments, and maybe consider the PGSQL 9.x dialect.

But after that, merge on I say. :+1:

2021-05-05 08:42 UTC, edalex-ian commented on Source/Plugins/Admin/com.tle.web.adminconsole/jarsrc/build.sbt
> +  case PathList("javax", "activation", _*)       => MergeStrategy.first
Maybe add a comment above this line to say something like: "The following three were added when the hibernate-types was added the the hibernate module".

2021-05-05 08:42 UTC, edalex-ian commented on Source/Plugins/Applet/com.tle.web.filemanager.applet/appletsrc/build.sbt
> +  case PathList("javax", "activation", _*)       => MergeStrategy.first
Add comment here as per adminconsole/jarsrc/build.sbt

2021-05-05 08:42 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/audit/AuditLogEntry.java
> +@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
After sorting out the deps issue, did you go back and try and simply use `BasicType` or `UserType` or `JsonBinaryType.INSTANCE` to add it?

2021-05-05 08:42 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/jarsrc/build.sbt
> +  case PathList("javax", "activation", _*)       => MergeStrategy.first
Yeah, let's add a comment here to explain why these are added.

2021-05-05 08:42 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/hibernate/dialect/ExtendedPostgresDialect.java
> -public class ExtendedPostgresDialect extends PostgreSQLDialect implements ExtendedDialect {
I'm not sure we support PGSQL8, I think it's 9.x or maybe more so 9.6+ so perhaps we go with `org.hibernate.dialect.PostgreSQL9Dialect` or more specifically `org.hibernate.dialect.PostgreSQL95Dialect`. Might be safe (easier for adopters) if we go with the simple `PostgreSQL9Dialect`.

2021-05-05 08:43 UTC, edalex-ian commented
Oh actually, before merging I'm happy to try and figure out that type registration with you.

2021-05-06 00:54 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.base/src/com/tle/beans/audit/AuditLogEntry.java
> +@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
Registering JsonBinaryType.INSTANCE works very well!

2021-05-06 01:14 UTC, edalex-ian requested changes
Looks great @PenghaiZhang , just one more thing ....

Don't forget to register the custom JSONB type in the two other main supported dialects - Oracle and SQL Server.

You'll note there is a good amount of code duplication. May want to consider setting up an `enum` to hold the supported custom types, and simply use that in the three classes rather than redefining the constants. Maybe something like:

```java
enum CoreCustomTypes {
  BLANKABLE,
  CSV,
  JSONB,
  XSTREAM
}
```

And then add a custom `value()` to hold a `BasicType` and then you can still have a mapping from `CoreCustomTypes` -> `JsonBinaryType.INSTANCE`. Then in ExtendedPostgresDialect your `getExtraOverrides` would end up looking something like:

```java
  return ImmutableList.of(
    new TextCloubType(),
    CoreCustomType.BLANKABLE,
    CoreCustomType.CSV,
    CoreCustomType.JSONB,
    CoreCustomType.XSTREAM);
```

Or hey, maybe you can simply add `CoreCustomTypes.values()`.

And then use when updating the other extended dialect classes.

2021-05-06 06:22 UTC, PenghaiZhang commented
> Looks great @PenghaiZhang , just one more thing ....
> 
> Don't forget to register the custom JSONB type in the two other main supported dialects - Oracle and SQL Server.
> 
> You'll note there is a good amount of code duplication. May want to consider setting up an `enum` to hold the supported custom types, and simply use that in the three classes rather than redefining the constants. Maybe something like:
> 
> ```java
> enum CoreCustomTypes {
>   BLANKABLE,
>   CSV,
>   JSONB,
>   XSTREAM
> }
> ```
> 
> And then add a custom `value()` to hold a `BasicType` and then you can still have a mapping from `CoreCustomTypes` -> `JsonBinaryType.INSTANCE`. Then in ExtendedPostgresDialect your `getExtraOverrides` would end up looking something like:
> 
> ```java
>   return ImmutableList.of(
>     new TextCloubType(),
>     CoreCustomType.BLANKABLE,
>     CoreCustomType.CSV,
>     CoreCustomType.JSONB,
>     CoreCustomType.XSTREAM);
> ```
> 
> Or hey, maybe you can simply add `CoreCustomTypes.values()`.
> 
> And then use when updating the other extended dialect classes.

Thanks for this good idea! I have implemented this with `List` instead of `enum` though.

2021-05-06 23:56 UTC, edalex-ian approved these changes
Looks good @PenghaiZhang , just a couple of comments around types, but feel free to merge when ready.

2021-05-06 23:56 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/type/HibernateCustomTypes.java
> +  public static ArrayList<BasicType> getCustomTypes() {
Why not just:

```suggestion
  public static List<BasicType> getCustomTypes() {
```

2021-05-06 23:56 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/hibernate/type/HibernateCustomTypes.java
> +    return new ArrayList<>(Arrays.asList(TYPE_JSONB, TYPE_BLANKABLE, TYPE_CSV, TYPE_XSTREAM));
I feel like I've forgotten something, but why not just:

```suggestion
    return Arrays.asList(TYPE_JSONB, TYPE_BLANKABLE, TYPE_CSV, TYPE_XSTREAM);
```

2021-05-07 04:59 UTC, merged