Refactor `OAuthServerAccess.scala`
openequella/openEQUELLA pull request #3011
Opened 2021-05-20 01:02 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR replaces the Scala `CacheValue` with the Java one and replaces Scala `tokenQuery` with Java `ReplicatedCacheDao`.  The changes are mostly around the feature of Cloud provider. Due to my limited knowledge of Scala monad, I am honestly not 100% confident in the simplified code. But I did run through the feature of Cloud provider locally and every things seem fine.

Unfortunately, we can't remove all the code related to the use of simpleDBA until we rewrite `CloudProviderDB`.

![image](https://user-images.githubusercontent.com/47203811/118902543-348fcf80-b959-11eb-8d60-4e1ba779b62c.png)

2021-05-24 01:12 UTC, edalex-ian requested changes
Heya @PenghaiZhang 

Just a suggestion to maintain encapsulation and also a query around DAO usage rather than Service.

BTY.

2021-05-24 01:12 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/replicatedcache/dao/ReplicatedCacheDao.java
> +  CachedValue getByValue(String cacheId, String value);
This should have symmetry with `put()` and so should be:

```suggestion
  CachedValue getByValue(String cacheId, byte[] value);
```

That also then means you can keep the knowledge around Base64 encoding encapsulated.

2021-05-24 01:12 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/oauthserver/OAuthServerAccess.scala
> +                                                  new Base64().encode(clientIdBytes))) match {
As mentioned in other comment, we don't want to be concerned with internal implementations of Base64 encoding here - that should be down in the `ReplcatedCacheDao`.

2021-05-24 01:12 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/oauthserver/OAuthServerAccess.scala
> +        LegacyGuice.replicatedCacheDao.getByValue(CloudTokenCache,
Why is this using the DAO rather than the Service (`ReplicatedCacheService`)?

2021-05-24 01:12 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/replicatedcache/dao/ReplicatedCacheDaoImpl.java
> +                                + " AND cacheId = :cacheId AND institution = :institution");
I know it's convention for this class (and many others) but I'd definitely like to see less use of HQL and more of Criteria and named queries to try and add some robustness. :disappointed:

2021-05-24 06:40 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/oauthserver/OAuthServerAccess.scala
> +        LegacyGuice.replicatedCacheDao.getByValue(CloudTokenCache,
I actually had asked myself the same question. According to the previous code, there seems no need to save the `CachedValue` in a cache. If you look into `ReplicatedCacheService` you will see it only provides a method which returns a cache.

I feel there is some confusion here. `ReplicatedCacheDao` is just a dao which serves entity `CachedValue`, but `ReplicatedCacheService` is not like other Services we have. It doesn't do anything about `CachedValue` but `Cache`.

2021-05-24 07:55 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/oauthserver/OAuthServerAccess.scala
> +        LegacyGuice.replicatedCacheDao.getByValue(CloudTokenCache,
hmmm, let's discuss in person tomorrow. From a quick look now it'd seem that `ReplicatedCacheService` manages `Caches` with the default implementation being cluster aware. Seems to then use a cache that is stored locally on a server, but then distributed across the cluster via the DB. (kind of like hibernates L1/L2 caches)

2021-05-26 03:42 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/replicatedcache/dao/ReplicatedCacheDaoImpl.java
> +                                + " AND cacheId = :cacheId AND institution = :institution");
Not a problem. I have replaced this HQL with Criteria.

2021-05-26 05:57 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/oauthserver/OAuthServerAccess.scala
> +        LegacyGuice.replicatedCacheDao.getByValue(CloudTokenCache,
Okay, after our discussion I can more importantly see that you have matched the code as was.

The question about the use of the `ReplicatedCacheService` will more so come in when we look at  `OAuthClientService.scala`. As we've noted, in that file is seems to use the scala re-implementation of `ReplicatedCacheService` in the form of `DBCacheBuilder`. So that'll be interesting times.

2021-05-26 06:14 UTC, edalex-ian approved these changes
GTG! Thanks @PenghaiZhang

2021-05-26 23:07 UTC, merged