Bugfix/default viewer disabled
openequella/openEQUELLA pull request #3064
Opened 2021-06-02 04:13 UTC by PenghaiZhang

#2707 

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

When attachment default viewer is not enabled, New Search UI complains that viewer detail is missing. To fix this issue, we need to do three things: 
1. fix existing data by a data migration;
2. fix imported data;
3. prevent users from saving a MIME type which does not enable its default viewer.

So a new function was added to the `MimeTypeService` to build the correct list of enabled viewers, and then this function is used in the new migration `EnableDefaultViewerMigration` and `MimeEntryConverter`. Lastly, UI side changes were made in `MimeDefaultViewerSection`.

Examples:

1. `video/x-flv`
Before migration: 
![image](https://user-images.githubusercontent.com/47203811/120422662-15a72980-c3ac-11eb-8c91-e7a1ff95d605.png)
after:
![image](https://user-images.githubusercontent.com/47203811/120422911-b1d13080-c3ac-11eb-92f8-7e69960353b1.png)

2. `image/jpeg`
Before migration:
![image](https://user-images.githubusercontent.com/47203811/120422819-79315700-c3ac-11eb-8839-4ce97422a6bc.png)
after:
![image](https://user-images.githubusercontent.com/47203811/120422881-a54cd800-c3ac-11eb-8c3b-0ef13714b8b2.png)

2021-06-03 07:38 UTC, edalex-ian requested changes
Good stuff @PenghaiZhang , all feedback is just around doco and language string.

2021-06-03 07:38 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties
> +/com.tle.core.entity.services.migration.v20211.enable.default.viewer=Enable default viewer
```suggestion
/com.tle.core.entity.services.migration.v20211.enable.default.viewer=Ensure configured default viewers are also enabled
```

2021-06-03 07:38 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/institution/migration/v20211/EnableDefaultViewerMigration.java
> +public class EnableDefaultViewerMigration extends AbstractHibernateDataMigration {
Be good to add JavaDoc to capture details about what this migration is for/doing.

2021-06-03 07:38 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/institution/migration/v20211/EnableDefaultViewerMigration.java
> +        session.flush();
I'm missing something here, but this reads:

1. For each entry
2. Read in the attributes
3. From the attributes (from the entry) get the list of enabled viewers
4. If there are any enabled viewers
5. then write back the same values to the entry

So, the end result is no change. :confused: 

Now I'm going to take a punt and say you're relying on some kind of data correction in `getEnabledViewerList` and so really you should document that here in a comment.

2021-06-03 07:38 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/mimetypes/MimeTypeService.java
> +   * the list. However, if the default viewer is "file", it will not be included.
> However, if the default viewer is "file", it will not be included.

Why not?

Often, the Why in a comment is the most important thing. It's that knowledge that the comment preserves when we come back to this and try and understand what is going on.

2021-06-03 07:38 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/mimetypes/MimeTypeService.java
> +   * @return A string representing a list of enabled viewers
What format is that string?

2021-06-03 07:38 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/mimetypes/MimeTypeServiceImpl.java
> -
Thank you! :+1:

2021-06-04 01:10 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/mimetypes/MimeTypeService.java
> +   * @return A string representing a list of enabled viewers
I think it's array.

2021-06-04 01:23 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/mimetypes/MimeTypeService.java
> +   * the list. However, if the default viewer is "file", it will not be included.
The reason is `file` is added to the list by `MimeDefaultViewerSection, depending on some conditions IIRC. Also the MIME type REST endpoint does this, too.

2021-06-04 03:28 UTC, edalex-ian approved these changes
GTG @PenghaiZhang , but be good if you could just tweak that comment on format a bit more.

2021-06-04 03:28 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/mimetypes/MimeTypeService.java
> +   * @return A string representing a list of enabled viewers in the format of array.
That's still unclear really, best to either give an example or specify the standard format being used e.g.  "[..] formatted as a JSON array of strings".

2021-06-04 06:17 UTC, edalex-ian approved these changes

2021-06-04 07:10 UTC, merged