Apply the gallery visibility settings in New Search UI
openequella/openEQUELLA pull request #3067
Opened 2021-06-02 06:13 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Apply the gallery visibility settings in New Search UI. 

https://user-images.githubusercontent.com/47203811/120432568-75f29700-c3bd-11eb-90c5-2a123721204c.mp4

2021-06-02 06:15 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
> -const searchSettingPromise = mockSearchSettings.mockResolvedValue(
I found this const is redundant so I removed it.

2021-06-03 04:53 UTC, edalex-ian requested changes
Heya @PenghaiZhang , just a couple of minor tweaks required.

2021-06-03 04:53 UTC, edalex-ian commented on react-front-end/__stories__/search/DisplayModeSelector.stories.tsx
> +  disableImageMode: false,
It'd probably make sense to add three additional stories here for each being off in turn, and then both being off.

2021-06-03 04:53 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
> +      expect(queryByLabelText(label)).not.toBeInTheDocument();
As well as make sure what should be hidden is _not_ in the document, we should probably make sure that we haven't hidden the rest.

2021-06-03 04:53 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
> +  ])(
Testing for the minimal case is good, how about also testing the maximal case. (i.e. be good to test it's fine when both image and gallery are hidden.)

2021-06-03 04:53 UTC, edalex-ian commented on react-front-end/tsrc/search/components/DisplayModeSelector.tsx
> +  const buttons = options.map(({ displayMode, icon, label, disabled }) => {
Rather than making the JSX block more complicated, why not just:

```suggestion
  const buttons = options.filter(option => !option.disabled).map(({ displayMode, icon, label }) => {
```

Then all the JSX can stay how it used to be.

2021-06-03 06:42 UTC, PenghaiZhang commented on react-front-end/__stories__/search/DisplayModeSelector.stories.tsx
> +  disableImageMode: false,
Probably two ? Because the standard mode is never off.

2021-06-03 06:44 UTC, PenghaiZhang commented on react-front-end/__stories__/search/DisplayModeSelector.stories.tsx
> +  disableImageMode: false,
Oh I misunderstood. Yeah, I have added three more.

2021-06-03 06:57 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
> +      expect(queryByLabelText(label)).not.toBeInTheDocument();
Good idea. Added.

2021-06-03 22:57 UTC, edalex-ian commented
Ah, flaked on the known LDAPTest - ldapLogon. Not worth worrying about.

2021-06-03 23:03 UTC, edalex-ian approved these changes
Heya @PenghaiZhang 

Couple of ponderings/suggestions. But really, it's GTG, so up to you. :grin: 

:+1:

2021-06-03 23:03 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
> +      ...disabledModes: string[]
Slight curious this, wonder why you didn't just specify both as simple arrays. :thinking:

2021-06-03 23:03 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
> +    languageStrings.searchpage.displayModeSelector.modeGalleryVideo;
This is rather verbose. How about a simple destructure - and you can rename them if desired?

2021-06-04 00:27 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
> +    languageStrings.searchpage.displayModeSelector.modeGalleryVideo;
I really should do this.

2021-06-04 00:28 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
> +      ...disabledModes: string[]
Haha not particular reason. Just because two test cases do not need an array and one needs

2021-06-04 03:24 UTC, edalex-ian approved these changes
Cool dude, merge on! :+1:

2021-06-04 05:10 UTC, merged