EBP for the Kaltura dialog
openequella/openEQUELLA pull request #3078
Opened 2021-06-04 05:24 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Some EBP work to make the Kaltura dialog look nicer.

![image](https://user-images.githubusercontent.com/47203811/120750008-eb3ea300-c548-11eb-8655-8c1bae1ff96e.png)

![image](https://user-images.githubusercontent.com/47203811/120750044-fe517300-c548-11eb-8293-444757aea971.png)

![image](https://user-images.githubusercontent.com/47203811/120749933-c5b19980-c548-11eb-82af-480c1f2ed662.png)

2021-06-07 07:07 UTC, SammyIsConfused reviewed
Thanks Penghai! Just a few suggestions :+1:

2021-06-07 07:07 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    background-color: #80d2ee !important;
These !important flags - where are you overriding? Is it somewhere in legacy.scss? If so, we might be able to fix up the rule causing this. 
If its somewhere in equella, but not in legacy.scss, you should be able to `import thefileinquestion.css` at the top of legacy.scss. 
If its external, then yes this is probably the only way.

2021-06-07 07:07 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    background-color: #f3f1eb;
Do these need to refer to the theme at all?

2021-06-07 07:07 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    opacity: 0.35;
These lines appear to do the same thing. Does one need removing?

2021-06-07 07:07 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    padding: 8px 10px;
Any time we refer to 8px, we can use $singleMargin.

2021-06-07 07:07 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    padding-bottom: 10px;
Interesting that you need 10px, which is close to our standard $singleMargin. Does it look okay with 2px less?

2021-06-07 07:07 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    font-size: 12px;
There might be a mixin at the top of the file that achieves what we need here in the same way as native MUI, Worth checking, so we aren't adding text that is styled inconsistently with others.

2021-06-07 07:07 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    zoom: 1;
isn't zoom: 1 the default? Is it needed?

2021-06-08 01:08 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    background-color: #80d2ee !important;
Yeah looks like we can remove these `!important`.

2021-06-08 01:12 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    background-color: #f3f1eb;
Not quite sure.  Should this go with primary color or secondary color ?

2021-06-08 01:14 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    opacity: 0.35;
Yes, the `filter` is an ancient thing.

2021-06-08 01:17 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    padding: 8px 10px;
Good idea! And I think `doubleMargin` looks nicer!
![image](https://user-images.githubusercontent.com/47203811/121107353-20017180-c84b-11eb-83c1-ac320faaa867.png)

2021-06-08 01:19 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    padding-bottom: 10px;
I just copied this from the Kaltura codebase.  I think this rule is redundant. I will remove it.

2021-06-08 01:21 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    zoom: 1;
Looks like it is! I have removed it. Cheers.

2021-06-08 01:40 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    font-size: 12px;
Since this rule applies to a `h4`, I thought the mixin of `typography-headline-4` could be the one to use. But it turned out this mixin provides very different font styles. The only one that looks similar to what we need is `typography-body-1`, but I have to add `font-weight: bold;`.

You can see the font size is bigger.
![image](https://user-images.githubusercontent.com/47203811/121109140-57bde880-c84e-11eb-8543-9d059140933c.png)

2021-06-08 01:42 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    background-color: #f3f1eb;
We will have different user experience in Old UI if we change this.

2021-06-08 03:34 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    background-color: #f3f1eb;
According to the slack discussions, let's keep this as it is now.

2021-06-08 03:34 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    font-size: 12px;
According to the slack discussions, let's keep this as it is now

2021-06-08 04:50 UTC, PenghaiZhang commented
![image](https://user-images.githubusercontent.com/47203811/121124802-dd4e9200-c868-11eb-9550-9021bd387174.png)

2021-06-08 05:19 UTC, SammyIsConfused requested changes
Thanks Penghai! Just one last tweak to do and then you're good to go.

2021-06-08 05:19 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/resources/web/sass/legacy.scss
> +    padding-bottom: 4px;
```suggestion
    padding-bottom: $minimalMargin;
```

2021-06-08 05:23 UTC, SammyIsConfused commented
Also of note - remember in future to write your commit messages such that they fit in the sentence:
"If applied, this commit will {blank}."
Such as
Improve styles for Kaltura wizard control dialog.

For more info see https://chris.beams.io/posts/git-commit/ (this is also in our CONTRIBUTING.md)

2021-06-08 07:21 UTC, SammyIsConfused approved these changes
Looks good to me! Thanks for fixing those up @PenghaiZhang . Good to go.

2021-06-09 00:47 UTC, edalex-ian approved these changes
LGTM. :+1:

2021-06-09 02:10 UTC, merged