Move resource attachment thumbnail selection to its own function
openequella/openEQUELLA pull request #3090
Opened 2021-06-07 11:26 UTC by SammyIsConfused

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]

##### Description of change

I made a mistake earlier today on f8edd01, initially intending to include the correct default thumbnail for resource attachments pointing towards links but instead incorrectly defaulting to oeqProvidedThumb which caused generated thumbnails not to be used. 
I wonder if its worth doing a refactor of this component at some point, as the logic is somewhat strange.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2021-06-07 14:15 UTC, ChristianMurphy approved these changes

2021-06-07 23:05 UTC, edalex-ian requested changes
With additional logic it'd be good to have a test for it. But I note this component has no specific tests or stories.

Could you please add a component/OEQThumb story? Feel free to just have enough stories to cover your new setup, plus one or so of the others.

And for bonus points, it'd be pretty useful to have a Jest test around this component - strange it was skipped. :thinking:

2021-06-07 23:07 UTC, SammyIsConfused commented
> With additional logic it'd be good to have a test for it. But I note this component has no specific tests or stories.
> 
> Could you please add a component/OEQThumb story? Feel free to just have enough stories to cover your new setup, plus one or so of the others.
> 
> And for bonus points, it'd be pretty useful to have a Jest test around this component - strange it was skipped. thinking

Sounds good, thanks for that. I'll add some tests and stories - this wouldn't have happened if they were there in the first place.

2021-06-08 02:03 UTC, SammyIsConfused commented
Tests and stories have been added to surround this component :+1:

2021-06-08 02:23 UTC, PenghaiZhang reviewed
Hi Sam, I have left some queries for you. Thank you!

2021-06-08 02:23 UTC, PenghaiZhang commented on react-front-end/__stories__/components/OEQThumb.stories.tsx
> +  component: OEQThumb,
Perhaps you can add
```
  argTypes: {
    showPlaceholder: {boolean: false},
  },
```

and then don't need to repeat `showPlaceholder: false,` below.

2021-06-08 02:23 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/components/OEQThumb.test.tsx
> +  const OEQThumbComponent = (
```suggestion
  const buildOEQThumb = (
```

2021-06-08 02:23 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/components/OEQThumb.test.tsx
> +      expect(queryForIconId(container, query)).not.toBeNull();
```suggestion
      expect(queryForIconId(container, query)).toBeTruthy();
```

2021-06-08 02:23 UTC, PenghaiZhang commented on react-front-end/tsrc/components/OEQThumb.tsx
> +      result = <ImageIcon id="imageIcon" {...generalThumbStyles} />;
I image there will be multiple image icons that have the this ID in one page?

2021-06-08 02:23 UTC, PenghaiZhang commented on react-front-end/tsrc/components/OEQThumb.tsx
> +      result = <VideoIcon id="videoIcon" {...generalThumbStyles} />;
Same query as above.

2021-06-08 02:45 UTC, SammyIsConfused commented on react-front-end/__stories__/components/OEQThumb.stories.tsx
> +  component: OEQThumb,
Done, thanks!

2021-06-08 02:46 UTC, SammyIsConfused commented on react-front-end/tsrc/components/OEQThumb.tsx
> +      result = <ImageIcon id="imageIcon" {...generalThumbStyles} />;
Yup, good catch. Added the attachment ID to the end, to make it unique.

2021-06-08 02:46 UTC, SammyIsConfused commented
Fixed those up @PenghaiZhang , thanks so much :)

2021-06-08 03:39 UTC, PenghaiZhang approved these changes
Thanks Sam. I think it is good to go.

2021-06-08 04:46 UTC, PenghaiZhang approved these changes

2021-06-08 07:23 UTC, SammyIsConfused commented
@PenghaiZhang and I looked at and discussed the language string commit in the office and it was all good with him (actually his suggestion). So I'll go ahead and merge this.

2021-06-08 07:23 UTC, merged