Feature/navigate attachments in gallery
openequella/openEQUELLA pull request #3091
Opened 2021-06-10 07:20 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds the support for viewing previous/next attachments with Lightbox in Gallery mode. The function used to build the handler for `onNext` and `onPrevious` was focused on `Attachment` so it did not support `GalleryEntry` very well. So I refactored this function to support both.

During implementation, Sam found a bug where if you are on the first/last image and you press the left/right arrow button you will see a blank Lightbox. The fix is also added in this PR.

https://user-images.githubusercontent.com/47203811/121481993-052c2a00-ca10-11eb-82f1-182278a90282.mp4

2021-06-10 07:23 UTC, PenghaiZhang commented on react-front-end/tsrc/components/Lightbox.tsx
>      setContent(undefined);
Here is the cause for the bug. We set `content` to undefined before we get the new lightbox config. The fix is that we do nothing when the handlers (onNext / onPrevious) provided are undefined.

2021-06-11 00:46 UTC, edalex-ian requested changes
Looks good @PenghaiZhang , but I think we need one refactor before proceeding.

2021-06-11 00:46 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> + * Build a function to handler navigation between Lightbox entries.
```suggestion
 * Build a function to handle navigation between Lightbox entries.
```

2021-06-11 00:46 UTC, edalex-ian commented on react-front-end/tsrc/search/components/GallerySearchResult.tsx
> +        };
I think this change - maybe the one before - has pushed `mapItemsToTiles()` over the edge of readability. I think perhaps some of the nested functions should be pushed out - such as `buildOnClickHandler()` - and we probably also probably want to minimise use of external variables to help - such as using `lightboxEntries`.

Refactor needed.

2021-06-15 06:08 UTC, edalex-ian approved these changes
Good stuff @PenghaiZhang . Merge on :+1:

2021-06-15 23:13 UTC, merged