feat: support copying resource embed code from Lightbox
openequella/openEQUELLA pull request #3132
Opened 2021-06-23 00:51 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds the support for copying resource embed code from Lightbox. I also reordered language strings in this PR.

![image](https://user-images.githubusercontent.com/47203811/123017846-c6837000-d410-11eb-8156-04082251578d.png)

![image](https://user-images.githubusercontent.com/47203811/123017874-d4d18c00-d410-11eb-8638-602e86aab504.png)

![image](https://user-images.githubusercontent.com/47203811/123017904-e5820200-d410-11eb-9dbe-483509c8f642.png)

2021-06-23 00:56 UTC, PenghaiZhang commented on react-front-end/tsrc/components/Lightbox.tsx
> +  const [content, setContent] = useState<ReactElement | undefined>();
Since type of the content we build is `JSX.Element`,  `ReactNode`  is too broad. So I changed it to `ReactElement`.

2021-06-23 00:56 UTC, PenghaiZhang commented on react-front-end/tsrc/components/Lightbox.tsx
> +    const unneededAttributes = ["class"];
I don't think we want to include `class` as part of the embed code. But if we want, this function can be simplified to 
```
 return renderToStaticMarkup(content);
```

2021-06-23 13:26 UTC, ChristianMurphy reviewed
Thanks @PenghaiZhang!
Just a few questions and considerations.

2021-06-23 13:26 UTC, ChristianMurphy commented on react-front-end/tsrc/search/components/EmbedCodeDialog.tsx
> +    <DialogContent>{embedCode}</DialogContent>
Would it make sense from an HTML semantics perspective to wrap this in a `<code>` tag?
```suggestion
    <DialogContent><code>{embedCode}</code></DialogContent>
```

2021-06-23 13:26 UTC, ChristianMurphy commented on react-front-end/tsrc/components/Lightbox.tsx
> +    );
I'm cautious about including `renderToStaticMarkup` which is part of `react-dom/server` on the clientside.
Would it be possible to render the component using something like
```jsx
<div ref={staticRenderRef} style={{display: 'none'}}>{content}</div>
```
 and get the inner HTML of the `staticRenderRef`?

2021-06-23 13:26 UTC, ChristianMurphy commented on react-front-end/tsrc/util/langstrings.ts
> +  dateRangeSelector: {
it looks like there is a mix of camelcase and all lowercase, would it make sense to use just one or the other?
Personally I find the camelcase names a bit easier to read, but either could work.

2021-06-23 23:51 UTC, edalex-ian commented on react-front-end/tsrc/util/langstrings.ts
> +  dateRangeSelector: {
Yup, we're slowly moving towards all being camelCase - so at least all new ones are. I think what we're seeing here is @PenghaiZhang has gone through and sorted these more (thanks @PenghaiZhang ) and as a result highlighting some of the old 'all lowercase' varieties.

2021-06-24 03:46 UTC, PenghaiZhang commented on react-front-end/tsrc/search/components/EmbedCodeDialog.tsx
> +    <DialogContent>{embedCode}</DialogContent>
Yeah this makes sense! Thank you!

2021-06-24 04:25 UTC, PenghaiZhang commented on react-front-end/tsrc/components/Lightbox.tsx
> +    );
I have tried this approach and got an error. The result of `innerHTML` does not have a closing tag for `img`. For example, it gives me `<img  alt="macaw.jpg" src="...">` and then the DOM parser makes errors. 
`

2021-06-24 04:27 UTC, PenghaiZhang commented on react-front-end/tsrc/components/Lightbox.tsx
> +    );
If I change to HTML parser, I don't have errors but the result is wrapped in a bare-bones `<html><head></head><body><img></body></html>`.

2021-06-24 04:28 UTC, PenghaiZhang commented on react-front-end/tsrc/components/Lightbox.tsx
> +    );
Do you have any suggestion @ChristianMurphy ?

2021-06-24 04:43 UTC, ChristianMurphy commented on react-front-end/tsrc/components/Lightbox.tsx
> +    );
> I don't have errors but the result is wrapped in a bare-bones `<html><head></head><body><img></body></html>`

Right, dom parser will try to generate a full HTML document, the fragment can be accessed from `doc.body.childNodes[0]`

2021-06-24 05:12 UTC, PenghaiZhang commented on react-front-end/tsrc/components/Lightbox.tsx
> +    );
Thanks! I have pushed some changes.

2021-06-24 05:15 UTC, ChristianMurphy commented on react-front-end/tsrc/components/Lightbox.tsx
> +    const unneededAttributes = ["class"];
Probably fine to filter it out.
Down the road, if the list grows, I could potentially see inverting this.
Listing the attributes to keep, rather than those to remove.
But with just a single attr at the moment it seems fine.

2021-06-24 05:18 UTC, ChristianMurphy approved these changes

2021-06-24 05:18 UTC, ChristianMurphy commented on react-front-end/tsrc/search/components/EmbedCodeDialog.tsx
> +  closeDialog: () => void;
Potentially `onCloseDialog` to clarity its intent as an event listener, rather than an action to close.

2021-06-24 06:37 UTC, edalex-ian requested changes
Looks good @PenghaiZhang . Just need to relocate the new dialog to keep it nice and generic. No need to tie it down into Search. ;)

After that, should be GTG.

2021-06-24 06:37 UTC, edalex-ian commented on react-front-end/tsrc/search/components/EmbedCodeDialog.tsx
> + * Provide a Dialog which allows users to copy embed code of a Lightbox viewable resource(e.g. image && video).
There is nothing in here specific to Lightbox. I think this should be moved to `tsrc/components` and the reference here to `Lightbox` removed. I can see in the future this being used in other contexts.

2021-06-24 06:37 UTC, edalex-ian commented on react-front-end/tsrc/components/Lightbox.tsx
> +  // Generate a HTML string from current Lightbox content.
Interesting idea @PenghaiZhang . I like it. I wonder if we'll get tripped up at some point (like if we need to add SSO tokens or the like), but for now it's great. :+1:

2021-06-25 05:12 UTC, edalex-ian approved these changes
Looks good @PenghaiZhang , and thanks for the additional cosmetic tweaks.

2021-06-27 23:13 UTC, merged