feat: preview Youtube videos on standard list mode
openequella/openEQUELLA pull request #3142
Opened 2021-06-25 05:57 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Changes of this PR enable previewing of YouTube videos from the Search results attachment list in the same way that local videos can currently be previewed from the same place (Lightbox). 

The approach is to update the MIME type of Youtube attachment and what viewer to be used.

https://user-images.githubusercontent.com/47203811/123376446-d5635180-d5cd-11eb-9c22-845eeaaa74cd.mp4

2021-06-25 06:01 UTC, PenghaiZhang commented on react-front-end/tsrc/modules/AttachmentsModule.ts
> +  attachment.attachmentType === ATYPE_YOUTUBE
Perhaps we need to  use `match` here when we support more attachment types that need custom information.

2021-06-25 06:01 UTC, PenghaiZhang commented on react-front-end/tsrc/search/components/SearchResultAttachmentsList.tsx
> +        return "htmlFiveViewer";
Not quite sure if we should `htmlFiveViewer` or `file` here, but `htmlFiveViewer` makes more sense to me.

2021-06-25 06:01 UTC, PenghaiZhang commented on react-front-end/tsrc/search/components/SearchResultAttachmentsList.tsx
> +              mimeType && !brokenAttachment
No need to pass `brokenAttachment` to `getViewerID` - just return `undefined` for broken attachments.

2021-06-28 05:47 UTC, edalex-ian reviewed
Hmmm, I've made a few comments here on trivial things, but then I realised we have some rather fundamental issues. Although this change does the job, I fear it's built on top of a foundation that is going to be costly to maintain.

A few areas that drew my attention:

1. We have a rather meandering useEffect of over 100 lines;
2. Inside that affect we have an async IIFE which is over 70 lines long - and I resorted to an IDE to determine where it starts/ends and is called;
3. The function `getViewerId` should probably be over in the `ViewerModule` and just take an `Attachment`;
4. And then the question comes in is there a better way to transform the attachments to be fit for purpose in building the attachment and viewer definitions rather; and
5. How does this overlap with what's in the gallery (and referencing back to the above point, can we have a clearer pipeline like we have there).

I think it'd be worthwhile to discuss and figure out what direction to take.

2021-06-28 05:47 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  if (![ATYPE_FILE, ATYPE_RESOURCE, ATYPE_YOUTUBE].includes(attachmentType)) {
I feel having the not operator so removed from the logic hear hinders readability, how about:

```suggestion
  if ([ATYPE_FILE, ATYPE_RESOURCE, ATYPE_YOUTUBE].includes(attachmentType) === false) {
```

Also, the comment below needs to be update now - should've been updated when `"custom/resource"` was added.

2021-06-28 05:47 UTC, edalex-ian commented on react-front-end/tsrc/modules/YouTubeModule.ts
> + * Update Youtube Video Attachment with Custom MIME type and View URL.
```suggestion
 * Update YouTube Video Attachment with Custom MIME type and View URL.
```

2021-06-28 05:47 UTC, edalex-ian commented on react-front-end/tsrc/modules/YouTubeModule.ts
> +  throw new Error("Missing Youtube Video Attachment external ID.");
```suggestion
  throw new Error("Missing YouTube Video Attachment external ID.");
```

2021-06-30 06:57 UTC, PenghaiZhang commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  if (![ATYPE_FILE, ATYPE_RESOURCE, ATYPE_YOUTUBE].includes(attachmentType)) {
I am cool with this, but Intellij keeps suggesting me that `[...].includes(x)===false` can be simplified to what I have done.

2021-06-30 21:02 UTC, ChristianMurphy commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  const task = () => {
Would it make sense to mark this function as `async` since it appears to always return a promise?
That would also automatically convert `throw`'s into `Promise.rejects`.

2021-06-30 23:32 UTC, PenghaiZhang commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  const task = () => {
Hi @ChristianMurphy , do you mean we refactor this to 
```
  const task = async () => {
    try {
      return await getViewerDetails();
    } catch (error) {
      return (
        `${languageStrings.searchpage.searchResult.errors.getAttachmentViewerDetailsFailure}: ${error.message}`
      )
    }
  };

```

2021-07-01 00:04 UTC, PenghaiZhang commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  const task = () => {
Oh I see. I should throw an error with the string rather than `return`.

2021-07-01 00:07 UTC, ChristianMurphy commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  const task = () => {
right, something like

```ts
  const task = async () => {
    return getViewerDetails();
  };
```

or

```ts
  const task = async () => {
    try {
      return getViewerDetails();
    } catch (error) {
      throw new Error(`${languageStrings.searchpage.searchResult.errors.getAttachmentViewerDetailsFailure}: ${error.message}`);
    }
  };
```

2021-07-01 00:12 UTC, ChristianMurphy approved these changes

2021-07-05 07:12 UTC, edalex-ian requested changes
Great work on tidying up the Uber Effect.

Now as discussed, we just want to tidy-up that pipeline.

2021-07-05 07:12 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/modules/ViewerModule.test.ts
> +  it("returns a left of Either if any attachment fails to build viewer definition", async () => {
```suggestion
  it("returns a Left if any attachment fails to build viewer definition", async () => {
```

2021-07-05 07:12 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/modules/ViewerModule.test.ts
> +  it("returns a right of Either if viewer definitions are built for all attachments", async () => {
```suggestion
  it("returns a Right if viewer definitions are built for all attachments", async () => {
```

2021-07-05 07:12 UTC, edalex-ian commented on react-front-end/tsrc/modules/AttachmentsModule.ts
> + * @param attachment An attachment that might need custom information
```suggestion
 *
 * @param attachment An attachment that might need custom information
```

2021-07-05 07:12 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  const task = () => {
Oops, looks like you forgot to add the async discussed, i.e.:

```suggestion
  const task = async () => {
```

2021-07-05 07:12 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> +): Promise<E.Either<string, AttachmentAndViewerDefinition[]>> => {
As discussed, I was expecting to see a return type here of `Promise<E.Either<NonEmptyArray<string>, NonEmptyArray<AttachmentAndViewerDefinition>>>`.  That does two things:

1. Provides flexibility on how all the errors are possibly used; and
2. Use the `NonEmptyArray` (typically imported as `NEA`) to remove future need for checking `isEmpty` etc.

2021-07-05 07:12 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  );
As discussed, it looks like this could benefit from use of things like `flow`/`pipe`, `Do`.

Also, for `brokenAttachment` we should just be able to shortcircuit and end up with a `AttachmentAndViewerDefinition` of:

```typescript
{
  attachment,
  viewerDefinition: undefined
}
```

Obviously for that though, you'll need to modify the `interfaces` for things like `AttachmentAndViewerDefinition`.

2021-07-05 07:12 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  return A.isEmpty(lefts) ? E.right(rights) : E.left(lefts.join());
As per the comment on the return type, there'll be no need to do the `join`...

2021-07-05 07:12 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> +export const buildViewerConfigForAttachment = async (
Shouldn't this be plural?

```suggestion
export const buildViewerConfigForAttachments = async (
```

2021-07-05 07:12 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  const attachmentsAndViewerDefinitions = await buildAttachmentsAndViewerDefinitions(
For readability, could I please request that you explicitly type this? I.e.:

```suggestion
  const attachmentsAndViewerDefinitions: Either<string, AttachmentAndViewerDefinition> = await buildAttachmentsAndViewerDefinitions(
```

2021-07-05 07:12 UTC, edalex-ian commented on react-front-end/tsrc/modules/YouTubeModule.ts
> + * @param attachment An Youtube Video Attachment
```suggestion
 *
 * @param attachment An Youtube Video Attachment
```

2021-07-07 00:03 UTC, PenghaiZhang commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  );
I also modified `AttachmentAndViewerConfig`

2021-07-07 00:48 UTC, PenghaiZhang commented
Ah dear I did not install the new version of prettier and then lots of format issues come up. I will fix this now.

2021-07-08 07:13 UTC, edalex-ian requested changes
Fair effort here @PenghaiZhang ! Thank you! :+1: :pray: :star: 

I do have some final comments for some last tweaks. And after that it should be fine to merge.

2021-07-08 07:13 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/modules/ViewerModule.test.ts
> +    },
This seems like a rather odd (almost broken) definition for a file attachment. Is it testing some special case? If so perhaps a comment above it highlight such. :thinking:

2021-07-08 07:13 UTC, edalex-ian commented on react-front-end/tsrc/components/ItemAttachmentLink.tsx
> +
(Sorry, went down a rabbit hole on this one.... :disappointed: )

It's a shame this is fragmented from the below ternary. It's be great if we could end with a nicely merged single return statement. Could we do this with `pipe` and `match`? :thinking: 

```typescript
return pipe(
  viewerConfig,
  O.fromNullable,
  O.match(
    () => (<Typography>...</Typography>),
    flow(
      E.fromPredicate(
        isViewerLightboxConfig,
        identity
      ),
      E.match(
        buildLightboxLink,
        buildSimpleLink
    )
  )
);
```

Hmmm, for readability (and future easy of use) I think we could make that easier by adding a `pfTernary` function. Then it could look like:

```typescript
return pipe(
  viewerConfig,
  O.fromNullable,
  O.match(
    // Broken attachments just have a textual placeholder
    () => (<Typography>...</Typography>),
    // For other attachments we use the <Lightbox> where suitable
    pfTernary(
      isViewerLightboxConfig,
      buildLightboxLink,
      buildSimpleLink
  )
);
```

Here's the proposed `util/pointfree.ts` with `pfTernary` (wish I could tweak the typing though and simply use `flow` rather than `pipe` but hey):

```typescript
import * as E from "fp-ts/Either";
import { identity, pipe } from "fp-ts/function";

/**
 * Point-free ternary. For cases where you'd typically use a ternary, but want to reap the benefits
 * of point-free code. For example:
 *
 * ```typescript
 * const isLoud = (m: string): boolean => m.match(/.+!/) !== null;
 * const shout = (m: string): string => m.toUpperCase();
 * const whisper = (m: string): string => m.toLowerCase();
 *
 * const msg = "Announcement!";
 * isLoud(msg) ? shout(msg) : whisper(msg);
 *
 * // Now point-free:
 * pipe(
 *   msg,
 *   pfTernary(isLoud, shout, whisper)
 * );
 * ```
 */
export const pfTernary =
  <A, B>(
    predicate: (a: A) => boolean,
    onRight: (a: A) => B,
    onLeft: (a: A) => B
  ) =>
  (a: A): B =>
    pipe(a, E.fromPredicate(predicate, identity), E.match(onLeft, onRight));
```

2021-07-08 07:13 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> + * message and right is 'AttachmentAndViewerDefinition'. However, the final result is an Either where left is a string
```suggestion
 * message and right is 'AttachmentAndViewerDefinition'. The final result is an Either where left is a string array
```

2021-07-08 07:13 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  return A.isEmpty(lefts) ? E.right(rights) : E.left(lefts);
This all seems slightly at odds with the above functional code. It'd be great to see it combined/composed with pipe etc. But no biggy.

2021-07-08 07:13 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> +      attachments.map(async (originalAttachment) => {
Did you consider doing `pipe(attachments, A.map ... )`? or perhaps to accommodate broken attachments `pipe(attachments, A.partition ... )`?

Doing so you might have been able to minimise the hybrid approach and possibly skip the need for any `return` statements - vs. the two here.

2021-07-08 07:13 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> +    A.map(({ attachment: { id, description, mimeType }, viewerDefinition }) =>
Might be possible here to utilise `flow`:

```suggestion
export const buildLightboxEntries = (
  attachmentsAndViewerDefinitions: AttachmentAndViewerDefinition[]
): LightboxEntry[] =
  flow(
    A.map(({ attachment: { id, description, mimeType }, viewerDefinition }) =>
```

2021-07-08 07:13 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> + * Build Lightbox entries based on a list of attachments and viewer definitions
Might be value in mentioning that it drops any non-lightbox entries.

2021-07-08 07:13 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> +                }
This section has some readability issues. Would it be possible to create a builder function for each of the two object types? Then maybe you'd have something like:

```typescript
viewer === "lightbox"
  ? buildLightboxViewerConfig(attachment, viewer, viewUrl, lightboxEntries, initialLightboxEntryIndex)
  : buildBasicViewerConfig(attachment, viewer, viewUrl)

2021-07-09 00:47 UTC, PenghaiZhang commented on react-front-end/tsrc/components/ItemAttachmentLink.tsx
> +
We also added one more function `pfTernaryTypeGuard`  to fit where the ternary is used as a type guard .

2021-07-09 01:34 UTC, PenghaiZhang commented on react-front-end/tsrc/modules/ViewerModule.ts
> +                }
Can do this. But the type of viewer will be `lightbox` and `link` in each function rather than `Viewer`.

2021-07-09 05:56 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/modules/ViewerModule.test.ts
> +    },
As discusses, they where copied from some other mock data.

2021-07-09 06:02 UTC, PenghaiZhang commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  return A.isEmpty(lefts) ? E.right(rights) : E.left(lefts);
How about this ? 

```
pipe(either, A.separate, ({ left, right }) =>
    pipe(
      left,
      A.isEmpty,
      B.match(
        () => E.left(left),
        () => E.right(right)
      )
    )
  )
```

2021-07-09 06:05 UTC, PenghaiZhang commented on react-front-end/tsrc/modules/ViewerModule.ts
> +      attachments.map(async (originalAttachment) => {
Refactored by `partitionMapWithIndex`.

2021-07-12 04:37 UTC, edalex-ian approved these changes
Just a few minor considerations, then go for merge when happy.

A lot of efforts here @PenghaiZhang . Thanks for sticking with it! :+1:

2021-07-12 04:37 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> +        )
Is that the same as:

```typescript
flow(
  TE.tryCatchK(getViewerDetails, String),
  TE.map(...)
)
```

I'm not sure, but seems almost like it...

2021-07-12 04:37 UTC, edalex-ian commented on react-front-end/tsrc/util/pointfree.ts
> +    predicate: (a: A | B) => a is A,
```suggestion
    guard: (a: A | B) => a is A,
```

2021-07-12 04:37 UTC, edalex-ian commented on react-front-end/tsrc/modules/ViewerModule.ts
> +  A.map((entry) => entry.value)
I thought I wrote this comment already, but I can't find it. So if you get this twice...

Would this be more idiomatic as:

```suggestion
  A.map(O.getOrElse(absurd))
```

Requires:

```typescript
import {absurd} from "fp-ts/function";
```

2021-07-12 07:12 UTC, edalex-ian approved these changes

2021-07-12 22:59 UTC, merged