feat: save wild card mode in local storage
openequella/openEQUELLA pull request #3157
Opened 2021-07-01 03:17 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds the feature of saving wild card mode in browser local storage.

![Screenshot from 2021-07-01 13-13-14](https://user-images.githubusercontent.com/47203811/124059624-ba318f80-da6e-11eb-85ed-b038e9c0149d.png)

2021-07-01 03:47 UTC, SammyIsConfused reviewed
Looks good Penghai!
Could be worth adding this to some tests, and I'm unsure whether or not we need to handle potential errors thrown by the JSON functions.

2021-07-01 03:47 UTC, SammyIsConfused commented on react-front-end/tsrc/util/BrowserStorageUtil.ts
> +  localStorage.setItem(key, JSON.stringify(value));
JSON.stringify can throw a TypeError on a couple circumstances - 
    Throws a TypeError ("cyclic object value") exception when a circular reference is found.
    Throws a TypeError ("BigInt value can't be serialized in JSON") when trying to stringify a BigInt value.
Since value isn't constrained to type, this function could cause that error to be thrown if value was a BigInt. 
Note - I'm not necessarily saying we need to handle that, just that it could potentially throw an error here.

2021-07-01 03:47 UTC, SammyIsConfused commented on react-front-end/tsrc/util/BrowserStorageUtil.ts
> +  return value ? JSON.parse(value) : undefined;
JSON.parse can throw a SyntaxError if the value is not in an expected format.

2021-07-01 05:25 UTC, PenghaiZhang commented
> Looks good Penghai!
> Could be worth adding this to some tests, and I'm unsure whether or not we need to handle potential errors thrown by the JSON functions.

Thanks Sam! I have added tests.

2021-07-01 05:51 UTC, SammyIsConfused approved these changes
Looks great Penghai! Thanks for clearing those up. Just a couple suggestions, but you should be mostly good to go.

2021-07-01 05:51 UTC, SammyIsConfused commented on react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
> +  it("saves wildcard mode in local storage", async () => {
```suggestion
describe("Wildcard mode persistence", () => {
  it("saves wildcard mode value in local browser storage", async () => {
```

2021-07-01 05:51 UTC, SammyIsConfused commented on react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
> +  it("retrieves wildcard mode from local storage", async () => {
```suggestion
  it("retrieves wildcard mode value from local storage", async () => {
```

2021-07-01 05:51 UTC, SammyIsConfused commented on react-front-end/tsrc/search/SearchPage.tsx
> +      console.error(
I like that we are catching these and logging them out - nice work.

2021-07-01 05:51 UTC, SammyIsConfused commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +export const WILD_CARD_MODE = `wildcardMode_${AppConfig.baseUrl}`;
wildcard is one word, needs no underscore. Also - it might be worth having a better identifier as just calling it WILDCARD_MODE is somewhat ambiguous. WILDCARD_MODE_STORAGE_KEY or something along those lines.

2021-07-01 07:10 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/search/SearchPage.test.tsx
> +  it("saves wildcard mode in local storage", async () => {
We might have more data that need to be saved in local storage, but I am happy to rename the describe block. `local storage` is a term so I guess it should be `brower  local storage` ?

2021-07-01 07:11 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPage.tsx
> +      console.error(
Yeah I think this error should not stop users from using the new search UI. An console error should be enough.

2021-07-01 14:34 UTC, ChristianMurphy approved these changes

2021-07-01 14:34 UTC, ChristianMurphy commented on react-front-end/tsrc/search/SearchPage.tsx
> +        return JSON.parse(wildcard);
Would it make sense to use runtypes or typescript-is here to assert that the parsed value is a boolean? :thinking: 
`JSON.parse` can return a lot of possible values.

2021-07-01 23:31 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPage.tsx
> +        return JSON.parse(wildcard);
Good idea! I use runtypes to do this.

2021-07-05 00:26 UTC, SammyIsConfused approved these changes

2021-07-07 01:29 UTC, edalex-ian requested changes
Thanks @PenghaiZhang , this is an interesting one as we continue to add feature on top of feature for the SearchPage.

Main comment on the code you'll see is around changing the logic of when and at what point to store, read and use the value in LocalStorage.

My second main feedback is around the `BrowserStorageUtil.ts` file. Best to place that here I guess as it's at the file level.

**`BrowserStorageUtil.ts`**

I like the idea of abstracting out this storage, but as it stands this file only seems to offer that it's closed over `window.localStorage`. Could I suggest that we expand this further - which possibly then also pushes it more so to `BrowserStorageModule.ts`.

* Have it handle the prefixing of keys with an institution specific identifier;
* Remove all the logic and try/catch logic for reading and storing the values from `SearchPage.tsx` and encapsulate it here in one place
* Consider making the functions object aware - don't just return a string and receive a string
  * In doing so, maybe then the validation of the read in data shapes can be centralised here too
* Have these functions do the serialisation and deserialisation - and hey, why not play with some more fp-ts via the [`Json.ts` Module](https://gcanti.github.io/fp-ts/modules/Json.ts.html) which can then feed into the above point about error handling etc.

2021-07-07 01:29 UTC, edalex-ian commented on react-front-end/tsrc/util/langstrings.ts
> +    },
I'm inclined to say we don't need language strings for console messages. :thinking: Console messages are more so targetted at debugging issues - possibly via support - not for end-user consumption.

2021-07-07 01:29 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +    return !searchPageOptions.rawMode;
hmmm. :thinking: 

hmmmmmmm... :thinking: 

This oddity caught my attention. We have potential for a mismatch here of what we're displaying in the search results vs what the toggle is displaying. I'm thinking maybe the logic should more so be:

* Wildcard toggle display state is _only_ based on `searchPageOptions` - as that is kept in sync with the search results (due to the reducer)
* We should indeed store the value of `rawMode` on each change, but it should use the same sequencing of how we store the SearchPageOptions into history. (i.e. do it as part of the `state.status === "searching"` effect just after we do the `history.replace`)
* Reading the persisted value should then be part of the process of setting the initial state of `SearchPageOptions`. It's kind of interesting how that is currently done, it should probably be within the `state.status === "initialising"` effect and I'd suggest that's where this initial read is done. To do so may require 'fixing' that setting of it the initial value of `SearchPageOptions` so that it is in the effect and then if there is nothing in 'history' but there is a value in LocalStorage then it's combined with the `defaultSearchPageHistory.searchPageOptions`, otherwise just use plain old `defaultSearchPageHistory.searchPageOptions`.

2021-07-07 01:29 UTC, edalex-ian commented on react-front-end/tsrc/util/BrowserStorageUtil.ts
> + * @param key Key of the data.
```suggestion
 *
 * @param key Key of the data.
```

2021-07-07 01:29 UTC, edalex-ian commented on react-front-end/tsrc/util/BrowserStorageUtil.ts
> +export const getDataFromLocalStorage = (key: string): string | null =>
Feels more idiomatic to go with:

```suggestion
export const readFromLocalStorage = (key: string): string | null =>
```

2021-07-07 01:29 UTC, edalex-ian commented on react-front-end/tsrc/util/BrowserStorageUtil.ts
> +export const setDataToLocalStorage = (key: string, value: string) =>
Feels more idiomatic to go with:

```suggestion
export const saveToLocalStorage = (key: string, value: string) =>
```

2021-07-07 01:29 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +export const WILDCARD_MODE_STORAGE_KEY = `wildcardMode_${AppConfig.baseUrl}`;
I think it could be useful to flip these around such as:

```suggestion
export const WILDCARD_MODE_STORAGE_KEY = `${AppConfig.baseUrl}_wildcardMode`;
```

That way if have more, then we can easily delete for an institution. But, not to phased. :shrug:

2021-07-09 00:46 UTC, edalex-ian requested changes
That's looking really tidy and well structured @PenghaiZhang .

Just a few minor tweaks remain and then should be good to go.

2021-07-09 00:46 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/modules/BrowserStorageModule.test.ts
> +    expect(readDataFromLocalStorage("test", booleanValidator)).toBe(true);
```suggestion
    expect(readDataFromLocalStorage(KEY, booleanValidator)).toBe(true);
```

2021-07-09 00:46 UTC, edalex-ian commented on react-front-end/tsrc/modules/BrowserStorageModule.ts
> + * no data is found.
```suggestion
 * no data is found, cannot be parsed or fails validation.
```

2021-07-09 00:46 UTC, edalex-ian commented on react-front-end/tsrc/modules/BrowserStorageModule.ts
> +      flow(
I think the idomatic way to do the interop is to use the provided interop function `toUndefined`. In which case your pipe would more so be:

```typescript
pipe(
  localStorage.getItem(...),
  O.fromNullable,
  O.map(
    flow(
      ...
    )
  ),
  O.toUndefined
);
```

2021-07-09 00:46 UTC, edalex-ian commented on react-front-end/tsrc/modules/BrowserStorageModule.ts
> +        E.getOrElseW(() => undefined)
With the above suggestion, perhaps this line should just be:

```suggestion
        O.fromEither)
```

Mind you, in doing that, you'd then want to use `O.chain` rather than `O.map`.

But at least with these two comments we only go back to the wild west of `undefined` and `null` when we exit the functional area.

2021-07-09 00:46 UTC, edalex-ian commented on react-front-end/tsrc/modules/BrowserStorageModule.ts
> +export const saveDataToLocalStorage = (key: string, value: unknown) =>
Please add an explicit return type.

(I should find the ESLint rule used over in the kaltura module to check for this and enable it on this repo. :thinking: )

2021-07-09 00:46 UTC, edalex-ian commented on react-front-end/tsrc/modules/BrowserStorageModule.ts
> + * @param key Key of the data.
```suggestion

 * @param key Key of the data.
```

2021-07-09 00:46 UTC, edalex-ian commented on react-front-end/tsrc/modules/BrowserStorageModule.ts
> +export const clearDataFromLocalStorage = (key: string) =>
Explicit return type please.

It's good to make sure we have explicit types on exported / public functions.

2021-07-09 00:46 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +            saveDataToLocalStorage(RAW_MODE_STORAGE_KEY, state.options.rawMode);
Like you've done for `getRawModeFromStorage`, this should probably be encapsulated in a `writeRawModeToStorage`.

2021-07-09 00:46 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +      rawMode: searchPageOptions.rawMode,
I think this warrants a comment:

```suggestion
      // As per requirements for persistence of rawMode, it is _not_ reset for New Searches
      rawMode: searchPageOptions.rawMode,
```

2021-07-09 00:46 UTC, edalex-ian commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +          clearDataFromLocalStorage(RAW_MODE_STORAGE_KEY);
Maybe encapsulate this in `SearchPageHelper` as `deleteRawModeFromStorage()`.

2021-07-09 06:21 UTC, PenghaiZhang commented on react-front-end/tsrc/modules/BrowserStorageModule.ts
> +      flow(
Ah ha I forgot `O.toUndefined`. Thanks !

2021-07-09 06:26 UTC, PenghaiZhang commented on react-front-end/tsrc/modules/BrowserStorageModule.ts
> +export const clearDataFromLocalStorage = (key: string) =>
Sure :smile:   Perhaps I thought the type is void so ...

2021-07-12 04:46 UTC, edalex-ian approved these changes
Very tidy and robust @PenghaiZhang . Great work! :+1: :tada:

2021-07-12 06:10 UTC, merged