Feature/add Item DRM settings to search2 API
openequella/openEQUELLA pull request #3159
Opened 2021-07-02 05:12 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds one optional field to case class `SearchResultItem` for Item DRM settings. Only when the Item is protected by DRM and the DRM has not been accepted yet, the DRM settings are included. 

In terms of what specific DRM settings are include, I looked into `terms.ftl` and add whatever this template may render to the new field. Due to my limited experience of DRM, there may be more DRM settings we need to include. 

https://user-images.githubusercontent.com/47203811/124223575-5038e900-db47-11eb-926c-5457d492f37c.mp4

2021-07-05 01:02 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
> +    val item = LegacyGuice.itemService.getUnsecure(itemKey)
There are a few methods we can call to get an Item by its item key: 
1. `getUnsecure`
2. `getUnsecureIfExists`
3. `getItemPack` chained with `getItem`.

The reason I chose the first one is because this method can throw an `ItemNotFoundException` and it is widely used in where Old UI handles DRM (e.g. `DRMContentFilter.java`).

The second method works, too. But we probably need to manually throw an exception. The third method requires ACL `VIEW_ITEM` which is not what we want here.

2021-07-06 00:16 UTC, SammyIsConfused reviewed
Thanks Penghai! Would be nice to have some tests too - apart from that I have some queries and a couple tweak suggestions :+1:

2021-07-06 00:16 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
> +    val item = LegacyGuice.itemService.getUnsecure(itemKey)
What happens if this error is thrown? Will it prevent the search? 
If this happens then you should still be able to use the new search.

2021-07-06 00:16 UTC, SammyIsConfused commented on oeq-ts-rest-api/src/Search.ts
> +   * Actions that users are allowed to do for the Item.
```suggestion
   * Actions that users are allowed to perform on the Item.
```

2021-07-06 00:16 UTC, SammyIsConfused commented on oeq-ts-rest-api/src/Search.ts
> +   * Additional actions that users are allowed to do.
```suggestion
   * Additional actions that users are allowed to perform.
```

2021-07-06 00:16 UTC, SammyIsConfused commented on oeq-ts-rest-api/src/Search.ts
> +   * Server-side language string describing this item is strictly restricted to the educational sector.
Not sure I understand this comment - how does `educationSector` work?

2021-07-06 00:16 UTC, SammyIsConfused commented on oeq-ts-rest-api/src/Search.ts
> +  parties?: {
I'm just trying to wrap my head around this - `parties` here refers to relevant people/groups that provide DRM for content?

2021-07-06 00:16 UTC, SammyIsConfused commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResultItem.scala
> +    val permission1 = Option(drmI18n.getPermissions1List) match {
I'm guessing this is how it is named elsewhere too - would just be good if it wasn't called `permission1` and `permission2` as it gives no indication as to what the difference is between the two. But this is a very common problem in openEQUELLA DB Land, so I think it's fine.

2021-07-07 00:39 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
> +    val item = LegacyGuice.itemService.getUnsecure(itemKey)
Yes, this 404 error will prevent the search. This usually indicates data is corrupted. Shouldn't we show the error ?

2021-07-07 00:42 UTC, PenghaiZhang commented on oeq-ts-rest-api/src/Search.ts
> +   * Server-side language string describing this item is strictly restricted to the educational sector.
`educationSector` is just a server side language string - `Use of this item is strictly restricted to the educational sector`

Whether it's included depends on the DRM configuration.

2021-07-07 00:43 UTC, PenghaiZhang commented on oeq-ts-rest-api/src/Search.ts
> +  parties?: {
Honestly, I am not entirely sure. This field is named as `parties` on server so I simply reuse this name.

2021-07-07 00:45 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResultItem.scala
> +    val permission1 = Option(drmI18n.getPermissions1List) match {
Yes, you can see this one as well as `parties` from class `I18nDRM`.

2021-07-07 05:32 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/SearchHelper.scala
> +    val item = LegacyGuice.itemService.getUnsecure(itemKey)
If we want to keep new search working despite this error,  I can change the code to

```scala
    Option(LegacyGuice.itemService.getUnsecureIfExists(itemKey))
      .flatMap(item => Option(LegacyGuice.drmService.requiresAcceptance(item, false, false)))
      .map(drm => SearchResultItemDrm(drm))
```

2021-07-07 07:09 UTC, PenghaiZhang commented
As discussed, we need to change the data structure to 
```
DrmStatus: {
termAccepted: boolean;
isAuthrosed: boolean;
}
```


So please do not review until I push new changes.

2021-07-08 23:37 UTC, PenghaiZhang commented
![image](https://user-images.githubusercontent.com/47203811/125002877-48be9600-e099-11eb-89bd-2224b828871b.png)

2021-07-08 23:38 UTC, PenghaiZhang commented
OK. It's ready for review now.

2021-07-09 01:34 UTC, edalex-ian requested changes
Looks good @PenghaiZhang , just need to change the singluar `term` to the plural `terms` everywhere. And then some comment tweaks. :wink:

2021-07-09 01:34 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResultItem.scala
> +case class DrmStatus(termAccepted: Boolean, isAuthorised: Boolean)
I've noticed a few places above the singular `term` has been used rather than `terms`. I think it should be the plural. Maybe start here with:

```suggestion
case class DrmStatus(termsAccepted: Boolean, isAuthorised: Boolean)
```

And then address all other places.

2021-07-09 01:34 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchResultItem.scala
> +  * @param drmStatus Status of Item's DRM, consisting if terms accepted and if authorised
```suggestion
  * @param drmStatus Status of Item's DRM, consisting if terms accepted and if authorised, absent if item not DRM controlled.
```

2021-07-09 01:34 UTC, edalex-ian commented on oeq-ts-rest-api/src/Search.ts
> +   * Item's DRM Status.
```suggestion
   * Item's DRM Status. Absent if item is not under DRM control.
```

2021-07-12 04:49 UTC, edalex-ian approved these changes
GTG! :+1:

2021-07-12 05:16 UTC, merged