Feature/DRM rest endpoints
openequella/openEQUELLA pull request #3194
Opened 2021-07-12 05:35 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds two REST endpoints for DRM - one for listing terms and the other one for accepting terms.

![Screenshot from 2021-07-12 15-21-20](https://user-images.githubusercontent.com/47203811/125236079-baf7da80-e326-11eb-880a-563de5502c41.png)
![Screenshot from 2021-07-12 15-21-45](https://user-images.githubusercontent.com/47203811/125236080-bc290780-e326-11eb-9df4-e593e699fe5e.png)
![Screenshot from 2021-07-12 15-22-50](https://user-images.githubusercontent.com/47203811/125236083-bcc19e00-e326-11eb-877f-75ac97d454ae.png)
![Screenshot from 2021-07-12 15-23-12](https://user-images.githubusercontent.com/47203811/125236084-bd5a3480-e326-11eb-9ee9-615bee7432f7.png)
![Screenshot from 2021-07-12 15-23-29](https://user-images.githubusercontent.com/47203811/125236085-bdf2cb00-e326-11eb-88ae-0870bc0e002f.png)
![Screenshot from 2021-07-12 15-24-04](https://user-images.githubusercontent.com/47203811/125236087-be8b6180-e326-11eb-8545-46f0652b3881.png)

2021-07-12 06:57 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/drm/DrmResource.scala
> +      Response.ok().entity(drmService.acceptLicenseOrThrow(item)).build()
I guess it is enough to just return the ID of new `DrmAcceptance` instance ?

2021-07-13 01:06 UTC, PenghaiZhang commented
I have updated a new screenshot for the listing endpoint.

![image](https://user-images.githubusercontent.com/47203811/125374452-6312af80-e3ca-11eb-8f9c-bf57ede30917.png)

2021-07-13 04:15 UTC, edalex-ian requested changes
The content of this PR is good, but a few key considerations:

1. Lots of missing Java/ScalaDoc;
2. Missing API documentation - especially at the verb level;
3. This should probably be an endpoint under `/item/{uuid}/{version}/drm`. It doesn't have to be nestled into the 'Item' API though, it could possibly still be stand-alone and be 'Item DRM' just like there's 'Item Actions'.
4. I note in the Swagger API docs there's already mention of a number of DRM related models/beans - such as DRMOptions. Did you consider using some of them?
5. The one small code mentioned to refactor `acceptDRM` to aim for more functional code.

2021-07-13 04:15 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/drm/DrmResource.scala
> +  def getDRMTerms(@ApiParam("Item UUID") @PathParam("uuid") uuid: String,
```suggestion
  def getDrmTerms(@ApiParam("Item UUID") @PathParam("uuid") uuid: String,
```

2021-07-13 04:15 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/drm/DrmResource.scala
> +  def acceptDRM(@ApiParam("Item UUID") @PathParam("uuid") uuid: String,
```suggestion
  def acceptDrm(@ApiParam("Item UUID") @PathParam("uuid") uuid: String,
```

2021-07-13 04:15 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/drm/DrmResource.scala
> +    }
The rather repetitive catch block caught my eye, and it got me thinking, "could we use scala's FP capabilities to improve this?"

So how about something roughly like follows.

First, for the class define a HOF to map the exceptions:

```scala
def mapException(e: Exception) => (errors: String*): Response => e match {
  case BadRequestException => badRequest
  case AccessDeniedException => forbiddenRequest
  case DRMException => unauthorizedRequest
  case ItemNotFoundException => resourceNotFound
}
```

(If order not important though, please sort those - I just copied your order.)

```scala
allCatch.withTry {
  (LegacyGuice.itemService.getUnsecure andThen drmService.acceptLicenseOrThrow)(ItemId(uuid, version))
} match {
  case Failure(e) => mapException(e)(e.getMessage)
  case Success(item) => Response.ok().entity(item).build()
}
```

And if needed, you could replace `allCatch` with a custom catcher to just limit to those exceptions in `mapException`. See more @ https://www.baeldung.com/scala/exception-handling

Also, doing this, you can then use the same exception handling in the other DRM endpoints for consistent error handling.

(There's a few bits that could be further improved here - it'd be great to thread the value through, and repeated references to`e` in the `Failure(e)` clause - and there might be some syntax issues as I just roughed it up. But hopefully you can see what I'm aiming for.)

2021-07-14 02:17 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/drm/DrmResource.scala
> +    }
Thanks Ian for this suggestion!! I have use `Try` together with some function compositions to improve !

2021-07-14 06:41 UTC, edalex-ian approved these changes
Good stuff @PenghaiZhang :+1: :tada:

2021-07-14 23:13 UTC, merged