Feature/drm acceptance dialog
openequella/openEQUELLA pull request #3214
Opened 2021-07-19 05:05 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds a new dialog for DRM term acceptance. The dialog has three states. While the dialog is waiting for terms, it shows a skeleton dialog. And then, depending on the result, it shows a dialog listing all terms or an error dialog describing why failed.

https://user-images.githubusercontent.com/47203811/126105779-1ad8d6eb-4ea7-4250-8530-9a9ef861364e.mp4

2021-07-19 23:22 UTC, ChristianMurphy reviewed
Thanks @PenghaiZhang!

2021-07-19 23:22 UTC, ChristianMurphy commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +            <Typography>{`${term}`}</Typography>
could `term` be rendered directly?

```suggestion
            <Typography>{term}</Typography>
```

2021-07-19 23:22 UTC, ChristianMurphy commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +    : [resolveUrl(`${LEGACY_CSS_URL}`)];
```suggestion
    : [resolveUrl(LEGACY_CSS_URL)];
```

2021-07-20 00:01 UTC, PenghaiZhang commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +            <Typography>{`${term}`}</Typography>
Yeah definitely!

2021-07-20 02:34 UTC, edalex-ian requested changes
Great work @PenghaiZhang . This is nice and compact and deliberate. :+1: 

Few requests:

- Stick with the pattern of splitting out reducers to their own file - aiding testing and minimising file sizes;
- Consider the suggestion around the use of pfTernaryTypeGuard; and
- Other minor suggestions.

2021-07-20 02:34 UTC, edalex-ian commented on react-front-end/__stories__/drm/DrmAcceptanceDialog.stories.tsx
> +
Our convention seems to be to not have a blank line here. Perhaps we should remove this one and the one below. :thinking:

2021-07-20 02:34 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/components/DrmAcceptanceDialog.test.tsx
> +          selector: "h2",
Here and below where we're using a selector (`h2` / `p2`) is that necessary?

I ask because it violates the philosophy of testing-library where we ideally test on what the user sees.

In this case it feels like as long as the text is shown on the screen in a dialog, we should be happy. So no need to narrow to element type.

And if in the future MUI changes the structure of elements, currently these tests would break.

2021-07-20 02:34 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +   * Function fired to retrieve DRM terms from server.
```suggestion
   * Function to retrieve DRM terms from server.
```

2021-07-20 02:34 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +   * Function fired when the Accept button is clicked.
```suggestion
   * Function fired when the Accept button is clicked. Typically to do an accept API call to the server.
```

2021-07-20 02:34 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +   * Function fired when accepting terms is successful.
So this is after `onAccept` is successful? (If so, this comment should mention that.)

2021-07-20 02:34 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +      </li>
Why this structure of a `<Grid>` in an `<li>`? (Same pattern is used above in `NonStandardDrmTerms`, but this is a more concise example so I comment here.)

2021-07-20 02:34 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +  );
Hmmm, I wonder:

```suggestion
  const customTermDetails = pipe(
    customTerms,
    A.filterMap(flow(
      O.fromNullable,
      O.map(({ title, terms }) => (
        <NonStandardDrmTerms title={title} terms={terms.split("\n")} />
      )
    )
  );
```

And then with that you can really see (in the absence of all the type definitions) that you could have one function to do all that, and possibly just two calls along the lines of:

```typescript
const partyDetails = buildNonStandardDrmTerms(
  customTerms, 
  ({ title, partyList }) => (
    <NonStandardDrmTerms title={title} terms={partyList} />
  ));
const customTermDetails = buildNonStandardDrmTerms(
  customTerms, 
  ({ title, terms }) => (
    <NonStandardDrmTerms title={title} terms={terms.split("\n")} />
  ));
```

And really, then if you just worried about the data mapping (code to support not listed here), you could end up with:

```typescript
const partyDetails = buildNonStandardDrmTerms(
  parties, 
  ({ title, partyList: terms }) => ({title, terms}));
const customTermDetails = buildNonStandardDrmTerms(
  customTerms, 
  ({ title, terms }) => ({title, terms: terms.split("\n")}));
```

Something to ponder. :wink:

2021-07-20 02:34 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +const SkeletonDialogProps = {
Seeing this just a variable - not a type - should have a lowercase first letter. Also, maybe a slightly different name like `skeletonDialogStructure`, or `skeletonDialogDefinition`, or maybe just `skeletonDialog`.

2021-07-20 02:34 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +const reducer = (state: State, action: Action): State => {
Great reducer here @PenghaiZhang :+1: 

Could you please move the `reducer` and `State` and `Action` into `drm/DrmAcceptanceDialogReducer.tsx`. You'll also then need to slightly restructure some of the collaborators so that you don't end up with a circular dependency between `DrmAcceptanceDialogReducer` and `DrmAcceptanceDialog`.

2021-07-20 02:34 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +        result,
Are you able to just do:

```suggestion
      pipe(
        await runInTask(onAccept),
```

Or did you break it out for readability? (I note the same done further down.)

2021-07-20 03:22 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/search/components/DrmAcceptanceDialog.test.tsx
> +          selector: "h2",
No they are not necessary. I guess my thinking was to limit the search scope.

2021-07-20 03:23 UTC, PenghaiZhang commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +   * Function fired when accepting terms is successful.
Yes it's. I will add more comments.

2021-07-20 03:27 UTC, PenghaiZhang commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +      </li>
Ah I will remove the grid.

2021-07-20 03:58 UTC, PenghaiZhang commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +        result,
I was not sure if we can do a `await` in a pipe. Now, I think we can for the first input but maybe can't in the mid of pipe.

2021-07-20 04:10 UTC, PenghaiZhang commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +  );
Why use `A.filterMap`  may I ask ? `customTerms` is not an array.

Actuall, I can do this: 
```
  const customTermDetailss = pipe(
    customTerms,
    O.fromNullable,
    O.map(({ title, terms }) => <NonStandardDrmTerms title={title} terms={terms.split("\n")} />),
    O.toUndefined
    );
```

2021-07-20 04:23 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +  );
Ah, I miss-read it. I guess that was kind of the point, in this case there was a lot going on so the logic got lost on first pass.

So yes, your suggestion is good and you should easily make that a shared function like buildNonStandardDrmTerms mentioned above.

2021-07-20 04:51 UTC, PenghaiZhang commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +const reducer = (state: State, action: Action): State => {
Good idea! I have also moved the two child components to one `tsx` file.

2021-07-20 04:53 UTC, PenghaiZhang commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +  );
Not so easy :sweat_smile: . I am not sure how to dynamically destructure the object.

2021-07-20 05:24 UTC, PenghaiZhang commented on react-front-end/tsrc/drm/DrmAcceptanceDialog.tsx
> +  );
With a `transformer` it becomes much easier.

2021-07-20 16:51 UTC, ChristianMurphy approved these changes
Thanks @PenghaiZhang!

2021-07-21 00:49 UTC, edalex-ian approved these changes
Looks good! :+1: 

May want to add a bit more TSDoc, and then merge when ready. :wink:

2021-07-21 00:49 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmTerms.tsx
> +// Child component for displaying non-standard DRM term which usually has a title and a list of terms.
Now that it's an exported component, please add TSDoc.

2021-07-21 00:49 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmTerms.tsx
> +// Child component for displaying all DRM terms.
Now that it's an exported component, please add TSDoc.

2021-07-21 06:29 UTC, merged