Feature/integrate DRM Acceptance dialog with Item
openequella/openEQUELLA pull request #3219
Opened 2021-07-23 05:10 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds the support of showing DRM Acceptance dialog when users attempt to view an Item. On standard list mode, the dialog pops up when an Item link is clicked,  and on gallery mode the dialog pops up when an Info icon is clicked. 

Once the terms are accepted, Item Summary page will be opened by different approaches, depending on whether in Selection Session or not.

https://user-images.githubusercontent.com/47203811/126739698-8e628e1c-e74c-48ff-b687-0971b440d790.mp4

2021-07-26 05:03 UTC, PenghaiZhang commented on react-front-end/tsrc/components/OEQItemSummaryPageButton.tsx
> +  const onClick = pipe(
I am thinking if I should move this `onClick` to `GallerySearchItemTiles` for two reasons:
1. maybe this component should not concern the logic of DRM.
2. better support next feature - show dialog to list why unauthorised.

2021-07-26 05:17 UTC, PenghaiZhang commented on react-front-end/tsrc/components/OEQItemSummaryPageButton.tsx
> +  const onClick = pipe(
Perhaps it should still stay here as how to open the summary page is what this component controls.

2021-07-26 07:19 UTC, edalex-ian requested changes
Wowsers, this DRM late addition is getting twisty and turny. Good work trying to wrangle it!

Key things for this PR:

1. There's some duplicated logic that should perhaps be pushed into its own function;
2. The new DRM context is missing documentation of the props, and could do with some better abstraction of naming for the `setOnDrmAcceptCallback` prop (see * below); and
3. In independent components like `OEQItemSummaryPageButton` we want to maintain orthogonality by keeping the props specific to themselves - so again the naming and typing of the `setOnDrmAcceptCallback` prop should be reworked.

\* We discussed possibly also using `showDrmAcceptDialog: (onAccept: () => void) => void` for that.

P.S. I like the way you reworked the mocked data and tests, made for a great improvement for readability and a clear definition of what is being tested. :+1:

2021-07-26 07:19 UTC, edalex-ian commented on react-front-end/tsrc/components/OEQItemSummaryPageButton.tsx
> +      setOnDrmAcceptCallback: (_: (() => void) | undefined) => void;
This should probably be simplified to just:

```suggestion
      setOnDrmAcceptCallback?: () => void;
```

That's based on my understand that the only reason for this complexity is due to how it is used elsewhere - i.e. the storage of a function in state. But that should be abstracted away at this point.

2021-07-26 07:19 UTC, edalex-ian commented on react-front-end/tsrc/search/components/SearchResult.tsx
> +        (url) => ({
```suggestion
        // Selection session values
        (url) => ({
```

2021-07-26 07:19 UTC, edalex-ian commented on react-front-end/tsrc/search/components/SearchResult.tsx
> +        (url) => ({
```suggestion
        // Normal page values
        (url) => ({
```

2021-07-26 07:19 UTC, edalex-ian commented on react-front-end/tsrc/search/components/SearchResult.tsx
> +        muiLinkUrlProvider={() => url}
So is having two of these now redundant? Can there just be one prop?

2021-07-26 07:19 UTC, edalex-ian commented on react-front-end/tsrc/components/OEQItemSummaryPageButton.tsx
> +  };
It feels like this is duplicated logic from further down. It'd be good to capture that logic in a single function that'd have a signature like:

```typescript
const openSummaryPage: () => (uuid: string, version:number): void
```

2021-07-26 07:19 UTC, edalex-ian commented on react-front-end/tsrc/components/OEQItemSummaryPageButton.tsx
> +      setOnDrmAcceptCallback: (_: (() => void) | undefined) => void;
Ahhhhh! Alright, following our discussion it looks like if we changed this like:

```suggestion
      showDrmAcceptDialog: (onAccept: () => void) => void;
```

That'd better reflect the usage in this component, and abstract it away from what it's doing elsewhere. Plus the naming and typing would greatly aid readability.

2021-07-26 07:32 UTC, edalex-ian commented on react-front-end/tsrc/components/OEQItemSummaryPageButton.tsx
> +  const onClick = pipe(
I think this is fine, but my main observation is that there may be some shared logic forming around the place just written in different ways. So we have to wonder if there's a need for a DRMHelper (or perhaps it fits the DRMModule - but it's very presentation layer centric) and a function that'd wrap this such as:

```typescript
export const onClickWithDrm = (
  drm?:  OEQ.Search.DrmStatus,
  showDrmDialog: (onAccept: () => void) => void,
  onAccept: () => void
): (() => void) => flow(
  drm,
  O.fromNullable,
  ...
);
```

Or something like that...

2021-07-28 00:40 UTC, PenghaiZhang commented on react-front-end/tsrc/search/components/SearchResult.tsx
> +        muiLinkUrlProvider={() => url}
Hmmm, maybe no for now. The reason is we still these two to differentiate URLs of remote searches and advanced searches. They are in component `AuxiliarySearchSelector`.

2021-07-28 01:02 UTC, PenghaiZhang commented
The last three commits made significant changes, particularly on

1. How to do DRM check - now the check is centralised in `DrmHelper` which is consumed by `SearchResult` and `GallerySearchItemTiles` .

2. How to build URL and handler for Item Summary page. There were mixed approaches to do this, but now they are centralised in `SearchPageHelper`.

2021-07-28 03:10 UTC, edalex-ian commented on react-front-end/tsrc/search/components/SearchResult.tsx
> +        muiLinkUrlProvider={() => url}
No probs, as long as you're sure. :grin:

2021-07-28 04:22 UTC, edalex-ian approved these changes
Great job @PenghaiZhang ! This was a curly one, but I think you've told it who's the boss. Well done. :tada: 

A few suggestions around naming and comments, plus one about whether to wrap the logic for the creation of the DRM dialog.

But all minor stuff, so feel free to address as you see fit and then merge on. :+1:

2021-07-28 04:22 UTC, edalex-ian commented on react-front-end/tsrc/components/OEQItemSummaryPageButton.tsx
> +        }
```suggestion
        checkDrmPermission ? checkDrmPermission(onClick) : onClick();
```

2021-07-28 04:22 UTC, edalex-ian commented on react-front-end/tsrc/components/OEQLink.tsx
> +   * Function fired when the link is clicked.
Might want to include the reason for having this available.

Is it so that you can intercept calls before the browser navigates away?

2021-07-28 04:22 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmHelper.tsx
> + * this function checks DRM status and based on the result build different DRM dialogs.
```suggestion
 * this function checks DRM status and based on the result builds different DRM dialogs.
```

2021-07-28 04:22 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmHelper.tsx
> + * The handler will then be used by interacting with the dialog.
```suggestion
 * Depending on which dialog is triggered and which button the user clicks, the handler will then be called. Examples:
 * 1. The DRM check says the user needs to accept terms, then the accept terms dialog will be shown and if the user
 *    accepts, then the handler will be called;
 * 2. The DRM check says the user is _not_ authorised, then a dialog will be shown and after which the handler will
 *    never be called; (TODO: Coming soon.)
 * 3. DRM checks are all in order, no dialog is displayed and the handler is called immediately.
```

2021-07-28 04:22 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +export const builderOpenSummaryPageHandler = (
Although it's a 'builder' function, our convention is just to prefix with `build`.

```suggestion
export const buildOpenSummaryPageHandler = (
```

2021-07-28 04:22 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +) =>
Please specify return type - especially for exported function.

(I really need to turn on the ESLint rule for that. It was quite handy over in the Kaltura uploader.)

2021-07-28 04:22 UTC, edalex-ian commented on react-front-end/tsrc/search/components/GallerySearchItemTiles.tsx
> +      createDrmDialog(
It's a bit tricky how this function returns undefined if the handler is undefined. I think we need to add a comment here to say what's happening, or perhaps that logic shouldn't be hidden in the builder - as the comment you'll need to add would match the ternary expression you'd write. :thinking:

2021-07-28 04:22 UTC, edalex-ian commented on react-front-end/tsrc/search/components/SearchResult.tsx
> +    setDrmCheckOnSuccessHandler(() => onSuccess);
Good stuff @PenghaiZhang . Nice to keep this at this level. :+1:

2021-07-28 04:22 UTC, edalex-ian commented on react-front-end/tsrc/search/components/SearchResult.tsx
> +    // and Right is for normal page.
I think that comment's out of date now.

2021-07-28 04:47 UTC, PenghaiZhang commented on react-front-end/tsrc/components/OEQLink.tsx
> +   * Function fired when the link is clicked.
Yeah that's exactly why add this function. I will add the reason.

2021-07-28 04:51 UTC, PenghaiZhang commented on react-front-end/tsrc/drm/DrmHelper.tsx
> + * The handler will then be used by interacting with the dialog.
Wow many thanks Ian for such detailed explanations!! You are Mr DRM.

2021-07-28 04:53 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +export const builderOpenSummaryPageHandler = (
This must be because I have recently fought against builders :smile:

2021-07-28 04:55 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +) =>
Agreed.

2021-07-28 05:06 UTC, PenghaiZhang commented on react-front-end/tsrc/search/components/GallerySearchItemTiles.tsx
> +      createDrmDialog(
What about this ? 
```
// No dialog needed when the handler is undefined.
const dialog = drmCheckOnSuccessHandler ? createDrmDialog(...) : undefined;
setDrmDialog(dialog)

```

2021-07-28 05:07 UTC, PenghaiZhang commented on react-front-end/tsrc/search/components/GallerySearchItemTiles.tsx
> +      createDrmDialog(
Move the logic of whether a dialog is needed out from the helper and to here.

2021-07-28 09:30 UTC, merged