Feature/show DRM violations in dialog
openequella/openEQUELLA pull request #3240
Opened 2021-07-29 23:37 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds the support for listing DRM violations for unauthorised Items and attachments. The main change is to update the logic of DRM check in `DrmHelper`. This change results in function `createDrmDialog` becoming an async function, and therefore the `useEffect` which uses this function gets slightly changed as well. 

I tried to implement a custom hook `useAsyncEffect` but did not get it completed yet.

https://user-images.githubusercontent.com/47203811/127578666-fe879e2a-1ea5-4687-9571-f3371a170598.mp4

2021-07-29 23:40 UTC, PenghaiZhang commented on react-front-end/tsrc/drm/DrmHelper.tsx
> +const listDrmViolationsInTask = async (
This function was in the module but I moved it to the helper.

2021-07-30 00:51 UTC, edalex-ian requested changes
Nice @PenghaiZhang , this has come together rather cleanly.

Just a couple of minor requests, and we probably need to check the wording on the dialog with @cathfitz

2021-07-30 00:51 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/components/GallerySearchResult.test.tsx
> +      ["attachment", languageStrings.searchpage.gallerySearchResult.ariaLabel],
The `languageStrings` have been de-structured up the top, so:

```suggestion
      ["item", viewItem],
      ["attachment", ariaLabel],
```

That `ariaLabel` though keeps grabbing my attention. At somepoint we may want to refactor that with a more useful name - or maybe just in the de-structured context it loses meaning.

2021-07-30 00:51 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/components/GallerySearchResult.test.tsx
> +        });
There's a lot of boilerplate here. I wonder if we need a general (available for all tests) function like:

```typescript
const asyncClick = (element: Element, init?: MouseEventInit, {skipHover, clickCount}?: clickOptions): void =>
  act(async () => {
    await userEvent.click(element);
  });
```

And then we'd just be able to have:

```suggestion
        await asyncClick(getByLabelText(galleryEntryLabel));
```

I wonder too if `asyncClick` is the best name. Maybe `clickThenWait` as really this is all about clicking a button and then waiting for React to do it's state updates etc. Hmmm... :thinking:

2021-07-30 00:51 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/components/SearchResult.test.tsx
> +      ["attachment", "DRM Attachment"],
The string literals of `"DRM Item"` and `"DRM Attachment"` are now in three places and ideally should all be linking to the same thing. Perhaps over in the mock we need to set a constant, and then use that to tie them altogether.

2021-07-30 00:51 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmHelper.tsx
> +};
Does this need to be broken up, or can it just be:

```suggestion
): Promise<string> =>
  await pipe(
    TE.tryCatch<Error, OEQ.Drm.DrmViolation>(
      () => listDrmViolations(uuid, version),
      (error) => new Error(`${error}`)
    ),
    TE.map<OEQ.Drm.DrmViolation, string>(({ violation }) => violation)
    TE.getOrElse(
      (error) => `Failed to list DRM violations due to ${error.message}`
    )
  )();
```

Are are the issues with the async/await?

2021-07-30 00:51 UTC, edalex-ian commented on react-front-end/tsrc/drm/DrmHelper.tsx
> +  } else if (!isAuthorised) {
I wonder if we should more so go with a 'deny all' default for the sake of robustness. To demonstrate with pseudo code:

```
if isAuthorised
  if termsAccepted
    call handler
  else
    show DrmAcceptanceDialog
else
  show Violations dialog
```

2021-07-30 01:06 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/search/components/GallerySearchResult.test.tsx
> +      ["attachment", languageStrings.searchpage.gallerySearchResult.ariaLabel],
Perhaps rename to `viewAttachment` ?

2021-07-30 01:44 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/search/components/GallerySearchResult.test.tsx
> +        });
As discussed, we leave this for now and try to do it maybe in next tech debt.

2021-07-30 04:22 UTC, merged