Feature/only show authorised entries in Lightbox
openequella/openEQUELLA pull request #3242
Opened 2021-07-30 05:06 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR includes two parts. 
1. Only show gallery entries that have been accepted DRM terms and authorised.
2. Add the gallery entry that has just been accepted to the Lightbox entry list.

https://user-images.githubusercontent.com/47203811/127603321-e7dbe9e5-f2a4-46e0-bbe9-b0bff7267800.mp4

2021-07-30 06:09 UTC, edalex-ian requested changes
Mostly there @PenghaiZhang , just needs a few things tidied up to help with future maintenance me thinks. This are of generating items for the scrolling lightbox controlled with going across item boundaries and now DRM is getting rather dense.

2021-07-30 06:09 UTC, edalex-ian commented on react-front-end/tsrc/search/components/GallerySearchItemTiles.tsx
> +  entry: GalleryEntry
Need to be captured in the above TSDoc.

2021-07-30 06:09 UTC, edalex-ian commented on react-front-end/tsrc/search/components/GallerySearchItemTiles.tsx
> +      updateGalleryItemList({ ...item, drmStatus: defaultDrmStatus })(
Why is it setting `drmStatus` to the defaults?

From what I can gather after reading all (which other people wont be able to do as easily when working on the code) it is because we assume that a successful check means they have the default DRM status which is terms accepted and authorised.

We may want to note that.

One thing though, this is a bit different to before, because before there was no modification to the item. But the end of this all items will have 'drmStatus' even if they're not DRM items. Is that a good idea?

2021-07-30 06:09 UTC, edalex-ian commented on react-front-end/tsrc/search/components/GallerySearchResult.tsx
> +        // If no a DRM Item, keep it.
```suggestion
        // If not a DRM Item, keep it.
```

2021-07-30 06:09 UTC, edalex-ian commented on react-front-end/tsrc/search/components/GallerySearchResult.tsx
> +  const lightboxHandler = (
It's typical to have the functions declared before using - helps with readability. Any chance you could pop this up before `updateGalleryItemList`?

2021-07-30 06:09 UTC, edalex-ian commented on react-front-end/tsrc/search/components/GallerySearchResult.tsx
> +    );
I wonder whether it's worth adding a comment such as:

```suggestion
    // Update replace existing gallery item with newItem
    const newItems = galleryItems.map((i) =>
      i.uuid === newItem.uuid && i.version === newItem.version ? newItem : i
    );
```

Or, would it be better to just have a function like

```typescript
const updateGalleryItem = (item: GallerySearchResultItem): GallerySearchResultItem[] => {
  const updatedItems = galleryItems.map((i) =>
    i.uuid === newItem.uuid && i.version === newItem.version ? newItem : i
  );
  setGalleryItems(updatedItems);

  return updatedItems;
}
```

2021-08-02 00:31 UTC, PenghaiZhang commented on react-front-end/tsrc/search/components/GallerySearchItemTiles.tsx
> +      updateGalleryItemList({ ...item, drmStatus: defaultDrmStatus })(
I have slightly refactored this component so that items that have DRM status do not get updated here.

2021-08-02 00:48 UTC, PenghaiZhang commented on react-front-end/tsrc/search/components/GallerySearchResult.tsx
> +    );
I like renaming this const to `updatedItems`.

2021-08-02 01:18 UTC, PenghaiZhang commented on react-front-end/tsrc/search/components/GallerySearchItemTiles.tsx
> +  entry: GalleryEntry
It's a bit tricky to add TSDoc for a function's parameters in the function's type declaration.

2021-08-02 04:28 UTC, edalex-ian approved these changes
LGTM! :+1:

2021-08-02 05:02 UTC, merged