Feature/wizard definition endpoint
openequella/openEQUELLA pull request #3344
Opened 2021-08-26 05:11 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds a REST endpoint for retrieving Advanced search wizard definition. Several data models are created to represent controls that wizard controls. 

The initial idea was to use inheritance - create a basic control to provide common fields and then those having special fields just extend the basic one. I tried `trait` and `abstract class` both of them can produce lots of duplication. 

So I went to composition which works well, but I am not so sure if this is the best choice.

![Screenshot from 2021-08-26 15-10-52](https://user-images.githubusercontent.com/47203811/130904493-ea86df95-48ac-499a-9d58-9959c08b723e.png)

I have attached a full json file.
[controls.zip](https://github.com/openequella/openEQUELLA/files/7051791/controls.zip)

2021-08-26 05:12 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param size2 #todo
Help wanted to figure out what these fields mean.

2021-08-26 05:12 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param powerSearchFriendlyName #todo
Help wanted to figure out what this field means.

2021-08-26 08:12 UTC, edalex-ian commented
A quick confirmation before I start @PenghaiZhang , did you also check and test nested Shuffle Lists? (I think that was the only nesting we needed to support for this....)

2021-08-26 23:31 UTC, PenghaiZhang commented
> A quick confirmation before I start @PenghaiZhang , did you also check and test nested Shuffle Lists? (I think that was the only nesting we needed to support for this....)

I guess you were talking about `Repeater` which is only available in Contribution Wizard ?  The Shuffle list does not support any nested control.

2021-08-30 01:18 UTC, edalex-ian commented
Another pondering @PenghaiZhang ... Seeing this is `GET /settings/advancedsearch/{uuid}` are there any other values about the Advanced Search we should also be returning? For example, should we return the name, description and collection(s) configured to search against?

And although the search endpoint has the odd idea of specifying the UUID of the advanced search to get the list of collections to use in the search, we simply returned the list of collections as part of this endpoint then it would further help us construct the query client side with existing logic. :thinking:

2021-08-30 01:45 UTC, PenghaiZhang commented
> Another pondering @PenghaiZhang ... Seeing this is `GET /settings/advancedsearch/{uuid}` are there any other values about the Advanced Search we should also be returning? For example, should we return the name, description and collection(s) configured to search against?
> 
> And although the search endpoint has the odd idea of specifying the UUID of the advanced search to get the list of collections to use in the search, we simply returned the list of collections as part of this endpoint then it would further help us construct the query client side with existing logic.

Ah I totally forgot that an advanced search can be configured to work for certain collections. Yes, I agree that we should also return the list of configured collections rather than specifying the UUID of the advanced search in search2.

2021-08-30 04:44 UTC, edalex-ian requested changes
Looks almost there @PenghaiZhang . Great work. :+1: 

Just needs:

* Minor refactoring;
* Tidy up of some comments - and clarification; and
* Expand the test a little.

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/AdvancedSearchResource.scala
> +    notes = "This endpoint is used to retrieve Wizard definition of an Advanced Search by UUID.",
As mentioned in the general comments for the PR (https://github.com/openequella/openEQUELLA/pull/3344#issuecomment-907936446) I wonder if this should also include some of the auxiliary information about the advanced search too. :thinking:

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/AdvancedSearchResource.scala
> +        UnknownWizardControl()
This should be split out into a stand-alone mapping/factory function over near `WizardControlDefinition`. It's definitely not specific to `AdvancedSearchResource` - only the actual `ps.getWizard.getControls.asScala.map(fn).toList` is specific.

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +/** Data structure for Wizard Control option
Unclear what this case class is for. This description needs improvement.

Is it for 'Option' type wizard control, or is to encapsulate options which may be presented in various controls? Or, is it something else entirely - like just labels and titles....? :thinking:

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +// We can probably remove it trait once we can use Scala 3.
```suggestion
// We can probably remove it once we can use Scala 3.
```

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param reload Whether to reload all controls after this control has different selection. This may affect how scripting works.
Ooooh, that is something we've not mentioned in the Design. I'll add something brief now.

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param reload Whether to reload all controls after this control has different selection. This may affect how scripting works.
Ah, so yeah we kind of have captured this, but see my new section in the Design capturing the thinking.

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param size2 #todo
Yeah, not sure:

* `include` seems to only impact Advanced Searches, but I can't see how you set it - but if false, it should not be seen in advanced searches;
* `size1` seems to map to Admin Console option of 'Number of columns' for Radio Button groups and Checkbox groups.
* `size2`seems to map to Admin Console option of 'Number of rows' for Editbox.

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param customName The controls' customised name.
Do you mean custom in the sense of display, or... ??

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param visibilityScript Script running on Client to control the visibility of the control.
"running on Client" is really an implementation detail. Probably best to just have:

```suggestion
  * @param visibilityScript Script which controls the visibility of the control. (Commonly run when rendering control.)
```

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param powerSearchFriendlyName #todo
On some controls if you go down the bottom of their settings you'll see an 'Advanced Search Options' section which then has a text field for 'Friendly Name'. I think - you'll need to test - this is used when showing the summary of criteria instead of simply showing the XML node name.

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param isRange Whether to support a date range.
Probably need more. Something like: If false, should only display a single calendar control and supply a single date value, however if true, two controls should be displayed with the values from both representing a range.

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param isTokenise Whether to tokenise the value.
Tokenise how?

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param isAllowMultiLang Whether to allow multiple lines.
Curious, the comment talks about multiple lines, but the variable name seems to talk about multiple languages (Lang). What's going on here?

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param isCheckDuplication Whether to check duplicated values.
These seem to be a common theme, should then be put into another case class to compose with? e.g. ControlUniqueConstraints or something...

2021-08-30 04:44 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +    attributes: Map[Object, Object]
This `Object, Object` concerns me. But I've no idea what this WizardCustomControl is about - the description in the comment is unhelpful. Could you please update comment and let me know? Then I can figure out this very generic map.

2021-08-30 04:44 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/AdvancedSearchApiTest.java
> +  @Test(description = "list all Wizard controls of an Sdvanced search")
```suggestion
  @Test(description = "list all Wizard controls of an Advanced search")
```

2021-08-30 04:44 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/AdvancedSearchApiTest.java
> +  public void testRetrieveWizardDefinition() throws IOException {
Needs a bit more work. Checks that it gets the right number of controls back, but they could arguably all be 'unknown' controls....

2021-08-30 06:14 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/AdvancedSearchResource.scala
> +        UnknownWizardControl()
I added another object named `WizardControlHelper` to provide this function.

2021-08-30 06:15 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +/** Data structure for Wizard Control option
It's for a Option' type wizard control. I will update the doco.

2021-08-30 06:23 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param reload Whether to reload all controls after this control has different selection. This may affect how scripting works.
Great!

2021-08-30 06:29 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param isTokenise Whether to tokenise the value.
I have added this - `If true, an '*' must be appended to the schema node in the Lucene query.`

2021-08-30 06:40 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param isAllowMultiLang Whether to allow multiple lines.
:sweat:  I might misread the property.  I will update the comment. 

Actually, these is no usage of this boolean property and I have not found any configuration for it in admin console.

2021-08-30 06:44 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +    attributes: Map[Object, Object]
This class is all about `CustomControl` which is a subtype of `WizardControl` such as `Term Selector`. The most important property of a CustomControl is `attributes` which is `Map[Object, Object]`.

2021-08-30 06:48 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +    attributes: Map[Object, Object]
The property `attributes` is a map where keys and values represent configurations that are specific to a certain type of CustomControl.

2021-08-30 06:51 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param isCheckDuplication Whether to check duplicated values.
Not very common though :smile:  Only in two types. If put it into another case class, then we need to use `@JsonUnwrapped` again.

2021-08-30 08:34 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param isCheckDuplication Whether to check duplicated values.
True, but once you have the same in more than once place you normally want a good reason for the repetition - which I'm not sure avoiding an annotation is a great one.

2021-08-30 08:36 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +    attributes: Map[Object, Object]
Okay, that additional information in your first comment here would be great to help flesh out the code comment describing the case class. As for the map, if it is for configurations is the key seriously different types of Object and not just `String`?

2021-08-30 23:43 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +    attributes: Map[Object, Object]
Not sure why the map was designed to use `Object` as key, but I can confirm that all the keys are `String`. So on Scala side I will use String.

2021-08-31 00:05 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param size2 #todo
So should we filter out controls whose `include` is false on server then  ?

2021-08-31 00:12 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param size2 #todo
Yes I know what `size1` and `size2` mean now! Thank you!

2021-08-31 00:14 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param powerSearchFriendlyName #todo
You are 100% correct! I have tested.

2021-08-31 00:20 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param size2 #todo
> So should we filter out controls whose `include` is false on server then ?

No, I don't think so. Again, it's REST endpoint, leave it to the client.

2021-08-31 00:44 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param customName The controls' customised name.
After some debugging, I think this property is used in `admin console` rather than the page.
![Screenshot from 2021-08-31 10-43-49](https://user-images.githubusercontent.com/47203811/131423576-6de05d22-39ab-4286-8435-ccaf0a0dbd64.png)

2021-08-31 01:04 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param customName The controls' customised name.
Aha! Good to describe that, because in the future if we move this to the Web then we'd most likely be using this endpoint. :wink:

2021-08-31 01:21 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param size2 #todo
Actually, `include` is also used in admin console - whether the control is ticked or not.

![Screenshot from 2021-08-31 11-20-39](https://user-images.githubusercontent.com/47203811/131426094-bc21cb95-227f-4609-b506-e723c852981c.png)

2021-08-31 01:24 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param size2 #todo
But even though the control in not selected in Admin Console, it is still displayed in the page.

2021-08-31 02:31 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/wizard/WizardBasicControl.scala
> +  * @param size2 #todo
Yeah, I played with that ticket too but couldn't get it to do anything useful. :thinking: :man_shrugging:

2021-08-31 03:56 UTC, edalex-ian approved these changes
LGTM! Merge on! :tada:

2021-08-31 03:58 UTC, merged