chore: install `psc-package` via a NPM script
openequella/openEQUELLA pull request #3386
Opened 2021-09-12 23:44 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

With NPM 7 `psc-package` is not installed properly. So we created a new NPM script which will downloaded the package and use it.

2021-09-12 23:46 UTC, PenghaiZhang commented on autotest/IntegTester/ps/package.json
> +    "psc-package": "./psc-package/psc-package.exe"
If we don't worry about `Windows` we don't need to rename the file, and then we can remove `bin`.

2021-09-13 00:02 UTC, edalex-ian reviewed
Looks pretty good, may just want to tweak description to also mention this was triggered due to issues with renovate.

2021-09-13 00:02 UTC, edalex-ian commented on autotest/IntegTester/ps/package.json
> +    "shelljs": "^0.8.2"
Best to still use pinned versions for these:

```suggestion
    "follow-redirects": "1.5.9",
    "tar": "4.4.8",
    "shelljs": "0.8.2"
```

2021-09-13 00:02 UTC, edalex-ian commented on autotest/IntegTester/ps/package.json
> +    "install": "node install.js && npm exec psc-package install",
So the expectation of the `npm exec psc-package` here is that it's running the `psc-package` specified in the `bin` block?

At first I was concerned that this would in turn go and download `psc-package` just like `npx psc-package` would. :thinking:

2021-09-13 00:29 UTC, PenghaiZhang commented on autotest/IntegTester/ps/package.json
> +    "install": "node install.js && npm exec psc-package install",
Yes - to run the `psc-package` specified in the bin block. I think `npx` is deprecated ?

2021-09-13 00:52 UTC, edalex-ian requested changes
Cool, so just the one comment around the left over GHA step, and still need to pin those deps.

2021-09-13 00:52 UTC, edalex-ian commented on .github/workflows/ci.yaml
> +          node-version: "${{ steps.nvm.outputs.NVMRC }}"
Oops, but you still left this step down below.

2021-09-13 01:11 UTC, PenghaiZhang commented
> Looks pretty good, may just want to tweak description to also mention this was triggered due to issues with renovate.

Can I mention this was triggered due to issues with renovate in the merge commit ?

2021-09-13 01:52 UTC, edalex-ian commented
Good to have both places. At least if you just duck up and edit the merge request description it'll be there nice and loud for if we need to reference back to it. And then if you put it in the merge commit it will be nicely there for future prosperity on the quite.

2021-09-13 01:53 UTC, edalex-ian approved these changes
LGTM! :+1:

2021-09-13 01:55 UTC, PenghaiZhang commented
> Good to have both places. At least if you just duck up and edit the merge request description it'll be there nice and loud for if we need to reference back to it. And then if you put it in the merge commit it will be nicely there for future prosperity on the quite.

Cool. I have updated the PR description.

2021-09-13 02:17 UTC, PenghaiZhang commented
Ah GHA is still using NPM 6...

2021-09-13 03:59 UTC, PenghaiZhang commented
Failed on `pulp build`...

```
> pulp build

* Building project in /home/penghai/Edalex/forks/openEQUELLA/autotest/IntegTester/ps
* ERROR: `psc-package` executable not found.


```

2021-09-13 06:14 UTC, edalex-ian approved these changes
Good job @PenghaiZhang ! Looks like you've pretty well won. :tada: 

Just need to remove that bit of redundant code in `install.js` and then you should be GTG. :+1:

2021-09-13 07:21 UTC, HonkingGoose commented on .github/workflows/ci.yaml
> +          node-version: "${{ steps.nvm.outputs.NVMRC }}"
Did you know that `setup-node` comes with caching now?

```suggestion
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: npm
```

Read the readme and learn more it here: https://github.com/actions/setup-node#caching-packages-dependencies.

By the way `setup-java` comes with caching as well, but I don't know much about Java, so won't apply any suggestions here.

https://github.com/actions/setup-java#caching-packages-dependencies

Also check if the version of `setup-java` you're using comes with the caching capability before you turn it on for Java.

2021-09-13 07:40 UTC, edalex-ian commented on .github/workflows/ci.yaml
> +          node-version: "${{ steps.nvm.outputs.NVMRC }}"
That's a nice new feature. Thanks for letting us know. We'll have a look and see what we might be able to refactor, because the build definition sure is long.

2021-09-13 07:57 UTC, HonkingGoose commented on .github/workflows/ci.yaml
> +          node-version: "${{ steps.nvm.outputs.NVMRC }}"
@edalex-ian Do you want me to make an issue with the same text? That way I'm not blocking this PR, and you can track the issue that way, and follow up when you have time to work on it.

2021-09-13 08:11 UTC, edalex-ian commented on .github/workflows/ci.yaml
> +          node-version: "${{ steps.nvm.outputs.NVMRC }}"
That'd be great thanks @HonkingGoose. :+1: 

I'll go and merge this in the meantime. :wink:

2021-09-13 08:11 UTC, merged

2021-09-13 08:21 UTC, HonkingGoose commented on .github/workflows/ci.yaml
> +          node-version: "${{ steps.nvm.outputs.NVMRC }}"
See issue #3390 for the "feature request".