feat: support for retrieving Advanced search definition in REST Module
openequella/openEQUELLA pull request #3387
Opened 2021-09-13 06:50 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds the support for retrieving Advanced search to the REST Module. 

The major change is creating different data structures to support Wizard controls used in Advanced search. And a new function was added to talk to the endpoint.

2021-09-14 04:13 UTC, PenghaiZhang commented on oeq-ts-rest-api/src/AdvancedSearch.ts
> +export interface AdvancedSearch {
Probably need a different name for this type...

I am working on another branch created off this branch and I have this awkward naming.
```
Promise<OEQ.AdvancedSearch.AdvancedSearch>
```

2021-09-14 04:18 UTC, PenghaiZhang commented on oeq-ts-rest-api/src/AdvancedSearch.ts
> +export interface AdvancedSearch {
The namespace is very clear to say this is `AdvancedSearch`  so maybe  rename the type to  `Definition`?

2021-09-14 05:20 UTC, edalex-ian commented on oeq-ts-rest-api/src/AdvancedSearch.ts
> +export interface AdvancedSearch {
Maybe, I'm not to worried either way.

2021-09-14 05:21 UTC, PenghaiZhang commented on oeq-ts-rest-api/src/AdvancedSearch.ts
> +export interface AdvancedSearch {
I renamed it to `WizardDefinition`.

2021-09-14 06:25 UTC, edalex-ian requested changes
Thanks @PenghaiZhang .

Most of the feedback is to tweak comments. But other than that:

- Some queries around some of the data definitions; and
- Request to continue to avoid TS enums.

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/AdvancedSearch.ts
> +export interface WizardDefinition {
Nope, can't use this name, this is _not_ a definition of a wizard, it is the definition of an Advanced Search.

Here's some options in order of preference:

- `AdvancedSearchDefinition`
- `AdvancedSearch` - what you originally had, I'm not too concerned about the repitition
- `Definition`

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/AdvancedSearch.ts
> +   * Name of an Advanced Search.
```suggestion
   * Name of the Advanced Search.
```

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/AdvancedSearch.ts
> +   * Description of an Advanced Search.
```suggestion
   * Description of the Advanced Search.
```

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/AdvancedSearch.ts
> +   * All the Wizard Controls of an Advanced Search.
```suggestion
   * All the Wizard Controls of the Advanced Search.
```

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/Taxonomy.ts
> +export enum SelectionRestriction {
A reminder that we're avoiding the use of `enum`s on the TS side - due to poor support and possible future clashes with ESCMA versions.

Typically instead we've gone with a simple object definition. e.g.

```typescript
export const SelectionRestriction = {
  TOP_LEVEL_ONLY: 'TOP_LEVEL_ONLY',
  LEAF_ONLY: 'LEAF_ONLY',
  UNRESTRICTED: 'UNRESTRICTED'
}
```

If you wish, you could also add typing to then mark them as `readonly` but I don't think we bothered elsewhere.

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/Taxonomy.ts
> + * Formats which ae used to search for a term.
```suggestion
 * Formats which are used to search for a term.
```

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/Taxonomy.ts
> +export enum TermStorageFormat {
As above: A reminder that we're avoiding the use of `enum`s on the TS side - due to poor support and possible future clashes with ESCMA versions.

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/wizard/WizardCommonTypes.ts
> +  attribute: string;
Odd that the above comment uses plural but this is both singular in name and type. :thinking:

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/wizard/WizardCommonTypes.ts
> +   * XOQ path of the target node.
```suggestion
   * XOQL path of the target node.
```

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/wizard/WizardCommonTypes.ts
> +   * Free text field of the target node.
if I follow this right, perhaps this should be:

```suggestion
   * Free text search index field of the target node.
```

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/wizard/WizardCommonTypes.ts
> + * Options of Option' type control such as CheckBox Group and Shuffle List.
```suggestion
 * Options of 'Option' type control such as CheckBox Group and Shuffle List.
```

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/wizard/WizardControl.ts
> +export type ControlType =
Needs doc. Maybe:

```suggestion
/**
 * Supported Wizard Control types.
 */
export type ControlType =
```

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/wizard/WizardControl.ts
> +    IsRestrictedGroups: boolean;
```suggestion
    isRestrictedGroups: boolean;
```

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/wizard/WizardControl.ts
> +    IsSelectMultiple: boolean;
```suggestion
    isSelectMultiple: boolean;
```

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/wizard/WizardControl.ts
> +    RestrictToGroups: UuidString[];
```suggestion
    restrictToGroups: UuidString[];
```

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/wizard/WizardControl.ts
> +  attributes: {
The names and casing of the properties of this are rather odd. What's going on here? :thinking:

2021-09-14 06:25 UTC, edalex-ian commented on oeq-ts-rest-api/src/wizard/WizardControl.ts
> +  controlType: ControlType;
It's a little interesting that you didn't set the explicit value for this in each interface below - which could then be used as a union discriminator. Why was that?

2021-09-15 00:20 UTC, PenghaiZhang commented on oeq-ts-rest-api/src/wizard/WizardControl.ts
> +  attributes: {
I have refactored both server and client for this type :smile:

2021-09-15 00:21 UTC, PenghaiZhang commented on oeq-ts-rest-api/src/Taxonomy.ts
> +export enum SelectionRestriction {
Can we just create a type instead ? 

```
export type TermStorageFormat = 'FULL_PATH' | 'LEAF_ONLY';
```

2021-09-15 00:38 UTC, PenghaiZhang commented on oeq-ts-rest-api/src/wizard/WizardCommonTypes.ts
> +  attribute: string;
I think this field is a singular so I will update the JSDoc.

2021-09-15 00:45 UTC, PenghaiZhang commented on oeq-ts-rest-api/src/wizard/WizardControl.ts
> +  controlType: ControlType;
I was thinking to create some type guards in future work.

2021-09-15 00:47 UTC, PenghaiZhang commented on oeq-ts-rest-api/src/wizard/WizardControl.ts
> +  controlType: ControlType;
Not a problem. I will add explicit control type in each type definition.

2021-09-15 00:52 UTC, PenghaiZhang commented
I have updated the data structure for `TermSelector` and `UserSelector`. 
![Screenshot from 2021-09-15 10-51-22](https://user-images.githubusercontent.com/47203811/133352859-82cdf2c6-3fa7-4791-95ec-1cfd2b9711f3.png)

2021-09-15 03:58 UTC, edalex-ian commented on oeq-ts-rest-api/src/Taxonomy.ts
> +export enum SelectionRestriction {
Actually, yes. That might be the approach we've been using - I was hoping to find you an example, but I can't remember... :confused:

2021-09-15 04:39 UTC, edalex-ian approved these changes
Looks great @PenghaiZhang ! Merge on! :+1:

2021-09-15 04:45 UTC, merged