feat: don't show Collection Selector in Advanced search page
openequella/openEQUELLA pull request #3393
Opened 2021-09-14 01:08 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds the feature of not showing Collection Selector and Classification panel in Advanced search mode. 

Also the REST API call to list Classifications will not be executed. Should not need to list Collections as well, but due to the existing implementation this will require more changes.

2021-09-14 06:38 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/SearchPageTestHelper.tsx
> +export const queryClassificationPanel = (
Wow! I'm amazed that we don't already have these functions. It'd appear we don't currently have a test to cover the display of the Classifications panel on the Search page under normal usage. :disappointed:

2021-09-14 07:07 UTC, edalex-ian requested changes
I think we need a few changes here:

1. Let's not add a new `isInAdvancedSearchMode` - just stick with the current check of the `advancedSearchId` as is already in place;
2. Make the skipping of retrieving classifications more explicit (see comment); and
3. Modify `<SidePanel>` such that `classificationsPanelProps` is optional and when not present all logic related to the classifications is skipped - which probably just means changing on line 47 `classificationsPanelProps.classifications.some` to `classificationsPanelProps?.classifications.some`. Then use `advancedSearchId` to optionally set that value of SidePanel in SearchPage.

2021-09-14 07:07 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +  const isInAdvancedSearchMode = advancedSearchId !== undefined;
Hmmm, introducing this means we now have a mix - existing code checks `advancedSearchId`. I'm inclined to say we stick to that idea.

2021-09-14 07:07 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +      disabled: isInAdvancedSearchMode,
I like this method of disabling the control. It is explicit and actually addresses your concern of "Should not need to list Collections as well". Seeing the control is 'disabled' the component never mounts and never does its effect with REST calls.

What does concern me is that the method used to hide the classifications selector is very different to this. It uses an implicit method by short-circuiting the retrieval of classifications when in Adv. Search mode. No retrieval means empty list which the current code results in a hide.

But in the current component tree definition a whole lot of extra code will still get executed just with an always empty list. As per the above comment, I think we need to revisit this.

2021-09-14 07:07 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +        ? emptyClassifications
Hiding this logic down in the get function could lead to confusion. I think we should make it explicit in the below calls. That may involve rather than using the simple `Promise.all` the code need to make one explicit call and then (if `advancedSearchId` is not set) make the second one. (Probably best done async/await style.)

2021-09-15 01:06 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPage.tsx
> +      disabled: isInAdvancedSearchMode,
oh dear I forgot that Collection Selector is hidden in this case :face_exhaling:

2021-09-15 04:17 UTC, edalex-ian reviewed
Thanks for the updates @PenghaiZhang . I think that really helps readability and comprehension.

I do however just a have a few further suggestions on the logic checks based on what is already in place though. (And one which is really optional though.)

2021-09-15 04:17 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +        }
How about:

```suggestion
        classificationsPanelProps={
          // When in advanced search mode, hide classifications panel
          !!advancedSearchId
            ? {
                  classifications: getClassifications(),
                  onSelectedCategoriesChange: handleSelectedCategoriesChange,
                  selectedCategories: searchPageOptions.selectedCategories,
                }
              : undefined
        }
```

2021-09-15 04:17 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +      disabled: advancedSearchId !== undefined,
How about:

```suggestion
      disabled: !!advancedSearchId,
```

2021-09-15 04:17 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +            advancedSearchId === undefined
Based on the comments below, I wonder if for consistency this should be:

```suggestion
            !!advancedSearchId
```

But up to you, as I also don't really mind this way. I'm just mentioning it.

2021-09-15 04:17 UTC, edalex-ian commented on react-front-end/tsrc/search/components/SidePanel.tsx
> +  classificationsPanelProps?: CategorySelectorProps;
Maybe tweak the comment to say, "Props passed to Classifications Panel, if undefined the panel is not displayed"

2021-09-15 04:47 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPage.tsx
> +      disabled: advancedSearchId !== undefined,
I personally like `!!`, but I remember there were discussion around the confusion caused by `!!`. Excellent I will go with `!!`

2021-09-15 04:51 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPage.tsx
> +        }
I think here should be single exclamation mark ?

2021-09-15 04:53 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPage.tsx
> +            advancedSearchId === undefined
I think here should be single `!`.

2021-09-15 05:22 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/search/SearchPageTestHelper.tsx
> +export const queryClassificationPanel = (
Do you want me to add some tests in this PR ?

2021-09-15 07:33 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/SearchPageTestHelper.tsx
> +export const queryClassificationPanel = (
Nah, wasn't in the scope. I was just surprised. No action required.

2021-09-15 07:34 UTC, edalex-ian approved these changes
GTG @PenghaiZhang - well, other than it seems your other PR you merged conflicts. Merge when sorted. :wink:

2021-09-16 02:42 UTC, merged