Feature/retrieve advanced search definition
openequella/openEQUELLA pull request #3412
Opened 2021-09-16 04:32 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds the support for retrieving Advanced search definition in Search page and passing the Wizard controls to component `AdvancedSearchPanel`. 

In Advanced search mode, the retrieval is started when Search page is in initialising state. Once that is done, update `SearchPageOptions` to use the Collections configured for Advanced search.

![Screenshot from 2021-09-16 14-32-19](https://user-images.githubusercontent.com/47203811/133549776-0386cb42-2926-4b66-82eb-4f0bf9c0e564.png)

2021-09-16 06:25 UTC, edalex-ian commented
The new tests for the Advanced Search Panel displaying logic are failing @PenghaiZhang , and seeing they're pretty critical to this I better wait until you fix to review. :wink:

2021-09-16 06:34 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +  const [wizardDefinition, setWizardDefinition] = useState<
Just a quick one while you fix the tests though... Would make sense to go with a more specific name here:

```suggestion
  const [advancedSearchDefinition, setAdvancedSearchDefinition] = useState<
```

Mind you though, we've quickly accumulated a bit of state relating to advanced search mode, should we merge it - maybe even another reducer I wonder.

Bits that come to mind:

- this definition
- show/hide the panel
- maybe the id
- and soon the values or query...

hmmm, what do you think?

2021-09-16 06:44 UTC, edalex-ian commented on oeq-ts-rest-api/src/index.ts
> +export * as WizardControl from './wizard/WizardControl';
Also, just another quick one, I missed in the code review that there was a new subfolder created for the wizard types. You'll note there are no others, and it is just using a flat directory structure at this point. Any chance we could just move the two files to the top level?

If we're lucky, it may be fine to keep this whole module flat. You'll also note there are already files in there which are purely shape definitions - Common and Acl.

2021-09-16 07:05 UTC, PenghaiZhang commented on oeq-ts-rest-api/src/index.ts
> +export * as WizardControl from './wizard/WizardControl';
Yeah I will update the structure.

2021-09-16 07:12 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPage.tsx
> +  const [wizardDefinition, setWizardDefinition] = useState<
> The new tests for the Advanced Search Panel displaying logic are failing @PenghaiZhang , and seeing they're pretty critical to this I better wait until you fix to review.

Ah I forgot to mock the new function. No problems. Fixed.

2021-09-16 07:25 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPage.tsx
> +  const [wizardDefinition, setWizardDefinition] = useState<
At the moment we have two. How about we merge them into a object first ?

2021-09-16 07:44 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +  const [wizardDefinition, setWizardDefinition] = useState<
Sounds good, we can start there and see how it goes when we add the others.

But keeping in mind that one of the key purposes of a reducer is to manage multiple pieces of related state. And where this was already jumping out at me was when you were checking for both show advanced search panel and whether there was a wizard definition.

2021-09-17 04:20 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPage.tsx
> +  const [wizardDefinition, setWizardDefinition] = useState<
I have implemented a reducer for this.

2021-09-17 05:57 UTC, edalex-ian requested changes
Looks great @PenghaiZhang . Love the move to the reducer, has really tidied things up.

Just two main things:

1. Are those tests I've highlighted actually needed/doing anything? and
2. Let's add a bit more to the reducer as discussed.

2021-09-17 05:57 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/modules/AdvancedSearchModule.test.ts
> +});
Hmmmm, is this actually testing anything? Both those functions really have no logic, just wiring to call the REST module and then you've mocked that out. So unless I'm missing something, you're just testing that you've mocked the functions correctly. :thinking:

2021-09-17 05:57 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +        throw new Error("Control Advanced search panel in wrong state");
```suggestion
        throw new Error("Request to toggle Advanced Search Panel when _not_ in Advanced Search mode. Request ignored.");
```

2021-09-17 05:57 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +      });
As discussed, rather than simply using the action of `useAdvSearch` to even change the state of the panel display, how about adding three more actions to cover the various usages: `toggleAdvSearchPanel`, `hideAdvSearchPanel` and `showAdvSearchPanel`. In the reducer, they could then use the previous `state` to just tweak the `showPanel` value as required.

Then you'd update the various callbacks below and they'd be nice and clean like `searchPageModeDispatch({type: "toggleAdvSearchPanel"})`.

2021-09-17 05:57 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageModeReducer.ts
> +      useMode: "normal";
Nit: How about just `mode`?

2021-09-17 05:57 UTC, edalex-ian commented on oeq-ts-rest-api/src/index.ts
> +export * as WizardControl from './WizardControl';
While here, could you also:

```suggestion
export * as WizardCommonTypes from './WizardCommonTypes';
export * as WizardControl from './WizardControl';
```

As I've needed to do that in my branch, so can I assure you it is needed. :wink:

2021-09-20 00:44 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/modules/AdvancedSearchModule.test.ts
> +});
I think we have similar tests which are meant to ensure the front end talks to rest module properly. :thinking:

2021-09-20 01:56 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/modules/AdvancedSearchModule.test.ts
> +});
I have tests these redundant tests.

2021-09-20 04:43 UTC, edalex-ian requested changes
Almost there @PenghaiZhang , just need one more tweak to the reducer to allow it to look after the logic of toggling etc.

2021-09-20 04:43 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +                              !searchPageModeState.isAdvSearchPanelOpen,
This should not be required, just keep the logic (even though it's simple) in the reducer - see other comment.

2021-09-20 04:43 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageModeReducer.ts
> +};
This function should really just have all the logic based on the `action` - and then it better aligns with the name. For example:

```
const toggleOrHidePanel = (
  state: State,
  action: "toggle" | "hide"
) => {
  if (state.mode !== "advSearch") {
    throw new Error(
      `Request to ${action} Advanced Search Panel when _not_ in Advanced Search mode. Request ignored.`
    );
  }
  return { ...state, isAdvSearchPanelOpen: (action === "toggle" ? !state.isAdvSearchPanelOpen : false) };
};
```

Notes:

- I've dropped the third arg; and
- Used the `action` to determine what `isAdvSearchPanelOpen` should be.

2021-09-20 04:43 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageModeReducer.ts
>        showPanel: boolean;
Not required - the action is `toggleAdvSearchPanel`, so the reducer can do that logic based on previous state.

2021-09-20 06:17 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPageModeReducer.ts
> +};
Good idea!

2021-09-20 06:40 UTC, edalex-ian approved these changes
GTG! :tada:

2021-09-21 01:11 UTC, merged