chore: update contributor guidelines
openequella/openEQUELLA pull request #3524
Opened 2021-10-27 01:01 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [x] documentation is changed or added

##### Description of change

Add more information to `setting up development environment ` section in contributor guidelines.
Change the order of `IDE` section.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2021-10-27 11:46 UTC, PenghaiZhang reviewed
Thanks @edalex-yinzi !! Very very very helpful!

2021-10-27 11:46 UTC, PenghaiZhang commented on CONTRIBUTING.md
> +sudo apt install curl
I think `curl` is pre-installed on most Linux distributions :thinking:

2021-10-27 11:46 UTC, PenghaiZhang commented on CONTRIBUTING.md
> +### Install sbt
Since we use the sbt wrapper (the file named `sbt` under root folder), we should not need to install sbt.

2021-10-27 11:46 UTC, PenghaiZhang commented on CONTRIBUTING.md
> +It will install everything required for compiling basic software written in C and C++. We do need this to build openEquella.
May I ask why we need to install this ? I have never done this before.

2021-10-27 11:46 UTC, PenghaiZhang commented on CONTRIBUTING.md
> +Which will be used for function of creating new resources, etc. Without it you are not able to contribute a new resource in the web.
I think `resources` in the context of OEQ refers to Items and Attachments. Image Magic is used to generate thumbnails for attachment. Without it we can still contribute an Item.

2021-10-27 11:46 UTC, PenghaiZhang commented on CONTRIBUTING.md
> +in folder`./react-front-end` run `npm run dev` command.
Also need to run `npm ci` before `npm run dev`.

2021-10-27 11:46 UTC, PenghaiZhang commented on CONTRIBUTING.md
> +##### Disable some plugins
Instead of `Disable some plugins`, what about `plugins recommended` and then give a list of the recommendations ?

2021-10-28 00:31 UTC, edalex-yinzi commented on CONTRIBUTING.md
> +sudo apt install curl
Try this on a new vm, it doesn't have curl package.
![image](https://user-images.githubusercontent.com/92769668/139166267-336b51f5-6a12-4107-b460-804f93bff2b6.png)

2021-10-28 00:36 UTC, edalex-yinzi commented on CONTRIBUTING.md
> +It will install everything required for compiling basic software written in C and C++. We do need this to build openEquella.
On my laptop and VM, I do need this otherwise the following bunch of `sbt commands` will popup many errors.

2021-10-28 00:53 UTC, edalex-yinzi commented on CONTRIBUTING.md
> +Which will be used for function of creating new resources, etc. Without it you are not able to contribute a new resource in the web.
Odd, on my laptop it will just pop up an error like this:
![image](https://user-images.githubusercontent.com/92769668/139167773-7618a4a0-48c9-4d89-85e1-a39323da90f5.png)

2021-10-28 01:30 UTC, edalex-yinzi commented on CONTRIBUTING.md
> +### Install sbt
Maybe we just keep this? Because I got an error in my VM.
![image](https://user-images.githubusercontent.com/92769668/139170718-52d58f80-0624-4295-b915-0d46cd395d25.png)

2021-10-28 01:43 UTC, PenghaiZhang commented on CONTRIBUTING.md
> +### Install sbt
You should do `./sbt`

2021-10-28 02:43 UTC, edalex-yinzi commented on CONTRIBUTING.md
> +##### Disable some plugins
Very tedious but done.

2021-10-28 03:23 UTC, edalex-yinzi commented on CONTRIBUTING.md
> +### Install sbt
Yes. If you look at the second command in the pic, it's `./sbt`.

2021-10-28 04:47 UTC, edalex-ian requested changes
Great to see this coming along @edalex-yinzi . Please work through the feedback and suggestions, and while doing this how about removing the parts from README.md which also try and capture steps on the build process?

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +[TOC]
Not sure TOC works with GHFM. :thinking:

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +===
What's this for?

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +Setup note for Ubuntu 20.04
Should this be a heading or bold or something?

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +Notice these instructions is mainly for fresh people. Please bear with the redundant and messy information.
```suggestion
Notice these instructions assume a person is starting with a fresh machine. Therefore there'll be additional information which may seem redundant to someone who already has a significantly established development machine.
```

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +sudp apt-get update
Only need one of these - they do the same thing.

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +WE suggest using SDKMAN installing/managing JDK, Scala, Gradle - any other JVM bits.
```suggestion
We suggest using SDKMAN for installing (and managing multiple versions of) JDK, Scala, Gradle - any other JVM bits.
```

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +#### Install Java 8
```suggestion
### Install Java

At the time of writing the openEQUELLA is built with Java 8. For this, we prefer to use
openJDK and that latest version of that is 8.0.302. To install that with SDKMAN:
```

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +```
Rather than repeating the instructions from other sites, we should just advise them to follow the install instructions provided by the tool.

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +https://github.com/nvm-sh/nvmFornode/npmIntelliJ
```suggestion
https://github.com/nvm-sh/nvm
```

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +We suggest using NVM to manage different nodejs env.
```suggestion
We suggest using NVM to manage different NodeJS versions.
```

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +```
As per SDKMAN, point them to NVM for instructions on how to install.

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +#### Install nodejs
```suggestion
### Install NodeJS / NPM

openEQUELLA has a `.nvmrc` in the root of its repository, as a result installation of the correct version of NodeJS and NPM is as simple as:
```

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +nvm install node
```suggestion
nvm install
```

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +### Install Docker
I'd say this whole Docker and Postgres section could be replaced with something like

```markdown
### Install a local database

To run openEQUELLA locally for development and testing, you'll need a local database. By far the easiest to setup
is PostgreSQL. The two main ways to do this are:

- Simple install the package as part of your distro; or
- (Recommended) run an instance in docker to keep it nice and self contained.

Once you have an instance running, make sure you create a database with a user for access:

    CREATE DATABASE equella;
    CREATE USER euqellauser WITH PASSWORD 'password';
    GRANT ALL PRIVILEGES ON DATABASE "equella" to euqellauser;
```

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +### Install sbt
The second command is failing due to `java` command not found.

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +```
If this is kept here, keep in mind that above you installed SDKMAN for this purpose, so all this would become:

    sdk install sbt 1.5.5

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +It will install everything required for compiling basic software written in C and C++. We do need this to build openEquella.
Yeah, this has started to be needed by some of our NPM deps which go through their own compilation of binaries - pretty scary. You may recall @PenghaiZhang when you were trying to setup local instances of the GitHub Actions builds you also needed to do it.

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +Old basic lib used in openEquella.
Heh, not sure I'd say that. It is old, but actively maintained and far from basic, a good portion of the internet relies on it for the processing of their images and videos.

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +sudo apt install imagemagic
```suggestion
sudo apt install imagemagick
```

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +### Install ffmepg
```suggestion
### Install FFmpeg
```

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +Because openEquella uses some old libs, so link these libs.
```suggestion
openEQUELLA was originally developed to use libav for thumb-nailing and previewing of videos.
However [libav has been deprecated](https://github.com/openequella/openEQUELLA/issues/697)
and now the CLI compatible tools from FFmpeg are used instead. To make this work  symbolic links
need to be setup as follows:
```

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +https://www.apereo.org/licensing/agreements/icla
This is covered at the top in the 'Contributing Code / Pull Requests' section.

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +
This is more so standard git/github usage. No need to document.

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +```
I'd leave this out and instead advise people follow the instructions provided by JetBrains at https://www.jetbrains.com/help/idea/installation-guide.html

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +2. Set the necessary amount of memory that you want to allocate and click **Save and Restart**.
```suggestion
Due to the heavy memory requirements of the SBT based build, it is recommended to setup IntelliJ's maximum heap to 4GiB. Documentation on how to do this can be found at <https://www.jetbrains.com/help/idea/increasing-memory-heap.html>.
```

2021-10-28 04:47 UTC, edalex-ian commented on CONTRIBUTING.md
> +##### Plugins recommended
I didn't get a chance to comment before you reworked this section, but I'd say keep this simple.

Keep your message around speeding up the IDE with only relevant plugins. But advise that they must make sure they have the Scala plugin as well as support for Typescript and Gradle (you have Java by default).

2021-10-28 05:07 UTC, edalex-yinzi commented on CONTRIBUTING.md
> +[TOC]
Hmmm, you are right not working in GItHub.

2021-10-28 05:10 UTC, edalex-yinzi commented on CONTRIBUTING.md
> +===
Should be a horizontal line like <hr>, but seems not working on GitHub.

2021-10-28 05:11 UTC, edalex-yinzi commented on CONTRIBUTING.md
> +Setup note for Ubuntu 20.04
Good suggestion.

2021-10-28 05:44 UTC, edalex-yinzi commented on CONTRIBUTING.md
> +Old basic lib used in openEquella.
Ahh, I will change it.

2021-11-03 02:01 UTC, edalex-ian requested changes
Nice work @edalex-yinzi . Definitely getting there. :wink: 

Please make the suggested changes, and then grab me tomorrow to discuss how to merge the JS/New UI sections.

2021-11-03 02:01 UTC, edalex-ian commented on CONTRIBUTING.md
> +```shell
For readability (in text mode), good to have some white space.

```suggestion

```shell
```

2021-11-03 02:01 UTC, edalex-ian commented on CONTRIBUTING.md
> +openJDK and that latest version of that is 8.0.302. To install that with SDKMAN:
```suggestion
openJDK which is current at version 8.0.302. To install that with SDKMAN:
```

2021-11-03 02:01 UTC, edalex-ian commented on CONTRIBUTING.md
> +```
Again, please add a blank line above.

2021-11-03 02:01 UTC, edalex-ian commented on CONTRIBUTING.md
> +openEQUELLA has a `.nvmrc` in the root of its repository, as a result installation of the correct version of NodeJS and NPM is as simple as:
```suggestion
openEQUELLA has a `.nvmrc` in the root of its repository, as a result installation of the correct version of NodeJS and NPM is as simple as
running the following when in the root of your openEQUELLA clone:
```

2021-11-03 02:01 UTC, edalex-ian commented on CONTRIBUTING.md
> +- Simple install the package as part of your distro; or
```suggestion
- Simply install the package as part of your distro; or
```

2021-11-03 02:01 UTC, edalex-ian commented on CONTRIBUTING.md
> +Which will be used for function of creating new resources, etc. Without it you are not able to contribute a new resource in the web.
```suggestion
A suite of software (and specifically, command line tools) used by openEQUELLA for querying and manipulating
image attachments. A key requirement for when contributing items with image attachments.
```

2021-11-03 02:01 UTC, edalex-ian commented on CONTRIBUTING.md
> +### link new lib to other alias
```suggestion
#### Setup Libav compatible symbolic links
```

2021-11-03 02:01 UTC, edalex-ian commented on CONTRIBUTING.md
> +## Build openEquella on terminal
```suggestion
## Build openEquella in a terminal
```

2021-11-03 02:01 UTC, edalex-ian commented on CONTRIBUTING.md
> +
Hmm, we actually need to merge this section up with the above 'Developing the JS code'. When you're ready, let me know and we'll discuss - probably easier (and will help your understanding of the codebase).

2021-11-03 02:01 UTC, edalex-ian commented on CONTRIBUTING.md
> +All code should be formatted using the following formatting tools:
```suggestion
All code should be formatted using the following tools. Assuming you've followed the above steps to install the pre-commit hooks this will be done automatically for you at commit time. However if you don't, then the CI pipelines will fail during checking.
```

2021-11-03 02:01 UTC, edalex-ian commented on CONTRIBUTING.md
> +Some aspects of the build can be configured by editing the `build.conf` file.
```suggestion
Some aspects of the build can be configured by editing the `build.conf` file. This is typically though only done for CI builds.
```

2021-11-03 02:01 UTC, edalex-ian commented on CONTRIBUTING.md
> +~$ sbt installerZip
Two things:

- good to stay consistent with paths; and
- all the uses of SBT should be updated in this file to use the wrapper via `./sbt` (there's several above) and we can drop the shell prompt for consistency me thinks.

So as well as this below suggestion, could you please go and update the above uses of sbt too?

```suggestion
cd /path/to/openEquella
./sbt installerZip
```

2021-11-03 04:05 UTC, edalex-yinzi commented on CONTRIBUTING.md
> +~$ sbt installerZip
Sure.

2021-11-04 00:05 UTC, edalex-ian requested changes
Alright, just a few more tweaks that went astray there in your updates, then tomorrow let's discuss how we can merge the JS part.

2021-11-04 00:05 UTC, edalex-ian commented on CONTRIBUTING.md
> +openJDK which is current at version 8.0.302. To install that with SDKMAN:
```suggestion
openJDK which is currently at version 8.0.302. To install that with SDKMAN:
```

2021-11-04 00:05 UTC, edalex-ian commented on CONTRIBUTING.md
> +~$ ./sbt resources
As mentioned, we want to have consistent style, so remove the shell prompt (here, and also all the others):

```suggestion
./sbt resources
```

2021-11-04 00:05 UTC, edalex-ian commented on CONTRIBUTING.md
> +However if you don't, then the CI pipelines will fail during checking.
```suggestion
However if you don't, then the CI pipelines will fail for your pull requests.
```

2021-11-05 02:29 UTC, edalex-ian requested changes
So so close. Just the 'Running the admin tool' section seems to have gone wacky.

2021-11-05 02:29 UTC, edalex-ian commented on CONTRIBUTING.md
>  Ensure you have your server running and know it's
Hmmm, something has gone astray here. :thinking:

2021-11-05 04:56 UTC, edalex-yinzi commented on CONTRIBUTING.md
>  Ensure you have your server running and know it's
I move this sentence from `build installer` section. I think it just means we can get rid of the init step (those loding info) each time?

2021-11-07 23:15 UTC, edalex-ian commented on CONTRIBUTING.md
>  Ensure you have your server running and know it's
Okay, how about you change this section to read:

```
### Running the Admin Console

Once you have successfully started the server with the above commands, you can then launch the Admin Console
to manage it. To do so from the command line with SBT, run:
```

2021-11-07 23:57 UTC, edalex-yinzi commented on CONTRIBUTING.md
>  Ensure you have your server running and know it's
Wired, I got this error when running this command. 

`./sbt compile adminTool/run`

![image](https://user-images.githubusercontent.com/92769668/140666777-e97fa454-5c0a-45f3-a35d-0f8c34a7d9b6.png)

2021-11-08 00:39 UTC, edalex-ian commented on CONTRIBUTING.md
>  Ensure you have your server running and know it's
Oh wow that is odd. That'd be attempting to use javaws perhaps to launch a Java WebStart application - which is what the Admin Console was until only a couple of years ago when we changed it. Strange though, I would've expected that task to run the class...

I reckon leave it in there, but we'll need to raise an issue to look at how that task is written.

2021-11-11 02:36 UTC, edalex-yinzi commented on CONTRIBUTING.md
>  Ensure you have your server running and know it's
I asked Penghai to check this command on his laptop, he said it works. So maybe it's my env's issue.

2021-11-11 03:14 UTC, edalex-ian approved these changes
Woohoo! Great to have this doco in better shape. A big leap forward. :+1:

2021-11-11 03:14 UTC, merged