Feature/process adv search criteria
openequella/openEQUELLA pull request #3561
Opened 2021-11-03 08:58 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This is the first PR for building advanced search criteria. 

In draft for now.

2021-11-03 23:57 UTC, edalex-ian requested changes
Looks good, but two key tweaks:

1. Use Optional in the interface - which in turn will also require tweaks through the other layers; and
2. Need to make sure the test also exercises the idea of merging the custom query with another query falling out of the other params being specified.

2021-11-03 23:57 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.base/src/com/tle/common/searching/Search.java
> +  }
Could we push with the new direction of Optional?

```suggestion
  default Optional<String> getCustomLuceneQuery() {
    return Optional.empty();
  }
```

If doing this, make sure to update the JavaDoc too.

2021-11-03 23:57 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.base/src/com/tle/common/searching/Search.java
> +   * The background of creating this method is to support the Lucene query built in New Advanced
Rather than just jumping straight into the background, be good to also have the description of the method still.

```suggestion
   * Returns an optional additional query which is in raw text Lucene query syntax, available to be merged with other
   * query parameters.
   *
   * <p>The background of creating this method is to support the Lucene query built in New Advanced
```

2021-11-03 23:57 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/model/SearchParam.scala
> +  @ApiParam("Custom Lucene query")
```suggestion
  @ApiParam("Custom Lucene query which will be merged with the query generated from the other parameters")
```

Although in that suggestion where I put "will be merged" it would be good to say _how_ it will be merged. AND, OR, other?

2021-11-03 23:57 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ApiTest.java
> +    JsonNode result = doSearch(200, null, new NameValuePair("customLuceneQuery", q));
I think you need the test to also include at least one other param (collection perhaps - but has to actually have a tangible impact on the results) so that the `customLuceneQuery` has to go through merging with the other params.

2021-11-04 03:28 UTC, PenghaiZhang commented on autotest/OldTests/src/test/java/io/github/openequella/rest/Search2ApiTest.java
> +    JsonNode result = doSearch(200, null, new NameValuePair("customLuceneQuery", q));
Good idea! Added!.

2021-11-04 04:26 UTC, edalex-ian approved these changes

2021-11-05 04:29 UTC, edalex-ian approved these changes
Great stuff @PenghaiZhang (even with your sneaky extra commit). :wink: :+1:

2021-11-06 06:05 UTC, PenghaiZhang commented
Failed on `BulkMetadataEditTest` so will merge on.

2021-11-06 06:06 UTC, merged