Component/add clear button to advanced search
openequella/openEQUELLA pull request #3575
Opened 2021-11-10 02:57 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Add clear button in advanced search.
Click Clear button will clear filters and update search results.

Also, Ian fix a bug in `getOptionValues`.

https://user-images.githubusercontent.com/92769668/141041087-894cc193-c9cd-4248-ae35-96b218a24f08.mp4

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2021-11-10 22:45 UTC, edalex-ian commented
That test failure is all fine, just on a known flakey test - `EquellaConnectorTest`.

2021-11-10 23:45 UTC, edalex-ian requested changes
Great start there @edalex-yinzi , and good to see you taking fp-ts for a spin already.

As you can see, a few bits of feedback to look at, main ones being:

- Tiding up your pipe in the test; and
- Reworking how you're trigger a search after the clear button is clicked.

2021-11-10 23:45 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +    };
Not required (see following comment). But also, be aware this could have been done as:

```suggestion
    const isNotEmptyMap = (m: Map<unknown, unknown>): boolean => !M.isEmpty(m);
```

2021-11-10 23:45 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +    const afterClearLabelsAndValues: WizardControlLabelValue[] = pipe(
Great to see you using fp-ts already. Well done.

Just something to keep in mind though, it is important to aim for consistent style. So unless you really needed to use fp-ts here, you'd really want to use the pattern used elsewhere in this function - .e.g `buildMockedControls.map()`.

And further keeping that in mind, you now have multiple implementation of the same code (more or less), so to follow the [DRY principal](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), you'd want to functionalise it and in this and the above places use the new function. Perhaps in the new function you could do it with fp-ts, but up to you.

2021-11-10 23:45 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +      A.filter(isNotEmptyMap),
Only recently did I finally find how better to do these negated cases with fp-ts.

First:

```typescript
import { not } from "fp-ts/Predicate";
```

Then you can simply do this line as:

```suggestion
      A.filter(not(M.isEmpty)),
```

2021-11-10 23:45 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +      ),
With the above in mind, this becomes:

```suggestion
      A.filter(
        flow(
          M.filter(not(A.isEmpty)),
          not(M.isEmpty)
        )
      ),
```

2021-11-10 23:45 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +        )
And let's continue the theme:

```suggestion
        flow(
          M.filter(flow(
              A.filter(not(S.isEmpty)),
              A.isNonEmpty
            )
          ),
          not(M.isEmpty)
        )
```

Not also here I've dropped your type coercion (i.e. `m as string[]`). You don't want to be doing that at all, most of the type you can solve this by explicitly specifying the types for the generics. So if you take the above approach but then have type issues, look at the generic type specifiers rather than adding the coercion back in.

2021-11-10 23:45 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +    );
And now at the end of the pipe let's revisit the `not(M.isEmpty)`. Rather than doing it as the first step, and then continuing to do it in each of the intermediate steps. You could do it just once right at the end here.

2021-11-10 23:45 UTC, edalex-ian commented on react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
> +          onClick={() => onClear()}
Redundant arrow operator. Keep in mind we have first class function support, so:

```suggestion
          onClick={onClear}
```

2021-11-10 23:45 UTC, edalex-ian commented on react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
> +  const [isTriggerClearSearch, setIsTriggerClearSearch] = useState(false);
Not required. Only `useState` and `useEffect` if you have to - as they quickly amp up the complexity.

Instead, you'd simply want to factor out the function currently on the search button, so to something like:

```typescript
const doSearch = () => onSubmit(currentValues)
```

Then update the search button to use that, and in your `onClear` function rather than calling `setIsTriggerClearSearch()` call `doSearch()`.

2021-11-10 23:45 UTC, edalex-ian commented on react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
> +    setIsTriggerClearSearch(true);
See above comment.

2021-11-10 23:45 UTC, edalex-ian commented on react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
> +
As per previous comments, not required.

2021-11-11 04:20 UTC, edalex-yinzi commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +        )
Still got errors by explicitly specifying the types for generics. I tried to use ternary to avoid the error. Not sure whether it's a good solution? See the latest commit.

2021-11-11 08:32 UTC, edalex-ian requested changes
Ah okay, I see the union type of `string | string[]` may be causing your havoc, but see what you can do with the suggestions.

But you're almost there. Grab me tomorrow if there's time.

2021-11-11 08:32 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +    const afterClearLabelsAndValues: WizardControlLabelValue[] = pipe(
Ummm, although you marked this as resolved you don't appear to have taken any action on it. Please action.

2021-11-11 08:32 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +          not(M.isEmpty)
As mentioned, rather than repeating yourself, just do this once as a final pass - i.e. Add another `A.filter` which is just doing a `not(M.isEmpty)`.

2021-11-11 08:32 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +          ),
You'll probably find that you have a look at our `pfTernary` and then either `isStringArray` or `S.isString` you'll be able to improve the readability of this. (e.g. `M.filter(pfTernary(S.isString,not(S.isEmpty),not(A.isEmpty))` - but your YMMV depending on the types etc - and hence why `isStringArray` may be a better fit.

2021-11-11 08:32 UTC, edalex-ian commented on react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
> +  const doSearch = (value = currentValues) => onSubmit(currentValues);
Do you really need the default value here? Ideally we want `doSearch` to only ever use what's in state. :thinking:

2021-11-11 23:14 UTC, edalex-yinzi commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +    const afterClearLabelsAndValues: WizardControlLabelValue[] = pipe(
Aha,  I didn't notice the duplicated code in the previous test. But now I know what you mean.

2021-11-11 23:31 UTC, edalex-yinzi commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +          not(M.isEmpty)
Since there is a filter wrapper around this, I need to change the logic of this function to achieve this improvement.

2021-11-11 23:41 UTC, edalex-yinzi commented on react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
> +  const doSearch = (value = currentValues) => onSubmit(currentValues);
There is a mistake here, onSubmit should use `values` as param. And the reason I left a param here is we can call doSearch immediately after `setCurrentValues`  by passing an empty map rather than the default value `currentValues` which might not update immediately?

2021-11-12 00:44 UTC, edalex-yinzi commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +          ),
Work out!

2021-11-12 01:10 UTC, PenghaiZhang commented on react-front-end/tsrc/search/components/AdvancedSearchPanel.tsx
> +  const doSearch = (value = currentValues) => onSubmit(value);
I am not sure if you need this and `onClear`. You can update the props to have `onClear` and then in SearchPage you can just do `onClear={() => handleSubmitAdvancedSearch(new Map())}`  

Please note `handleSubmitAdvancedSearch` is a new function in my PR.

2021-11-12 04:17 UTC, edalex-ian requested changes
Very close now. Last tweaks for test, and then @PenghaiZhang 's suggestion for the clear prop for the button, and you'll be done.

2021-11-12 04:17 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +              A.filter((arrayItem) => arrayItem !== ""),
Can that just be:

```suggestion
              A.filter(not(S.isEmpty)),
```

2021-11-12 04:17 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +            () => false
Have a look at things like `constTrue`, `constFalse` which provide nice little helpers for these cases.

2021-11-12 04:17 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +    const filteredLabelsAndValues = pipe(
This now being rather long, it makes sense to pull it out into a function over in `AdvancedSearchTestHelper.ts` so  as to maintain readability of this test.

Perhaps a function like: `const filterEmptyValues = (labelsAndValues: WizardControlLabelValue[]): WizardControlLabelValue[] => flow(...)`.

Then you can just call that direct in your expect statement below. (e.g. `expect(pipe(getCurrentLabelsAndValues, filterEmptyValues)).toEqual([])`).

2021-11-14 06:26 UTC, edalex-ian commented
Heya @edalex-yinzi 

To action that last part of feedback from @PenghaiZhang , could you please merge `component/advanced_search` into your branch and then proceed?

Thanks,

2021-11-14 23:28 UTC, edalex-ian approved these changes
LGTM. Let's await a green build and then merge. :+1:

2021-11-15 01:16 UTC, edalex-ian commented
Cool, just failed on ol' flaky `AdvancedScriptControlTests`.

Merging.

2021-11-15 01:16 UTC, merged