Feature/process adv search criteria
openequella/openEQUELLA pull request #3576
Opened 2021-11-10 04:55 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This is the third PR for building the Advanced search criteria.

1. Add the support for Tokensation in REST Module.
2. Create `TokensationModule` which talks to the REST Module in `react-front-end` .
3. Update the type definition of `ControlTarget` to include a new flag indicating whether to tokenise.
4. Create functions to build raw Lucene queries in `WizardHelper`.

2021-11-10 22:04 UTC, PenghaiZhang commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +      .join(AND)})`;
I will need to confirm it is `and` or `or` here. I remember it's `or` in Old UI, but I think it should be `and`...Let me confirm.

2021-11-11 02:07 UTC, edalex-ian requested changes
Nice work @PenghaiZhang . Considering what it's doing I find it very readable. Great job! :+1: 

Couple of tweaks requested, and one query a potential issue with calendars. BTY.

2021-11-11 02:07 UTC, edalex-ian commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +  S.isString(s) && not(S.isEmpty)(s);
In the interest of pointfree I was trying to understand how you'd use the `and` combinator here. But all I've come up with is:

```typescript
import * as S from "fp-ts/string";
import { not, and } from "fp-ts/Predicate";
import { flow, pipe } from "fp-ts/function";

const isNonEmptyString: (s: string | number) => s is string = flow(
  pipe(S.isString, and(not(S.isEmpty)))
);
```

I'm not sure that's an improvement - and may cause some type concerns. So in your case where you're not limited to functions (i.e. not in a pipeline) you'd probably be better as:

```suggestion
  S.isString(s) && !S.isEmpty(s);
```

The Predicate combinators are really only great inside pipelines where you want to stick to functions and being pointfree.

2021-11-11 02:07 UTC, edalex-ian commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +      .map((n) => builder(`${n}${isValueTokenised ? "\\*" : ""}`, values))
It would be good to document this weird asterisk field name suffix - just think of the confusion it caused us. Maybe to keep things clear it could be good to have a function like:

```typescript
/**
 * Create the fieldname matching the format of the fields used in the oEQ lucene index. Specifically, for any
 * schema node which is tokenised, there are two fields. One which contains full raw values, and another which
 * has gone through the analyzer (and tokenizer). This name of this second type of has an asteriks (`*`) suffix.
 *
 * This function then looks after adding this special suffix when required based on the `isTokenised` flag.
*/
const fieldName: (name: schemaNode, isTokenised: boolean) => string
```

Sommink like that...

2021-11-11 02:07 UTC, edalex-ian commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +          [start, end]: ControlValue
Keep in mind you're essentially shadowing the `start` and `end` created above... Might want to try for some other names to avoid potential issues.

2021-11-11 02:07 UTC, edalex-ian commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +        );
But if I provide `["", "2021-11-11"]` wouldn't this mean my `end` date suddenly becomes my start date?

2021-11-11 02:07 UTC, edalex-ian commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +          E.fromPredicate(S.isString, () => ""), // No query needed when both are undefined so return an empty string.
Why not just start with `E.fromPredicate(start || end, () => "")`?

2021-11-11 03:31 UTC, PenghaiZhang commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +  S.isString(s) && not(S.isEmpty)(s);
Yeah I agree. The `!` looks better

2021-11-11 03:35 UTC, PenghaiZhang commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +      .map((n) => builder(`${n}${isValueTokenised ? "\\*" : ""}`, values))
Good idea!!! Added.

2021-11-11 03:38 UTC, PenghaiZhang commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +          E.fromPredicate(S.isString, () => ""), // No query needed when both are undefined so return an empty string.
`start || end` is not a predicate though.

2021-11-11 03:38 UTC, PenghaiZhang commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +        );
Aaaaaaaaah...yeah.. this is a problem.. Let me think how to fix it.

2021-11-11 08:03 UTC, edalex-ian requested changes
Almost there, I just think we need to tighten up the handling of those date `values` to avoid us pain in the future. (See comment.)

2021-11-11 08:03 UTC, edalex-ian commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +        const [start, end] = A.filter(S.isString)(values);
This could still lead to unpredictable behaviour if there has been some messed up data - e.g. `[123, "2021-11-11"]`.

I think you need to do some validation somewhere with: `isStringArray` and `A.size === 2`. And arguably if it's not, maybe you should throw a `TypeError`.

I think that goes back to then the start of the pipe using the  `||` operator as a shortcut to make sure at least one string is present. But once you've validated the types (and know you have a string array of two elements) that could then be replaced with:

```typescript
pipe(
  values,
  E.fromPredicate(A.every(not(S.isEmpty)), () => ""),
  E.map(A.map(processDateString)),
  E.fold(
    identity,
    (dates) => buildQueries(schemaNode, dates, dateRangeQueryBuilder)
  )
);`.

2021-11-11 08:52 UTC, PenghaiZhang commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +        const [start, end] = A.filter(S.isString)(values);
I like this idea, but I also want to slightly change the validation to `isStringArray && A.size <= 2` because there may be only one value. For instance, if you set a default value, the endpoint would just return `["2011-01-01"]`  rather than `["2011-01-01", ""]`.

2021-11-11 12:13 UTC, edalex-ian approved these changes
Thanks @PenghaiZhang , great job on this, I look forward to seeing the integration. :+1: 

Merge on! :tada:

2021-11-11 22:06 UTC, PenghaiZhang commented
GHA failed on a couple flaky tests so merge on.

2021-11-11 22:06 UTC, merged