feat: integrate Advanced search criteria with New Search UI
openequella/openEQUELLA pull request #3578
Opened 2021-11-11 23:34 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This is the fourth (and hopefully the last) PR for the advanced search criteria. It's all about the integration with `SearchPage`.
 
Main changes are:
1. Add a new field to `SearchParam` and `SearchOptions` to support the raw Lucene query.
2. Hide the Adv search panel whenever a search is triggered.
3. Update how to generate the initial advanced search query values.
4. Rework how to perform the initial search.
5. Update how to check if any adv search criteria has been set.

2021-11-12 03:58 UTC, edalex-ian requested changes
Lookin' good @PenghaiZhang . A couple of queries, and a couple of requests for shuffling. :wink:

2021-11-12 03:58 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +    // Search with the EditBox's default value.
Hmmm, but doesn't that now happen on initial render?

2021-11-12 03:58 UTC, edalex-ian commented on react-front-end/tsrc/modules/SearchModule.ts
> +  advFieldValue?: FieldValueMap;
Are these `SearchOptions` or `SearchPageOptions`?

2021-11-12 03:58 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +          );
In a continued bid to keep this effect and SearchPage.tsx under control, this should probably be placed in a function in SearchPageHelper.tsx. And then would it be possible to place that function in the array of functions for the `Promise.all` block? Or (acknowledging dependencies on the output from other items in that array), how about simply changing the line in setting `customeLuceneQuery` of `initialSearchPageOptions` to call the new function (with `await`)?

2021-11-12 03:58 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +      A.some((v) => v.length > 0)
Function should sit over in `WizardHelper` me thinks. :wink:

2021-11-12 04:04 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/search/AdvancedSearch.test.tsx
> +    // Search with the EditBox's default value.
Ah yeah! Do not need to click the button at all.

2021-11-12 04:07 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPage.tsx
> +      A.some((v) => v.length > 0)
Ah yes! `isControlValueNonEmpty` I found it.

2021-11-12 05:05 UTC, PenghaiZhang commented on react-front-end/tsrc/modules/SearchModule.ts
> +  advFieldValue?: FieldValueMap;
`advFieldValue` has been moved `SearchPageOptions`.

2021-11-14 06:23 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +      A.some((v) => v.length > 0)
As discussed, once merged then this can be refactored in another PR. :wink:

2021-11-14 06:23 UTC, edalex-ian approved these changes
As discussed, all looks good and I'm happy to wait for that last bit to be refactored as part of another PR.

2021-11-14 06:24 UTC, edalex-ian commented
Will merge now to keep the ball rolling so that @edalex-yinzi can merge to his clear button branch to finish that feature.

2021-11-14 06:24 UTC, merged