bugfix: add a visiable waiter to avoid StaleElementReferenceException
openequella/openEQUELLA pull request #3582
Opened 2021-11-15 05:00 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Trying to fix this issue, but failed to reproduce in local env. 

![image](https://user-images.githubusercontent.com/92769668/141724611-62996443-b412-483b-ba93-983af4777232.png)

But based on this [reference](https://stackoverflow.com/questions/38596456/how-to-over-staleelementreferenceexception-when-working-with-pagefactory)  I add a waiter before clicking the finish button. Not sure if it works or not.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2021-11-15 05:05 UTC, edalex-yinzi commented
Seems the usage is wrong....

2021-11-15 05:38 UTC, edalex-yinzi commented
Also, I found an interesting situation. It seems every failed test was come after by a test call `accessDenied`.

![image](https://user-images.githubusercontent.com/92769668/141727926-56c149d3-85fb-4eeb-9c6a-ef059070ed68.png)

2021-11-15 06:05 UTC, edalex-yinzi commented
I reproduce the same error by adding a command `logout` which is also used in `accessDenied`. So,  I guess this test will influence the login session globally and cause failure to another test that is running at the same time.

2021-11-16 04:49 UTC, edalex-yinzi commented
Looks good so far, I will move this change to #3584 and see how it works.

2021-11-18 01:17 UTC, edalex-ian requested changes
Good start @edalex-yinzi . I like where you've put the waiter as it aligns with the stale element exception we're seeing. However I think it still needs a bit more consideration.

(And let's not worry about the `@After`.)

2021-11-18 01:17 UTC, edalex-ian commented on autotest/OldTests/src/test/java/io/github/openequella/rest/DrmApiTest.java
> +  @After
As discussed, this should be removed.

2021-11-18 01:17 UTC, edalex-ian commented on autotest/Tests/src/main/java/com/tle/webtests/pageobject/selection/SelectionStatusPage.java
> +    ExpectWaiter.waiter(ExpectedConditions.visibilityOf(finishedButton), this).get();
Keep in mind that the main symptom being seeing is that `finishedButton` has become **stale**. As a result, even if you wait here, when you go to click below that's still no good - the original object is still stale.

Perhaps rather than relying on the class level button property:

- Change the class level property to a `By`; then
- In this method add a `WebElement finishButton = ...`; and
- Consider using something like `com.tle.webtests.pageobject.AbstractPage#waitForElement(org.openqa.selenium.By)`

2021-11-22 00:12 UTC, edalex-ian commented
Ran cleanly other than flaking on known flaky - AdvancedScriptControlTests.

Doing rerun 2, and if we get 3 all happy we'll merge.

2021-11-22 00:12 UTC, edalex-ian approved these changes

2021-11-22 06:36 UTC, edalex-ian commented
Run 2 was all green. Starting third and final. If green, will merge. :wink:

2021-11-22 21:49 UTC, edalex-ian commented
Alright, another pass. Merging now.

2021-11-22 21:49 UTC, merged