refactor: ThemePage
openequella/openEQUELLA pull request #3587
Opened 2021-11-17 04:07 UTC by edalex-yinzi

…y for it

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
Convert ThemePage to functional component.
Create a story for ThemePage.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2021-11-17 04:19 UTC, edalex-yinzi commented
Found two conflict variables `LogoSettings`...

2021-11-18 02:04 UTC, edalex-ian requested changes
Looking good @edalex-yinzi . Mostly just tidy up and making things consistent with existing codebase.

BTY.

2021-11-18 02:04 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
> +interface IThemeColors {
Please remove the `I` prefix (include the places below you've added it) - you'll note we don't use this coding style. Please be consistent with existing code style. :wink:

2021-11-18 02:04 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
> +  const mapThemeSettings2ThemeColors = (
Just looking at this naming:

- Could we please avoid the `2` and instead use `To`; and
- To shorten how about just `mapSettingsToTheme`?

2021-11-18 02:04 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
> +    _themeSettings = themeSettings
The default here obfuscates what's happening in some cases. Best to require the value to be mapped to always be provided. Please remove default.

Also, rather than `_themeSettings` just go with `settings`. But, please also include the type.

2021-11-18 02:04 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
> +    return {
`return` is redundant here, just going with a simple arrow function expression, i.e.:

```
const mapSettingsToTheme = (settings: ??): IThemeColors => ({
  primary: settings.PrimaryColor,
  // etc
});
```

2021-11-18 02:04 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
> +    return {
Same feedback above:

- Rename: `mapThemeToSettings`
- Drop the default for `_themeColors` and rename to just `theme` (keep the default for `fontSize` though as that's not confusing things);
- Add typing; and
- Remove redundant `return`.

2021-11-18 02:04 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
> +    setIsChangesUnsaved(true);
Hmmmm, but below they are saved when you call `submitTheme`. So this line is either wrong or not required. :thinking:

2021-11-18 02:04 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
>    };
This seems odd. It could be simplified to:

```typescript
const reload = window.location.reload;
```

2021-11-18 02:04 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
> +    themeSettings: IThemeSettings = mapThemeColors2ThemeSettings()
Although fun that we can do this kind of thing with the language, it obfuscates what's really happening. Please remove the default - no need for one here.

2021-11-18 02:04 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
> +      onSave={() => saveChanges()}
```suggestion
      onSave={saveChanges}
```

2021-11-18 03:17 UTC, edalex-yinzi commented on react-front-end/tsrc/theme/ThemePage.tsx
> +    setIsChangesUnsaved(true);
It's the issue I mentioned in slack. I will delete this.

2021-11-18 04:17 UTC, edalex-yinzi commented on react-front-end/tsrc/theme/ThemePage.tsx
>    };
Error said "Uncaught TypeError: Illegal invocation". Need bind context window. So I will only remove the `{}`.

2021-11-18 06:14 UTC, edalex-ian requested changes
Looking good @edalex-yinzi, just one minor change to convert a `function` to an arrow function.

2021-11-18 06:14 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
> +  async function saveChanges() {
Ah, I missed this, for consistency please change to an arrow function (i.e. `const saveChanges = async () => {....}`).

2021-11-18 06:14 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
> +  const mapSettingsToColors = (settings: IThemeSettings): ThemeColors => ({
No action required on this, just FYI:

Aaaahhhh, this now highlights potentially why you were prefixing all the interfaces with `I`. Due to this (IThemeSettings) I went and had a closer look at the file it's in and that highlighted extra things to be done as part of the broader refactor you're doing here. I'll capture the detail in the internal Jira ticket.

But just quickly highlighting, in the work your doing to add the Theme endpoints to oeq-ts-rest-api I'd expect `IThemeSettings` to become `ThemeSettings` and live in something like `OEQ.Theme`.

2021-11-22 00:07 UTC, edalex-ian approved these changes
Good stuff. Thanks @edalex-yinzi

2021-11-22 00:07 UTC, merged