Api/theme
openequella/openEQUELLA pull request #3590
Opened 2021-11-19 01:23 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

Create api with tests for Theme module.

API: 
  - getThemeSettings,
  - updateThemeSettings,
  - getThemeLogo,
  - updateThemeLogo,

Because I am still struggling with tests for theme logo, only contains tests for:
 - getThemeSettings
 - updateThemeSettings

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2021-11-19 04:38 UTC, edalex-yinzi commented
testAddMyResource failed

2021-11-22 00:24 UTC, edalex-ian approved these changes
Looks pretty good @edalex-yinzi , just need to:

- Write you own type guard instead of using `is`;
- Tidy up the modification of the settings after test; and
- Revisit the use of `File` and remove `dom` from the libraries.

2021-11-22 00:24 UTC, edalex-ian commented on oeq-ts-rest-api/src/Theme.ts
> +    (data): data is any => is<any>(data)
As discussed, don't use `is` (typescript-is) here, instead you need to manually write a type guard.

2021-11-22 00:24 UTC, edalex-ian commented on oeq-ts-rest-api/test/Theme.test.ts
> +  beforeAll(async () => {
Be a good idea to add an `afterAll()` to return them to `settingsAtStart`.

2021-11-22 00:24 UTC, edalex-ian commented on oeq-ts-rest-api/tsconfig.json
> +      "dom"
Do we really need this?

I gather you've added for `File`, but the oEQ server has no notion of a `dom` `File`. So perhaps we need something else, as that concern would only be in the front-end's Theme Module.

2021-11-22 00:25 UTC, edalex-ian requested changes
Whoops, that was meant to be a 'request changes'. Sorry. :wink:

2021-11-22 00:31 UTC, edalex-yinzi commented on oeq-ts-rest-api/src/Theme.ts
> +    (data): data is any => is<any>(data)
Yes, just wonder do we still need this API, if we are not going to test the reset of logo API.

2021-11-22 00:46 UTC, edalex-yinzi commented on oeq-ts-rest-api/test/Theme.test.ts
> +  beforeAll(async () => {
Do you mean reset the value of the setting in afterAll?

2021-11-22 00:51 UTC, edalex-ian commented on oeq-ts-rest-api/test/Theme.test.ts
> +  beforeAll(async () => {
Yup. :+1:

2021-11-22 00:53 UTC, edalex-ian commented on oeq-ts-rest-api/src/Theme.ts
> +    (data): data is any => is<any>(data)
Could drop it, and just add something like:

```typescript
export const getThemeLogoUrl = (apiBasePath: string): string =>
  apiBasePath + THEME_ROOT_PATH + '/newLogo.png';
```

2021-11-22 02:21 UTC, edalex-yinzi commented on oeq-ts-rest-api/tsconfig.json
> +      "dom"
Use blob instead?

2021-11-22 02:42 UTC, edalex-ian commented on oeq-ts-rest-api/tsconfig.json
> +      "dom"
Yeah, if that works and matches the server API.

2021-11-22 02:52 UTC, edalex-yinzi commented on oeq-ts-rest-api/tsconfig.json
> +      "dom"
After testing, `Buffer` might be a good type.

2021-11-22 03:05 UTC, edalex-ian commented on oeq-ts-rest-api/tsconfig.json
> +      "dom"
Just make sure whatever you choose works in Browsers.

2021-11-22 04:12 UTC, edalex-yinzi commented
I might not implement any test for theme logo in this branch because it needs more consideration. 
Also, I keep the `File` type in theme logo API in order to use it in browsers.

What do you think? @edalex-ian

2021-11-22 05:19 UTC, edalex-ian approved these changes
Sure thing. It's not super critical, and it's not leaving it worse than you found it, so let's proceed.

2021-11-22 06:35 UTC, edalex-ian commented
Heh, flaked on `MyResourcesTest`. Good to merge. :wink:

2021-11-22 06:35 UTC, merged