refactor(frontend): integrate ThemePage with rest Theme API
openequella/openEQUELLA pull request #3594
Opened 2021-11-23 01:26 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
1. Replace all Axios requests with rest API from the rest module.
2. Move content in theme/index.ts to /modules/ThemeModule.ts.
3. Replace old errorHandle with a new function setError.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2021-11-23 23:12 UTC, edalex-ian requested changes
Nice work @edalex-yinzi , just need to rework one area and we should be good to go.

2021-11-23 23:12 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
> +    reload();
You've done a curious mix here of the new school async/await and the old school promise chains.

One of the key drivers for the introduction of async/await was the removal promise chains. So could you please revert to the try/catch approach?

2021-11-23 23:37 UTC, PenghaiZhang reviewed
Thanks @edalex-yinzi ! My comment is about the future conflicts.

2021-11-23 23:37 UTC, PenghaiZhang commented on react-front-end/tsrc/theme/ThemePage.tsx
> +  const setError = useError((error: Error) => {
Seeing this,  I believe there will be lots of conflicts when we merge component to develop because the props of this page, how to export it and how to handle errors is different.

2021-11-23 23:43 UTC, PenghaiZhang commented on react-front-end/tsrc/theme/ThemePage.tsx
> +  const setError = useError((error: Error) => {
I think the future conflicts won't be hard to address so let's continue.

2021-11-24 06:17 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
> +  const setError = useError((error: Error) => {
Good point though @PenghaiZhang , I'll do a quick diff before merging to check how bad.

2021-11-25 00:55 UTC, edalex-ian requested changes
Looks like you may have rushed that refactor a little, please fix the problems.

2021-11-25 00:55 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
> +          : new Error(`Unexpected non-Error caught in saveChanges(): $(error)`)
Whoops, you've got a typo there:

```suggestion
          : new Error(`Unexpected non-Error caught in saveChanges(): ${error}`)
```

2021-11-25 00:55 UTC, edalex-ian commented on react-front-end/tsrc/theme/ThemePage.tsx
>        reload();
Ummm, looks like you've made quite a mess of it here (doubled up, dropped a key one). How about just get the original code and copy it back in which would result in no differences being highlighted here.

2021-11-25 03:11 UTC, edalex-yinzi commented
Sorry, looks like I was still in the dream at that time. :face_with_spiral_eyes: 

> Looks like you may have rushed that refactor a little, please fix the problems.

2021-11-26 04:13 UTC, edalex-ian approved these changes

2021-11-26 04:21 UTC, edalex-ian commented
@PenghaiZhang I did have a look at the diff between this version of ThemePage.tsx and that on component/advanced-search and they will indeed heavily conflict. More so due to the refactor from class based to functional based component.

On merge, the best idea will probably be to simply take this version as is, and then manually convert to the new WithError HOC. Will that still be pretty straightforward?

If so, then I'll merge.

2021-11-26 05:35 UTC, edalex-yinzi commented
HOC represents what?

2021-11-26 05:55 UTC, edalex-ian commented
HOC : HigherOrderComponent

https://reactjs.org/docs/higher-order-components.html

2021-11-28 03:49 UTC, PenghaiZhang commented
> @PenghaiZhang I did have a look at the diff between this version of ThemePage.tsx and that on component/advanced-search and they will indeed heavily conflict. More so due to the refactor from class based to functional based component.
> 
> On merge, the best idea will probably be to simply take this version as is, and then manually convert to the new WithError HOC. Will that still be pretty straightforward?
> 
> If so, then I'll merge.

I think so. Let's merge this .

2021-11-28 23:38 UTC, merged