Feature/build advanced search criteria on front end
openequella/openEQUELLA pull request #3596
Opened 2021-11-24 04:23 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds the support for building Advanced search criteria on both REST Module and React front end.

The key changes are:

1. Add a new function to execute a search with additional params through a POST request.
2. Update a new field to `SearchOptions` to represent Advanced search criteria.
3. Update `SearchModule` to control whether to search through a POST or GET.
4. Update `WizardHelper` to support building the criteria.
5. Update `SearchPage` and `reducer` for the integration.

I also dropped some of the code written previously to support this feature.

https://user-images.githubusercontent.com/47203811/143174597-5367fcd9-99ed-4d2a-86fc-ba60664dbd67.mp4

2021-11-25 01:54 UTC, edalex-ian reviewed
Looks pretty good @PenghaiZhang . Just two minor items for you. :wink:

2021-11-25 01:54 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/components/wizard/WizardHelper.test.ts
> +  it("builds raw Lucene query for Wizard controls", () => {
Needs rewording... Perhaps:

```suggestion
  it("builds SearchAdditionalParams for Wizard controls", () => {
```

2021-11-25 01:54 UTC, edalex-ian commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +        O.fromPredicate(A.exists(not(S.isEmpty))), // No query needed when both are undefined.
Probably redundant for two reasons:

1. `dateRange` is of type `NEA.NonEmptyArray<string>` - so we know it's non-empty and it has `string`s in it; and
2. That is because above you used the `isStringArray` which from memory checks the members are actual strings - non empty.

2021-11-25 02:03 UTC, PenghaiZhang commented on react-front-end/__tests__/tsrc/components/wizard/WizardHelper.test.ts
> +  it("builds raw Lucene query for Wizard controls", () => {
oops I forgot to update the description. :smile:

2021-11-25 02:06 UTC, PenghaiZhang commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +        O.fromPredicate(A.exists(not(S.isEmpty))), // No query needed when both are undefined.
But `dateRange` can be `["", ""]`, can it not ?

2021-11-25 02:07 UTC, PenghaiZhang commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +        O.fromPredicate(A.exists(not(S.isEmpty))), // No query needed when both are undefined.
The comment is wrong. 
It should be `// No query needed when both are empty strings.`

2021-11-25 03:52 UTC, edalex-ian approved these changes
All sounds good @PenghaiZhang , merge when ready. :+1:

2021-11-25 10:18 UTC, edalex-ian requested changes
Sorry @PenghaiZhang ,  I just belatedly realised something... There's two functions in the wrong file - see comment.

Could you please shuffle them as per one of the suggestions?

2021-11-25 10:18 UTC, edalex-ian commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +export const generateAdvancedSearchCriteria = (
Oh hold on! I mentioned this in a side channel somewhere, but then forgot about it. These **Advanced Search** specific functions should not be in the **Wizard** helper - they're not about the generic concept, but a specific use case.

So this (and `queryFactory`) should either be in a `tsrc/search/AdvancedSearchHelper.ts` or alongside `initialiseAdvancedSearch` over in `tsrc/search/SearchPageHelper.ts`. Personally, I feel there's value in creating `AdvancedSearchHelper.ts` and moving `initialiseAdvancedSearch` into it as well.

2021-11-25 22:43 UTC, PenghaiZhang commented on react-front-end/tsrc/components/wizard/WizardHelper.tsx
> +export const generateAdvancedSearchCriteria = (
I have created `AdvancedSearchHelper.ts` and move these functions to there :smile: .

2021-11-25 23:21 UTC, edalex-ian approved these changes
Excellent, thanks for the refactor @PenghaiZhang :+1:

2021-11-28 03:46 UTC, PenghaiZhang commented
Failed on flaky test `ItemApiEditTest` so merge on.

2021-11-28 03:46 UTC, merged