Feature/support search shared from old UI
openequella/openEQUELLA pull request #3630
Opened 2021-12-06 04:10 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This PR adds the support for converting a Legacy advanced search criteria into a `PathValueMap` which can be further used to generated a `FieldValueMap`. As a result, any search shared from Old UI or favourited in Old UI can be viewed in the new Search UI.

2021-12-07 00:17 UTC, edalex-ian requested changes
Looks good @PenghaiZhang , seems to have come together reasonably nicely. :+1: 

Just a few things to change up a little though, and a query or two. :wink:

2021-12-07 00:17 UTC, edalex-ian commented on react-front-end/tsrc/search/AdvancedSearchHelper.ts
> +// Function to pull values of PathValueMap and copy to FieldValueMap for each unique Schema node.
Convert to TSDoc.

2021-12-07 00:17 UTC, edalex-ian commented on react-front-end/tsrc/search/AdvancedSearchHelper.ts
> +          A.map(RA.toArray),
Why did you need to `RA.toArray` here?

2021-12-07 00:17 UTC, edalex-ian commented on react-front-end/tsrc/search/AdvancedSearchHelper.ts
> +          A.map((n) => pMap.get(n) ?? v),
Two things here:
1. Although slightly longer, I think it makes sense to stay in the paradigm and use `M.lookup` rather than `pMap.get()`; and
2. I think it's help to pull the arrow function you're passing to `M.mapWithIndex` out to highlight what it's doing - along with more meaningful param names.

For example:

```typescript
const fromPathValueMap = ({schemaNode}: ControlTarget, defaultValue: ControlValue): ControlValue =>
  pipe(
    schemaNode,
    A.map((node) => pipe(  // note the use of the longer `node` here rather than `n` to avoid confusion with _number_
      pMap,
      M.lookup(S.Eq)(node),
      O.getOrElse(defaultValue),
    ),
    A.flatten
  );
```

Of note is that although we typically use the short variable names when close to context, be careful with ones like `n` which have common meanings - e.g. we often assume `n` is referring to a number value - just like `s` for string values.

2021-12-07 00:17 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +            O.toUndefined
If you remove this, then down below on line 339 you wouldn't need to do `O.fromNullable` - you'd already have an `Option`.

2021-12-07 00:17 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPage.tsx
> +            initialAdvSearchFieldValueMap,
In my yet again constant strive to keep this effect under control, I think the code behind this value (the two pipes above) needs to be pushed out into a single function you can call here - saving some 30 lines of code here. Or, do you need to revisit `initialiseAdvancedSearch` to achieve/include that so that line is the call to `initialiseAdvanceSearch(...)`?

2021-12-07 00:17 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +   * Advanced search criteria configured in the Old UI. This props is intended to support searches shared
```suggestion
   * Advanced search criteria configured in the Old UI. This prop is intended to support searches shared
```

2021-12-07 00:17 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +export const processLegacyAdvSearchCriteria = (
Although Hoisting saves us, it is considered good practice to have a function declared _before_ using it - so above `legacyQueryStringToSearchPageOptions`.

2021-12-07 00:17 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +// and value is an array of string.
```suggestion
// and value is an array of strings.
```

2021-12-07 00:17 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +  const tree = parser.parseFromString(s, "text/xml");
Might want to wrap that in a `E.tryCatch`.

2021-12-07 00:17 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +    tree.firstChild, // The tree should always have node `xml` as its first child.
Probably should take the extra step and validate that assumption.

2021-12-08 00:25 UTC, PenghaiZhang commented on react-front-end/tsrc/search/AdvancedSearchHelper.ts
> +          A.map(RA.toArray),
This is due to error : The type 'readonly string[]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.

2021-12-08 00:39 UTC, PenghaiZhang commented on react-front-end/tsrc/search/AdvancedSearchHelper.ts
> +          A.map((n) => pMap.get(n) ?? v),
Good idea! I will create a separate function!

2021-12-08 00:48 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPage.tsx
> +            O.toUndefined
Yeah this is better. But on line 351 I will just need to tweak `initialAdvSearchFieldValueMap` to  `O.toUndefined(initialAdvSearchFieldValueMap)`.

2021-12-08 00:49 UTC, edalex-ian commented on react-front-end/tsrc/search/AdvancedSearchHelper.ts
> +          A.map(RA.toArray),
Ah, that'd probably just be due to the next step where you use `A.flatten` rather than `RA.flatten`.

2021-12-08 00:54 UTC, PenghaiZhang commented on react-front-end/tsrc/search/AdvancedSearchHelper.ts
> +          A.map(RA.toArray),
If I use `RA.flatten` I  will get `readonly string[]` which is compatible with `ControlValue` so I will still need to do a `RA.toArray`.

2021-12-08 01:18 UTC, edalex-ian commented on react-front-end/tsrc/search/AdvancedSearchHelper.ts
> +          A.map(RA.toArray),
I think that's okay, but like `O.toUndefined` you want to kind of do it as a last step - thinking of it as an interop step.

2021-12-08 01:23 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPage.tsx
> +            initialAdvSearchFieldValueMap,
I have updated `initialiseAdvanceSearch` to make it return a tuple so that in `SearchPage` I just need to destructure the tuple to get the initial FieldValueMap and the criteria.

2021-12-08 01:31 UTC, PenghaiZhang commented on react-front-end/tsrc/search/AdvancedSearchHelper.ts
> +          A.map(RA.toArray),
Great! I have updated this.

2021-12-08 07:25 UTC, PenghaiZhang commented
Here is a new video which shows the support for sharing or favouriting a search that is originally shared or favourited in Old UI
https://user-images.githubusercontent.com/47203811/145166022-96579eb4-62a8-422a-a684-82f5d06c912d.mp4

2021-12-08 23:39 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +    ),
Oooh, that's tidy. :+1:

2021-12-08 23:52 UTC, edalex-ian approved these changes
Looking good @PenghaiZhang . One optional bit of tweaking for readability, but good to merge really. :wink:

2021-12-08 23:52 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +    ),
If you extract the `E.fromPredicate` into `validateFirstNode` - so have it return an `E.Either<string,ChildNode>` - then this could just be: `E.chain(validateFirstNode),`. Make things nice and tidy.

2021-12-09 01:48 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +    ),
Good idea. I have added a tweak for this.

2021-12-09 05:56 UTC, edalex-ian reviewed
Great job adding support for attributes. Looks good! :+1: 

But a couple of ponderings - and one recommend tweak. OTY.

2021-12-09 05:56 UTC, edalex-ian commented on react-front-end/__tests__/tsrc/search/SearchPageHelper.test.ts
> +  it("supports a Schema node that targets to an attribute", () => {
I love this example, great choice of test data.

But it also got me thinking, what if...

```xml
<xml>
  <country population='100'>
    <city size='small'>hobart</city>
    <city size='medium'>Canberra</city>
  </country>
</xml>
```

Not sure how likely the double attribute situation is though - based on the limitations we've seen with the building of Advanced Searches in the Admin Console - but might still be a valid test... Or, perhaps this is the more likely scenario:

```xml
<xml>
  <country population='100'>
    <city size='small'>hobart</city>
    <city size='small'>Darwin</city>
  </country>
</xml>
```

2021-12-09 05:56 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +  return pipe(valueMap, M.union(S.Eq, A.getSemigroup<string>())(attributeMap));
Could this just be:

```suggestion
  return mergeMaps(valueMap, attributeMap);
```

2021-12-09 05:56 UTC, edalex-ian commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +  ) => pipe(firstMap, M.union(S.Eq, A.getSemigroup<string>())(secondMap));
Is it good, bad or otherwise that this could result in duplicate values (due to the simple `A.getSemigroup<string>()`)?

2021-12-09 06:17 UTC, PenghaiZhang commented on react-front-end/tsrc/search/SearchPageHelper.ts
> +  ) => pipe(firstMap, M.union(S.Eq, A.getSemigroup<string>())(secondMap));
Yes It will. So I think I will use `A.getUnionSemigroup(S.Eq)` instead.

2021-12-09 06:39 UTC, edalex-ian approved these changes
GTG! Merge on green @PenghaiZhang :tada:

2021-12-09 08:21 UTC, edalex-ian commented
Ah rats! conflicts. :disappointed:

2021-12-09 09:22 UTC, PenghaiZhang commented
> Ah rats! conflicts. disappointed

No problems. I have resolved.

2021-12-09 11:37 UTC, merged