fix: display attachment actions only in editable mode
openequella/openEQUELLA pull request #3640
Opened 2021-12-10 00:41 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
Now attachment actions only display after the user click the edit button.

So before we were misled by the local variable `editable` and props `editable`. :smile: 
It can actually be done in the front end.

https://user-images.githubusercontent.com/92769668/145497673-7911dbc4-1244-4442-8222-4b21031b670f.mp4

 

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2021-12-10 01:14 UTC, edalex-ian requested changes
Good working finding the fix @edalex-yinzi . Now just need to tidy things a bit. :wink: 

And are there any existing supporting tests for this? I can't remember...

2021-12-10 01:14 UTC, edalex-ian commented on react-front-end/tsrc/fileuploader/InlineFileUploader.tsx
> +      if (!editable) return [];
Good practice in C based syntax languages (so JS, TS, Java) to use curly braces even for simple statements like this to protect against accidental future editing causing modified logic errors.

```suggestion
      if (!editable) {
        return [];
      }
```

2021-12-10 01:14 UTC, edalex-ian commented on react-front-end/tsrc/fileuploader/InlineFileUploader.tsx
>    const buildActions = (file: UploadedFile | UploadingFile): UploadAction[] => {
Gah, this function's become a bit of a meandering mess due to it's nested `if`s combined with ternaries for return values.

Could you please rework as part of this?

Something along the lines of:

```typescript
const buildActions = (file: UploadedFile | UploadingFile): UploadAction[] => {
  const uploadComplete = isUploadedFile(file);

  if(!uploadComplete) {
    return [
      {
        onClick: () => onCancel(file.localId),
        text: strings.cancel,
        icon: <CancelIcon />,
      },
    ];
  }
  else if(!editable) {
    // No further actions available
    return [];
  }
  else {
    const actions = ...

    return actions;
  }
}
```

Mind you, I still don't love that heavily imperative approach, but it kind of fits with what is there. That said though, if you come up with nice readable declarative approach (perhaps with some judicious use of fp-ts) then that'd be a bonus. :wink:

2021-12-10 01:40 UTC, PenghaiZhang commented on react-front-end/tsrc/fileuploader/InlineFileUploader.tsx
> +      return fileEditable
Looks like the issue is caused by variable shadowing.

2021-12-10 03:25 UTC, edalex-yinzi commented
We have some tests that test the drop and drag function and attachments list for this.

2021-12-10 03:27 UTC, edalex-yinzi commented on react-front-end/tsrc/fileuploader/InlineFileUploader.tsx
>    const buildActions = (file: UploadedFile | UploadingFile): UploadAction[] => {
I refactored the func based on your demo and will come to see if we can use fp-ts in here later.

2021-12-10 03:30 UTC, edalex-yinzi commented
I refactored the func based on @edalex-ian 's demo and will come back to see if we can improve it by using fp-ts later.

2021-12-10 03:39 UTC, edalex-ian approved these changes

2021-12-10 04:27 UTC, PenghaiZhang approved these changes

2021-12-13 03:20 UTC, edalex-yinzi commented
@edalex-ian @PenghaiZhang 
Tried to extract each action and use fp-ts, but `actions` are based on the `file` type so it's hard to get rid of the type error.
![image](https://user-images.githubusercontent.com/92769668/145747127-886fedf5-9aa2-42ad-93db-61226cc046e7.png)

Also get more error after adding getOrElse func.

I think we can merge it.

2021-12-13 05:32 UTC, edalex-ian commented
Heya @edalex-yinzi 

Thanks for the heads up about the target branch, I've tweaked it.

As for the code change (screenshot), that's not quite what we're after. So let's stick with what you've got for now. :wink:

2021-12-13 05:33 UTC, merged

2021-12-13 06:33 UTC, PenghaiZhang commented
Sorry I am late. At your first line of the pipe, I think you should use `O.fromPredicate` rather than `O.some`. And then in the `O.map` I am not sure where the `match` comes from

2021-12-13 22:10 UTC, edalex-yinzi commented
@PenghaiZhang from fp-ts boolean