fix: hdie menu bar for error page in IMS viewer
openequella/openEQUELLA pull request #3744
Opened 2022-01-12 06:02 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
This is a draft pr.

There are two cases in old UI if there is a missing file:

https://user-images.githubusercontent.com/92769668/149067406-a5ddd62c-233c-4531-ae5d-4dbfee38e529.mp4

An index in the catalogue points to a missing file:
![image](https://user-images.githubusercontent.com/92769668/149067111-3c2943ad-3d60-4ea4-ac5c-098e25551c2d.png)

An internal link in IMS viewer points to a missing file:
![image](https://user-images.githubusercontent.com/92769668/149067280-ad70e166-12fb-4c5f-87e9-1984ac37b42b.png)

But in New UI both cases will display the menu:
![image](https://user-images.githubusercontent.com/92769668/149068436-673a3735-b097-4bd7-8190-d37b2e18244c.png)

In old UI it actually uses param `temp.hn=true` to hide the menu (`RenderTemplate.java:394`).
And 404 page will directly return after the request `IntroToDBS_summary.html?temp.hn=true&temp.hb=true`.

But in new UI, `IntroToDBS_summary.html?temp.hn=true&temp.hb=true` will only return 404 code with some useless HTML content, and trigger a new request to the `LeagcyContent content/submit API`. 

If the URL points to a normal Legacy content, the server will find corresponding content from old UI (`LeagcyContentApi.scala:347`) and generate a `fullscreenMode` variable and pass it to React component (`LeagcyContentApi.scala:576`, `LeagcyContent.tsx:272`).

But if the URL is points to a missing file, the legacy content API will direct return a 404 response (`LeagcyContentApi.scala:346`).

And this 404 response will trigger a catch statement (`LegacyContent.tsx:292`) and finally execute a props method passed from `IndexPage.tsx:154`
![image](https://user-images.githubusercontent.com/92769668/149068067-0147dd3d-5677-4b2b-beb8-0246bd7c2c13.png)
![image](https://user-images.githubusercontent.com/92769668/149070009-8a8b886e-ba33-418b-a062-253679458080.png)

So, currently, I just change the code in the frontend to make new UI has the same behaviour as old UI.

The solution idea is quite simple: if the error response contains the params 'temp.hn=true' let `fullscreenMode` props equal to "YES" otherwise keep undefined.

Here is the screenshot:
![image](https://user-images.githubusercontent.com/92769668/149072370-af6cc844-0670-4c69-9023-8cba6882bc1d.png)

The next step is to hide the menu for the internal link. 

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2022-01-17 01:24 UTC, edalex-ian requested changes
Heya Yinzi,

Great work finding out what is going on and find a possible fix.

A few things, what you have here would appear to directly address what's in #2873 and achieve parity with the Legacy UI. With that in mind, this is all that is required for now. (To address the other issue looks like a more fundamental fix and so we'd want that in another ticket.)

Next, as far as the fix goes a few things need attention:

1. First, needs a bit of work cosmetically - notice how the paper element looses any padding next to the IMS navigator - need bring that back in; 
2. This logic really shouldn't be down in the depths of Error.ts and tied to processing of Axios responses.  It needs to come back up higher and be (most likely) in legacy content. Perhaps even this needs to be stored in state somewhere because obviously the IMS viewer has already been forced to full screen mode at some point - so it seems odd that in the code processing the response, we're first checking the request again, and then modifying the state; lastly
3. If that kind of code was to remain, a bit more rigour should be placed around the processing of `response.config.data` - such as overlaying with an interface and I wonder why JSON.parse is being used for what wouldn't be JSON data (maybe)... Perhaps doco needed to as to what is going on...

2022-01-17 05:14 UTC, edalex-yinzi commented
> This logic really shouldn't be down in the depths of Error.ts and tied to processing of Axios responses. It needs to come back up higher and be (most likely) in legacy content. Perhaps even this needs to be stored in state somewhere because obviously the IMS viewer has already been forced to full screen mode at some point - so it seems odd that in the code processing the response, we're first checking the request again, and then modifying the state; lastly

In my understanding, the IMS viewer is actually in old UI, so it already left SPA, thus IMS viewer's fullscreenMode is not related to frontend state.

2022-01-17 05:18 UTC, edalex-yinzi commented
> If that kind of code was to remain, a bit more rigour should be placed around the processing of response.config.data - such as overlaying with an interface and I wonder why JSON.parse is being used for what wouldn't be JSON data (maybe)... Perhaps doco needed to as to what is going on...

The data: 
![image](https://user-images.githubusercontent.com/92769668/149711921-3b6b5b64-c924-4833-a16c-5dfbf816bcec.png)

2022-01-17 06:04 UTC, edalex-yinzi commented on react-front-end/tsrc/mainui/ErrorPage.tsx
> +    marginRight: t.spacing(3),
In the old UI the padding is 27px.

2022-01-17 06:07 UTC, edalex-yinzi commented
![image](https://user-images.githubusercontent.com/92769668/149716332-888b4452-c8fe-4325-ac64-4a1ca4fe4a8e.png)

2022-01-17 06:43 UTC, edalex-ian commented
> > This logic really shouldn't be down in the depths of Error.ts and tied to processing of Axios responses. It needs to come back up higher and be (most likely) in legacy content. Perhaps even this needs to be stored in state somewhere because obviously the IMS viewer has already been forced to full screen mode at some point - so it seems odd that in the code processing the response, we're first checking the request again, and then modifying the state; lastly
> 
> Thanks Ian, In my understanding, the IMS viewer is actually in old UI, so it already left SPA, thus IMS viewer's fullscreenMode is not related to frontend state.

Yes, but.... Keep in mind we maintain various bits of state about whether we're viewing Legacy UI etc. For example, the control of whether we're in full screen.

2022-01-18 02:40 UTC, edalex-yinzi commented
Force push for correcting wrong typing in commit msg....

2022-01-18 04:48 UTC, edalex-yinzi commented
Gah! testBulkMetadataEdit failed.

2022-01-18 23:39 UTC, PenghaiZhang reviewed
Thanks Yinzi. I have added some feedback for you to think.

2022-01-18 23:39 UTC, PenghaiZhang commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +          O.fromNullable(error.response),
The type of `error` is `any`. Do we need the type guard `isAxiosError` here ?

2022-01-18 23:39 UTC, PenghaiZhang commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +            const configData: AxiosResponseConfigData = JSON.parse(
Do you want to try `fp-ts/Json` and then use `J.parse` which returns a `Either` ?

2022-01-18 23:39 UTC, PenghaiZhang commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +          O.map((e: AxiosResponse) => {
```suggestion
          O.map((response: AxiosResponse) => {
```

2022-01-18 23:39 UTC, PenghaiZhang commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +              ? configData["temp.hn"][0] === "true"
I have tried this code but all I got was an empty object from `error.response.config.data`. Perhaps I missed something ?

2022-01-18 23:39 UTC, PenghaiZhang commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +          O.getOrElseW<ErrorResponse>(() => generateFromError(error)),
Is not `getOrElse` enough ?

2022-01-18 23:39 UTC, PenghaiZhang commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +            handleError(fullScreen, e);
Do not need the curly braces.

2022-01-19 04:30 UTC, edalex-ian requested changes
Thanks for the updates @edalex-yinzi . @PenghaiZhang has added some good comments, so I've added to those.

I've also got one thing for you to query... Rather than reaching around and trying to figure out what was used in the previous Axios call (i.e. `config.data`) you are now executing this from within `submitForm` so you're very close to where the values are known before they're submitted. So couldn't you actually execute the `updateTemplate` call up before you even call `submitRequest`? Or, should it perhaps be done _in_ `submitRequest`? May simplify how you process the additional params - possibly no JSON parsing required.

2022-01-19 04:30 UTC, edalex-ian commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +}
Unusual declaration here. Am I correct in thinking this is:

```suggestion
interface AxiosResponseConfigData {
  temp?: {
    hn?: string[],
    hb?: string[]
  }
}
```

But is that even right? Are the string arrays just booleans? In which case:

```suggestion
interface AxiosResponseConfigData {
  temp?: {
    hn?: boolean[],
    hb?: boolean[]
  }
}
```

2022-01-19 04:30 UTC, edalex-ian commented on react-front-end/tsrc/mainui/ErrorPage.tsx
> +    marginRight: t.spacing(3),
Normally it's an even number, with the minimum being 2. Should we just use 2?

2022-01-19 04:30 UTC, edalex-ian commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +          O.map((e: AxiosResponse) => {
I was looking at the anonymous function you have inline here (and, specifically how it impacts readability) and was thinking you need to either create a function for it, or perhaps it'd be clearer if you simply do it more declaratively with a pipe rather then the switch to the imperative approach.

It'd be (really roughly) something like:

```typescript
O.map((response: AxiosResponse) => {
  updateTemplate((tp) => ({
    ...tp,
    fullscreenMode: pipe(
      response.config.data,
      J.parse,
      O.fromEither,
      O.chain(({temp:{hn}}) =>
        // Here you now need to still do a few things:
        // 1. Make sure it's not undefined
        // 2. Make sure it's a non-empty array
        // 3. Get the first element (A.head - which may also fulfil the above step)
        // 4. Then if `true` you can return "YES"
      ),
      O.toUndefined
    )
  );

  return fromAxiosResponse(e);
})
```

It is a bit odd though to have the two disjointed operations (update template, and then the actual map operation - `fromAxiosResponse`) in this O.map but maybe that's good enough here.

2022-01-19 04:30 UTC, edalex-ian commented on react-front-end/tsrc/mainui/IndexPage.tsx
> -    setTemplateProps((p) => ({ ...p, fullscreenMode: undefined }));
Wonder if that causes problems anywhere else. :thinking:

2022-01-20 00:53 UTC, edalex-yinzi commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +}
The original data is quite odd: {"temp.hn": ["true"], "temp.hb":["true"]}

2022-01-20 00:56 UTC, edalex-yinzi commented on react-front-end/tsrc/mainui/ErrorPage.tsx
> +    marginRight: t.spacing(3),
Should be OK there is not much difference between appearance.

2022-01-20 02:18 UTC, edalex-yinzi commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +          O.fromNullable(error.response),
The previous code is judging error is whether `Error` and `AxiosError`. 
But I wonder because the code block is actually in catch statement from an Axios request, is that means the error must be AxiosError type?

2022-01-20 03:16 UTC, PenghaiZhang commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +          O.fromNullable(error.response),
No it didn't. It just checked whether `error.response` is undefined or not.

2022-01-20 03:17 UTC, PenghaiZhang commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +}
I'ts hard to guess what `hn` and `hb` mean. Please add some JSDoc.

2022-01-20 03:29 UTC, edalex-yinzi commented on react-front-end/tsrc/mainui/IndexPage.tsx
> -    setTemplateProps((p) => ({ ...p, fullscreenMode: undefined }));
Not sure but the initial value is "No", and I also tried deleting this line before I made any other changes, nothing happened.

2022-01-20 04:05 UTC, edalex-yinzi commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +              ? configData["temp.hn"][0] === "true"
It depends on whether the request url contains the params or not.

2022-01-20 05:34 UTC, edalex-yinzi commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +          O.fromNullable(error.response),
Yes, it uses this attribute to judge and call different function `fromError` and `fromAxiosError`

2022-01-20 23:38 UTC, edalex-ian approved these changes
Nice, much simpler. I think it's good to go, what do you think @PenghaiZhang ?

2022-01-21 00:22 UTC, PenghaiZhang commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +    updateTemplate((tp) => ({
`updateTemplate` is called regardless of whether `"temp.hn"` is there or not.  I am not sure if we need this ?

2022-01-21 00:22 UTC, PenghaiZhang commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +    const isFullscreenMode = submitValues["temp.hn"]
If you like 'fp-ts' you may have a look this
```
    pipe(
      O.fromNullable(submitValues["temp.hn"]),
      O.map(([firstValue]) => firstValue === "true"),
      O.getOrElse(constFalse),
      (isFullscreenMode) => {
        updateTemplate((tp) => ({
          ...tp,
          fullscreenMode: isFullscreenMode ? "YES" : tp.fullscreenMode,
        }));
      }
    )
```

2022-01-21 05:47 UTC, edalex-ian requested changes
Almost there, just a couple of tweaks and really need to make sure there's not an unnecessary call to updateTemplate.

2022-01-21 05:47 UTC, edalex-ian commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +    pipe(
Can be nice and simple like:

```suggestion
  const preUpdateFullscreenMode = (submitValues: StateData) =>
    pipe(
```

2022-01-21 05:47 UTC, edalex-ian commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +        updateTemplate((tp) => ({
So just keep in mind this is still getting called every-time. Does that need to occur? If it does get called every-time, I'm concerned of unnecessary re-renders and/or screen flickers.

Could you please confirm?

If you see it's best _not_ to call everytime, how about changing the above `O.map` to `O.chain` and simply return `some` if you do need to call it, and then you can have a subsequent `O.map` to do the call to updateTemplate with a hard coded YES.

2022-01-23 23:26 UTC, edalex-yinzi commented on react-front-end/tsrc/legacycontent/LegacyContent.tsx
> +        updateTemplate((tp) => ({
The props will be updated after submitting the form anyway and currently no screen flickers， but it would absolutely be better not to call everytime. :+1:

2022-01-24 03:22 UTC, edalex-ian approved these changes
Excellent, thanks @edalex-yinzi . You do still have some redundant curly braces in `preUpdateFullscreenMode` - so that's something to focus on going forward. But I reckon, let's get it merged.

2022-01-24 03:23 UTC, merged