Feature/upgrade log2j to v2
openequella/openEQUELLA pull request #3756
Opened 2022-01-17 02:57 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This is the second PR for the work of consolidating logging layer. And this PR is focused on updating Log4J to the latest version.

Overall,  the changes can be categorised into 5 groups.

1. Update Log4J to the latest version and address SBT dependency conflicts.
2. Drop code that's used to implement the custom daily rolling appender and HTML layout.
3. Rewrite Log4j configuration files in YAML format.
4. Update existing code to use the the new YAML files.
5. Update JPF plugin files to drop useless Log4j relevant configurations.

2022-01-17 07:19 UTC, PenghaiZhang commented
Failded on `OAIEndpointTest` because the dependency `Oclc Harvester2` still uses Log4j 1.2.

2022-01-17 07:20 UTC, PenghaiZhang commented
`Oclc Harvester2` was last updated in 2009!!!

2022-01-17 07:33 UTC, PenghaiZhang commented
There is not updates for Oclc Harvester2 at all.

The alternative may be using OAI harvest manager which has a new release for the famous Log4J bug.

But...I can't find OAI harvest manager from maven repo.

[This is the link ](https://github.com/clarin-eric/oai-harvest-manager)

2022-01-18 03:33 UTC, PenghaiZhang commented
I am not familiar with the OAI stuff, but I think what we can do is either replacing that OAI lib with another one which is not dependent on the old Log4J or bringing Log4J back only in this project `OldTest`.

2022-01-19 07:23 UTC, edalex-ian requested changes
Great work @PenghaiZhang . Main feedback is for the dependency declarations add some variables to keep things DRY. :wink:

2022-01-19 07:23 UTC, edalex-ian commented on Installer/data/server/learningedge-config/learningedge-log4j.yaml
> +        fileName: "${install.path}/logs/resource-centre/application.html"
The old templates had the filenames in properties right at the top of the file to make it easy for people to tweak. Perhaps do the same with this YAML format too?

2022-01-19 07:23 UTC, edalex-ian commented on Installer/data/server/learningedge-config/learningedge-log4j.yaml
> +            regex: ".*(HHH90000022|HHH90000014).*"
Please add a comment defining what this is filtering.

2022-01-19 07:23 UTC, edalex-ian commented on Installer/data/server/manager/all/log4j.yaml
> +        value: "${filePath}/%d{yyyy-MM-dd}/services-%i.html"
Just to be sure, these don't get processed by any templating in the installer do they?

2022-01-19 07:23 UTC, edalex-ian commented on Source/Server/equellaserver/build.sbt
> +  "org.apache.logging.log4j"  % "log4j-1.2-api"            % "2.17.1",
Hmm, shouldn't this just be:

```suggestion
  "org.apache.logging.log4j"  % "log4j-api"            % "2.17.1",
```

And, do we need the API dep? Kind of feels like it should be a transitive for log4j-slf4j-impl. :thinking:

2022-01-19 07:23 UTC, edalex-ian commented on Source/Server/equellaserver/build.sbt
> +  "org.apache.logging.log4j"  % "log4j-1.2-api"            % "2.17.1",
Be good to pop `2.17.1` into a `val`. Maybe place that in CommonSettings... Or maybe place the whole dependency specifier in there for easy re-use - I see you also need to specify in the installer. :thinking:

2022-01-19 07:23 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/build.sbt
> +  "com.fasterxml.jackson.dataformat" % "jackson-dataformat-yaml" % "2.11.3"
How about use `jacksonVersion`?

```suggestion
  "com.fasterxml.jackson.core"       % "jackson-databind"        % jacksonVersion,
  "com.fasterxml.jackson.dataformat" % "jackson-dataformat-yaml" % jacksonVersion
```

2022-01-19 07:23 UTC, edalex-ian commented on docker/learningedge-log4j.yaml
> +          regex: ".*(HHH90000022|HHH90000014).*"
As per the other, please add comment.

2022-01-19 07:23 UTC, edalex-ian commented on docker/learningedge-log4j.yaml
> +    RollingFile:
Please add the RegexFilter for this appender as well.

2022-01-20 03:40 UTC, PenghaiZhang commented on Installer/data/server/manager/all/log4j.yaml
> +        value: "${filePath}/%d{yyyy-MM-dd}/services-%i.html"
No, they don't. They are processed by Log4j Lookups.

2022-01-20 03:40 UTC, PenghaiZhang commented on Installer/data/server/manager/all/log4j.yaml
> +        value: "${filePath}/%d{yyyy-MM-dd}/services-%i.html"
![image](https://user-images.githubusercontent.com/47203811/150269198-84701003-eccb-4f76-b0d6-90b86e1f019b.png)

You can see the install leaves these as they are.

2022-01-20 03:55 UTC, PenghaiZhang commented on Source/Server/equellaserver/build.sbt
> +  "org.apache.logging.log4j"  % "log4j-1.2-api"            % "2.17.1",
Actually, `log4j-1.2-api` is a bridge which allows log4j2 to be used with some old log4j code. 

For example, in `ItemServiceImpl` there is usage of `MDC` which is replaced by `Thread Context Map`. And in 
`AuthenticatedThread` there is usage of `NDC` which is replaced by `Thread Context Stack`. 

I did try to update the code to use the new stuff, but I stopped and then forgot...I will try again.

2022-01-20 04:32 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/build.sbt
> +  "com.fasterxml.jackson.dataformat" % "jackson-dataformat-yaml" % "2.11.3"
The `jacksonVersion` created in `equellaserver/build.sbt` is not available here. 

`jackson-dataformat-yaml` is only used `UpgradeInstallation` so what about create a val here ?

2022-01-20 04:38 UTC, PenghaiZhang commented on Source/Server/equellaserver/build.sbt
> +  "org.apache.logging.log4j"  % "log4j-1.2-api"            % "2.17.1",
I have moved these to `CommonSettings`.

2022-01-20 05:40 UTC, PenghaiZhang commented on Installer/data/server/manager/all/log4j.yaml
> +        value: "${filePath}/%d{yyyy-MM-dd}/services-%i.html"
After lots of digging, I found `learningedge-log4j.yaml`  does get processed by the installer.

The class is `Interpreter.java`.

2022-01-20 21:16 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/build.sbt
> +  "com.fasterxml.jackson.dataformat" % "jackson-dataformat-yaml" % "2.11.3"
Sounds like a plan. :+1:

2022-01-20 23:57 UTC, PenghaiZhang commented on Installer/data/server/learningedge-config/learningedge-log4j.yaml
> +        fileName: "${install.path}/logs/resource-centre/application.html"
As discussed, leave this file as it's now due to the complexity of refactoring how the installer processes templates.

2022-01-21 03:38 UTC, edalex-ian approved these changes
GTG! Thanks @PenghaiZhang :bow:

2022-01-21 03:46 UTC, merged