bugfix: ensure Custom Attachment uses the correct latest version
openequella/openEQUELLA pull request #3777
Opened 2022-01-21 08:19 UTC by PenghaiZhang

#3769 

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

We have added a fix for the bug caused by a custom attachment which points to the latest version of another resource. 

However, that fix only works when the linked resource is an Item. When the resource is an Attachment, the issue can still happen such as when checking the MIME type of the linked attachment. 

So this PR adds some improvements to make sure whenever a linked resource is used in search2 API, the genuine latest version is used. 

During implementation, I realised that `SearchHelper` has been getting bigger and bigger. So I move some functions to the Scala version `AttachmentResourceService` and some to `AttachmentHelper`.

2022-01-21 08:21 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/service/AttachmentResourceService.scala
> +    val key = new ItemId(uuid, getLatestVersionForCustomAttachment(version, uuid))
Unfortunately,  we need to check the version in here again. This is because what is processed here is an `Attachment` rather than an `AttachmentBean`. Even though we sanitise the bean in earlier stage, that does not make any difference on `Attachment`.

2022-01-23 23:27 UTC, edalex-ian requested changes
It was a bit tricky to review due to the reshuffle, so just to confirm that the key change here is:

- New function - `sanitiseAttachmentBean`; and
- Calling that function in `SearchHelper` on line 293.

And all the other functions stayed as were.

One thing I do wonder, is how will this be for backporting - will the reshuffle cause problems, or should it be pretty straight forward?

But onto specifics, the main feedback is the structure with the new Service. Whether it's in the right package, and how it relates to the existing service.

Other than all that though, I think the fix seems fine. :grin:

2022-01-23 23:27 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/service/AttachmentResourceService.scala
> +object AttachmentResourceService {
So there's already an `AttachmentResourceService` over in `com.tle.web.viewurl.attachments.AttachmentResourceService` (with the implementation at `com.tle.web.viewurl.attachments.impl.AttachmentResourceServiceImpl`). So that raises two questions:

1. Should this be merged with that?; and
2. Is this in the right package?

2022-01-23 23:27 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/service/AttachmentResourceService.scala
> +    Option(LegacyGuice.itemService.getAttachmentForUuid(itemKey, attachmentUuid).getDescription)
This feels more like AttachmentHelper to me.

2022-01-24 10:04 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/search/service/AttachmentResourceService.scala
> +object AttachmentResourceService {
Were you suggesting that we rewrite these Scala methods in Java ?

2022-01-24 22:56 UTC, edalex-ian commented
As discussed, how about:

- rename your AttachmentResourceService to AttachmentService
- and place AttachmentService in the core plugin at `com.tle.core.item.service`

2022-01-24 23:51 UTC, edalex-ian approved these changes
Excellent, thanks @PenghaiZhang . LGTM! :+1:

2022-01-25 01:10 UTC, merged