Feature/consolidate logging layer
openequella/openEQUELLA pull request #3790
Opened 2022-01-26 22:13 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

This is finally the third PR for the Log4J work. What are included in this PR:

1. A new migration to update three Log4J configurations to use the new syntax in YAML format. The files are `leanringedge-log4j.properties` under folder `learningedge-config` and `log4j.properties` and `upgrader-log4j.properties` under folder `manager`. The scala files are housed in `Source/Tools/UpgradeInstallation/scalasrc`.

2. Some dependency updates and JPF plugin updates to support running above migration.
3. Bring back the migration `UpdateLog4jConfigForTomcatLog`  which was dropped in the second PR, but deprecate it. This is due to the `incompatible backwards migration` issue.
4. Update how to set the Log4J configuration when `database-upgrade.jar` is executed. This one could be confusing so please grab me to explain more.

2022-01-26 22:43 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/build.sbt
> +(assembly / assemblyOption) := (assembly / assemblyOption).value.withIncludeScala(true)
Quick one, what's this change for?

2022-01-26 22:58 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/build.sbt
> +(assembly / assemblyOption) := (assembly / assemblyOption).value.withIncludeScala(true)
To include the Scala runtime library in the jar. I had an error complain missing something like scala.serializable.

2022-01-27 01:54 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/build.sbt
> +(assembly / assemblyOption) := (assembly / assemblyOption).value.withIncludeScala(true)
Aha! :+1:

2022-01-27 02:00 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/resources/com/tle/upgrade/upgraders/learningedge-log4j.yaml
> +# This file configures the logging features of TLE.  Please go through each
I have to add one more copy of this configuration to this module to support using the default Log4j configuration. The original file is in `Installer`.

2022-01-27 02:23 UTC, PenghaiZhang commented
![image](https://user-images.githubusercontent.com/47203811/151280437-667bbbfc-411b-4859-8892-79f87306f796.png)

When the update fails, error messages are printed. Ideally, the messages should be highlighted, but the only way to highlight is to fail the whole upgrade.

2022-01-27 05:03 UTC, edalex-ian requested changes
Thanks @PenghaiZhang , this is looking good.

Few things to address:

1. Missing any ScalaDoc in Appender.scala, Filter.scala, Layout.scala and Logger.scala
2. You appear to have not done any tests - prime candidate for unit tests (could stick with TestNG, but I'd say bring in ScalaTest)
3. Just need to tidy up a few minor syntax warnings - unnecessary blocks, parens, etc

and then the various comments.

Good stuff! :+1:

2022-01-27 05:03 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/Appender.scala
> +                         "SizeBasedTriggeringPolicy" -> SizeBasedTriggeringPolicy(maxFileSize))
This should be somewhat optional, as you wont always have both - e.g. you may only have size based.

2022-01-27 05:03 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/Appender.scala
> +      .filter(_.split("\\.").length == 3)
It's unclear what this is. Plus you have an undocumented magic number (3).

2022-01-27 05:03 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/Appender.scala
> +      .map(groupAppenders)
What's the grouping for?

2022-01-27 05:03 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/PropertyHelper.scala
> +    * @return An Option of String.
All of these functions have this issue of just repeating what the type system is already telling us. Instead perhaps, "None if the key is not found in the provided properties, otherwise the value as a String."

2022-01-27 05:03 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/PropertyHelper.scala
> +          case Failure(_)     => 0
You do a similar thing with with Boolean above, but I'm not sure this is the correct pattern.

If it turns out that the type is not correct, perhaps really None should be returned - or otherwise some kind of error.

2022-01-27 05:03 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/UpdateLog4JConfigFile.scala
> +class UpdateLog4JConfigFile extends AbstractUpgrader {
Be good to add ScalaDoc to this class to provide details of its purpose.

2022-01-27 05:03 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/Appender.scala
> +          Filters = filters,
Just checking, if there are _no_ filters, that doesn't trigger a failure does it?

2022-01-27 05:03 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/Layout.scala
> +      .map {
As discussed how about .toRight then .flatMap.

2022-01-27 05:32 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/Appender.scala
> +      .filter(_.split("\\.").length == 3)
This is to only keep property keys that are in the format of `log4j.appender.XXX`. We must use this format is the old property file to define an appender. Obviously, the result of spliting this text by a dot is an array of 3 strings. I put a comment above this method to explained this.

2022-01-27 05:39 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/Appender.scala
> +      .map(groupAppenders)
Because you may have multiple appenders which are the same type. 

For example, if you have two ConsoleAppender, in the yaml file you would see
```yaml
Console:
   - name: aaa
     filters:...
     layout:...
   - name: bbb
     layout: ....
```

So here we do a grouping which will builds a Map where key is the appender type and value is a list of appenders.

If we don't do this, the yaml file would look like 
```yaml
 - Console:
    name: aaa
    filters:...
    layout:...
- Console:   
    name: bbb
    layout: ....
```

This violates the configuration syntax.

2022-01-27 05:43 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/PropertyHelper.scala
> +    * @return An Option of String.
Yeah definitely!

2022-01-27 06:01 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/PropertyHelper.scala
> +          case Failure(_)     => 0
Indeed. This helper was a result of rush...

I have changed to use `Try{...}.toOption`.

2022-01-27 06:07 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/Appender.scala
> +          Filters = filters,
No, it does. Filters are optional.

2022-01-27 06:39 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/Appender.scala
> +      .filter(_.split("\\.").length == 3)
I have added scaladoc for this method.

2022-01-28 05:25 UTC, edalex-ian commented
> Thanks @PenghaiZhang , this is looking good.
> 
>     2. You appear to have not done any tests - prime candidate for unit tests (could stick with TestNG, but I'd say bring in ScalaTest)

As discussed, unfortunately due to the JPF tweaks for SBT builds there were issues getting tests to work properly in this project - although scalatest dependency was added, and IDE was happy, tests would fail to compile due to missing dependency - we'll leave it for now.

2022-01-28 05:32 UTC, edalex-ian approved these changes
Good to go @PenghaiZhang , just one query - but if then, could proceed without addressing.

2022-01-28 05:32 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/Filter.scala
> +      case (regexFilters, thresholdFilter) =>
I thought we figured this is not required?

2022-01-28 09:26 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/log4j2/Filter.scala
> +      case (regexFilters, thresholdFilter) =>
Ah yes. I forgot this. Updated.

2022-01-29 04:20 UTC, merged