refactor: FacetedSearchSettingsModule
openequella/openEQUELLA pull request #3792
Opened 2022-01-26 23:16 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
Create rest module FacetedSearchSettings.
Replace all Axios usage in FacetedSearchSettingsModule in react-front-end.

Will remove deps query-string after mergeing.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2022-01-26 23:37 UTC, edalex-yinzi commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/settings/FacetedSearch/FacetedSearchClassificationResource.scala
>                case Some(oldClassification) =>
I was planning to rebase this pr but got a message `Current branch is up to date`.

2022-01-26 23:37 UTC, edalex-yinzi commented on oeq-ts-rest-api/src/FacetedSearchSettings.ts
> +export interface FacetedSearchClassification {
It was named `Facet`, but there is already a `Facet` interface in `SearchFacet`. So I just use the model name in java.

2022-01-26 23:37 UTC, edalex-yinzi commented on oeq-ts-rest-api/test/FacetedSearchSettings.test.ts
> +    // update filters
```suggestion
    // update faceted search classifications
```

2022-01-26 23:37 UTC, edalex-yinzi commented on react-front-end/tsrc/modules/FacetedSearchSettingsModule.ts
>    });
```suggestion
  ).then((data) => OEQ.BatchOperationResponse.groupErrorMessages(data));
```

2022-01-26 23:37 UTC, edalex-yinzi commented on react-front-end/tsrc/modules/FacetedSearchSettingsModule.ts
>  };
```suggestion
) => (facet: FacetedSearchClassificationWithFlags) => facet === target;
```

2022-01-26 23:37 UTC, edalex-yinzi commented on react-front-end/tsrc/modules/FacetedSearchSettingsModule.ts
>        if (facet.orderIndex === deletedOrderIndex) {
```suggestion
): FacetedSearchClassificationWithFlags[] => facets
    .map((facet) => {
      if (facet.orderIndex === deletedOrderIndex) {
```

2022-01-27 23:46 UTC, edalex-ian requested changes
Looking good @edalex-yinzi , just a couple of minor tweaks required. :wink:

2022-01-27 23:46 UTC, edalex-ian commented on oeq-ts-rest-api/src/FacetedSearchSettings.ts
> +export interface FacetedSearchClassification {
That's good. Typically we match the naming here (more or less) to what is on the server side for easy look-up etc.

2022-01-27 23:46 UTC, edalex-ian commented on oeq-ts-rest-api/src/FacetedSearchSettings.ts
> +   * ID of a facet; being undefined means this facet is dirty(i.e., not saved to the server).
```suggestion
   * ID of a facet; being undefined means this facet is dirty (i.e., not saved to the server).
```

2022-01-27 23:46 UTC, edalex-ian commented on oeq-ts-rest-api/src/FacetedSearchSettings.ts
> +   * Latest date time when a facet was modified. Unnecessary for create or update.
Please specify the date format for these strings. (So also in the above comment for `dateCreated`.)

2022-01-27 23:46 UTC, edalex-ian commented on oeq-ts-rest-api/src/FacetedSearchSettings.ts
> +   * The number of category of a facet; Being undefined means the number is unlimited.
```suggestion
   * The number of categories to display for a facet; Being undefined means the number is unlimited.
```

2022-01-27 23:46 UTC, edalex-ian commented on oeq-ts-rest-api/src/FacetedSearchSettings.ts
> +   * Used for re-ordering facets.
```suggestion
   * Used to control the order of list of facets in the UI.
```

2022-01-27 23:46 UTC, edalex-ian commented on oeq-ts-rest-api/src/FacetedSearchSettings.ts
> + * Retrieve faceted search settings (classification)
```suggestion
 * Return a list of the settings for all available faceted searches (classifications).
```

2022-01-27 23:46 UTC, edalex-ian commented on oeq-ts-rest-api/src/FacetedSearchSettings.ts
> +  facetedSearchClassificationIds: number[] | string[]
I think this should only be `number[]` considering `number` is the type of `id` up in `FacetedSearchClassification`.

2022-01-28 02:30 UTC, edalex-yinzi commented on oeq-ts-rest-api/src/FacetedSearchSettings.ts
> +  facetedSearchClassificationIds: number[] | string[]
I add a type string[] because in `react-front-end` actually uses a func `idExtractor` which returns a string array. Should I refactor this func ?

2022-01-28 02:57 UTC, edalex-yinzi commented on react-front-end/tsrc/modules/FacetedSearchSettingsModule.ts
>  export const batchDelete = (ids: string[]): Promise<string[]> =>
I didn't change the type here because it use a func `idExtractor` which return a string array.

2022-01-28 03:51 UTC, edalex-ian approved these changes
Thanks @edalex-yinzi . LGTM. :+1:

2022-01-28 05:15 UTC, edalex-ian commented
Gah, the old GHA out of memory issue surfaces again.

But I see key tests have passed and also the New UI tests are run on CodeBuild, so let's merge this.

2022-01-30 22:27 UTC, merged