fix: correctly set base url in error page under ssl env
openequella/openEQUELLA pull request #3838
Opened 2022-02-16 22:56 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
Get schema based on both request and URI.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2022-02-16 23:38 UTC, edalex-ian requested changes
Good stuff @edalex-yinzi and great to see the refactor to keep it DRY.

Just one tweak for the comment and then we should be good to go when we get a (mostly) green build. :wink:

2022-02-16 23:38 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/services/impl/UrlServiceImpl.java
> +  // based on the request and base institution url.
Good job adding the doco. Seeing you've gone to the effort, might as well put it as JavaDoc so that the IDE will display it when someone queries the function.

2022-02-17 05:58 UTC, edalex-ian reviewed
Almost there, just make sure you do the JavaDoc completely.

2022-02-17 05:58 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.serverbase/src/com/tle/core/services/impl/UrlServiceImpl.java
> +   * @return UriBuilder
Don't just leave these as the template place holders, add some _useful_ descriptions.

2022-02-17 22:52 UTC, PenghaiZhang approved these changes

2022-02-18 00:30 UTC, edalex-ian reviewed
Would've made sense to keep the `@param`, but for the sake of keeping this moving let's merge on green(ish).

2022-02-18 00:30 UTC, merged

2022-02-18 01:41 UTC, edalex-yinzi commented
Thanks, @edalex-ian and @PenghaiZhang. Just one question if I keep @param what's the appropriate description for it? I can't figure out a proper des.

2022-02-18 06:44 UTC, edalex-ian commented
Well first, keep in mind that both the JavaDoc generator and the IDE can determine the type for you, so the type information like the below is redundant:

```
@param request HttpServletRequest
```

But that also doesn't mean it's good to translate a code type into plain english like:

```
@param request The request object from a HTTP Servlet
```

No, you want to detail any kind of contractual expectations or how it will be used:

```
@param request The source which will be used to determine if the request was over a secure protocol
               from which the scheme in the builder will be derived.
```

Have a look at some of the standard Java JavaDoc to get more of an idea. :wink: