Feature/rewrite cloud provider
openequella/openEQUELLA pull request #3892
Opened 2022-02-24 08:43 UTC by PenghaiZhang

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

In order to remove the use of simpleDBA in Cloud provider, we firstly need to drop the `CloudProviderDB`. At the beginning, this class name made me think it worked like a DAO, but I was wrong. This one is more like a Service which provided supports like registering a Cloud providers and was mostly used in the Cloud provider REST APIs. So I created a new class named `CloudProviderRegistrationService` which uses the `EntityService` implemented in previous PR.

Major changes:
1. more methods in `EntityService` and `EntityDAO`  and named query in `Entity`.
2. The new implementation in the new Service which required some changes in `EntityValidation` as well.
3. Due to the class `Entity` being a normal class and the types of its fields are either primitive types or String, an extra handling for converting string to `CloudProviderData` is required
4. Use the Service in `CloudProviderApi`.
5. Drop unused methods in `CloudProviderDB`. 

I tried to minimise changes, especially logical changes. But some of the previous implementation did not look quite right to me and did not work seamlessly with the new implementation. So I had to change some logical (but all minor). 

There is only one previous implementation related to cloud provider registration left. It is `refreshCloudProvider`. The main reason is the use of `CloudProviderService.serviceRequest` which obviously has simpleDBA code. Refactoring this one will cause a lot of more changes in different files. So I decided to do this in next PR when I will focus on refactoring `CloudProviderService`.

I have tested initialising a Cloud provider registration, listing all Cloud providers, adding a new one and deleting an existing one via the page. I can't find any UI that allows me to edit a Cloud provider so I tested this in the Swagger API page.

2022-02-25 00:19 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +      .getAllByType(typeId)
The previous implementation used `fs2 scream` to handle reading all the entities. I think we discussed this in previous PR and if needed we can use pagination to optimise here.

2022-02-28 01:48 UTC, edalex-ian requested changes
Fair effort @PenghaiZhang :star: 

Mostly queries, and just a couple of minor items. :+1:

2022-02-28 01:48 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.base/scalasrc/com/tle/beans/newentity/Entity.scala
> +    case that: EntityID => that.uuid == that.uuid && this.inst_id == that.inst_id
Should this be:

```suggestion
    case that: EntityID => this.uuid == that.uuid && this.inst_id == that.inst_id
```

2022-02-28 01:48 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.base/scalasrc/com/tle/beans/newentity/Entity.scala
> +  override def hashCode(): Int = inst_id.hashCode + uuid.hashCode
You'd probably get a more reliable hash with:

```suggestion
  override def hashCode(): Int = Objects.hash(inst_id, uuid)
```

2022-02-28 01:48 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderDB.scala
> +        .map { _ =>
hmmm, ignore the value passed into a `map` seems odd - if anything says this is _not_ a map operation... What's happening here?

2022-02-28 01:48 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +    * Check whether a registration token is valid. If yes, invalidate the token.
This is so confusing. One would use `validToken` to invalidate an existing valid token. Huh?

2022-02-28 01:48 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +    tokenCache.put(newToken, newToken)
Is this right, the token is _both_ the key and the value??

2022-02-28 01:48 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +    entityService.createOrUpdate(entity)
Hmmm, this got lost in my first reading - indeed, I wondered why this was called `save` as I thought it didn't persist anything.

Maybe to make it jump out:

```suggestion

    // Persist the new Entity
    entityService.createOrUpdate(entity)
```

2022-02-28 01:48 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +    entity.descriptionStrings = edits.descriptionStrings.map(_.asJson.noSpaces).orNull
Do you really want to mutate the passed in Entity?

2022-02-28 01:48 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/newentity/service/EntityService.scala
> +  def getAllByType(typeId: String): java.util.List[Entity]
Should it limit by institution?

2022-02-28 01:48 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/newentity/service/EntityService.scala
> +    * Get an Entity by UUID.
```suggestion
    * Get an Entity by UUID limited to those in the current institution.
```

2022-02-28 01:48 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/cloudprovider/CloudProviderApi.scala
> +      .valueOr(badRequest(_: _*))
Oooh, nice. I love how that reads. :+1:

2022-02-28 22:54 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.base/scalasrc/com/tle/beans/newentity/Entity.scala
> +    case that: EntityID => that.uuid == that.uuid && this.inst_id == that.inst_id
Oops my mistake! Yes it should be `this`.

2022-02-28 23:01 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/newentity/service/EntityService.scala
> +  def getAllByType(typeId: String): java.util.List[Entity]
It's limited by current institution. Do you want to make it a bit more flexible to support different institution ?

2022-02-28 23:04 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/newentity/service/EntityService.scala
> +  def getAllByType(typeId: String): java.util.List[Entity]
Or I can `limited to those in the current institution.` to the docs like below comment.

2022-02-28 23:15 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderDB.scala
> +        .map { _ =>
How the previous implementation worked here was like `giving an entity and some values -> validate values -> make a copy of the entity with the values -> return the copy`.

Because of what I changed, the return of `EntityValidation.standardValidation` is not needed here any more.

2022-02-28 23:17 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderDB.scala
> +        .map { _ =>
I did not update too much in this file because the intention is to drop it so I just made minor changes to let the complier happy.

2022-02-28 23:19 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +    * Check whether a registration token is valid. If yes, invalidate the token.
I guess the idea is: if the token is no longer in the cache, return a error; if the token is still available, invalidate it so it cannot be reused.

2022-02-28 23:29 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +    tokenCache.put(newToken, newToken)
According to how the cache of token is invalidated, I think this is right. 


```
tokenCache.invalidate(regToken)
```

2022-02-28 23:32 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +    entityService.createOrUpdate(entity)
Ah yes it's to persist an entity. I will add this comment.

2022-02-28 23:38 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +    entity.descriptionStrings = edits.descriptionStrings.map(_.asJson.noSpaces).orNull
I did ponder this for quite a while as well and I also added a `todo`!  But before I committed,  I thought this `Entity` is a normal class rather than a case class which focuses on immutability, so maybe it's fine and does not violate Scala coding convention to mutate.  

That said, we can definitely create a `copy` method to support creating a new instance with given values.

2022-03-01 23:33 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderDB.scala
> +        .map { _ =>
Okay, fair enough - if it's just a temporary situation before outright removal. :wink:

2022-03-01 23:39 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +    * Check whether a registration token is valid. If yes, invalidate the token.
Yeah, but why do the two disparate operations in the one function called validXyz.. Let's discuss.

2022-03-01 23:50 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +    entity.descriptionStrings = edits.descriptionStrings.map(_.asJson.noSpaces).orNull
It's not so much about a "Scala coding convention" as it is about being cautious about mutating passed in data - as it could cause an unexpected surprise (especially in any future use/maintenance). It's probably mostly because this seems like an innocuous 'save' function, so you wouldn't typically expect it to be modifying inputs. However if it was called something like 'applyValues' then it wouldn't be unexpected.

But so in this context I'd expect `entity` to be unchanged after use. Now you could add a copy, or you could simple use the constructor with named args in this `save` to build up the new one.

2022-03-01 23:51 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +    tokenCache.put(newToken, newToken)
Okay, cool.

2022-03-01 23:53 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/newentity/service/EntityService.scala
> +  def getAllByType(typeId: String): java.util.List[Entity]
Ah I see, I went into the DAO and had a closer look. Yes, just make it explicit in the docs.

2022-03-01 23:55 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/newentity/service/EntityService.scala
> +  def getAllByType(typeId: String): java.util.List[Entity]
Ah! I see you've done it. :wink:

2022-03-02 03:14 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +    * Check whether a registration token is valid. If yes, invalidate the token.
This method now returns the valid token and the invalidation is moved to `register`.

2022-03-02 03:15 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +    entity.descriptionStrings = edits.descriptionStrings.map(_.asJson.noSpaces).orNull
This method is renamed to `applyValues` and only mutates the Entity. The persisting and CP instance building are move to `register` and `editRegistered`.

2022-03-02 05:29 UTC, edalex-ian reviewed
Looks like it's there @PenghaiZhang . Just one query....

2022-03-02 05:29 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +          tokenCache.invalidate(token)         // Invalidate the token so it can't be reused.
Should this only happen after a successful DB update (i.e. after the below `createOrUpdate`)?

2022-03-02 06:43 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/scalasrc/com/tle/core/cloudproviders/CloudProviderRegistrationService.scala
> +          tokenCache.invalidate(token)         // Invalidate the token so it can't be reused.
I understand this is how it was. All good. :+1:

2022-03-02 06:43 UTC, edalex-ian approved these changes

2022-03-03 22:41 UTC, merged