fix: correctly handle error for UserSearch dialog
openequella/openEQUELLA pull request #3908
Opened 2022-03-07 02:33 UTC by edalex-yinzi

##### Checklist

- [X] the [contributor license agreement][] is signed
- [X] commit message follows [commit guidelines][]
- [ ] tests are included
- [X] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
Add a callback onError
Correctly show 404 and error message

https://user-images.githubusercontent.com/92769668/156957434-b1b046df-0449-490b-8dcb-6068f36ac948.mp4

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2022-03-07 03:49 UTC, edalex-ian requested changes
Good work @edalex-yinzi . One change required, and one query.

BTY

2022-03-07 03:49 UTC, edalex-ian commented on react-front-end/tsrc/components/UserSearch.tsx
> +  const [errorMessage, setErrorMessage] = useState<String | null>(null);
Typically we just use `undefined`, so:

```suggestion
  const [errorMessage, setErrorMessage] = useState<String>();
```

And then update the usages accordingly.

2022-03-07 03:49 UTC, edalex-ian commented on react-front-end/tsrc/components/UserSearch.tsx
> +  onError?: (error: OEQ.Errors.ApiError) => void;
Why is this needed? I don't see an other files updated to use this. :thinking:

2022-03-07 04:01 UTC, edalex-yinzi commented on react-front-end/tsrc/components/UserSearch.tsx
> +  onError?: (error: OEQ.Errors.ApiError) => void;
The ticket says 

> Fix notes: Keeping in mind that the `<SelectUserDialog>` wraps the standalone `<UserSearch>` component, `UserSearch` should simply take an additional `onError` prop - as opposed to using one of the existing contexts. This will allow it to remain decoupled.

So I added this callback.

2022-03-07 06:38 UTC, PenghaiZhang commented on react-front-end/tsrc/components/UserSearch.tsx
> +  const [errorMessage, setErrorMessage] = useState<String>();
Looks like `errorMessage` is used more like a boolean.

2022-03-07 06:38 UTC, PenghaiZhang commented on react-front-end/tsrc/components/UserSearch.tsx
> +      .catch((error: OEQ.Errors.ApiError) => {
Can `error` be any other type?

And what would happen if you just disable the network and do the search ?

2022-03-07 06:38 UTC, PenghaiZhang commented on react-front-end/tsrc/components/UserSearch.tsx
> +        if (error.status !== 404) {
Why skip 404 may I ask?

2022-03-07 22:03 UTC, edalex-yinzi commented on react-front-end/tsrc/components/UserSearch.tsx
> +  const [errorMessage, setErrorMessage] = useState<String>();
Yes. I had used two variables one is a boolean hasError and another one is string errorMessage but I think it would be more elegant to combine them together.

2022-03-07 22:06 UTC, edalex-yinzi commented on react-front-end/tsrc/components/UserSearch.tsx
> +        if (error.status !== 404) {
Because I think 404 can be regarded as a normal response for a search query, it's not a `real` error.

2022-03-07 22:55 UTC, edalex-yinzi commented on react-front-end/tsrc/components/UserSearch.tsx
> +      .catch((error: OEQ.Errors.ApiError) => {
The func is from oeq-ts-rest-api module and calls axios so I think error will always wrapped as ApiError.

Disable network:
![image](https://user-images.githubusercontent.com/92769668/157130804-1f7b68a1-2044-4398-ae09-dfbe41847386.png)

2022-03-08 01:16 UTC, edalex-ian approved these changes

2022-03-08 03:54 UTC, edalex-ian commented
Before merging will just check if @PenghaiZhang has anything else needing addressing.

2022-03-08 04:00 UTC, PenghaiZhang commented
> Before merging will just check if @PenghaiZhang has anything else needing addressing.

I have left some queries which yinzi marked as resolved but I did not see any update. But they are not big deals.

2022-03-08 05:13 UTC, PenghaiZhang approved these changes
Had a chat with Yinzi and it's good to go.

2022-03-08 05:13 UTC, PenghaiZhang commented on react-front-end/tsrc/components/UserSearch.tsx
> +  const [errorMessage, setErrorMessage] = useState<String>();
I can see two usage of `errorMessage`. 
`errorMessage ? "secondary" : "inherit"` and `errorMessage ?? sprintf(failedToFindUsersMessage, query)`.

You are not using it as string, aren't you ?

2022-03-08 05:13 UTC, PenghaiZhang commented on react-front-end/tsrc/components/UserSearch.tsx
> +        if (error.status !== 404) {
For this request, I would expect to see an empty list of something instead of a 404 error is returned.

2022-03-08 06:50 UTC, merged