fix: handle multiple status for api search
openequella/openEQUELLA pull request #3946
Opened 2022-03-16 05:36 UTC by edalex-yinzi

##### Checklist

- [X] the [contributor license agreement][] is signed
- [X] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
Change query param status type from string to CsvList.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2022-03-17 01:25 UTC, edalex-ian requested changes
Thanks @edalex-yinzi . Needs a couple of tweaks, and don't forget to add something to test this over in SearchApiTest.

2022-03-17 01:25 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/api/search/SearchResourceImpl.java
> +      CsvList status,
You'll note that by the time CsvList for collectionUuids has been passed to this function it's done the conversion to the standard `Collection` type. This is along the lines of the pattern that the first entry point marshalls the data into a standard model which can then readily be used anywhere.

So here, this should be:

```suggestion
      List<String> status,
```

This can be done rather cleanly up in `searchItems` with:

```java
Optional.ofNullable(status).map(CsvList::asList).orElse(null);
```

2022-03-17 01:25 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/api/search/SearchResourceImpl.java
> +                .map(sta -> ItemStatus.valueOf(sta.toUpperCase()))
You could keep this as is. However, seeing you're essentially doing another map in here it makes it really clear if you do something like:

```java
List<ItemStatus> itemStatuses = status.stream()
    .map(String::toUpperCase)
    .map(ItemStatus::valueOf)
    .collect(Collectors.toList());
```

Note also I've changed the name of the variable there - not sure `statusT` really conveys much idea of what's happening here.

2022-03-17 01:25 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/api/search/SearchResourceImpl.java
>          // Invalid status
BTW, while playing in this error it would be worthwhile to change this to a WARN log entry capturing what invalid status was attempted.

2022-03-18 07:04 UTC, edalex-ian approved these changes
Thanks @edalex-yinzi . LGTM! :+1:

2022-03-18 07:07 UTC, edalex-ian requested changes

2022-03-18 07:07 UTC, edalex-ian commented on autotest/OldTests/src/test/java/com/tle/webtests/test/webservices/rest/SearchApiTest.java
> +import com.tle.beans.item.ItemStatus;
Ah whoops! I didn't notice the failed build.

There's no dependencies across from the `autotest` to the core code based - keeps the completely decoupled. It's acceptable then to define your own constants for `LIVE` and `DRAFT`.

Interesting that your IDE let you do this. :thinking:

2022-03-20 22:57 UTC, edalex-yinzi commented on autotest/OldTests/src/test/java/com/tle/webtests/test/webservices/rest/SearchApiTest.java
> +import com.tle.beans.item.ItemStatus;
Actually, it popped up a fix that said add core_base dependencies and didn't change any files so I thought it might be ok.

2022-03-20 23:31 UTC, edalex-ian commented on autotest/OldTests/src/test/java/com/tle/webtests/test/webservices/rest/SearchApiTest.java
> +import com.tle.beans.item.ItemStatus;
Aha! Yeah, that changes the IntelliJ project setup - not the build etc.

2022-03-20 23:31 UTC, edalex-ian approved these changes

2022-03-21 03:36 UTC, edalex-ian commented
Failed known flaky on CodeBuild(`HierarchyTopicTest`), fine to merge.

2022-03-21 03:36 UTC, merged