fix: update swagger ui annotations for info and status params
openequella/openEQUELLA pull request #3973
Opened 2022-03-28 05:45 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
Update annotations for api `search`.
Including status and info params.
Before:
![image](https://user-images.githubusercontent.com/92769668/160333786-4fe78887-989e-41ab-adfc-9823af53ecfa.png)

After:
![image](https://user-images.githubusercontent.com/92769668/160333599-d05870dc-b116-458b-a350-6f6744bf1053.png)

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2022-03-28 06:31 UTC, edalex-ian reviewed
Hmmm, we've lost info here. Now people can't see what values are available. :thinking:

2022-03-28 22:46 UTC, edalex-yinzi commented
How about this:
![image](https://user-images.githubusercontent.com/92769668/160499342-d82dfd81-c461-4a62-8b23-c7567603ba7f.png)

2022-03-28 22:52 UTC, edalex-ian commented
hmmm, please see the discussion in the thread in slack I mentioned you in.

2022-03-29 21:52 UTC, edalex-yinzi commented
Tried to set serialization param but not work.

2022-03-29 23:24 UTC, edalex-ian requested changes
Okay, so as per discussions I agree let's just stick with a raw string for now.

BUT, we want to tidy up the formatting of the doco strings.

2022-03-29 23:24 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/api/search/EquellaSearchResource.java
> +                      + "DRAFT,LIVE,REJECTED,MODERATING,ARCHIVED,SUSPENDED,DELETED,REVIEW,PERSONAL",
Seeing this is now doco, let's make sure we include spaces:

```suggestion
                      + "DRAFT, LIVE, REJECTED, MODERATING, ARCHIVED, SUSPENDED, DELETED, REVIEW, PERSONAL",
```

But also, I note above (for `info`) you've used the enum directly. Is that an option here? But the other thing is, in one you're saying the values should be lower case and the other upper case - be good to be consistent.

2022-03-30 00:56 UTC, edalex-yinzi commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/api/search/EquellaSearchResource.java
> +                      + "DRAFT,LIVE,REJECTED,MODERATING,ARCHIVED,SUSPENDED,DELETED,REVIEW,PERSONAL",
No, but I can add one.

2022-03-30 00:58 UTC, edalex-yinzi commented
Format string ALL_ALLOWABLE_INFOS and add a string ALL_ALLOWABLE_STATUSES in IteamResource.

2022-03-30 00:59 UTC, edalex-yinzi commented
![image](https://user-images.githubusercontent.com/92769668/160730127-4da565e9-d8f8-4930-8be0-7862ede1b33a.png)

2022-03-30 03:28 UTC, edalex-ian approved these changes
Thanks @edalex-yinzi :+1:

2022-03-30 03:28 UTC, merged