fix: blackboard 500 error from manage external resources
openequella/openEQUELLA pull request #4037
Opened 2022-04-14 00:09 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
Change func `findAllUsages` to throw UnsupportedOperationException.
Add catch statement to set error message.

![image](https://user-images.githubusercontent.com/92769668/163289324-1cc6112c-e809-4ab1-9561-a675c3bbf206.png)
![image](https://user-images.githubusercontent.com/92769668/163289345-e57478db-68d6-4a95-8bc8-7b0bb5322963.png)

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2022-04-14 06:03 UTC, edalex-ian commented
Curious, both GHA new UI functional_testing jobs failed on `io.github.openequella.search.AdvancedSearchPageTest` but was fine on CodeBuild.

Have attempted to re-run them. Let's see what happens.

2022-04-14 06:06 UTC, edalex-ian requested changes
Looks good Yinzi. Just needs a wording tweak, and a query for you.

2022-04-14 06:06 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +    throw new UnsupportedOperationException("Feature not supported by Blackboard Rest");
```suggestion
    throw new UnsupportedOperationException("Feature not supported by Blackboard REST");
```

2022-04-14 06:06 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/connectors/manage/ConnectorManagementResultsSection.java
> +      throws RuntimeException {
Don't normally need to declare `RuntimeException` as it's an unchecked exception. :thinking:

2022-04-14 06:07 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/connectors/blackboard/service/impl/BlackboardRESTConnectorServiceImpl.java
> +    throw new UnsupportedOperationException("Feature not supported by Blackboard Rest");
Oh! Actually, that should be a language string.

2022-04-14 06:08 UTC, edalex-ian commented
BTW... What happens in something like Canvas (which does not support Find Uses)? We should be doing the same.

2022-04-14 07:30 UTC, edalex-ian commented
Excellent, the two GHA fails are different to before, just flaky known ones.

2022-04-20 00:29 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/connectors/manage/ConnectorManagementResultsSection.java
> +              null, null, null, 0, connectorSearchEvent.getConnector());
I have not dug into the code, but I found that if you pass `null`  to the constructor , you might trigger another NPE. For example, in line 168 of  `ConnectorManagementResultsSection`, calling `results.getResults().getResults()` would result in a NPE.

2022-04-20 00:31 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/connectors/manage/ConnectorManagementResultsSection.java
> +              null, null, null, 0, connectorSearchEvent.getConnector());
But I am not sure if this kind of code will be executed or not as you have set `error` and `message`.

2022-04-20 03:39 UTC, edalex-yinzi commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/connectors/manage/ConnectorManagementResultsSection.java
> +              null, null, null, 0, connectorSearchEvent.getConnector());
Thanks, Penghai, after investigating I found the function `processResults` you mentioned will be triggered at line 220 in `AbstractSearchResultSection.java` which has been wrapped by an if statement so it will just skip it if the result is null or errored.

FYI: 220 line `context.processEvent(resultsEvent)` will trigger the `fire` func  in `ConnectorManagementResultsSection` and `fire` will trigger `processResults` 

![image](https://user-images.githubusercontent.com/92769668/164144944-b16e5fe5-ad88-471d-82c7-a5976eed04c4.png)

2022-04-20 03:47 UTC, edalex-yinzi commented
Thanks Ian,

> BTW... What happens in something like Canvas (which does not support Find Uses)? We should be doing the same.

The interesting thing is `CanvasConnecterService` actually implemented the func `findAllUsages`.

2022-04-21 05:20 UTC, PenghaiZhang approved these changes

2022-04-21 09:02 UTC, edalex-ian commented
> > BTW... What happens in something like Canvas (which does not support Find Uses)? We should be doing the same.
> 
> The interesting thing is `CanvasConnecterService` actually implemented the func `findAllUsages`.

Gah, that's curious. Our feature matrix says otherwise... But you've drawn my attention to something else:

- In `CanvasConnecterService` although `findAllUsages` is implemented and based on code history has been since before open sourcing (be worth making sure it works), `findUsages` is not and returns an empty array.
- You'll note just above where you've made your fix is the `findUsages` for Bb, and it also is simply returning a `null`. Is that another NPE waiting to happen?
- So, what is the use cases for these two functions? I think you may need to have a look and then you may need to address that second function too.
  - I think the `findUsages` is used when from the Item Summary page you click the 'Find Uses' link on the right hand of the screen (under Details heading).

We could also follow up with @cathfitz on her return.

2022-04-26 06:23 UTC, edalex-yinzi commented
> > > BTW... What happens in something like Canvas (which does not support Find Uses)? We should be doing the same.
> > 
> > 
> > The interesting thing is `CanvasConnecterService` actually implemented the func `findAllUsages`.
> 
> Gah, that's curious. Our feature matrix says otherwise... But you've drawn my attention to something else:
> 
> * In `CanvasConnecterService` although `findAllUsages` is implemented and based on code history has been since before open sourcing (be worth making sure it works), `findUsages` is not and returns an empty array.
> * You'll note just above where you've made your fix is the `findUsages` for Bb, and it also is simply returning a `null`. Is that another NPE waiting to happen?
> * So, what is the use cases for these two functions? I think you may need to have a look and then you may need to address that second function too.
>   
>   * I think the `findUsages` is used when from the Item Summary page you click the 'Find Uses' link on the right hand of the screen (under Details heading).
> 
> We could also follow up with @cathfitz on her return.

Thanks for your info:

`findAllUsage` is used when you click the left menu `manage external resources` and choose a connector:
![image](https://user-images.githubusercontent.com/92769668/165234832-2e94b028-0399-4b45-9e80-7a3d1230586a.png)

`findUsage` is used when you click the 'Find Uses' link in the Item Summary page:
![image](https://user-images.githubusercontent.com/92769668/165234323-1789167d-8d04-466f-abc4-e5667de9c5c3.png)

and the workflow is in `FindUsesContentSection`: `loadUsage` -> `checkErrors` -> `getUsages` -> `BlackboardRESTConnectorServiceImpl`:`findUsage`.

The server just saves it into the model and has no other process on it.  

![image](https://user-images.githubusercontent.com/92769668/165233470-32c9237c-9c1c-4d30-9e64-71a35fc84c66.png)

![image](https://user-images.githubusercontent.com/92769668/165232366-aa1ed895-1a8c-4969-9682-40adf1519569.png)

I think null is ok for this use case :
![image](https://user-images.githubusercontent.com/92769668/165233892-a78b22ef-00d7-4607-8a69-738d2555602a.png)

2022-04-26 22:36 UTC, edalex-ian approved these changes
Excellent, thanks for checking it all. Let's merge and proceed.

2022-04-26 22:37 UTC, merged