refactor: replace libav with ffmpeg
openequella/openEQUELLA pull request #4115
Opened 2022-05-11 06:45 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
Replace libav with ffmpeg: 
* docs (comments and readme files)
* ffmpeg/libav module
* installer
![image](https://user-images.githubusercontent.com/92769668/167785203-46f72289-f598-4b65-8ff3-e834e54bbbad.png)

* upgrader
final optional configs output:
![image](https://user-images.githubusercontent.com/92769668/167782299-1fed10a0-baea-46ff-b3b5-7280629fb41f.png)

* ci
* docker

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2022-05-12 05:23 UTC, edalex-yinzi commented
GHA failed but seems OK on my machine, can you try re-run this?

2022-05-12 07:40 UTC, edalex-ian commented
Restarted. :crossed_fingers:

2022-05-13 05:49 UTC, edalex-ian requested changes
Nice work and very thorough @edalex-yinzi . Just a few queries and some tweaks needed.

2022-05-13 05:49 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +    result.addLogMessage("Updating optional-config properties")
Is it clear in the log that this is for FFmpeg, or does the person doing the upgrade only see this non-specific message?

2022-05-13 05:49 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +                                 result) {
This just looks/reads a bit clunky... I wonder if you can get away with:

```scala
val lineMod = new LineFileModifier(....) {
  override protected def procesLine(...) ... etc

  override protected def addLines(...) ... etc
}
```

And if you could get away with that, down in the try block you might as well just have:

```scala
new LineFileModifier(....) {
  ....
}.update()
```

2022-05-13 05:49 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +      var removeLibavBlankLine = false;
If I understand correctly, the only reason for these is to support the removal of the blank line. If that's correct, I'd say drop them and forget about the blank line - it's not worth it.

2022-05-13 05:49 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +        }
Rather than being all imperative, why not use a pattern `match`?

2022-05-13 05:49 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +        throw new RuntimeException("Failed to update config file", e)
```suggestion
        throw new RuntimeException("Failed to update optional-config.properties to support use of FFmpeg.", e)
```

2022-05-13 06:42 UTC, edalex-yinzi commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +    result.addLogMessage("Updating optional-config properties")
Only this message.

2022-05-13 07:28 UTC, PenghaiZhang approved these changes
THanks Yinzi! Just a few Scala code suggestions for you.

2022-05-13 07:28 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +    try {
Just a suggestion. What about 
``
private def updateOptionalProperties(result: UpgradeResult, configDir: File): Unit = 
   Try {.
    ..}
   match  {
     case ...
   }
``

2022-05-13 07:28 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +  override def isBackwardsCompatible: Boolean = false
I never fully understand this, but in my previous experience the value is `true` in most migrations.

2022-05-13 07:28 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +            if (Pattern.matches(libavCommentPattern, line) || Pattern.matches(libavPathPattern,
This if can be replaced by `Option.when`.

```
 Option.when(Pattern.matches(libavCommentPattern, line) || Pattern.matches(libavPathPattern, line))(line).orNull
```

2022-05-13 08:03 UTC, edalex-ian requested changes
Thanks for the updates, looks like I may have confused you so I apologise for that. I've just got a couple more items, and I see @PenghaiZhang has provided some great feedback too.

2022-05-13 08:03 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +            if (Pattern.matches(libavCommentPattern, line) || Pattern.matches(libavPathPattern,
Oh dear, sorry @edalex-yinzi I seem to have confused you. I did not mean `Pattern.matches` I meant _pattern matching_: https://docs.scala-lang.org/tour/pattern-matching.html

And then you can clearly have a `case` for each line you want removed.

but that said, I do like @PenghaiZhang 's one liner.

2022-05-13 08:03 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +      lineMod.update()
Having the intermediate `lineMod` is mostly redundant. You can just call `.update()` after the new's block. e.g.:

```scala
new LineFileModifier((new File(configDir, PropertyFileModifier.OPTIONAL_CONFIG)), result) {
 ...
}.update()
```

Or maybe you need parens:

```scala
(new LineFileModifier((new File(configDir, PropertyFileModifier.OPTIONAL_CONFIG)), result) {
 ...
}).update()
```

2022-05-13 08:03 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +  override def upgrade(result: UpgradeResult, tleInstallDir: File): Unit = {
I see you removed you addLog message from this method completely. I thought it was good to have the message, you just needed to make it more specific - and thereby meaningful and helpful for debugging client issues.

2022-05-13 08:03 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +  override def isBackwardsCompatible: Boolean = false
I was wondering about this too, so I'm glad @PenghaiZhang has clarified.

2022-05-16 01:04 UTC, edalex-yinzi commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +            if (Pattern.matches(libavCommentPattern, line) || Pattern.matches(libavPathPattern,
Use `match` pattern instead.

2022-05-16 01:35 UTC, edalex-yinzi commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +    try {
As discussed, no `Success`.

2022-05-16 06:48 UTC, edalex-yinzi commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +  override def isBackwardsCompatible: Boolean = false
Can't really understand it either. 

But what I found is:
if isBackwardsCompatible = `false` then the upgrader  `isMustExist` = "true". 

Use FFmpeg as example:
User executes upgrade which includes the FFmpeg upgrader, So finally you can find this entry in the log:

```
<com.tle.upgrade.UpgradeLog>
    <migrationId>AddFfmpegConfig</migrationId>
    <executed>2022-05-16 06:23:37.722 UTC</executed>
    <mustExist>true</mustExist>
    <canRetry>false</canRetry>
    <status>EXECUTED</status>
    <log>Updating optional-config properties to support use of FFmpeg
Added line &apos;&apos;
Added line &apos;# FFmpeg path&apos;
Added line &apos;#ffmpeg.path = /path/to/ffmpeg&apos;
</log>
  </com.tle.upgrade.UpgradeLog>
```

And then say next time you remove the FFmpeg upgrader in the code and the same user executes the upgrader again it will raise this error since the log entry tells server ffmpeg upgrader must be exsits:
```
16:40:55,864 INFO  [UpgradeMain] Upgrader started
16:40:55,966 ERROR [UpgradeMain] Error running database-upgrader.jar
java.lang.RuntimeException: Can not upgrade to this version, missing required backwards incompatible migration: AddFfmpegConfig
	at com.tle.upgrade.UpgradeMain.upgrade(UpgradeMain.java:244) ~[classes/:?]
	at com.tle.upgrade.UpgradeMain.main(UpgradeMain.java:161) ~[classes/:?]

Process finished with exit code 1
```
FYI
`UpgradeMain,java` line 190 - 246

![image](https://user-images.githubusercontent.com/92769668/168534585-7749804e-f762-4624-8741-1b63f6439282.png)

2022-05-16 07:24 UTC, edalex-ian commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +  override def isBackwardsCompatible: Boolean = false
I'll leave this for @PenghaiZhang to confirm.

2022-05-16 07:27 UTC, edalex-ian approved these changes
LGTM, will just wait for @PenghaiZhang to confirm correct usage of the flag - as I think I saw other upgraders use `true` but I know Penghai has worked with these both here and in migrations.

2022-05-16 07:51 UTC, PenghaiZhang commented on Source/Tools/UpgradeInstallation/scalasrc/com/tle/upgrade/upgraders/ffmpeg/AddFfmpegConfig.scala
> +  override def isBackwardsCompatible: Boolean = false
Yes you can also see that error when your DB has this log and you are using a version that does not have this migration.

I think this usually happens in our developer environment because we don't support downgrade for clients.

You can see probably only one or two very significant migrations set this to `false`. So I suggest we use `true` here.

2022-05-16 23:17 UTC, edalex-ian approved these changes
Looks good, I'll merge on green. ;)

2022-05-16 23:50 UTC, PenghaiZhang approved these changes

2022-05-17 04:53 UTC, edalex-ian commented
Failed on known flakys, I'm happy for it to merge.

2022-05-17 04:54 UTC, merged