fix: add missing collection query in breadcrumb
openequella/openEQUELLA pull request #4185
Opened 2022-05-31 05:28 UTC by edalex-yinzi

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [ ] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change
Add missing collection query in breadcrumb and "Collection" button in right menu in summary page.

Before:

https://user-images.githubusercontent.com/92769668/171098413-ce5bea8b-b74a-4758-b38b-779ecd0a5eaa.mp4

Now:

https://user-images.githubusercontent.com/92769668/171099165-adb5cee2-62a9-4238-a6d1-fb8d4cf2db2b.mp4

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2022-05-31 09:53 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/navigation/SearchCollectionBreadcrumbProvider.java
> +      collectionLink.setBookmark(new SimpleBookmark(baseBreadcrumbUrl + query));
You can move above line into the `try` block. And then you can also declare `query` inside the `try` block.

2022-05-31 09:53 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/navigation/SearchCollectionBreadcrumbProvider.java
> +        LOGGER.warn("Failed to encode url:", e);
I feel just logging the error is not enough because the users can still click the link which will give them another error I guess. Maybe throw a runtime exception :thinking:  ?

2022-06-01 00:43 UTC, edalex-yinzi commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/navigation/SearchCollectionBreadcrumbProvider.java
> +        LOGGER.warn("Failed to encode url:", e);
Why there will be another error ? They should still be able to back to the normal seach page 'page/search'.

2022-06-01 00:55 UTC, edalex-ian requested changes
Thank @edalex-yinzi , I like this idea.

Two things - which differ from @PenghaiZhang , so might need him to confirm I've not miss-understood what he was saying:

1. Fix up the LOGGER declaration; and
2. Be more explicit in what exception you're catching.

2022-06-01 00:55 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/navigation/SearchCollectionBreadcrumbProvider.java
> +        LOGGER.warn("Failed to encode url:", e);
So I see that the real exception here is `UnsupportedEncodingException`, you should update your `catch` to be more explicit - as that'd help the review too.

With this in mind, this relates to your use of UTF-8. Now if that's not supported, then things have gone pretty wacky - oEQ would be running in an unusual (one might even say, unsupported) environment. But with this knowledge in mind, I think it is fine here to simply log a warning and continue on; as I note the result of continuing will be simply a link to `page/search` just like this code did before the fix.

2022-06-01 00:55 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/navigation/SearchCollectionBreadcrumbProvider.java
> +        Logger LOGGER = LoggerFactory.getLogger(SearchCollectionBreadcrumbProvider.class);
It's idiomatic to declare LOGGERs at the top of the class as a `private static final` member variable. (See examples in other code).

So if you come across a class that doesn't already have one setup, you simply do that - don't just add one down in a method.

2022-06-01 00:55 UTC, edalex-ian commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/navigation/SearchCollectionBreadcrumbProvider.java
> +      collectionLink.setBookmark(new SimpleBookmark(baseBreadcrumbUrl + query));
I think leave this hear for the fall through, based on my understanding that on error this will simply match the old functionality before the fix - i.e. the breadcrumb link will simply take them to a full search page (but with a warning in the logs).

2022-06-01 01:10 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/web/searching/navigation/SearchCollectionBreadcrumbProvider.java
> +        LOGGER.warn("Failed to encode url:", e);
No, I was wrong as I thought `collectionLink.setBookmark` was in the `try` block and then if users click the link they would see a 404 error.

2022-06-01 01:34 UTC, edalex-yinzi commented
Thanks @PenghaiZhang and @edalex-ian

2022-06-01 02:44 UTC, PenghaiZhang approved these changes

2022-06-01 04:42 UTC, edalex-ian approved these changes

2022-06-01 04:44 UTC, edalex-ian commented
Ah, CodeBuild had ScalaCheck fail with browser issues. Rerunning CodeBuild.

2022-06-01 23:24 UTC, merged