Bugfix/808 broken workflow language string
openequella/openEQUELLA pull request #4913
Opened 2023-09-20 13:18 UTC by vunguyen96

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [ ] tests are included
- [x] screenshots are included showing significant UI changes
- [ ] documentation is changed or added

##### Description of change

I have reproduced the issue
![image](https://github.com/openequella/openEQUELLA/assets/23306774/4cbcb752-fce2-4cf5-b127-14d7f3e2a29d)
And after bug fixing:
![image](https://github.com/openequella/openEQUELLA/assets/23306774/aff8d195-dc89-4ab1-816e-7c3e1018b47b)

Just adding a missing translation text to fix https://github.com/openequella/openEQUELLA/issues/808#issue-428510056

UPDATE:
- I pushed one update based on the suggestion from @PenghaiZhang https://github.com/openequella/openEQUELLA/pull/4911#discussion_r1330884115

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2023-09-21 03:09 UTC, PenghaiZhang requested changes

2023-09-21 03:09 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/item/standard/operations/workflow/ReviewOperation.java
> +      throw new AccessDeniedException(CoreStrings.text("error.noworkflow"));
Hi @vunguyen96 , I think `CurrentLocale` is important because a language string can be defined in a different language pack file so we need `CurrentLocale` to find the correct value.

2023-09-21 15:08 UTC, vunguyen96 commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/item/standard/operations/workflow/ReviewOperation.java
> +      throw new AccessDeniedException(CoreStrings.text("error.noworkflow"));
Thank @PenghaiZhang for correcting me. I have brought back `CurrentLocale` and used `CoreStrings.key` instead of `CoreStrings.text`.
I have tested it in both of old and new UI.

2023-09-21 23:30 UTC, PenghaiZhang commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/item/standard/operations/workflow/ReviewOperation.java
> +      throw new AccessDeniedException(CoreStrings.text("error.noworkflow"));
Hi @vunguyen96 , I am sorry I gave you wrong information. I looked into the implementation of `CoreStrings.text` and I can see `CurrentLocale` is already in there. So yeah your previous commit is probably good.

2023-09-23 04:24 UTC, vunguyen96 commented on Source/Plugins/Core/com.equella.core/src/com/tle/core/item/standard/operations/workflow/ReviewOperation.java
> +      throw new AccessDeniedException(CoreStrings.text("error.noworkflow"));
No problem @PenghaiZhang , I have reverted it to the previous commit.
please help me check and thanks for your help

2023-09-26 04:13 UTC, PenghaiZhang approved these changes
LGTM!

2023-09-28 06:30 UTC, PenghaiZhang commented
CI failed on one flaky test so this one should be good to go.

2023-09-28 06:30 UTC, merged