fix: OAuthClientEditorTest fails with latest Chrome
openequella/openEQUELLA pull request #5084
Opened 2024-04-17 02:13 UTC by phungnguyenptn

##### Checklist

- [x] the [contributor license agreement][] is signed
- [x] commit message follows [commit guidelines][]
- [x] tests are included

##### Description of change
- I've added a condition on OAuthClientEditorTest to check WebElement get attribute by id not empty based on the below condition of this test.
- The issue by when we send the empty string into the find element of Selenium Webdriver it will show an error when we send the empty string. But in the latest Chrome maybe Selenium Webdriver doesn't support the latest version.

[contributor license agreement]: https://www.apereo.org/node/676
[commit guidelines]: https://chris.beams.io/posts/git-commit/

2024-04-18 02:25 UTC, edalex-ian requested changes
Thanks for the PR @phungnguyenptn 

Please tweak the code, and then I'll approve a pipeline run to see how it goes.

2024-04-18 02:25 UTC, edalex-ian commented on autotest/Tests/src/main/java/com/tle/webtests/pageobject/oauth/OAuthClientEditorPage.java
> +      if (!Objects.equals(we.getAttribute("id"), "")
hmmm, I'm confused why you've used `Objects.equals` here. The idiom would be `"".equals(...)`...

But anyway, in oEQ we do have apache StringUtils so you'd just want to do:

```java
if(StringUtils.isNotEmpty(...) && isPresent(...)) { ... }
```

But that said, if you're going to pull out this value, please just do it once:

```java
final String elementId = we.getAttribute("id")

for (WebElement control : invalidControls) {
  if(StringUtils.isNonEmpty(elementId) && isPresent(control, elementId)) {
    ...
  }
  ...
}
```

2024-04-19 02:03 UTC, phungnguyenptn commented on autotest/Tests/src/main/java/com/tle/webtests/pageobject/oauth/OAuthClientEditorPage.java
> +      if (!Objects.equals(we.getAttribute("id"), "")
Hi @edalex-ian . I've updated it based on your suggestion. Please help me check it

2024-04-19 02:15 UTC, edalex-ian approved these changes
Thanks @phungnguyenptn . Let's see how it runs. :crossed_fingers:

2024-04-19 04:54 UTC, edalex-ian commented
Woohoo! Solid run first time.

Considering it used to have a 100% fail rate, I'd say this is good to go! Thanks @phungnguyenptn :tada:

2024-04-19 04:55 UTC, merged